export enum SignCategory {
  Warning = 'Warning',
  Regulatory = 'Regulatory',
  Mandatory = 'Mandatory',
  Information = 'Information',
  Direction = 'Direction',
  RoadWorks = 'Road Works',
}

export type SignShape = 'triangle' | 'inverted-triangle' | 'circle' | 'rectangle' | 'octagon';

export interface RoadSign {
  id: string;
  name: string;
  category: SignCategory;
  shape: SignShape;
  borderColor: string;
  fillColor: string;
  textColor: string;
  displayText?: string;
  meaning: string;
  whatToDo: string;
  commonMistake: string;
  relatedRuleNumber?: number;
}

export interface QuizQuestion {
  sign: RoadSign;
  options: string[];
  correctIndex: number;
}

// ── Colour constants ─────────────────────────────────────────────────────────

const RED = '#CC0000';
const BLUE = '#003399';
const GREEN = '#00703C';
const WHITE = '#FFFFFF';
const BLACK = '#000000';
const AMBER = '#FF8C00';

// ── Sign data ─────────────────────────────────────────────────────────────────

export const roadSigns: RoadSign[] = [

  // ── WARNING SIGNS (triangular, red border, white background) ──────────────

  {
    id: 'crossroads',
    name: 'Crossroads',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '+',
    meaning: 'A crossroads junction lies ahead where roads cross at right angles. Vehicles may emerge from any of the four roads.',
    whatToDo: 'Reduce speed and be prepared to give way or stop. Check for traffic from all directions including straight ahead, left and right.',
    commonMistake: 'Drivers often look only left and right and forget to watch for vehicles already in the junction travelling straight through.',
    relatedRuleNumber: 170,
  },
  {
    id: 't-junction',
    name: 'T-junction with priority over vehicles from the right',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'T',
    meaning: 'A T-junction lies ahead where the road you are on meets another road. You are on the minor road approaching the major road.',
    whatToDo: 'Slow down and prepare to give way to traffic on the major road. Come to a stop at the Give Way or Stop line.',
    commonMistake: 'Assuming you have priority. At a T-junction the road ahead is the major road and you must give way.',
    relatedRuleNumber: 170,
  },
  {
    id: 'side-road-right',
    name: 'Side road',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A side road joins the main road from the right ahead. Traffic may emerge from this side road unexpectedly.',
    whatToDo: 'Watch for vehicles emerging from the right. Avoid moving into the right of your lane. Be prepared to brake if necessary.',
    commonMistake: 'Ignoring this sign because you are on the major road. Emerging vehicles may not always give way.',
    relatedRuleNumber: 170,
  },
  {
    id: 'staggered-junction',
    name: 'Staggered junction',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A staggered junction ahead where roads join the main road in a staggered rather than straight-across arrangement. Vehicles may emerge from either side.',
    whatToDo: 'Reduce speed and watch for traffic emerging from both sides. Take extra care as drivers at staggered junctions may not see each other.',
    commonMistake: 'Treating it the same as a crossroads. In a staggered junction, vehicles from opposite sides are offset, increasing the risk of conflict.',
    relatedRuleNumber: 170,
  },
  {
    id: 'roundabout-warning',
    name: 'Roundabout',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'O',
    meaning: 'A roundabout junction lies ahead. Traffic on the roundabout has priority over vehicles entering it.',
    whatToDo: 'Slow down, get into the correct lane well in advance, and be ready to give way to vehicles coming from your right on the roundabout.',
    commonMistake: 'Signalling too early or not signalling at all. Also, failing to check for cyclists or motorcyclists on the roundabout before entering.',
    relatedRuleNumber: 182,
  },
  {
    id: 'sharp-bend-left',
    name: 'Bend to left',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'c',
    meaning: 'A sharp bend to the left lies ahead. The bend may be tighter than it looks from a distance.',
    whatToDo: 'Slow down well before the bend to an appropriate speed. Do not cut across the bend into the path of oncoming traffic.',
    commonMistake: 'Braking during the bend rather than before it. Braking mid-bend can cause the vehicle to become unstable.',
    relatedRuleNumber: 126,
  },
  {
    id: 'sharp-bend-right',
    name: 'Bend to right',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'J',
    meaning: 'A sharp bend to the right lies ahead. Take extra care as oncoming vehicles may cut across the centre line on the bend.',
    whatToDo: 'Reduce speed before the bend. Keep well to the left. Do not attempt to overtake on or near the bend.',
    commonMistake: 'Moving into the centre of the road on the approach, risking a head-on collision with oncoming traffic.',
    relatedRuleNumber: 126,
  },
  {
    id: 'double-bend-left',
    name: 'Double bend first to left',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A series of two bends ahead, the first curving to the left then immediately to the right. These are taken at the speed of the sharpest bend.',
    whatToDo: 'Slow to a safe speed before the first bend. Maintain a steady speed through both curves. Avoid sudden steering corrections.',
    commonMistake: 'Thinking the double bend is less dangerous than a single sharp bend. The change of direction between bends requires extra concentration.',
    relatedRuleNumber: 126,
  },
  {
    id: 'steep-descent',
    name: 'Steep hill downwards',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '%',
    meaning: 'A steep downhill gradient ahead. The gradient is shown as a percentage or ratio on the sign (e.g. 10% or 1:10). Brakes can overheat on prolonged steep descents.',
    whatToDo: 'Engage a low gear before the hill, not during it. Brake in good time and do not let speed build. Avoid riding the brakes continuously.',
    commonMistake: 'Leaving gear selection until on the hill itself. By then, speed has already increased and changing gear is dangerous.',
    relatedRuleNumber: 160,
  },
  {
    id: 'steep-ascent',
    name: 'Steep hill upwards',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '%',
    meaning: 'A steep uphill gradient ahead. Vehicles including large goods vehicles may lose speed quickly and pull into the centre of the road.',
    whatToDo: 'Be prepared for slow-moving vehicles ahead. Allow extra time and space. Do not overtake unless there is a clear safe opportunity.',
    commonMistake: 'Attempting to overtake a slow lorry on a steep hill without checking that there is enough clear road ahead.',
    relatedRuleNumber: 126,
  },
  {
    id: 'uneven-road',
    name: 'Uneven road',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road surface ahead is uneven, potholed, or otherwise rough. The roughness may cause the vehicle to bounce or lose grip.',
    whatToDo: 'Reduce speed. Grip the steering wheel firmly. Be aware that your tyres may lose contact with the road surface momentarily.',
    commonMistake: 'Maintaining normal speed and being caught off guard by a bump that causes loss of control or vehicle damage.',
    relatedRuleNumber: 226,
  },
  {
    id: 'road-narrows-right',
    name: 'Road narrows on right',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road narrows from the right ahead. You may have to give way to oncoming traffic or squeeze past a parked vehicle.',
    whatToDo: 'Reduce speed and move towards the left. Be prepared to stop and allow oncoming vehicles to pass through the narrow section first.',
    commonMistake: 'Maintaining speed and trying to squeeze through. It is safer to stop and allow oncoming traffic through first.',
    relatedRuleNumber: 160,
  },
  {
    id: 'road-narrows-both',
    name: 'Road narrows on both sides',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road narrows on both sides ahead. Only one vehicle may be able to pass at a time through the narrow section.',
    whatToDo: 'Slow down significantly. Be prepared to pull over to let oncoming traffic pass. Watch for pedestrians and cyclists in the narrow section.',
    commonMistake: 'Assuming there is room for two vehicles to pass simultaneously when there may not be.',
    relatedRuleNumber: 160,
  },
  {
    id: 'slippery-road',
    name: 'Slippery road',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road ahead may be slippery, particularly in wet or cold conditions. Common causes include gravel, mud, ice, or oil contamination.',
    whatToDo: 'Reduce speed. Increase the following distance. Avoid sudden braking, steering, or acceleration. Be especially cautious in wet or frosty conditions.',
    commonMistake: 'Treating this sign as advisory when it may indicate genuinely hazardous conditions such as mud, ice, or diesel spills.',
    relatedRuleNumber: 229,
  },
  {
    id: 'risk-of-grounding',
    name: 'Risk of grounding',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'There is a risk that low-bodied vehicles or vehicles with long wheelbases may ground (scrape) on the road ahead due to a dip, hump, or gradient change.',
    whatToDo: 'Slow right down. If towing a trailer or driving a low-slung vehicle, approach at a very slow speed to avoid grounding.',
    commonMistake: 'Ignoring this sign when towing. A caravan or trailer can ground at speeds that are safe for a solo car.',
    relatedRuleNumber: 226,
  },
  {
    id: 'pedestrians-road',
    name: 'Pedestrians in road ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Pedestrians may be walking in the road ahead, often where no footway is available. Expect pedestrians on the carriageway itself.',
    whatToDo: 'Reduce speed. Be ready to stop or move over. Give pedestrians plenty of room, at least as much as you would give a cyclist.',
    commonMistake: 'Expecting pedestrians to stay to the far left. In the absence of a pavement, pedestrians should walk on the right facing traffic.',
    relatedRuleNumber: 204,
  },
  {
    id: 'school-crossing',
    name: 'School crossing patrol ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'S',
    meaning: 'A school crossing patrol (lollipop person) operates ahead. They will step into the road with a stop sign to allow children to cross.',
    whatToDo: 'When the lollipop person steps out, you must stop immediately. Wait until they have returned to the pavement before proceeding.',
    commonMistake: 'Failing to stop when the patrol steps out, or pulling away before the patrol has fully cleared the road.',
    relatedRuleNumber: 204,
  },
  {
    id: 'children',
    name: 'Children going to or from school',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Children are likely to be in or near the road ahead, typically near a school, playground, or housing estate. Children may run out unexpectedly.',
    whatToDo: 'Slow down significantly. Be ready to stop at any moment. Watch both sides of the road for children, especially between parked cars.',
    commonMistake: 'Slowing only slightly. Children can run into the road without warning and your stopping distance must allow for this.',
    relatedRuleNumber: 204,
  },
  {
    id: 'elderly-people',
    name: 'Frail pedestrians likely to cross',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Elderly pedestrians, who may move slowly or unpredictably, are likely to be crossing or walking near the road ahead.',
    whatToDo: 'Reduce speed and be patient. Allow extra time for elderly pedestrians to cross. Do not rev your engine or sound the horn.',
    commonMistake: 'Assuming elderly pedestrians will always use the crossing. They may cross anywhere and may not hear or see approaching vehicles.',
    relatedRuleNumber: 204,
  },
  {
    id: 'horse-riders',
    name: 'Accompanied horses or ponies',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Horse riders are likely to be on or crossing the road ahead. Horses can be startled by noise and sudden movements.',
    whatToDo: 'Slow right down and pass wide and slowly. Do not sound the horn or rev the engine. Be prepared for the horse to move unpredictably. Accelerate gently away after passing.',
    commonMistake: 'Sounding the horn or revving the engine as you approach. This can cause the horse to bolt and throw the rider.',
    relatedRuleNumber: 52,
  },
  {
    id: 'wild-animals',
    name: 'Wild animals',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Wild animals such as deer may be crossing the road ahead, particularly at dawn and dusk. Animals move unpredictably.',
    whatToDo: 'Reduce speed. If you see one animal, expect more to follow. Do not swerve sharply if an animal appears — brake in a straight line.',
    commonMistake: 'Speeding up after passing one animal. Deer and other herd animals often cross in groups.',
    relatedRuleNumber: 226,
  },
  {
    id: 'farm-animals',
    name: 'Cattle',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Cattle or other farm animals may be on or crossing the road ahead. This sign is common in rural areas near farms.',
    whatToDo: 'Slow down and be prepared to stop. Do not sound the horn. Give animals plenty of space and wait for farmers to move them off the road.',
    commonMistake: 'Trying to squeeze through a herd of cattle. Wait patiently — pushing through can cause animals to panic and injure people.',
    relatedRuleNumber: 57,
  },
  {
    id: 'falling-rocks',
    name: 'Falling or fallen rocks',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'There is a risk of falling or fallen rocks on the road ahead, typically in hilly or cliffed areas.',
    whatToDo: 'Reduce speed. Watch for debris on the road. Do not stop in a rockfall zone — proceed through as quickly as safely possible.',
    commonMistake: 'Stopping to take photos or look at rocks on the road. You are vulnerable to further rockfall while stationary.',
    relatedRuleNumber: 226,
  },
  {
    id: 'risk-of-ice',
    name: 'Risk of ice',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road ahead is prone to ice forming, often due to a frost hollow, bridge, or shaded section. Icy roads can be invisible (black ice).',
    whatToDo: 'Reduce speed well before the area. Avoid heavy braking. Use the highest gear appropriate to reduce wheel spin. Double your following distance.',
    commonMistake: 'Assuming the road looks clear means it is safe. Black ice is invisible and can catch drivers completely off guard.',
    relatedRuleNumber: 229,
  },
  {
    id: 'traffic-signals',
    name: 'Traffic signals',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Traffic lights are situated ahead, possibly at a junction, crossing, or road works. Traffic may be stopping ahead.',
    whatToDo: 'Reduce speed and be prepared to stop at a red light. Look out for vehicles braking sharply ahead, especially in poor visibility.',
    commonMistake: 'Assuming the lights will be green and maintaining speed. Be ready to stop smoothly.',
    relatedRuleNumber: 113,
  },
  {
    id: 'level-crossing-barriers',
    name: 'Level crossing with barrier or gate ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A railway level crossing with automatic barriers lies ahead. When red lights flash and the alarm sounds, barriers will lower.',
    whatToDo: 'Never cross when the red lights are flashing. Stop before the white line. If caught on the crossing, get everyone clear and call the signal operator immediately.',
    commonMistake: 'Trying to zig-zag around lowering barriers. This is extremely dangerous and a criminal offence.',
    relatedRuleNumber: 290,
  },
  {
    id: 'level-crossing-no-barriers',
    name: 'Level crossing without barrier or gate ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'An unprotected level crossing ahead that has no barriers or lights. You must judge when it is safe to cross.',
    whatToDo: 'Stop, look both ways along the railway line, listen, and only cross when you are certain no train is approaching. Treat an approaching train like any other vehicle that cannot stop quickly.',
    commonMistake: 'Looking only one way along the track. Trains can approach from either direction.',
    relatedRuleNumber: 293,
  },
  {
    id: 'level-crossing-countdown-3',
    name: 'Level crossing countdown — 3 bars',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '|||',
    meaning: 'Three diagonal bars on a triangular sign indicate you are 270 yards from a level crossing. This is the first of three countdown markers.',
    whatToDo: 'Begin reducing speed. Three bars means you are 270 yards away. Start anticipating the need to stop.',
    commonMistake: 'Not recognising the countdown markers and missing the crossing. The number of bars (3, 2, 1) shows your distance to the crossing.',
    relatedRuleNumber: 290,
  },
  {
    id: 'level-crossing-countdown-2',
    name: 'Level crossing countdown — 2 bars',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '||',
    meaning: 'Two diagonal bars indicate you are 180 yards from a level crossing. You should be actively reducing speed.',
    whatToDo: 'Continue slowing down. Be prepared to stop if the lights begin to flash.',
    commonMistake: 'Confusing these markers with general warning signs rather than level crossing countdowns.',
    relatedRuleNumber: 290,
  },
  {
    id: 'level-crossing-countdown-1',
    name: 'Level crossing countdown — 1 bar',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '|',
    meaning: 'One diagonal bar indicates you are 90 yards from a level crossing. You should be approaching at a speed at which you can easily stop.',
    whatToDo: 'Be ready to stop. Watch for the crossing lights and barriers. Never cross while red lights are flashing.',
    commonMistake: 'Still travelling too fast at the one-bar marker. You must be able to stop safely before the crossing.',
    relatedRuleNumber: 290,
  },
  {
    id: 'humpback-bridge',
    name: 'Hump bridge',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A humped or humpback bridge ahead where the road rises sharply. Vehicles cresting the bridge may be unable to see oncoming traffic.',
    whatToDo: 'Slow to a speed at which you could stop if there is oncoming traffic on the other side. Keep to the left.',
    commonMistake: 'Assuming there is nothing on the other side of the bridge. A cyclist or slow vehicle may be hidden over the crest.',
    relatedRuleNumber: 160,
  },
  {
    id: 'quayside',
    name: 'Quayside or river bank',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'The road ends at or near a quayside, riverbank, or water\'s edge ahead. Driving off the edge would result in entry into water.',
    whatToDo: 'Slow right down. Know your exit route. If the road is unfamiliar, stop and check before proceeding further.',
    commonMistake: 'Failing to realise the road actually ends. Especially dangerous at night or in poor visibility.',
    relatedRuleNumber: 226,
  },
  {
    id: 'two-way-traffic-ahead',
    name: 'Two-way traffic crosses one-way road',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'After a one-way section, two-way traffic resumes ahead. Oncoming vehicles will be in the road you are using.',
    whatToDo: 'Move to the left side of the road. Adjust your speed and road position for two-way traffic. Watch for oncoming vehicles.',
    commonMistake: 'Remaining in the middle of the road after driving on a one-way system and failing to move left in time.',
    relatedRuleNumber: 160,
  },
  {
    id: 'ford',
    name: 'Ford',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A ford (a shallow water crossing) lies ahead. After heavy rain the water depth may be greater than normal.',
    whatToDo: 'Slow right down. Check the depth gauge if provided. Drive through slowly in first gear at a steady speed. Test your brakes immediately after crossing.',
    commonMistake: 'Driving through a ford too quickly. Fast speeds can cause water to enter the engine or wash away vehicles in fast-flowing water.',
    relatedRuleNumber: 234,
  },
  {
    id: 'tunnel',
    name: 'Tunnel ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'A tunnel lies ahead. Visibility will change dramatically on entering and exiting. Lighting and ventilation may be limited.',
    whatToDo: 'Switch on headlights before entering. Remove sunglasses. Do not overtake in a tunnel unless lane markings permit. Follow any mandatory signs at the tunnel entrance.',
    commonMistake: 'Not switching headlights on before entering. In a tunnel, other road users need to see you as well as vice versa.',
    relatedRuleNumber: 144,
  },
  {
    id: 'low-aircraft',
    name: 'Low-flying aircraft or sudden aircraft noise',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Low-flying aircraft or sudden aircraft noise is possible ahead, typically near an airfield or flight path. Horses and other animals may be startled.',
    whatToDo: 'Be alert to sudden loud aircraft noise. If driving near horses, be prepared for them to react. No action required for normal driving.',
    commonMistake: 'Panicking at the aircraft noise and braking suddenly. The sign is advisory — simply be aware.',
    relatedRuleNumber: 226,
  },
  {
    id: 'opening-bridge',
    name: 'Opening or swing bridge ahead',
    category: SignCategory.Warning,
    shape: 'triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'An opening or swing bridge that opens to allow river or canal traffic to pass lies ahead. Barriers will lower when the bridge is about to open.',
    whatToDo: 'Slow down and follow any instructions or signals. Be prepared to wait for the bridge to reopen. Never attempt to cross when barriers are down.',
    commonMistake: 'Failing to leave enough stopping distance on the approach. Bridges can open unexpectedly.',
    relatedRuleNumber: 226,
  },

  // ── REGULATORY — PROHIBITION (circular, red border, white background) ──────

  {
    id: 'speed-20',
    name: 'Maximum speed 20 mph',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: '20',
    meaning: 'The maximum speed permitted on this road is 20 mph. You must not exceed this speed under any circumstances.',
    whatToDo: 'Reduce speed to 20 mph or below and maintain that speed throughout the restricted zone. Obey any associated zone signs.',
    commonMistake: 'Treating 20 mph zones as advisory. They are mandatory — exceeding 20 mph is an offence.',
    relatedRuleNumber: 113,
  },
  {
    id: 'speed-30',
    name: 'Maximum speed 30 mph',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: '30',
    meaning: 'The maximum speed permitted on this road is 30 mph. This is the default limit for built-up areas with street lighting.',
    whatToDo: 'Do not exceed 30 mph. Remember that 30 mph is a maximum, not a target — reduce speed for hazards, poor conditions, or heavy pedestrian activity.',
    commonMistake: 'Assuming 30 mph is always safe. In busy pedestrian areas or near schools, a lower speed may be appropriate.',
    relatedRuleNumber: 113,
  },
  {
    id: 'speed-40',
    name: 'Maximum speed 40 mph',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: '40',
    meaning: 'The maximum speed permitted on this road is 40 mph. Commonly found on urban arterial roads and some rural roads.',
    whatToDo: 'Do not exceed 40 mph. Adjust speed downwards in poor conditions, near junctions, or when pedestrians are present.',
    commonMistake: 'Travelling at 40 mph through hazards or bends where a lower speed would be appropriate.',
    relatedRuleNumber: 113,
  },
  {
    id: 'speed-50',
    name: 'Maximum speed 50 mph',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: '50',
    meaning: 'The maximum speed permitted is 50 mph. Often found on roads where the national limit would otherwise apply but local conditions require a lower limit.',
    whatToDo: 'Obey the 50 mph limit. It is a maximum, not a target. Slow for hazards, bends, and poor weather conditions.',
    commonMistake: 'Failing to drop from 60 mph when the road transitions from national speed limit to a 50 mph restricted section.',
    relatedRuleNumber: 113,
  },
  {
    id: 'speed-60',
    name: 'Maximum speed 60 mph',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: '60',
    meaning: 'The maximum speed is 60 mph, which is the national speed limit for single-carriageway roads.',
    whatToDo: 'Do not exceed 60 mph. On single carriageways this can feel very fast — slow for bends, junctions, and oncoming traffic.',
    commonMistake: 'Treating 60 mph on a single carriageway like a dual carriageway. Overtaking on single carriageways at 60 mph is especially hazardous.',
    relatedRuleNumber: 113,
  },
  {
    id: 'national-speed-limit',
    name: 'National speed limit applies',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'NSL',
    meaning: 'The national speed limit for the type of road and vehicle applies. 60 mph for single carriageways, 70 mph for dual carriageways and motorways (for cars).',
    whatToDo: 'Drive at or below the appropriate national limit for the road type and your vehicle category. Reduce speed for conditions.',
    commonMistake: 'Assuming 70 mph always applies. On single carriageways the national limit is 60 mph, not 70 mph.',
    relatedRuleNumber: 113,
  },
  {
    id: 'end-speed-restriction',
    name: 'End of speed restriction',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'END',
    meaning: 'A specific speed restriction has ended. The national speed limit or a higher restriction may now apply.',
    whatToDo: 'Check what speed limit now applies (national speed limit or another posted limit). Do not assume you can immediately accelerate to motorway speeds.',
    commonMistake: 'Immediately accelerating to 70 mph when a restriction ends. The road conditions or speed limit ahead may not be appropriate for this speed.',
    relatedRuleNumber: 113,
  },
  {
    id: 'no-entry',
    name: 'No entry for vehicular traffic',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: RED,
    textColor: WHITE,
    displayText: '-',
    meaning: 'No vehicle may enter this road in this direction. The road is one-way and you would be travelling against the traffic flow.',
    whatToDo: 'Do not enter. Find an alternative route. If you have entered by mistake, do not reverse on a busy road — find a safe place to turn.',
    commonMistake: 'Reversing in panic from a one-way street onto a busy road, which can be more dangerous than the original mistake.',
    relatedRuleNumber: 160,
  },
  {
    id: 'no-vehicles',
    name: 'No vehicles except bicycles being pushed',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'X',
    meaning: 'No vehicles of any kind may use this road. This is a pedestrianised area or road closed to all traffic.',
    whatToDo: 'Do not enter with any vehicle. Unless you have a specific exemption (e.g. loading at specified times), find an alternative route.',
    commonMistake: 'Thinking you can ride a bicycle through. The exception is pushing only — riding is not permitted. The plain red ring means no vehicles at all: cars, motorcycles, and ridden bicycles must not enter.',
    relatedRuleNumber: 160,
  },
  {
    id: 'no-motor-vehicles',
    name: 'No motor vehicles',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Motor vehicles are not permitted on this road. Cyclists and pedestrians may still use it.',
    whatToDo: 'Do not enter with a motor vehicle. If cycling, you may proceed. Check for any time-based or vehicle-type exemptions shown on the sign.',
    commonMistake: 'Assuming that because cyclists can use the road, low-speed motor vehicles (such as scooters) can too.',
    relatedRuleNumber: 160,
  },
  {
    id: 'no-cycling',
    name: 'No cycling',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    meaning: 'Cycling is not permitted on this road or path. Cyclists must dismount and walk.',
    whatToDo: 'Cyclists must dismount and push their bicycle through the area. Motor vehicles obey all other normal traffic rules.',
    commonMistake: 'Assuming that because the sign shows a bicycle it only applies to bicycles and not e-scooters. E-scooters may also be prohibited.',
    relatedRuleNumber: 62,
  },
  {
    id: 'no-right-turn',
    name: 'No right turn',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'No R',
    meaning: 'Turning right is prohibited at this junction. This is usually to improve traffic flow or because the manoeuvre would be unsafe.',
    whatToDo: 'Do not turn right. Find an alternative route — often this means going around the block. Obey even if no traffic is present.',
    commonMistake: 'Turning right because the road is clear. The prohibition applies at all times regardless of traffic conditions.',
    relatedRuleNumber: 170,
  },
  {
    id: 'no-left-turn',
    name: 'No left turn',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'No L',
    meaning: 'Turning left is prohibited at this junction, often to protect a junction from excessive traffic or for safety reasons.',
    whatToDo: 'Do not turn left. Follow an alternative route as directed. This prohibition applies at all times unless times are shown on the sign.',
    commonMistake: 'Following a sat-nav instruction to turn left when this sign is present. Always obey the road sign over the navigation device.',
    relatedRuleNumber: 170,
  },
  {
    id: 'no-u-turns',
    name: 'No U-turns',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'U',
    meaning: 'U-turns are prohibited on this road. This is usually because the road is too narrow, too busy, or the manoeuvre is unsafe at this point.',
    whatToDo: 'Do not attempt a U-turn. Find a safe place to turn around, such as a side road or car park, away from the restriction.',
    commonMistake: 'Making a U-turn because no traffic is visible. The prohibition is absolute, not conditional on whether traffic is present.',
    relatedRuleNumber: 160,
  },
  {
    id: 'no-overtaking',
    name: 'No overtaking',
    category: SignCategory.Regulatory,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'OT',
    meaning: 'Overtaking is prohibited. You must not pass any moving vehicle travelling in the same direction. This applies even if the vehicle ahead is very slow.',
    whatToDo: 'Do not overtake. Remain behind the vehicle ahead until the restriction ends, indicated by a national speed limit sign or a derestriction sign.',
    commonMistake: 'Attempting to overtake a cyclist or motorcycle when this sign is present. It prohibits overtaking any moving vehicle, including two-wheelers.',
    relatedRuleNumber: 126,
  },
  {
    id: 'give-way',
    name: 'Give way to traffic on major road',
    category: SignCategory.Regulatory,
    shape: 'inverted-triangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'GIVE\nWAY',
    meaning: 'You must give way to traffic on the road you are entering. Stop if necessary. Traffic on the major road has priority.',
    whatToDo: 'Slow down and be prepared to stop. Give way to all traffic on the main road. Only proceed when it is safe to do so and you will not cause other drivers to brake or swerve.',
    commonMistake: 'Rolling through a give way as if it were a Stop sign. You must stop completely if any traffic is present or approaching.',
    relatedRuleNumber: 172,
  },
  {
    id: 'stop-sign',
    name: 'Stop and give way',
    category: SignCategory.Regulatory,
    shape: 'octagon',
    borderColor: RED,
    fillColor: RED,
    textColor: WHITE,
    displayText: 'STOP',
    meaning: 'You must stop completely at the stop line before proceeding. This is a legal requirement even if the road appears clear.',
    whatToDo: 'Stop the vehicle completely with all wheels stationary at the white stop line. Look in both directions. Only move when the road is completely clear.',
    commonMistake: 'Only slowing down rather than stopping completely. The STOP sign requires a complete stop — this is a legal requirement, not a suggestion.',
    relatedRuleNumber: 172,
  },

  // ── MANDATORY (circular, blue fill, white symbol) ─────────────────────────

  {
    id: 'turn-left-ahead',
    name: 'Turn left ahead',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'L',
    meaning: 'You must turn left at the junction ahead. This is a mandatory order, not a suggestion. The road continues only to the left.',
    whatToDo: 'Signal left and turn left at the junction. No other manoeuvre is permitted at this point.',
    commonMistake: 'Confusing this with an advisory direction sign. Blue circle signs are orders — you must comply.',
    relatedRuleNumber: 170,
  },
  {
    id: 'turn-right-ahead',
    name: 'Turn right ahead',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'R',
    meaning: 'You must turn right at the junction ahead. A mandatory instruction — the route ahead is closed or one-way forcing a right turn.',
    whatToDo: 'Signal right and turn right at the junction. Follow the mandatory direction.',
    commonMistake: 'Treating it as an advisory direction sign. A blue circle means you MUST follow the instruction.',
    relatedRuleNumber: 170,
  },
  {
    id: 'keep-left',
    name: 'Keep left',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'KL',
    meaning: 'You must pass to the left of this feature, such as a traffic island, central reservation bollard, or road obstacle.',
    whatToDo: 'Always pass to the left side of the bollard or obstacle. Do not pass to the right even if the left side is congested.',
    commonMistake: 'Passing on the right of a keep left bollard, which can put you into the path of oncoming traffic.',
    relatedRuleNumber: 160,
  },
  {
    id: 'keep-right',
    name: 'Keep right',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'KR',
    meaning: 'You must pass to the right of this feature. Used on the approach to one-way roads or traffic islands.',
    whatToDo: 'Pass to the right side of the obstacle or marking. Do not move to the left side.',
    commonMistake: 'Assuming "keep right" means use the right lane. It means pass to the right of this specific feature.',
    relatedRuleNumber: 160,
  },
  {
    id: 'mini-roundabout',
    name: 'Mini-roundabout',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'O',
    meaning: 'A mini-roundabout is ahead and you must give way to vehicles already on it. Traffic circulates in a clockwise direction.',
    whatToDo: 'Give way to traffic from the right. Signal your intentions as you would at a normal roundabout. Go around the central marking (do not drive over it in a large vehicle if avoidable).',
    commonMistake: 'Failing to give way at a mini-roundabout because it looks informal. The same priority rules apply as for any roundabout.',
    relatedRuleNumber: 182,
  },
  {
    id: 'cycles-pedestrians-segregated',
    name: 'Segregated pedal cycle and pedestrian route',
    category: SignCategory.Mandatory,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'CYC/PED',
    meaning: 'The path ahead is divided into separate lanes for cyclists and pedestrians. Each must use their designated side.',
    whatToDo: 'Cyclists use the cycle lane; pedestrians use the pedestrian lane. Respect the division and do not cross into the other half.',
    commonMistake: 'Walking in the cycle lane or cycling in the pedestrian area, causing conflict and danger.',
    relatedRuleNumber: 62,
  },
  {
    id: 'cycles-only',
    name: 'Route to be used by pedal cycles only',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'CYC',
    meaning: 'This route is designated for cyclists only. Pedestrians and motor vehicles must not use it.',
    whatToDo: 'Cyclists may use this route. Pedestrians and motor vehicle drivers must use an alternative route.',
    commonMistake: 'Assuming pedestrians may share a cycle-only path. Unless specifically signed as shared, pedestrians must not use cycle-only routes.',
    relatedRuleNumber: 62,
  },
  {
    id: 'pedestrians-only',
    name: 'Route for pedestrians only',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'PED',
    meaning: 'This route is for pedestrians only. Cyclists and motor vehicles must not use it.',
    whatToDo: 'Pedestrians may use this route. Cyclists must dismount. Motor vehicle drivers must find an alternative route.',
    commonMistake: 'Cycling on a pedestrian-only path because it is convenient. Cyclists must dismount and push.',
    relatedRuleNumber: 66,
  },
  {
    id: 'min-speed-30',
    name: 'Minimum speed 30 mph',
    category: SignCategory.Mandatory,
    shape: 'circle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: '30',
    meaning: 'You must not travel below 30 mph on this road unless road conditions require it. Minimum speed signs are rare in the UK.',
    whatToDo: 'Maintain at least 30 mph unless conditions such as heavy traffic make it temporarily impossible.',
    commonMistake: 'Confusing minimum speed signs (blue circle) with maximum speed signs (white circle with red border). Blue = minimum, white with red = maximum.',
    relatedRuleNumber: 113,
  },
  {
    id: 'one-way-traffic',
    name: 'One-way traffic',
    category: SignCategory.Mandatory,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: '-->',
    meaning: 'Traffic must travel in one direction only on this road. A rectangular blue sign with an arrow indicates the permitted direction.',
    whatToDo: 'Travel in the direction indicated by the arrow only. Do not attempt to turn around or travel in the opposite direction.',
    commonMistake: 'Reversing in a one-way street. If you have gone the wrong way, find a suitable place to turn and exit at the nearest junction.',
    relatedRuleNumber: 160,
  },
  {
    id: 'buses-cycles-only',
    name: 'Buses and cycles only',
    category: SignCategory.Mandatory,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'BUS/CYC',
    meaning: 'Only buses and cyclists may use this lane or road. All other vehicles, including motorcycles (unless stated), are excluded.',
    whatToDo: 'Unless you are a bus driver or cyclist, do not enter this lane. Find an alternative route for your vehicle.',
    commonMistake: 'Driving a motorcycle into a bus-only lane. Unless the sign specifically includes motorcycles, they are prohibited.',
    relatedRuleNumber: 141,
  },

  // ── INFORMATION (rectangular) ─────────────────────────────────────────────

  {
    id: 'motorway-start',
    name: 'Start of motorway',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'M',
    meaning: 'The motorway begins here. Motorway rules now apply: different speed limits, no learner drivers, no stopping except in emergencies.',
    whatToDo: 'Ensure you are allowed to use the motorway. Build up speed on the slip road and merge into the left lane. Switch to the correct speed limit (usually 70 mph).',
    commonMistake: 'Assuming all vehicles can use the motorway. Learner drivers, cyclists, motorcycles under 50cc, and agricultural vehicles are prohibited.',
    relatedRuleNumber: 253,
  },
  {
    id: 'end-motorway',
    name: 'End of motorway',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'END M',
    meaning: 'The motorway ends here. Normal road rules now apply. Speed limits, road markings, and junction rules will change.',
    whatToDo: 'Reduce speed — after motorway driving, 60 mph may feel slow. Check the speedometer. Be alert to speed limit signs and junctions ahead.',
    commonMistake: 'Maintaining motorway speed after the end of the motorway. Speed perception is distorted after high-speed driving.',
    relatedRuleNumber: 273,
  },
  {
    id: 'lane-closed-overhead',
    name: 'Lane closed — overhead red X',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: BLACK,
    textColor: RED,
    displayText: 'X',
    meaning: 'A red X on an overhead motorway gantry means the lane directly below is closed. It is a criminal offence to drive in a lane showing a red X.',
    whatToDo: 'Move out of the closed lane immediately (check mirrors, signal, change lane safely). Do not drive in or re-enter the lane below the red X.',
    commonMistake: 'Treating the red X as advisory. Driving in a lane showing a red X is a criminal offence and carries a fine and penalty points.',
    relatedRuleNumber: 266,
  },
  {
    id: 'variable-speed-limit',
    name: 'Variable speed limit (smart motorway)',
    category: SignCategory.Information,
    shape: 'circle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'VSL',
    meaning: 'On a smart motorway, variable speed limits are shown on overhead gantries. These are mandatory when displayed in a red circle.',
    whatToDo: 'Obey the displayed speed limit. These limits are often set in response to incidents, congestion, or poor conditions. They are enforced by average speed cameras.',
    commonMistake: 'Assuming variable limits are advisory. When shown in a red circle on a smart motorway, they are mandatory.',
    relatedRuleNumber: 266,
  },
  {
    id: 'parking-place',
    name: 'Parking place',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'P',
    meaning: 'An authorised parking area is available ahead or nearby. Any time or vehicle restrictions will be shown on the sign.',
    whatToDo: 'You may park in the indicated area subject to any restrictions shown. Always check for time limits, permit requirements, or vehicle type restrictions.',
    commonMistake: 'Parking in a designated bay but ignoring the maximum time or permit requirement shown below the main sign.',
    relatedRuleNumber: 238,
  },
  {
    id: 'no-through-road',
    name: 'No through road for vehicles',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'NT',
    meaning: 'The road ahead is a dead end or cul-de-sac and does not lead to another road. You will have to reverse or turn around.',
    whatToDo: 'Only enter if your destination is in that road. Be prepared to turn around or reverse out. Do not use as a through route.',
    commonMistake: 'Following a sat-nav that routes through a no-through road, especially in a large vehicle where turning may be impossible.',
    relatedRuleNumber: 160,
  },
  {
    id: 'tourist-attraction',
    name: 'Tourist attraction',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: '#7B3F00',
    fillColor: '#7B3F00',
    textColor: WHITE,
    displayText: 'i',
    meaning: 'A tourist attraction, heritage site, leisure facility, or place of interest is in this direction. Brown signs indicate destinations of tourist interest.',
    whatToDo: 'Follow the brown signs if visiting the attraction. Take care on approach — tourist destinations can mean sudden braking and inexperienced drivers turning.',
    commonMistake: 'Treating brown signs as less important than other road signs. They are directional information signs and should be followed if they are your destination.',
    relatedRuleNumber: 160,
  },
  {
    id: 'hospital',
    name: 'Hospital ahead',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'H',
    meaning: 'A hospital is situated ahead or nearby. Emergency vehicles may be exiting or entering the hospital area. Pedestrians may be crossing.',
    whatToDo: 'Reduce speed near hospitals. Be prepared for emergency vehicles. Watch for vulnerable pedestrians including patients, wheelchair users, and visitors.',
    commonMistake: 'Sounding the horn near a hospital. This can disturb patients and is inconsiderate.',
    relatedRuleNumber: 219,
  },
  {
    id: 'camera-ahead',
    name: 'Speed cameras',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'CAM',
    meaning: 'Speed enforcement cameras are operating on this road. Fixed, average speed, or mobile cameras may be in use.',
    whatToDo: 'Ensure you are driving within the speed limit. Maintain your speed — there is no legitimate reason to brake for a camera if you are within the limit.',
    commonMistake: 'Braking sharply at camera signs and then speeding up afterwards. Drive at a safe, legal speed consistently.',
    relatedRuleNumber: 113,
  },
  {
    id: 'zone-30-entry',
    name: '20/30 mph zone — entry',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'ZONE',
    meaning: 'You are entering a speed restricted zone covering multiple roads. The posted speed limit applies to all roads within the zone.',
    whatToDo: 'Reduce speed to the stated limit immediately on entering the zone. The zone limit applies throughout, not just on the roads with repeater signs.',
    commonMistake: 'Assuming the limit only applies on the main road. Zone limits apply to all roads within the zone unless another limit is posted.',
    relatedRuleNumber: 113,
  },
  {
    id: 'red-route',
    name: 'Red route',
    category: SignCategory.Information,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: WHITE,
    textColor: RED,
    displayText: 'RED',
    meaning: 'This is a red route where stopping is prohibited at all times. Double red lines mean no stopping at any time. Single red lines mean restricted stopping.',
    whatToDo: 'Do not stop on double red lines. For single red lines, check the sign for the restricted times. Loading and unloading restrictions are shown separately.',
    commonMistake: 'Confusing red routes with yellow lines. Red routes have stricter enforcement — cameras monitor them continuously in London and some other cities.',
    relatedRuleNumber: 240,
  },

  // ── DIRECTION SIGNS ────────────────────────────────────────────────────────

  {
    id: 'motorway-direction',
    name: 'Motorway direction sign',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: BLUE,
    fillColor: BLUE,
    textColor: WHITE,
    displayText: 'M1',
    meaning: 'A blue rectangular sign indicates motorway route directions. Route numbers are shown in white with a motorway symbol (M).',
    whatToDo: 'Follow blue motorway signs for your destination. Get into the correct lane well before the junction to avoid last-minute lane changes.',
    commonMistake: 'Switching lanes at the last moment after missing the advance direction sign. Plan lane changes early.',
    relatedRuleNumber: 259,
  },
  {
    id: 'primary-route-direction',
    name: 'Primary route direction sign',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: GREEN,
    fillColor: GREEN,
    textColor: WHITE,
    displayText: 'A1',
    meaning: 'A green rectangular sign indicates primary route destinations. Primary routes form the main road network outside of motorways.',
    whatToDo: 'Follow green signs for primary route destinations. Move into the correct lane in advance of junctions.',
    commonMistake: 'Confusing green primary route signs with blue motorway signs. Green = A-road primary route; Blue = motorway.',
    relatedRuleNumber: 160,
  },
  {
    id: 'local-route-direction',
    name: 'Local route direction sign',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: 'B2345',
    meaning: 'White rectangular signs with black text indicate local road destinations (B-roads and non-primary routes).',
    whatToDo: 'Follow white signs for local destinations. Check for junctions and be prepared to slow for turnings.',
    commonMistake: 'Assuming local route signs are only advisory. They are the standard navigational signs for non-primary roads.',
    relatedRuleNumber: 160,
  },
  {
    id: 'countdown-300',
    name: 'Motorway exit countdown — 300 yards',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '|||',
    meaning: 'Three diagonal bars on a rectangular white sign: you are 300 yards from the motorway exit. Start planning your lane position.',
    whatToDo: 'Check you are in the left lane. If not, look for a safe gap and move left. Begin signalling left at the 300-yard point if not already in the exit lane.',
    commonMistake: 'Waiting until the 100-yard marker before moving left. Last-minute lane changes at motorway speeds are dangerous.',
    relatedRuleNumber: 273,
  },
  {
    id: 'countdown-200',
    name: 'Motorway exit countdown — 200 yards',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '||',
    meaning: 'Two diagonal bars: you are 200 yards from the motorway exit. You should already be in the left lane and signalling.',
    whatToDo: 'Ensure you are in the left lane and signalling left. Begin planning your speed for the slip road ahead.',
    commonMistake: 'Not yet in the left lane at 200 yards. At motorway speeds, 200 yards passes very quickly.',
    relatedRuleNumber: 273,
  },
  {
    id: 'countdown-100',
    name: 'Motorway exit countdown — 100 yards',
    category: SignCategory.Direction,
    shape: 'rectangle',
    borderColor: BLACK,
    fillColor: WHITE,
    textColor: BLACK,
    displayText: '|',
    meaning: 'One diagonal bar: you are 100 yards from the motorway exit. You must be in the left lane and ready to exit.',
    whatToDo: 'Enter the slip road. Reduce your speed on the slip road (not the motorway). Be aware that your speed perception may be distorted after motorway driving.',
    commonMistake: 'Braking on the motorway at the 100-yard marker. Brake on the slip road, not the motorway, to avoid rear-end collisions.',
    relatedRuleNumber: 273,
  },

  // ── ROAD WORKS SIGNS ──────────────────────────────────────────────────────

  {
    id: 'road-works-ahead',
    name: 'Road works',
    category: SignCategory.RoadWorks,
    shape: 'triangle',
    borderColor: RED,
    fillColor: AMBER,
    textColor: BLACK,
    meaning: 'Road works are taking place ahead. Lanes may be reduced, workers will be present, and speed restrictions will apply.',
    whatToDo: 'Reduce speed to the posted limit. Follow any lane closures indicated by cones or signs. Allow extra time for your journey. Do not be distracted by the works.',
    commonMistake: 'Treating the road works speed limit as advisory. Speed limits in road works zones are mandatory and are often camera-enforced.',
    relatedRuleNumber: 288,
  },
  {
    id: 'men-at-work',
    name: 'Men at work',
    category: SignCategory.RoadWorks,
    shape: 'triangle',
    borderColor: RED,
    fillColor: AMBER,
    textColor: BLACK,
    displayText: '!',
    meaning: 'Workers are present in the road or very close to the carriageway ahead. This sign is always temporary.',
    whatToDo: 'Reduce speed significantly. Give workers the same consideration you would give a pedestrian. Watch for signs directing you around the works.',
    commonMistake: 'Maintaining normal road speed when workers are present. Workers can step into the road, and your stopping distance must allow for this.',
    relatedRuleNumber: 288,
  },
  {
    id: 'loose-chippings',
    name: 'Loose chippings',
    category: SignCategory.RoadWorks,
    shape: 'triangle',
    borderColor: RED,
    fillColor: AMBER,
    textColor: BLACK,
    meaning: 'Loose gravel or chippings have been laid on the road surface as part of resurfacing works. These can be flicked up and crack windscreens.',
    whatToDo: 'Reduce speed significantly (typically to 20 mph). Increase the gap from the vehicle ahead to at least double. Ease off the accelerator to avoid spinning tyres.',
    commonMistake: 'Maintaining normal following distance. Spinning tyres on loose chippings can fire stones at high speed into following vehicles.',
    relatedRuleNumber: 288,
  },
  {
    id: 'road-works-lights',
    name: 'Traffic under signal control',
    category: SignCategory.RoadWorks,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: RED,
    textColor: WHITE,
    displayText: 'SIG',
    meaning: 'Traffic in the road works section ahead is controlled by temporary signals. Arrows indicate traffic may flow in both directions through the works.',
    whatToDo: 'Obey the temporary signals exactly as you would permanent traffic lights. Stop at red. Do not proceed until the signal shows green and the road ahead is clear.',
    commonMistake: 'Treating temporary signals as advisory. They carry the same legal force as permanent traffic lights — ignoring a red is an offence.',
    relatedRuleNumber: 288,
  },
  {
    id: 'contra-flow',
    name: 'Ramp',
    category: SignCategory.RoadWorks,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: RED,
    textColor: WHITE,
    displayText: 'RAMP',
    meaning: 'A ramp is present in the road works ahead, typically where the road surface changes level at the start or end of a works section.',
    whatToDo: 'Reduce speed before reaching the ramp. Cross it slowly and steadily to avoid bottoming out or losing control. Be especially careful when towing.',
    commonMistake: 'Taking a ramp at normal road speed. A sudden change in road level at speed can cause loss of control or vehicle damage.',
    relatedRuleNumber: 288,
  },
  {
    id: 'width-restriction-works',
    name: 'No road markings',
    category: SignCategory.RoadWorks,
    shape: 'rectangle',
    borderColor: RED,
    fillColor: RED,
    textColor: WHITE,
    displayText: 'NO MKG',
    meaning: 'Road markings have been removed or covered in the works area ahead. The distance shown indicates how far the markings are absent.',
    whatToDo: 'Follow the cones, signs, and any temporary road markings instead. Take extra care at junctions and where lane discipline is normally guided by markings.',
    commonMistake: 'Assuming the absence of markings means no rules apply. Normal traffic rules still apply — you must still keep to the correct side of the road.',
    relatedRuleNumber: 288,
  },
];

// ── Utility functions ─────────────────────────────────────────────────────────

export function getSignsByCategory(category: SignCategory): RoadSign[] {
  return roadSigns.filter((s) => s.category === category);
}

export function getSignById(id: string): RoadSign | undefined {
  return roadSigns.find((s) => s.id === id);
}

export function searchRoadSigns(query: string): RoadSign[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return roadSigns.filter(
    (s) =>
      s.name.toLowerCase().includes(q) ||
      s.meaning.toLowerCase().includes(q) ||
      s.whatToDo.toLowerCase().includes(q) ||
      s.category.toLowerCase().includes(q),
  );
}

export function generateQuiz(source: RoadSign[], count: number): QuizQuestion[] {
  const shuffled = [...source].sort(() => Math.random() - 0.5);
  const selected = shuffled.slice(0, Math.min(count, shuffled.length));
  return selected.map((sign) => {
    const wrongPool = roadSigns.filter((s) => s.id !== sign.id);
    const wrongs = wrongPool
      .sort(() => Math.random() - 0.5)
      .slice(0, 3)
      .map((s) => s.meaning);
    const options = [sign.meaning, ...wrongs].sort(() => Math.random() - 0.5);
    return { sign, options, correctIndex: options.indexOf(sign.meaning) };
  });
}
