import { Question, TopicCategory } from '@clearpass/core';

export const accidentsAndEmergenciesQuestions: Question[] = [
  {
    id: "AB2957",
    questionText: "Who can use a public access defibrillator (AED)?",
    options: [
    "Paramedics only",
    "First aiders only",
    "Doctors only",
    "Everyone",
    ],
    correctIndex: 3,
    explanation: "All AEDs give you easy-to-follow verbal and/or visual instructions. The 999 operator will direct you to the nearest AED, if you need to use one.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2958",
    questionText: "You’re asked to fetch a defibrillator (AED). What’s the best way to find the nearest AED?",
    options: [
    "Follow the arrows on marker posts",
    "The 999 operator will direct you",
    "Ask your vehicle’s built-in sat nav",
    "Check the casualty’s belongings",
    ],
    correctIndex: 1,
    explanation: "The sooner an AED is used, the better the chances of survival for the casualty. The 999 operator will direct you to the nearest AED, if it’s necessary.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2959",
    questionText: "You’re performing cardiopulmonary resuscitation (CPR) on a casualty. Someone stops to help. What should you get them to do?",
    options: [
    "Fetch a blanket",
    "Fetch a first aid kit",
    "Fetch a defibrillator",
    "Fetch a privacy screen",
    ],
    correctIndex: 2,
    explanation: "A defibrillator (AED) could improve the casualty’s chances of survival. Do not stop CPR to fetch an AED, but if there’s someone else with you, you can send them to get one. The 999 operator will direct you to the nearest AED, if you need to use one.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2960",
    questionText: "You need to use a defibrillator (AED) on a casualty, how will you know how to use it?",
    options: [
    "You need to be trained to use an AED",
    "The AED gives you visual and verbal instructions",
    "You must read the AED’s instruction manual",
    "The casualty will tell you what to do",
    ],
    correctIndex: 1,
    explanation: "AEDs are simple to use. They give you visual and verbal instructions and will not shock a casualty unless it’s required.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2961",
    questionText: "You’re performing cardiopulmonary resuscitation (CPR) on a 6-year-old child. How’s it different to performing CPR on an adult?",
    options: [
    "You may only need one hand and press down 4 to 5 cm",
    "You should press twice as fast but more gently",
    "You should press more slowly but more firmly",
    "You can only use 2 fingers and press down 1 to 2 cm",
    ],
    correctIndex: 0,
    explanation: "When performing CPR on an adult, you should use 2 hands and press down 5 to 6 cm.\r\nFor a child, you may only need to use one hand and should only press down 4 to 5 cm.\r\nFor an infant, you should use 2 fingers and press down about a third of their chest depth.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2962",
    questionText: "You’re performing cardiopulmonary resuscitation (CPR) on a casualty. When should you stop CPR?",
    options: [
    "When you need to talk to the 999 operator",
    "When you’ve completed 5 minutes of compressions",
    "When you want to fetch a defibrillator (AED)",
    "When they start breathing or a healthcare professional takes over",
    ],
    correctIndex: 3,
    explanation: "You should not stop CPR unless\r\n•\tthe casualty begins showing ‘signs of life’ like breathing normally\r\n•\ta healthcare professional takes over\r\n•\tthe AED tells you to stop.\r\nYou can use speaker phone to allow you to continue performing CPR while talking to the operator.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2963",
    questionText: "You arrive at the scene of an incident. You see a casualty who’s not moving. What should you do first?",
    options: [
    "Check if it’s safe to approach the casualty",
    "Begin cardiopulmonary resuscitation (CPR)",
    "Start looking for a defibrillator (AED)",
    "Move the casualty into the recovery position",
    ],
    correctIndex: 0,
    explanation: "The first thing to do is to assess the situation for danger. You need to make sure that there are no further risks. If you go to help and get hurt, then there are 2 casualties.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2964",
    questionText: "You’re performing cardiopulmonary resuscitation (CPR) on a casualty. How fast should chest compressions be?",
    options: [
    "Once per second",
    "Twice per second",
    "3 times per second",
    "Once every 5 seconds",
    ],
    correctIndex: 1,
    explanation: "When performing CPR, you should press down hard and fast in the centre of the casualty’s chest. You should aim for about 2 compressions per second and keep going until the casualty starts breathing normally or a healthcare professional takes over.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2949",
    questionText: "There's been a collision. A motorcyclist is lying injured and unconscious. Why should you only remove their helmet if it’s essential?",
    options: [
    "They might not want you to remove it",
    "Removing it could make any injuries worse",
    "Removing it could let them get cold",
    "You could scratch the helmet as you remove it",
    ],
    correctIndex: 1,
    explanation: "When someone is injured, any movement that’s not absolutely necessary should be avoided, since it could make the injuries worse. Unless it's essential to remove a motorcyclist's helmet, it’s generally safer to leave it in place.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB4422",
    questionText: "You're on a motorway. When can you use hazard warning lights?",
    options: [
    "When a vehicle is following too closely",
    "When you slow down quickly because of danger ahead",
    "When you're being towed by another vehicle",
    "When you're using the hard shoulder as a running lane",
    ],
    correctIndex: 1,
    explanation: "Briefly using your hazard warning lights will warn the traffic behind you that there's a hazard ahead. Turn them off again when following drivers have seen and responded to your signal.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2618",
    questionText: "When are you allowed to use hazard warning lights?",
    options: [
    "When stopped and temporarily obstructing traffic",
    "When travelling during darkness without headlights",
    "When parked on double yellow lines to visit a shop",
    "When travelling slowly because you're lost",
    ],
    correctIndex: 0,
    explanation: "You must not use hazard warning lights while moving, except to warn traffic behind when you slow suddenly on a motorway or unrestricted dual carriageway.\r\nNever use hazard warning lights to excuse dangerous or illegal parking.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2690",
    questionText: "What should you do if you have to stop while you're going through a congested tunnel?",
    options: [
    "Pull up very close to the vehicle in front to save space",
    "Ignore any message signs, as they're never up to date",
    "Keep a safe distance from the vehicle in front",
    "Make a U-turn and find another route",
    ],
    correctIndex: 2,
    explanation: "It’s important to keep a safe distance from the vehicle in front at all times. This still applies in congested tunnels, even if you're moving very slowly or have stopped. If the vehicle in front breaks down, you may need room to manoeuvre past it.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2855",
    questionText: "You arrive at the scene of a crash where someone is bleeding heavily from a wound in their arm. Nothing is embedded in the wound. What could you do to help?",
    options: [
    "Walk them around and keep them talking",
    "Dab the wound",
    "Get them a drink",
    "Apply pressure over the wound",
    ],
    correctIndex: 3,
    explanation: "If possible, lay the casualty down. Protect yourself from exposure to blood and, when you're sure there's nothing in the wound, apply firm pressure using clean material.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2862",
    questionText: "You're at an incident. What could you do to help an unconscious casualty?",
    options: [
    "Take photographs of the scene",
    "Check that they're breathing normally",
    "Move them to somewhere more comfortable",
    "Splash their face with cool water",
    ],
    correctIndex: 1,
    explanation: "If a casualty is unconscious, you need to check that they're breathing normally. Look for chest movements, look and listen for breathing, and feel for breath on your cheek.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2865",
    questionText: "A casualty is not breathing normally and needs cardiopulmonary resuscitation (CPR). At what rate should you press down and release on the centre of their chest?",
    options: [
    "10 times per minute",
    "120 times per minute",
    "60 times per minute",
    "240 times per minute",
    ],
    correctIndex: 1,
    explanation: "If a casualty is not breathing normally, CPR may be needed to maintain circulation. Place 2 hands on the centre of the chest and press down hard and fast –  around 5 to 6 centimetres and about twice a second.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2867",
    questionText: "Following a collision, a person has been injured. What would be a warning sign for shock?",
    options: [
    "Flushed complexion",
    "Warm dry skin",
    "Slow pulse",
    "Rapid shallow breathing",
    ],
    correctIndex: 3,
    explanation: "The effects of shock may not be immediately obvious. Warning signs to look for include\r\n•  a rapid pulse\r\n•  sweating\r\n•  pale skin\r\n•  rapid shallow breathing.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2870",
    questionText: "An injured person has been placed in the recovery position. They're unconscious but breathing normally. What else should be done?",
    options: [
    "Press firmly between their shoulders",
    "Place their arms by their side",
    "Give them a hot sweet drink",
    "Check their airway remains open",
    ],
    correctIndex: 3,
    explanation: "After a casualty has been placed in the recovery position, make sure their airway remains open and monitor their condition until medical help arrives. Where possible, do not move a casualty unless there’s further danger.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2879",
    questionText: "An injured motorcyclist is lying unconscious in the road. The traffic has stopped and there's no further danger. What could you do to help?",
    options: [
    "Remove their safety helmet",
    "Seek medical assistance",
    "Move the person off the road",
    "Remove their leather jacket",
    ],
    correctIndex: 1,
    explanation: "If someone has been injured, the sooner proper medical attention is given the better. Ask someone to phone for help or do it yourself. An injured person should only be moved if they’re in further danger. An injured motorcyclist’s helmet should not be removed unless it's essential.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2891",
    questionText: "What should you do if you see a large box fall from a lorry onto the motorway?",
    options: [
    "Go to the next emergency telephone and report the hazard",
    "Catch up with the lorry and try to get the driver's attention",
    "Stop close to the box until the police arrive",
    "Pull over to the hard shoulder, then remove the box",
    ],
    correctIndex: 0,
    explanation: "Lorry drivers can be unaware of objects falling from their vehicles. If you see something fall onto a motorway, look to see if the driver pulls over. If they do not stop, do not attempt to retrieve the object yourself. Pull onto the hard shoulder near an emergency telephone and report the hazard.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2900",
    questionText: "You're going through a long tunnel. What will warn you of congestion or an incident ahead?",
    options: [
    "Hazard warning lines",
    "Other drivers flashing their lights",
    "Variable message signs",
    "Areas with hatch markings",
    ],
    correctIndex: 2,
    explanation: "Follow the instructions given by the signs or by tunnel officials. In congested tunnels, a minor incident can soon turn into a major one, with serious or even fatal results.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2905",
    questionText: "An adult casualty is not breathing. To maintain circulation, cardiopulmonary resuscitation (CPR) should be given. What's the correct depth to press down on their chest?",
    options: [
    "1 to 2 centimetres",
    "5 to 6 centimetres",
    "10 to 15 centimetres",
    "15 to 20 centimetres",
    ],
    correctIndex: 1,
    explanation: "An adult casualty is not breathing normally. To maintain circulation, place 2 hands on the centre of the chest. Then press down hard and fast – around 5 to 6 centimetres and about twice a second.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2914",
    questionText: "You're the first person to arrive at an incident where people are badly injured. You’ve switched on your hazard warning lights and checked all engines are stopped. What else should you do?",
    options: [
    "Make sure that an ambulance has been called",
    "Stop other cars and ask the drivers for help",
    "Try and get people who are injured to drink something",
    "Move the people who are injured clear of their vehicles",
    ],
    correctIndex: 0,
    explanation: "If you’re the first to arrive at a crash scene, the first concerns are the risk of further collision and fire. Making sure that vehicle engines are switched off will reduce the risk of fire. Use hazard warning lights so that other traffic knows there’s a need for caution. Make sure the emergency services are contacted; do not assume it's already been done.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2915",
    questionText: "You arrive at the scene of a motorcycle crash. The rider is injured. When should their helmet be removed?",
    options: [
    "Only when it's essential",
    "Always straight away",
    "Only when the motorcyclist asks",
    "Always, unless they're in shock",
    ],
    correctIndex: 0,
    explanation: "Do not remove a motorcyclist's helmet unless it's essential. Remember they may be suffering from shock. Do not give them anything to eat or drink, but do reassure them confidently.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2917",
    questionText: "You arrive at an incident. There's no danger from fire or further collisions and the emergency services have been called. What's your first priority when attending to an unconscious motorcyclist?",
    options: [
    "Check whether they're breathing normally",
    "Check whether they're bleeding",
    "Check whether they have any broken bones",
    "Check whether they have any bruising",
    ],
    correctIndex: 0,
    explanation: "At the scene of an incident, always be aware of danger from further collisions or fire. The first priority when dealing with an unconscious person is to make sure they can breathe. This may involve clearing their airway if you can see an obstruction or if they’re having difficulty breathing.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2920",
    questionText: "At an incident, someone is unconscious and you want to help. What would be the first thing to check?",
    options: [
    "Whether their vehicle is insured",
    "Whether they have any allergies",
    "Whether they're comfortable",
    "Whether their airway is open",
    ],
    correctIndex: 3,
    explanation: "Give whatever first aid you can and stay with the injured person until a medical professional takes over.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2921",
    questionText: "What could you do to help injured people at an incident?",
    options: [
    "Keep them warm and comfortable",
    "Give them something to eat",
    "Keep them on the move by walking them around",
    "Give them a warm drink",
    ],
    correctIndex: 0,
    explanation: "There are a number of things you can do to help, even without expert training. Be aware of further danger from other traffic and fire; make sure the area is safe. People may be in shock. Do not give them anything to eat or drink. Keep them warm and comfortable and reassure them. Do not move injured people unless there’s a risk of further danger.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2924",
    questionText: "There's been a collision. How can you help a driver who's suffering from shock?",
    options: [
    "Give them a drink",
    "Reassure them confidently",
    "Ask who caused the incident",
    "Offer them a sugary snack",
    ],
    correctIndex: 1,
    explanation: "A casualty suffering from shock may have injuries that are not immediately obvious. Call the emergency services, then stay with the person in shock, offering reassurance until the experts arrive.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2926",
    questionText: "You arrive at the scene of a motorcycle crash. No other vehicle is involved. The rider is unconscious and lying in the middle of the road. What's the first thing you should do at the scene?",
    options: [
    "Move the rider out of the road",
    "Warn other traffic",
    "Clear the road of debris",
    "Give the rider reassurance",
    ],
    correctIndex: 1,
    explanation: "The motorcyclist is in an extremely vulnerable position, exposed to further danger from traffic. Approaching vehicles need advance warning in order to slow down and safely take avoiding action or stop. Do not put yourself or anyone else at risk. Use the hazard warning lights on your vehicle to alert other road users to the danger.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2927",
    questionText: "At an incident, how could you help a small child who’s not breathing?",
    options: [
    "Find their parents and explain what's happening",
    "Open their airway and begin cardiopulmonary resuscitation (CPR)",
    "Put them in the recovery position and slap their back",
    "Talk to them confidently until an ambulance arrives",
    ],
    correctIndex: 1,
    explanation: "If a young child has stopped breathing, first check that their airway is open and then begin CPR. With a young child, you may only need to use one hand and you should not press down as far as you would with an adult. Continue the procedure until the child is breathing again or until a medical professional takes over.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2928",
    questionText: "At an incident, a casualty is not breathing. What should you do while helping them to start breathing again?",
    options: [
    "Put their arms across their chest",
    "Shake them firmly",
    "Roll them onto their side",
    "Open their airway",
    ],
    correctIndex: 3,
    explanation: "It’s important to make sure that the airway is open before you start cardiopulmonary resuscitation (CPR). To open the casualty’s airway, place your fingers under their chin and lift it forward.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2930",
    questionText: "At an incident, someone is suffering from severe burns. How could you help them?",
    options: [
    "Apply lotions to the injury",
    "Burst any blisters",
    "Remove anything sticking to the burns",
    "Douse the burns with clean, cool water",
    ],
    correctIndex: 3,
    explanation: "Your priority is to cool the burns with clean, cool water. Its coolness will help take the heat out of the burns and relieve the pain. Keep the wound doused for at least 20 minutes. If blisters appear, do not attempt to burst them, as this could lead to infection.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2931",
    questionText: "You arrive at an incident. A pedestrian is bleeding heavily from a leg wound. The leg is not broken and there's nothing in the wound. How could you help?",
    options: [
    "Dab the wound to stop the bleeding",
    "Keep the casualty's legs flat on the ground",
    "Give them a warm drink",
    "Apply firm pressure over the wound",
    ],
    correctIndex: 3,
    explanation: "You should protect yourself from exposure to blood, and then apply firm pressure over the wound to stem the flow of blood. As soon as practical, fasten a pad to the wound with a bandage or length of cloth. Use the cleanest material available.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2932",
    questionText: "At an incident, a casualty is unconscious but breathing. When should you move them?",
    options: [
    "When an ambulance is on its way",
    "When bystanders tell you to move them",
    "When there's a risk of further danger",
    "When bystanders offer to help you",
    ],
    correctIndex: 2,
    explanation: "Do not move a casualty unless there's further danger; for example, from other traffic or fire. They may have unseen or internal injuries. Moving them unnecessarily could cause further injury. Do not remove a motorcyclist’s helmet unless it’s essential.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2934",
    questionText: "At an incident, it's important to look after any casualties. What should you do with them when the area is safe?",
    options: [
    "Move them away from the vehicles",
    "Ask them how it happened",
    "Give them something to eat",
    "Keep them where they are",
    ],
    correctIndex: 3,
    explanation: "When the area is safe and there's no danger from other traffic or fire, it's better not to move casualties. Moving them may cause further injury.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2935",
    questionText: "Which sign shows that a tanker is carrying dangerous goods?",
    options: [
    "Yellow rectangular plate outlined in red with the black text 'LONG VEHICLE'",
    "Orange diamond-shaped hazard plate with a black flame symbol, the code '1089' and the panel marked '2YE'",
    "Red triangular plate with white diagonal chevron stripes, used as a hazard marker on a long or slow-moving vehicle",
    "Red-bordered white triangle warning sign with a bold black exclamation mark",
    ],
    correctIndex: 1,
    optionImages: [
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4055.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4051.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4627.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4517.png",
    ],
    explanation: "Tankers will display a hazard warning plate on the side and rear of the vehicle. Details of hazard warning symbols are given in The Highway Code. If a tanker is involved in a collision, you may need to report the tanker's hazard labelling to the emergency services.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2936",
    questionText: "Which document may the police ask you to produce after you've been involved in a collision?",
    options: [
    "Your vehicle registration document",
    "Your driving licence",
    "Your theory test certificate",
    "Your vehicle service record",
    ],
    correctIndex: 1,
    explanation: "You must stop if you've been involved in a collision that results in injury or damage. The police may ask to see your driving licence and insurance details at the time or later at a police station.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2937",
    questionText: "After a collision, someone is unconscious in their vehicle. When should you call the emergency services?",
    options: [
    "Only as a last resort",
    "As soon as possible",
    "After you've woken them up",
    "After checking for broken bones",
    ],
    correctIndex: 1,
    explanation: "It's important to make sure that the emergency services arrive as soon as possible. When a person is unconscious, they could have serious injuries that are not immediately obvious.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2945",
    questionText: "A collision has just happened. An injured person is lying in a busy road. What’s the first thing you should do?",
    options: [
    "Treat the person for shock",
    "Warn other traffic",
    "Place them in the recovery position",
    "Make sure the injured person is kept warm",
    ],
    correctIndex: 1,
    explanation: "The most immediate danger is further collisions and fire. You could warn other traffic by switching on hazard warning lights, displaying an advance warning triangle or sign (but not on a motorway), or by any other means that does not put you or others at risk.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2946",
    questionText: "At an incident, how could you help a casualty who has stopped breathing?",
    options: [
    "Keep their head tilted forwards as far as possible",
    "Begin cardiopulmonary resuscitation (CPR)",
    "Raise their legs to help with circulation",
    "Try to give them something to drink",
    ],
    correctIndex: 1,
    explanation: "You should begin CPR on someone who has stopped breathing as soon as possible. If someone can help, send them to find the nearest defibrillator (AED). You should continue CPR until a healthcare professional can take over or the casualty starts breathing again.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "AB2947",
    questionText: "You’re at the scene of an incident. How could you help someone who's suffering from shock?",
    options: [
    "Reassure them confidently",
    "Keep them moving",
    "Give them a warm drink",
    "Offer them some food",
    ],
    correctIndex: 0,
    explanation: "If someone is suffering from shock, try to keep them warm and as comfortable as you can. Do not give them anything to eat or drink but reassure them confidently and try not to leave them alone.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1252",
    questionText: "You've broken down on a two-way road. You have a warning triangle. At least how far from your vehicle should you place the warning triangle?",
    options: [
    "5 metres (16 feet)",
    "25 metres (82 feet)",
    "45 metres (147 feet)",
    "100 metres (328 feet)",
    ],
    correctIndex: 2,
    explanation: "Advance warning triangles fold flat and do not take up much room. Use one to warn other road users if your vehicle has broken down or if there has been an incident. Place it at least 45 metres (147 feet) behind your vehicle (or the incident), on the same side of the road or verge. Place it further back if the scene is hidden by, for example, a bend, hill or dip in the road. Do not use warning triangles on motorways.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1254",
    questionText: "Your car breaks down on a level crossing. What's the first thing you should do?",
    options: [
    "Tell drivers behind what's happened",
    "Leave your vehicle and get everyone clear",
    "Walk down the track and signal the next train",
    "Stay in your car until you're told to move",
    ],
    correctIndex: 1,
    explanation: "If your vehicle breaks down on a level crossing, your first priority is to get everyone out of the vehicle and clear of the crossing. Then use the railway telephone, if there is one, to tell the signal operator. If you have time before the train arrives, move the vehicle clear of the crossing, but only do this if the alarm signals are not activated.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1256",
    questionText: "What should you do if a tyre bursts while you’re driving?",
    options: [
    "Pull on the parking brake",
    "Brake as quickly as possible",
    "Pull up slowly at the side of the road",
    "Continue on at a normal speed",
    ],
    correctIndex: 2,
    explanation: "A tyre bursting can lead to a loss of control, especially if you’re travelling at high speed. Using the correct procedure should help you to stop the vehicle safely.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1259",
    questionText: "What should you do if your vehicle has a puncture on a motorway?",
    options: [
    "Drive slowly to the next service area to get assistance",
    "Pull up on the hard shoulder or in an emergency area. Change the wheel as quickly as possible",
    "Pull up on the hard shoulder or in an emergency area and call for assistance",
    "Switch on your hazard warning lights. Stop in your lane",
    ],
    correctIndex: 2,
    explanation: "Pull up on the hard shoulder or in an emergency area and call for assistance. \r\nDo not attempt to repair your vehicle while it's on the hard shoulder, because of the risk posed by traffic passing at high speeds.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1363",
    questionText: "Your vehicle has stalled in the middle of a level crossing. What should you do if the warning bells start to ring while you're trying to restart the engine?",
    options: [
    "Get out of the car and clear of the crossing",
    "Run down the track to warn the signal operator",
    "Carry on trying to restart the engine",
    "Push the vehicle clear of the crossing",
    ],
    correctIndex: 0,
    explanation: "If the warning bells ring, leave the vehicle and get any passengers well clear of the crossing immediately.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1611",
    questionText: "What should you do before driving into a tunnel?",
    options: [
    "Switch off your radio",
    "Take off your sunglasses",
    "Close your sunroof",
    "Switch on your windscreen wipers",
    ],
    correctIndex: 1,
    explanation: "If you're wearing sunglasses, you should remove them before driving into a tunnel. If you do not, your vision will be restricted, even in tunnels that appear to be well lit.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1612",
    questionText: "Which lights should you use when you're driving in a tunnel?",
    options: [
    "Sidelights",
    "Front spotlights",
    "Dipped headlights",
    "Rear fog lights",
    ],
    correctIndex: 2,
    explanation: "Before entering a tunnel, you should switch on your dipped headlights, as this will allow you to see and be seen. In many tunnels, it's a legal requirement. \r\nDo not wear sunglasses while you're driving in a tunnel.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1623",
    questionText: "What should you do to reduce the risk of your vehicle catching fire?",
    options: [
    "Keep water levels above maximum",
    "Check out any strong smell of fuel",
    "Avoid driving with a full tank of fuel",
    "Use fuel additives",
    ],
    correctIndex: 1,
    explanation: "The fuel in your vehicle can be a dangerous fire hazard. If you smell fuel, check out where it's coming from. Never\r\n• use a naked flame near the vehicle if you can smell fuel\r\n• smoke when refuelling your vehicle.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1649",
    questionText: "You're driving on the motorway. What should you do if luggage falls from your vehicle?",
    options: [
    "Stop at the next emergency telephone and report the incident",
    "Stop on the motorway and switch on hazard warning lights while you pick it up",
    "Walk back up the motorway to pick it up",
    "Pull up on the hard shoulder and wave traffic down",
    ],
    correctIndex: 0,
    explanation: "If any object falls onto the motorway carriageway from your vehicle, pull onto the hard shoulder near an emergency telephone and call for assistance. Do not stop on the carriageway or attempt to retrieve anything.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1700",
    questionText: "What should you do if an instrument panel warning light comes on while you're driving?",
    options: [
    "Continue if the engine sounds all right",
    "Hope that it's just a temporary electrical fault",
    "Deal with the problem when there's more time",
    "Check out the problem quickly and safely",
    ],
    correctIndex: 3,
    explanation: "Make sure you know what the different warning lights mean. An illuminated warning light could mean that your car is unsafe to drive.  If you’re not sure about the problem, get a qualified mechanic to check it.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1704",
    questionText: "What should you do if your vehicle breaks down in a tunnel?",
    options: [
    "Stay in your vehicle and wait for the police",
    "Stand in the lane behind your vehicle to warn others",
    "Stand in front of your vehicle to warn oncoming drivers",
    "Switch on hazard warning lights, then go and call for help",
    ],
    correctIndex: 3,
    explanation: "A broken-down vehicle in a tunnel can cause serious congestion and danger to other road users. If your vehicle breaks down, get help without delay. Switch on your hazard warning lights, then go to an emergency telephone to call for help.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1721",
    questionText: "What should you do if your vehicle catches fire while you're driving through a tunnel?",
    options: [
    "Leave it where it is, with the engine running",
    "Pull up, then walk to an emergency telephone",
    "Park it away from the carriageway",
    "Drive it out of the tunnel if it's safe to do so",
    ],
    correctIndex: 3,
    explanation: "If it’s possible, and you can do so without causing further danger, it may be safer to drive a vehicle that's on fire out of a tunnel. The greatest danger in a tunnel fire is smoke and suffocation.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1785",
    questionText: "What should you do first if your vehicle has broken down on an automatic railway level crossing?",
    options: [
    "Get everyone out of the vehicle and clear of the crossing",
    "Telephone your vehicle recovery service to move it",
    "Walk along the track to give warning to any approaching trains",
    "Try to push the vehicle clear of the crossing as soon as possible",
    ],
    correctIndex: 0,
    explanation: "First, get yourself and anyone else well away from the crossing. If there’s a railway telephone, use that to get instructions from the signal operator. Then, if there’s time, move the vehicle clear of the crossing.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1788",
    questionText: "What's the first thing you must do if you have a collision while you're driving your car?",
    options: [
    "Stop only if someone waves at you",
    "Call the emergency services",
    "Stop at the scene of the incident",
    "Call your insurance company",
    ],
    correctIndex: 2,
    explanation: "If you're in a collision that causes damage or injury to any other person, vehicle, animal or property, by law you must stop. Give your name, the vehicle owner’s name and address, and the vehicle’s registration number to anyone who has reasonable grounds for requesting them.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
  {
    id: "BB1790",
    questionText: "What information should you share if you’re involved in a collision that causes damage to another vehicle?",
    options: [
    "Your occupation and reason for your journey",
    "Your name, address and vehicle registration number",
    "Your national insurance number",
    "Your internet service provider",
    ],
    correctIndex: 1,
    explanation: "Try to keep calm and do not rush. Make sure that you've shared all the relevant details with the other driver before you leave the scene. If possible, take pictures and note the positions of all the vehicles involved.",
    topicCategory: TopicCategory.AccidentsAndEmergencies,
    difficulty: 1,
  },
];
