import { Question, TopicCategory } from '@clearpass/core';

export const alertnessQuestions: Question[] = [
  {
    id: "AB2001",
    questionText: "What should you do before making a U-turn?",
    options: [
    "Give an arm signal as well as using your indicators",
    "Check road markings to see that U-turns are permitted",
    "Look over your shoulder for a final check",
    "Select a higher gear than normal",
    ],
    correctIndex: 2,
    explanation: "If you have to make a U-turn, slow down and make sure that the road is clear in both directions. Make sure that the road is wide enough for you to carry out the manoeuvre safely. Use your mirrors and look round to check it's safe before turning across the road.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2003",
    questionText: "What should you do as you approach this bridge?",
    options: [
    "Move to the right",
    "Slow down",
    "Change gear",
    "Keep to 30 mph",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1263.jpg",
    explanation: "You should slow down and be cautious. Hump bridges are often narrow and there may not be enough room for you to pass an oncoming vehicle at this point. Also, there's no footpath, so be aware of pedestrians in the road.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2005",
    questionText: "Where should you avoid overtaking?",
    options: [
    "Just after a bend",
    "In a one-way street",
    "On a dual carriageway",
    "Approaching a dip in the road",
    ],
    correctIndex: 3,
    explanation: "Oncoming vehicles or other hazards can be hidden from view by dips in the road. If you cannot see into the dip, wait until you have a clear view and can see that it's safe before starting to overtake.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2007",
    questionText: "What does this curved arrow road marking mean?",
    options: [
    "Heavy vehicles should take the next road on the left to avoid a weight limit",
    "The road ahead bends to the left",
    "Overtaking traffic should move back to the left",
    "The road ahead has a camber to the left",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1887.jpg",
    explanation: "In this picture, the road marking shows that overtaking drivers or riders need to return to the left. These markings show the direction drivers must pass hatch markings or solid double white lines. They're also used to show the route that high vehicles should take under a low arched bridge.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2008",
    questionText: "What should you do if your mobile phone rings while you're driving or riding?",
    options: [
    "Stop immediately",
    "Answer it immediately",
    "Leave it until you have stopped in a safe place",
    "Pull up at the nearest kerb",
    ],
    correctIndex: 2,
    explanation: "It’s illegal to use a hand-held mobile or similar device when driving or riding, except in a genuine emergency. The safest option is to switch off your mobile phone before you set off, and use a message service. If you've forgotten to switch your phone off and it rings, you should leave it. When you've stopped in a safe place, you can see who called and return the call if necessary.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2009",
    questionText: "Why are these yellow lines painted across the road?",
    options: [
    "To help you choose the correct lane",
    "To help you keep the correct separation distance",
    "To make you aware of your speed",
    "To tell you the distance to the roundabout",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW9937.jpg",
    explanation: "These lines are often found on the approach to a roundabout or a dangerous junction. They give you extra warning to adjust your speed. Look well ahead and do this in good time.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2501",
    questionText: "What should you do when you're approaching traffic lights that have been green for some time?",
    options: [
    "Accelerate hard",
    "Maintain your speed",
    "Be ready to stop",
    "Brake hard",
    ],
    correctIndex: 2,
    explanation: "The longer traffic lights have been green, the sooner they'll change. Allow for this as you approach traffic lights that you know have been green for a while. They're likely to change soon, so you should be prepared to stop.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2636",
    questionText: "What should you do before slowing down or stopping your vehicle?",
    options: [
    "Sound the horn",
    "Use the mirrors",
    "Select a higher gear",
    "Flash the headlights",
    ],
    correctIndex: 1,
    explanation: "Before slowing down or stopping, check the mirrors to see what's happening behind you. Also assess what's ahead and make sure you give the correct signal if it will help other road users.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2702",
    questionText: "You're following a large vehicle. Why should you stay a safe distance behind it?",
    options: [
    "You'll be able to corner more quickly",
    "You'll help the large vehicle to stop more easily",
    "You'll give the driver a chance to see you in their mirrors",
    "You'll keep out of the wind better",
    ],
    correctIndex: 2,
    explanation: "If you're following a large vehicle but are so close to it that you cannot see its exterior mirrors, the driver will not be able to see you. Keeping well back will also allow you to see the road ahead by looking past the large vehicle.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2828",
    questionText: "Why should you use your mirrors when you see a hazard ahead?",
    options: [
    "Because you'll need to accelerate out of danger",
    "To assess how your actions will affect the traffic behind",
    "Because you'll need to brake sharply and stop",
    "To check what's happening on the road ahead",
    ],
    correctIndex: 1,
    explanation: "You should be constantly scanning the road for clues about what's going to happen next. Check your mirrors regularly, particularly as soon as you spot a hazard. What's happening behind may affect how you respond to hazards ahead.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "AB2829",
    questionText: "You're waiting to turn right at the end of a road. What should you do if your view is obstructed by parked vehicles?",
    options: [
    "Stop and then move forward slowly and carefully for a clear view",
    "Move quickly to where you can see so you only block traffic from one direction",
    "Wait for a pedestrian to let you know when it's safe for you to emerge",
    "Turn your vehicle around immediately and find another junction to use",
    ],
    correctIndex: 0,
    explanation: "At junctions, your view is often restricted by buildings, trees or parked cars. You need to be able to see in order to judge a safe gap. Edge forward slowly and keep looking all the time. Do not cause other road users to change speed or direction as you emerge.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1002",
    questionText: "There are objects hanging from your interior mirror. Why could this be a hazard?",
    options: [
    "Your view could be obstructed",
    "Your sun visor might get tangled",
    "Your radio reception might be affected",
    "Your windscreen could mist up more easily",
    ],
    correctIndex: 0,
    explanation: "Make sure that you can see clearly through the windscreen of your vehicle. Stickers or hanging objects could obstruct your view or draw your attention away from the road.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1005",
    questionText: "You're on a long motorway journey. What should you do if you start to feel sleepy?",
    options: [
    "Play some loud music",
    "Stop on the hard shoulder for a rest",
    "Drive faster to complete your journey sooner",
    "Leave the motorway and stop in a safe place",
    ],
    correctIndex: 3,
    explanation: "If you feel sleepy, you should leave the motorway at a service area or at the next exit and stop in a safe place to rest. A supply of fresh air can help to keep you alert before you reach the exit, but it’s not a substitute for stopping and resting.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1007",
    questionText: "Why should you switch your headlights on when it first starts to get dark?",
    options: [
    "To make your dials easier to see",
    "So others can see you more easily",
    "So that you blend in with other drivers",
    "Because the street lights are lit",
    ],
    correctIndex: 1,
    explanation: "Your headlights and tail lights help others on the road to see you. It may be necessary to turn on your headlights during the day if visibility is reduced; for example, due to heavy rain. In these conditions, the light might fade before the street lights are timed to switch on. Be seen to be safe.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1287",
    questionText: "What’s most likely to distract you while you’re driving?",
    options: [
    "Using a mobile phone",
    "Using the windscreen wipers",
    "Using the demisters",
    "Using the mirrors",
    ],
    correctIndex: 0,
    explanation: "Except for emergencies, it’s illegal to use a hand-held mobile phone while you're driving. Even using a hands-free kit can severely distract your attention.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1294",
    questionText: "You're driving your car. When may you use a hand-held mobile phone?",
    options: [
    "When you're receiving a call",
    "When you've parked safely",
    "When you're driving at less than 30 mph",
    "When your car has automatic transmission",
    ],
    correctIndex: 1,
    explanation: "It's illegal to use a hand-held mobile phone while you're driving, except in a genuine emergency. Even using a hands-free kit can distract your attention. Park in a safe and convenient place before receiving or making a call or using text messaging. Then you'll also be free to take notes or refer to papers.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1366",
    questionText: "You're driving on a wet road. What should you do if you have to stop your vehicle in an emergency?",
    options: [
    "Apply the parking brake and footbrake together",
    "Keep both hands on the steering wheel",
    "Select reverse gear",
    "Give an arm signal",
    ],
    correctIndex: 1,
    explanation: "As you drive, look well ahead and all around so that you’re ready for any hazards that might develop. If you have to stop in an emergency, react as soon as you can while keeping control of the vehicle. Keep both hands on the steering wheel so you can control the vehicle's direction of travel.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1390",
    questionText: "What should you do when you move off from behind a parked car?",
    options: [
    "Give a signal after moving off",
    "Look around before moving off",
    "Look around after moving off",
    "Use the exterior mirrors only",
    ],
    correctIndex: 1,
    explanation: "Before moving off, you should use both the interior and exterior mirrors to check that the road is clear. Look around to check the blind spots and, if necessary, give a signal to warn other road users of your intentions. Also look well ahead as you'll have to steer out into the road to pass the parked car.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1439",
    questionText: "You're travelling along this road. How should you pass the cyclist?",
    options: [
    "Sound your horn as you pass",
    "Keep close to them as you pass",
    "Leave them plenty of room as you pass",
    "Change down one gear before you pass",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/BB1439.png",
    explanation: "Allow the cyclist plenty of room in case they wobble or swerve around a pothole or raised drain. Look well ahead before you start to overtake, because you'll need to cross the hazard line. Look for entrances where vehicles could be waiting to pull out.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1573",
    questionText: "When do windscreen pillars cause a serious obstruction to your view?",
    options: [
    "When you're driving on a motorway",
    "When you're driving on a dual carriageway",
    "When you're approaching a one-way street",
    "When you're approaching bends and junctions",
    ],
    correctIndex: 3,
    explanation: "Windscreen pillars can obstruct your view, particularly at bends and junctions. Look out for other road users – especially cyclists, motorcyclists and pedestrians who can easily be overlooked.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1595",
    questionText: "What should you do if you cannot see clearly behind when you're reversing?",
    options: [
    "Open the window to look behind",
    "Open the door to look behind",
    "Look in the nearside mirror",
    "Ask someone to guide you",
    ],
    correctIndex: 3,
    explanation: "If you want to turn your car around, try to find a place where you have good all-round vision. If this is not possible, and you’re unable to see clearly, then get someone to guide you.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1626",
    questionText: "What does the term ‘blind spot’ mean?",
    options: [
    "An area covered by your right-hand mirror",
    "An area not covered by your headlights",
    "An area covered by your left-hand mirror",
    "An area not visible to the driver",
    ],
    correctIndex: 3,
    explanation: "Modern vehicles provide the driver with a good view of both the road ahead and behind using well-positioned mirrors. However, the mirrors cannot see every angle of the scene behind and to the sides of the vehicle. It’s essential that you know when and how to check the vehicle's blind spots, so that you’re aware of any hidden hazards.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1629",
    questionText: "What's likely to happen if you use a hands-free phone while you're driving?",
    options: [
    "It will improve your safety",
    "It will increase your concentration",
    "It will reduce your view",
    "It will divert your attention",
    ],
    correctIndex: 3,
    explanation: "Talking to someone while you're driving can distract you and, unlike when someone is in the car with you, the person on the other end of a mobile phone is unable to see the traffic situations you're dealing with. They will not stop speaking to you even if you're approaching a hazardous situation. You need to concentrate on your driving at all times.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1632",
    questionText: "You're turning right onto a dual carriageway. What should you do before emerging?",
    options: [
    "Stop, apply the parking brake and then select a low gear",
    "Position your vehicle well to the left of the side road",
    "Check that the central reservation is wide enough for your vehicle",
    "Make sure that you leave enough room for a vehicle behind",
    ],
    correctIndex: 2,
    explanation: "Before emerging right onto a dual carriageway, make sure that the central reservation is deep enough to protect your vehicle. If it’s not, you should treat the dual carriageway as one road and check that it’s clear in both directions before pulling out. Neglecting to do this could place part or all of your vehicle in the path of approaching traffic and cause a collision.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1633",
    questionText: "You're waiting to emerge from a junction. The windscreen pillar is restricting your view. What should you be particularly aware of?",
    options: [
    "Lorries",
    "Buses",
    "Motorcyclists",
    "Coaches",
    ],
    correctIndex: 2,
    explanation: "Windscreen pillars can completely block your view of pedestrians, motorcyclists and cyclists. You should make a particular effort to look for these road users; do not just rely on a quick glance.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: "BB1726",
    questionText: "How can you make sure that a satellite navigation (sat nav) system does not distract you when you're driving?",
    options: [
    "Turn it off while you're driving in built-up areas",
    "Choose a voice that you find calming",
    "Only set the destination when you're lost",
    "Set it before starting your journey",
    ],
    correctIndex: 3,
    explanation: "Sat navs can be useful when driving on unfamiliar routes. However, they can also distract you and cause you to lose control if you look at or adjust them while you're driving. Set the sat nav before starting your journey, or pull up in a safe place before making any changes to it.",
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
];
