// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const alertnessQuestions: Question[] = [
  {
    id: 'ALT_001',
    questionText: 'You start to feel tired while driving on a motorway. What should you do?',
    options: [
      'Open a window and turn the radio up to stay stimulated',
      'Pull off at the next exit and rest in a safe place',
      'Speed up to reach your destination sooner',
      'Drink an energy drink and keep going',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rule 91 states you must stop at a safe place if you feel sleepy. Opening a window or stimulants only delay the problem - the only cure for tiredness is rest.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_002',
    questionText: 'You need to make a phone call while driving. What must you do?',
    options: [
      'Use the phone on loudspeaker while holding it on your lap',
      'Keep the call very brief and drive carefully',
      'Find a safe place to pull over before making the call',
      'Only make the call when stopped at traffic lights',
    ],
    correctIndex: 2,
    explanation:
      'It is illegal to hold a mobile phone while driving. Even hands-free calls can be a distraction. You should always find a safe place to stop before using a phone.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_003',
    questionText: 'How does driver fatigue affect your ability to drive?',
    options: [
      'It makes you more cautious and slows you down beneficially',
      'It has no effect if you are on a familiar route',
      'It significantly slows your reaction time and reduces concentration',
      'It only affects driving after more than four hours on the road',
    ],
    correctIndex: 2,
    explanation:
      'Fatigue is one of the leading causes of road accidents. It impairs judgement, slows reaction times, and can cause drivers to fall asleep at the wheel without warning.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_004',
    questionText: 'You are driving and feel hungry. You have a sandwich on the passenger seat. What is the safest action?',
    options: [
      'Eat while driving using one hand on the wheel',
      'Stop in a safe place before eating',
      'Eat quickly while stopped at traffic lights',
      'Ask a passenger to feed you while you drive',
    ],
    correctIndex: 1,
    explanation:
      'Eating while driving is a distraction that takes your hands off the wheel and your eyes off the road. You should always stop safely before eating or drinking.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_005',
    questionText: 'What is the most effective way to stay alert on a long motorway journey?',
    options: [
      'Drive faster to shorten the journey time',
      'Keep the car warm and the heater on full',
      'Take regular breaks - at least every two hours',
      'Turn up the radio and sing along',
    ],
    correctIndex: 2,
    explanation:
      'Highway Code Rule 91 recommends taking a break of at least 15 minutes after every two hours of driving. Monotonous motorway driving accelerates fatigue, making regular stops essential.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_006',
    questionText: 'You are taking prescription medication that may cause drowsiness. What should you do before driving?',
    options: [
      'Drive only on familiar roads where you know the route',
      'Check with your doctor or pharmacist whether it is safe to drive',
      'Take half the dose so the drowsiness effect is reduced',
      'Drive only in daylight and avoid motorways',
    ],
    correctIndex: 1,
    explanation:
      'Some prescription and over-the-counter medicines can impair driving. Always consult your doctor or pharmacist before driving while on medication. Driving whilst impaired by drugs - including prescribed ones - is an offence.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_007',
    questionText: 'What is the danger of carbon monoxide inside a vehicle?',
    options: [
      'It causes the windows to steam up and reduces visibility',
      'It is an odourless gas that can cause drowsiness and loss of consciousness',
      'It affects the fuel mixture and reduces engine performance',
      'It only affects passengers, not the driver',
    ],
    correctIndex: 1,
    explanation:
      'Carbon monoxide is colourless and odourless, making it impossible to detect without an alarm. A faulty exhaust or heater can introduce it into the cabin, causing drowsiness and eventually unconsciousness.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_008',
    questionText: 'How often should you check your mirrors while driving on an open road?',
    options: [
      'Only when you intend to turn or change speed',
      'At least every 8 to 12 seconds as a general guide',
      'Once every 30 seconds is sufficient',
      'Only when another vehicle is close behind you',
    ],
    correctIndex: 1,
    explanation:
      'Effective observation requires checking mirrors frequently - approximately every 8 to 12 seconds - so you always have an up-to-date picture of what is around you. Always check mirrors before signalling, changing speed, or changing position.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_009',
    questionText: 'What is a "microsleep" and why is it dangerous for drivers?',
    options: [
      'A very short but deliberate nap taken during a rest break',
      'An involuntary episode of sleep lasting seconds, often without the driver realising',
      'A state of reduced alertness caused by bright sunshine',
      'A period of inattention caused by distracting passengers',
    ],
    correctIndex: 1,
    explanation:
      'A microsleep is an involuntary, brief loss of consciousness lasting from a fraction of a second to several seconds. The driver is completely unaware it has happened. At 70mph, a 4-second microsleep means travelling blind for over 100 metres.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_010',
    questionText: 'You want to adjust your satellite navigation system. The safest thing to do is:',
    options: [
      'Make quick adjustments at traffic lights',
      'Ask a passenger to operate it while you drive',
      'Pull over in a safe place before making any adjustments',
      'Programme it while travelling below 20mph',
    ],
    correctIndex: 2,
    explanation:
      'Interacting with a sat nav while moving is a distraction. Even brief glances away from the road increase collision risk significantly. Always stop safely before making adjustments to any in-vehicle device.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_011',
    questionText: 'Driving at night is more tiring than driving during the day. Why?',
    options: [
      'Road surfaces are colder and require more steering effort',
      'Your body naturally wants to sleep during the night hours',
      'Headlights consume extra power that drains concentration',
      'Oncoming headlights cause pupils to constrict repeatedly',
    ],
    correctIndex: 1,
    explanation:
      'The body\'s natural circadian rhythm promotes sleep at night. This means alertness is inherently lower during night driving, making fatigue build faster. Drivers should be especially vigilant on late-night journeys.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_012',
    questionText: 'An oncoming vehicle has its full-beam headlights on, dazzling you. What should you do?',
    options: [
      'Flash your own full-beam to signal them to dip their lights',
      'Close one eye to protect your night vision',
      'Slow down and look towards the left edge of the road until they pass',
      'Pull over and stop until the dazzle has passed',
    ],
    correctIndex: 2,
    explanation:
      'Flashing back can dazzle the other driver. Looking towards the left edge of the road avoids direct exposure to the glare and gives you a reference point. Slow down, as your effective vision is reduced until the vehicle passes.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_013',
    questionText: 'You have been driving for three hours without a break and you feel fine. Should you still stop?',
    options: [
      'No - only stop if you feel tired',
      'Yes - fatigue can build up without you being aware of it',
      'No - three hours is within safe driving guidelines',
      'Yes - but only if travelling at motorway speeds',
    ],
    correctIndex: 1,
    explanation:
      'Fatigue can develop gradually and impair your driving before you feel obviously tired. Highway Code Rule 91 advises taking at least a 15-minute break every two hours regardless of how you feel.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_014',
    questionText: 'Which of these is most likely to cause a driver to lose concentration?',
    options: [
      'Driving in light rain on a well-lit road',
      'Talking on a hands-free mobile phone while on a dual carriageway',
      'Using cruise control on a clear motorway at the speed limit',
      'Driving a familiar route in good weather',
    ],
    correctIndex: 1,
    explanation:
      'Research shows that hands-free phone calls are almost as distracting as handheld calls because the mental demand of a conversation diverts attention from the driving task. The distraction is cognitive, not just physical.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_015',
    questionText: 'You are about to start a long journey and feel tired. What should you do?',
    options: [
      'Start the journey and stop if you become drowsy on the way',
      'Delay your journey and get adequate sleep before setting off',
      'Drink two cups of strong coffee before departing',
      'Set a shorter route to reduce the total driving time',
    ],
    correctIndex: 1,
    explanation:
      'Setting off while tired is dangerous. The only safe solution is to delay the journey until you are properly rested. Caffeine and other stimulants provide only temporary relief and cannot substitute for sleep.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_016',
    questionText: 'The sun is low and directly ahead of you, making it difficult to see the road. What should you do?',
    options: [
      'Speed up to pass through the affected area quickly',
      'Slow down, use your sun visor, and wear sunglasses if available',
      'Switch on your headlights to help other drivers see you',
      'Drive close behind the vehicle ahead to use it as a shield',
    ],
    correctIndex: 1,
    explanation: 'Low sun can be as dangerous as fog. Reduce your speed, use the sun visor, and wear good quality sunglasses if available. Never drive so close to another vehicle that you cannot stop safely.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_017',
    questionText: 'Which of the following is an early warning sign that you are becoming too tired to drive safely?',
    options: [
      'Your eyes feel dry and itchy',
      'You keep yawning and your eyes feel heavy',
      'You feel thirsty and need to stop for a drink',
      'Your hands feel slightly numb from holding the steering wheel',
    ],
    correctIndex: 1,
    explanation: 'Yawning repeatedly and heavy eyes are key early warning signs of fatigue. Other signs include difficulty keeping your head up, drifting across lanes, and missing junctions. Act on these warnings immediately by finding somewhere safe to stop.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_018',
    questionText: 'Even one or two units of alcohol can affect your driving. What effect does this have?',
    options: [
      'No measurable effect if you wait 30 minutes before driving',
      'It improves confidence without meaningfully impairing ability',
      'It slows your reaction time and can make you feel overconfident',
      'It only affects driving ability if combined with medication',
    ],
    correctIndex: 2,
    explanation: 'Even small amounts of alcohol slow reaction times, impair judgement, and create a false sense of confidence. There is no safe level for driving - any amount increases crash risk. The safest approach is not to drink at all if you are driving.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_019',
    questionText: 'You are driving with the car heater on full. How might this affect you?',
    options: [
      'It has no effect on alertness if you are not already tired',
      'It can make you drowsy and reduce your concentration',
      'It increases alertness by keeping your muscles warm',
      'It only becomes a problem on journeys over two hours',
    ],
    correctIndex: 1,
    explanation: 'A warm, stuffy car interior promotes drowsiness. Keep the car well ventilated - a slightly cooler temperature helps maintain alertness. Do not rely on warmth for comfort at the expense of your concentration.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_020',
    questionText: 'You are about to enter a long road tunnel during daylight. What adjustment should you make?',
    options: [
      'Switch off your lights as the tunnel will be artificially lit',
      'Speed up slightly to minimise the time spent inside',
      'Switch on your headlights before entering',
      'Slow to 20 mph for the duration of the tunnel',
    ],
    correctIndex: 2,
    explanation: 'You must switch on headlights before entering any tunnel, regardless of the tunnel lighting. This makes your vehicle visible to others. Your eyes also need time to adjust from bright daylight to the darker environment.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_021',
    questionText: 'You are feeling angry after a frustrating incident before you started driving. What should you consider?',
    options: [
      'Drive faster to release the tension and calm down quickly',
      'Anger will not affect your driving if you concentrate harder',
      'Wait until you have calmed down before setting off',
      'Play music loudly to distract yourself from the anger',
    ],
    correctIndex: 2,
    explanation: 'Strong emotions such as anger, upset, or excitement can significantly impair concentration and lead to reckless decisions. If you are in a heightened emotional state, take time to calm down before driving.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_022',
    questionText: 'You are driving on a motorway when you feel a vibration through the tyres as you drift towards the edge. What was the cause?',
    options: [
      'Contraflow markings indicating a reduced speed zone',
      'Rumble strips designed to alert drowsy drivers drifting out of lane',
      'A change in road surface indicating a lower speed limit ahead',
      'Rough tarmac installed to improve wet-weather grip',
    ],
    correctIndex: 1,
    explanation: 'Rumble strips (also called sleeper lines) are designed to alert drivers who drift towards the edge of the carriageway due to fatigue. The vibration and noise are intended as a warning. If you experience them, stop and rest at the first safe opportunity.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_023',
    questionText: 'You have taken antihistamine tablets for hay fever. How might these affect your driving?',
    options: [
      'They have no effect on driving ability',
      'They can cause drowsiness and slow your reactions',
      'They improve concentration by reducing sneezing distractions',
      'They only impair driving if taken in high doses',
    ],
    correctIndex: 1,
    explanation: 'Many antihistamines cause drowsiness as a side effect. Always read the label - if drowsiness is listed, do not drive. Some newer antihistamines are less sedating, but you should still check with a pharmacist and be alert to any effects.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_024',
    questionText: 'You are driving on a motorway and begin to feel drowsy with no immediate exit available. What should you do?',
    options: [
      'Drive in the outside lane for a change of scenery',
      'Open your window for fresh air as a short-term measure and plan to stop at the next services',
      'Increase your speed to reduce journey time',
      'Switch on your hazard lights and slow to 30 mph',
    ],
    correctIndex: 1,
    explanation: 'Opening a window for fresh air can help briefly, but is not a substitute for rest. Use it only as a very short-term measure while planning to stop at the next services or junction. Never continue a long journey when drowsy.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_025',
    questionText: 'Research suggests driver fatigue is a factor in approximately what proportion of fatal road collisions in the UK?',
    options: [
      'Around 1 in 20',
      'Around 1 in 8',
      'Around 1 in 100',
      'Around 1 in 3',
    ],
    correctIndex: 1,
    explanation: 'Government and DVSA figures suggest tiredness contributes to roughly 1 in 8 fatal collisions in the UK. Fatigue-related crashes tend to be high-speed impacts because a sleeping driver makes no attempt to brake, making them more likely to be fatal.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_026',
    questionText: 'A child in the back seat is repeatedly distracting you while driving. What is the best course of action?',
    options: [
      'Reach behind to attend to the child while keeping one eye on the road',
      'Raise your voice to quieten the child without looking back',
      'Ignore the distraction and focus entirely on your driving',
      'Pull over safely, attend to the child, and continue when calm',
    ],
    correctIndex: 3,
    explanation: 'Turning to attend to children or passengers while moving is extremely dangerous. The correct action is to pull over in a safe place, deal with the situation calmly, and then continue. Distraction from passengers is a significant cause of accidents.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_027',
    questionText: 'When scanning for hazards on a busy urban road, where should your primary focus be?',
    options: [
      'The rear-view mirror, checking for following traffic',
      'The road well ahead, while also checking junctions, pavements, and mirrors regularly',
      'Directly in front of your vehicle to avoid potholes',
      'The nearside kerb to maintain your lane position',
    ],
    correctIndex: 1,
    explanation: 'Effective scanning means looking well ahead for developing hazards while regularly checking mirrors and monitoring junctions, parked vehicles, and pavements for pedestrians or cyclists. Good observation allows time to plan and respond without harsh braking.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_028',
    questionText: 'You are approaching a junction and notice a pedestrian looking at their phone. What should you do?',
    options: [
      'Flash your lights to alert them to your presence',
      'Sound your horn to make sure they see you',
      'Anticipate that they may step out and be prepared to stop',
      'Assume they will look up before stepping into the road',
    ],
    correctIndex: 2,
    explanation: 'A pedestrian distracted by a phone may not notice approaching vehicles. Anticipate the possibility that they step out without looking and be prepared to stop. This is the principle of defensive driving - expect the unexpected.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_029',
    questionText: 'You are driving past the scene of an accident on the opposite carriageway. Why is this particularly dangerous?',
    options: [
      'The accident may have spread debris across the central reservation',
      'Drivers naturally look at the incident, reducing attention on their own road ahead',
      'Emergency vehicle lights can trigger photosensitive conditions',
      'Traffic may suddenly reverse on the carriageway ahead',
    ],
    correctIndex: 1,
    explanation: 'Rubbernecking - slowing down and staring at an incident - is a significant cause of secondary collisions. Keep your eyes on your own road. Being distracted for even two seconds at motorway speeds can result in a serious collision.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_030',
    questionText: 'After stopping at motorway services for 20 minutes, you rejoin the motorway. What should you be aware of?',
    options: [
      'Your vehicle will need more fuel than usual after a break',
      'You may underestimate your speed as you re-accelerate to motorway speed',
      'You should use only the left-hand lane for the first five miles',
      'Tyre pressure drops significantly after stationary periods',
    ],
    correctIndex: 1,
    explanation: 'After stopping, high motorway speeds can feel slower than they actually are when you rejoin. Check your speedometer carefully rather than relying on your sense of speed. This effect is particularly pronounced after extended breaks.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_031',
    questionText: 'Why are energy drinks not a safe long-term solution to driver fatigue?',
    options: [
      'They raise blood pressure to dangerous levels within 30 minutes',
      'They provide a temporary boost but do not address underlying tiredness, which returns sharply',
      'They are only effective when combined with food',
      'They slow reaction times more than fatigue itself',
    ],
    correctIndex: 1,
    explanation: 'Caffeine and energy drinks can mask the feeling of tiredness briefly, but cannot reverse the cognitive impairment caused by fatigue. When the effect wears off, tiredness returns - often more severely. The only real remedy is sleep.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_032',
    questionText: 'You are driving and notice your thinking feels slow and your steering is less precise than usual. What does this most likely indicate?',
    options: [
      'Your power steering fluid may be low',
      'You are fatigued and should stop as soon as safely possible',
      'You are driving on a road with a poor surface',
      'Your tyres may be over-inflated',
    ],
    correctIndex: 1,
    explanation: 'Slow thinking, imprecise steering, and difficulty maintaining lane position are clear signs of driver fatigue. These symptoms show your brain is no longer processing information efficiently. Stop at the earliest safe opportunity and rest.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_033',
    questionText: 'Why is driving performance significantly worse between 2am and 6am compared to other times?',
    options: [
      'Roads are less well lit and markings less visible at these hours',
      'Traffic is lighter so drivers become less careful',
      'The body is at its lowest natural alertness in the early hours',
      'Most vehicles have colder engines which affect handling',
    ],
    correctIndex: 2,
    explanation: 'The circadian rhythm causes natural alertness to be at its lowest between roughly 2am and 6am, regardless of how much sleep you have had. This is the highest-risk period for fatigue-related collisions. Plan journeys to avoid this window if possible.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_034',
    questionText: 'You are driving in heavy rain with wipers on maximum. How does this affect the demands on you as a driver?',
    options: [
      'There is little difference as long as you can see the road ahead',
      'You need greater concentration to compensate for reduced visibility and increased stopping distances',
      'Rain reduces alertness requirements because traffic naturally slows',
      'The noise of rain helps keep drivers more alert',
    ],
    correctIndex: 1,
    explanation: 'Heavy rain reduces visibility, increases stopping distances on wet roads, and makes road markings harder to see. You must concentrate harder to maintain the same situational awareness. Reduce speed and increase your following distance.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_035',
    questionText: 'What does the Highway Code say about driving if you feel unfit through illness?',
    options: [
      'You may drive short distances if you feel able to cope',
      'You must not drive if your ability is impaired by illness',
      'You should inform the DVLA but may continue driving',
      'It is acceptable to drive as long as you avoid motorways',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 90 states you must exercise proper control of your vehicle at all times. If illness impairs your ability - including fever, severe cold, or any condition affecting consciousness or concentration - you must not drive.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_036',
    questionText: 'A friend suggests that loud music helps you stay alert when tired. Is this correct?',
    options: [
      'Yes - music stimulates the brain and effectively combats fatigue',
      'Yes - but only if you listen to unfamiliar music',
      'No - music can temporarily mask the symptoms of fatigue without curing it',
      'No - music impairs reactions regardless of tiredness',
    ],
    correctIndex: 2,
    explanation: 'While music may seem to help in the short term, it does not address underlying fatigue and may mask warning signs. Sustained driving while fatigued is dangerous regardless of stimuli. Stopping to rest is the only effective remedy.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_037',
    questionText: 'You have had less than five hours of sleep before a long motorway drive. How does this affect your crash risk?',
    options: [
      'It has minimal effect if you are an experienced driver',
      'It roughly doubles your crash risk compared to driving fully rested',
      'It only increases risk if the journey exceeds two hours',
      'You can compensate by driving at slightly below the speed limit',
    ],
    correctIndex: 1,
    explanation: 'Research shows that getting only 5 to 6 hours of sleep roughly doubles crash risk compared to driving fully rested. Less than 4 hours increases risk to levels comparable with drink-driving. Experience does not compensate for acute sleep deprivation.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_038',
    questionText: 'What is the purpose of scanning far ahead as well as close to your vehicle?',
    options: [
      'Looking far ahead is only useful on motorways and dual carriageways',
      'It allows you to identify hazards early and plan your response with more time',
      'It reduces the need to check your mirrors as frequently',
      'It primarily helps you avoid potholes and road surface defects',
    ],
    correctIndex: 1,
    explanation: 'Looking well ahead - typically 12 seconds or more in open conditions - gives you maximum time to plan and respond to developing hazards. Early identification means smoother, safer responses and less need for emergency braking.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_039',
    questionText: 'You are dazzled by low winter sun while driving. What is the best immediate action?',
    options: [
      'Put on your hazard lights so other drivers can see you',
      'Slow down and, if necessary, stop in a safe place until the glare improves',
      'Change to a higher gear to smooth the engine and steady the car',
      'Move to the right-hand side of your lane to avoid the sun angle',
    ],
    correctIndex: 1,
    explanation: 'If you cannot see clearly due to sun glare, you must slow down significantly. If the glare is severe enough to prevent safe driving, find a safe place to stop until conditions improve. Driving without adequate visibility can be fatal.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_040',
    questionText: 'How does driving in fog increase the demands on your alertness compared to normal conditions?',
    options: [
      'It does not increase demands significantly if your fog lights are on',
      'It requires you to process less information because the road is quieter',
      'It reduces visibility and makes hazards appear suddenly, requiring much greater concentration',
      'It only increases demands for drivers who wear glasses',
    ],
    correctIndex: 2,
    explanation: 'Fog severely restricts visibility, forcing you to react to hazards that appear suddenly. It also makes distances and speeds harder to judge. Reduce speed substantially and increase your following distance.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 1,
  },
  {
    id: 'ALT_041',
    questionText: 'You are driving on an unfamiliar road at night when your passengers are talking loudly. What should you do?',
    options: [
      'Ask your passengers to be quieter as you need to concentrate',
      'Turn the radio on to create a neutral background noise',
      'Speed up to complete the journey faster',
      'Focus on the conversation while relying on instinct to drive',
    ],
    correctIndex: 0,
    explanation: 'Noise and conversation from passengers can significantly reduce concentration, especially on unfamiliar roads at night. It is entirely reasonable - and safer - to ask passengers to quieten down when you need to concentrate on driving.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_042',
    questionText: 'Which of these situations should make you most alert for unexpected hazards?',
    options: [
      'Driving in the outside lane of a three-lane motorway',
      'Approaching a school at 3:30pm on a weekday',
      'Driving on a dual carriageway in daylight with light traffic',
      'Travelling on a rural road with no junctions visible ahead',
    ],
    correctIndex: 1,
    explanation: 'School finishing times (typically 3pm to 4pm on weekdays) significantly increase the risk of children running into the road without warning. Reduce speed, be prepared to stop, and watch closely for children on both sides of the road.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_043',
    questionText: 'You are driving and realise you cannot remember the last few miles of your journey. What does this suggest?',
    options: [
      'Your driving has become automatic - this is a positive sign',
      'You may have experienced a period of inattention or microsleep',
      'The road was uneventful and your brain correctly filed it as low priority',
      'You should check your fuel gauge in case it ran low briefly',
    ],
    correctIndex: 1,
    explanation: 'Gaps in memory about a journey are a serious warning sign of fatigue-related inattention or microsleep. This means you were effectively driving unconsciously. Stop immediately at a safe place and rest - continuing is extremely dangerous.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_044',
    questionText: 'Your satnav announces a turn but you are unsure which road it means. What should you do?',
    options: [
      'Glance at the screen briefly while driving slowly to check',
      'Take the most logical turn and recalculate if wrong',
      'Pull over safely to check the route before proceeding',
      'Follow the instruction regardless to keep traffic moving',
    ],
    correctIndex: 2,
    explanation: 'Uncertainty about navigation can lead to last-minute lane changes or sudden braking that endangers others. It is always safer to pull over, confirm your route, and proceed with certainty than to make a hasty decision at speed.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_045',
    questionText: 'What does Highway Code Rule 148 say about distractions while driving?',
    options: [
      'Only electronic devices are considered a dangerous distraction',
      'You should avoid distractions including eating, loud music, and adjusting controls while moving',
      'Brief distractions are permitted if traffic conditions are light',
      'Passengers may assist with tasks such as map-reading while you drive',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 148 warns against all unnecessary distractions, including eating or drinking, tuning the radio, arguing with passengers, or anything that takes attention from the road. Safe driving requires full concentration at all times.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_046',
    questionText: 'After a long flight, you hire a car. Why is this particularly risky for alertness?',
    options: [
      'Foreign vehicles have different handling characteristics',
      'Jet lag, unfamiliar controls, and possibly driving on the opposite side combine to greatly increase demand',
      'Hire cars are generally older and less reliable than personal vehicles',
      'Insurance restrictions prevent you driving at full concentration',
    ],
    correctIndex: 1,
    explanation: 'Jet lag causes fatigue and cognitive impairment similar to sleep deprivation. Combined with unfamiliar roads and possibly driving on the opposite side, the demands on alertness are very high. Rest adequately before driving after a long flight.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_047',
    questionText: 'When severely sleep-deprived, how quickly can a driver fall asleep at the wheel?',
    options: [
      'The Highway Code states a minimum of 20 seconds of warning',
      'Within seconds, with little or no reliable warning',
      'Sleep takes at least 10 minutes to overcome an alert driver',
      'Collapse into sleep typically takes 60 to 90 seconds from first drowsiness',
    ],
    correctIndex: 1,
    explanation: 'When severely sleep deprived, a driver can fall asleep within seconds of first feeling sleepy - there is no reliable warning period. This is why acting on the very first signs of fatigue is critical. By the time you feel seriously drowsy, sleep may be moments away.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
  {
    id: 'ALT_048',
    questionText: 'You are involved in a minor bump in a car park that was not your fault. You feel shaken. Should you drive home immediately?',
    options: [
      'Yes - driving will help calm your nerves as you focus on the road',
      'Yes - only serious accidents cause sufficient shock to impair driving',
      'No - shock and stress can impair concentration and reaction times',
      'No - you must wait for police to clear the scene first',
    ],
    correctIndex: 2,
    explanation: 'Even a minor accident can trigger an adrenaline response that leaves you shaken. Stress and emotional upset impair concentration and reaction times. Take time to calm down before driving - ask someone else to drive if possible.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_049',
    questionText: 'You notice your speed has been gradually creeping above the limit without you intending it to on a motorway. What does this suggest?',
    options: [
      'There may be a fault with the throttle or cruise control',
      'Your awareness of speed has drifted - a possible sign of reduced alertness',
      'Traffic conditions have changed and you naturally matched the flow',
      'Your speedometer may be inaccurate and should be checked',
    ],
    correctIndex: 1,
    explanation: 'Unintentional speed creep is a sign of reduced attention and can indicate early fatigue. Monitoring your speedometer regularly is part of alert driving. If you repeatedly speed up without noticing, consider stopping for a break.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 2,
  },
  {
    id: 'ALT_050',
    questionText: 'Which driving scenario is statistically associated with the highest proportion of fatigue-related crashes?',
    options: [
      'Urban roads during the morning rush hour',
      'Motorways and long dual carriageways in the early hours between 2am and 6am',
      'Rural B-roads in the afternoon',
      'Multi-storey car parks and service roads',
    ],
    correctIndex: 1,
    explanation: 'Long monotonous motorway driving in the early hours (2am to 6am) combines the highest fatigue risk period with conditions that promote inattention. Crash statistics consistently show this as the highest-risk scenario for sleep-related road accidents.',
    topicCategory: TopicCategory.Alertness,
    difficulty: 3,
  },
];
