// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const attitudeQuestions: Question[] = [
  {
    id: 'ATT_001',
    questionText: 'Another driver cuts in front of you aggressively. What is the correct response?',
    options: [
      'Flash your headlights and sound the horn to express your frustration',
      'Follow closely behind them as a warning',
      'Stay calm, drop back, and maintain a safe following distance',
      'Overtake them at the first opportunity to reclaim your position',
    ],
    correctIndex: 2,
    explanation:
      'Reacting aggressively to poor driving escalates danger for everyone. The Highway Code advises keeping calm and not allowing other drivers to affect your driving behaviour.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_002',
    questionText: 'According to the Highway Code, what is the only correct reason to flash your headlights at another driver?',
    options: [
      'To warn them of a speed camera ahead',
      'To indicate that they may proceed',
      'To let them know you are there',
      'To signal your intention to overtake',
    ],
    correctIndex: 2,
    explanation:
      'Highway Code Rule 110 states headlights should only be flashed to warn other road users of your presence. Flashing to beckon others forward or warn of speed cameras is not a recognised signal.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_003',
    questionText: 'A driver is tailgating you on a dual carriageway. What is the safest course of action?',
    options: [
      'Brake sharply to warn them to back off',
      'Gradually reduce your speed to create more space ahead, then let them pass',
      'Speed up to increase the gap between you',
      'Put your hazard lights on to signal the problem',
    ],
    correctIndex: 1,
    explanation:
      'Braking sharply risks a rear-end collision. By slowing gradually and creating space ahead, you increase the overall safety margin and allow the tailgater to pass when safe.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_004',
    questionText: 'You are waiting in slow-moving traffic at a pedestrian crossing. What should you always do?',
    options: [
      'Creep forward slowly to maintain momentum with the queue',
      'Keep the crossing clear so pedestrians can use it',
      'Move forward to prevent motorcyclists filtering through',
      'Signal to pedestrians when they can cross',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rule 191 requires drivers not to block pedestrian crossings. Stopping on a crossing is dangerous and illegal.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_005',
    questionText: 'What is the principal cause of road rage incidents?',
    options: [
      'Driving on unfamiliar or congested roads',
      'Poor road surface and adverse weather',
      'Perceived inconsiderate or selfish behaviour by other road users',
      'Driving a slow or underpowered vehicle',
    ],
    correctIndex: 2,
    explanation:
      'Road rage is most commonly triggered when drivers feel another road user has acted selfishly or dangerously. Recognising this helps you stay calm and avoid escalating situations.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_006',
    questionText: 'An emergency vehicle with flashing blue lights and a siren is approaching from behind. What must you do?',
    options: [
      'Speed up to get out of the way as quickly as possible',
      'Move over safely to let it pass, even if this means crossing a solid white line',
      'Stop immediately wherever you are',
      'Continue normally and let it find a way around',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rule 219 requires you to move over and let emergency vehicles pass. You may cross a solid white line to do so if it is safe. Never stop on a motorway hard shoulder to let them pass unless instructed.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_007',
    questionText: 'Between 11:30pm and 7:00am in a built-up area, when is it illegal to sound your horn?',
    options: [
      'When stationary, except to warn of immediate danger',
      'At any time, regardless of circumstances',
      'Only when other vehicles are present',
      'When parked, but not when moving',
    ],
    correctIndex: 0,
    explanation:
      'Highway Code Rule 112 prohibits sounding the horn when stationary between 11:30pm and 7:00am in a built-up area, except to avoid danger. The horn must never be used aggressively at any time.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_008',
    questionText: 'You are stuck behind a slow-moving vehicle on a country road. The safest attitude is to:',
    options: [
      'Sit right behind it to put pressure on the driver to pull over',
      'Sound your horn repeatedly to encourage the driver to speed up',
      'Be patient, hang back, and wait for a safe opportunity to overtake',
      'Overtake as soon as there is a gap in oncoming traffic, regardless of road markings',
    ],
    correctIndex: 2,
    explanation:
      'Tailgating a slow vehicle is dangerous and intimidating. The correct attitude is patience. Overtake only when you can see the road ahead is clear, road markings permit, and you have enough distance to complete the manoeuvre safely.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_009',
    questionText: 'You are running late and feeling frustrated. How should this affect your driving?',
    options: [
      'It should not affect your driving at all - drive as you normally would',
      'You can exceed the speed limit slightly to make up time on a clear road',
      'You should take less time checking mirrors to save seconds',
      'It is acceptable to park briefly on yellow lines if you are only stopping for a moment',
    ],
    correctIndex: 0,
    explanation:
      'Emotional states such as frustration or stress are known to impair judgement and increase risk-taking. You must never let time pressure lead you to speed, take shortcuts on safety checks, or park illegally.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_010',
    questionText: 'A large lorry needs to pull out from a side road and is having difficulty. What is the considerate action?',
    options: [
      'Maintain your speed - the lorry driver should wait for a proper gap',
      'Flash your headlights to show you are giving way, then slow to let it out',
      'Slow down and wave the lorry out if it is safe to do so',
      'Sound your horn to warn the lorry driver to stay where they are',
    ],
    correctIndex: 2,
    explanation:
      'Being courteous to other road users improves traffic flow and reduces frustration. Slowing and waving a large vehicle out when safe is considerate driving. Flashing headlights to beckon another driver is not a recognised signal.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_011',
    questionText: 'You notice that a driver ahead is swerving slightly and driving erratically. What should you do?',
    options: [
      'Overtake them quickly to get ahead before they cause an accident',
      'Flash your lights and sound your horn to alert them',
      'Keep well back and, when safe, report your concerns to the police',
      'Pull alongside and shout to them through your window',
    ],
    correctIndex: 2,
    explanation:
      'Erratic driving may indicate tiredness, illness, or impairment. Keep a safe distance, never attempt to confront the driver, and report your concerns to the police when it is safe to do so.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_012',
    questionText: 'What is "queue jumping" and why is it considered poor driving?',
    options: [
      'Driving too slowly in a queue, causing obstruction behind',
      'Forcing your way into a queue of traffic instead of waiting your turn',
      'Leaving a large gap in a queue and allowing too many vehicles to join',
      'Using an outside lane to pass slow traffic then merging at the last moment unnecessarily',
    ],
    correctIndex: 1,
    explanation:
      'Forcing into a queue without waiting your turn is selfish and can cause accidents. It creates frustration and can lead to aggressive reactions from other drivers. Patience and consideration are hallmarks of good driving.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 3,
  },
  {
    id: 'ATT_013',
    questionText: 'You want to turn right but traffic in the opposite direction is blocking your path. What should you do?',
    options: [
      'Sound your horn to ask oncoming drivers to move',
      'Wait patiently until there is a safe gap in oncoming traffic',
      'Edge slowly into the oncoming lane to make your intentions clear',
      'Flash your headlights to ask oncoming traffic to give way',
    ],
    correctIndex: 1,
    explanation:
      'When turning right you must give way to oncoming traffic. Wait safely until there is a clear gap before completing the manoeuvre. Do not use the horn or headlights to demand right of way.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_014',
    questionText: 'A pedestrian is still crossing the road as traffic lights change to green in your favour. What must you do?',
    options: [
      'Sound your horn gently to alert them to move',
      'Edge forward slowly to encourage them to hurry',
      'Wait until the pedestrian has safely cleared the road before proceeding',
      'Move off carefully, passing behind the pedestrian',
    ],
    correctIndex: 2,
    explanation:
      'Pedestrians who have already started crossing have priority and must be allowed to finish crossing safely. Green lights give permission to proceed only when the way is clear - they do not override a pedestrian\'s right to finish crossing.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_015',
    questionText: 'You are driving in a residential area at night and want to signal that you have arrived at a friend\'s house. Which is the acceptable method?',
    options: [
      'Sound the horn briefly so they hear you arrive',
      'Flash your headlights twice outside their house',
      'Phone or text them to let them know you have arrived',
      'Rev the engine to let them know you are there',
    ],
    correctIndex: 2,
    explanation:
      'Sounding the horn or revving the engine in a residential area at night is inconsiderate and potentially illegal. Using a phone to notify someone of your arrival is the courteous alternative that does not disturb neighbours.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 3,
  },
  {
    id: 'ATT_016',
    questionText: 'You are driving along a narrow country lane when you meet an oncoming vehicle. Neither of you can pass. What should you do?',
    options: [
      'Sound your horn to insist the other driver reverses',
      'Flash your headlights repeatedly until they give way',
      'Look for the nearest passing place and be prepared to reverse if necessary',
      'Both drivers should open their doors to judge the gap available',
    ],
    correctIndex: 2,
    explanation: 'On single-track roads, drivers should use passing places and be prepared to reverse to allow others to pass. The driver nearest a passing place on their left should pull in. Cooperation and patience are essential on narrow roads.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_017',
    questionText: 'What does a yellow box junction marked on the road mean?',
    options: [
      'You must not enter it under any circumstances',
      'You must not enter unless your exit road is clear, except when turning right and waiting for oncoming traffic',
      'You may wait inside it briefly if traffic ahead is slow',
      'It applies only to buses and taxis during peak hours',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 174 states you must not enter a yellow box junction unless your exit is clear. The only exception is when turning right and you are prevented from doing so only by oncoming traffic. Blocking box junctions causes dangerous gridlock.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_018',
    questionText: 'You are approaching a roundabout and a cyclist is ahead of you in the lane. What should you do?',
    options: [
      'Overtake the cyclist before reaching the roundabout',
      'Sound your horn to alert them that you intend to pass',
      'Give the cyclist plenty of space and do not overtake unless there is a clear opportunity',
      'Flash your headlights so they pull to the left and let you through',
    ],
    correctIndex: 2,
    explanation: 'Highway Code Rule 163 advises giving cyclists at least 1.5 metres of space when overtaking. At roundabouts, cyclists may ride in the centre of a lane for safety. Give them room and only pass when you can do so safely without cutting them up.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_019',
    questionText: 'You are approaching horses being ridden on the road. What is the correct action?',
    options: [
      'Sound your horn gently to warn the riders you are approaching',
      'Pass quickly so the horses have less time to be startled',
      'Slow down, pass wide, and be prepared to stop if the horse becomes unsettled',
      'Flash your headlights as a warning signal',
    ],
    correctIndex: 2,
    explanation: 'Highway Code Rule 215 states you should slow to a walk when passing horses, pass wide and slowly, and be prepared to stop if necessary. Horses can be startled by sudden noise or movement. Never sound your horn or accelerate sharply near horses.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_020',
    questionText: 'An aggressive driver is following very close behind you and making threatening gestures. What should you do?',
    options: [
      'Brake sharply to teach them a lesson',
      'Pull over and confront them to resolve the situation',
      'Stay calm, do not react, and if it continues drive to a busy public place or police station',
      'Speed up to put distance between you and them',
    ],
    correctIndex: 2,
    explanation: 'Confronting an aggressive driver can escalate the situation dangerously. Stay calm, do not make eye contact or gestures, and drive to a public place or police station if you feel threatened. Never stop in an isolated location.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_021',
    questionText: 'You are following a learner driver who is driving slowly and hesitantly. What should your attitude be?',
    options: [
      'Sound your horn to encourage them to drive with more confidence',
      'Overtake at the first opportunity regardless of road markings',
      'Be patient - everyone has to learn and impatient behaviour makes it harder for the learner',
      'Flash your headlights to alert them that they should pull over and let you pass',
    ],
    correctIndex: 2,
    explanation: 'Learner drivers are developing skills and may drive more cautiously than experienced drivers. Impatience or intimidation behind a learner increases their anxiety and the risk of mistakes. Being patient is the considerate and safer response.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_022',
    questionText: 'What is "undertaking" and when is it permitted on a motorway?',
    options: [
      'Passing on the left - always prohibited on motorways',
      'Passing on the left - permitted only in slow-moving queued traffic where the left lane is moving faster',
      'Passing on the left - permitted at any time if the driver ahead is driving below the speed limit',
      'Passing on the left - permitted only if you signal first',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 268 states you should not overtake on the left or move to a lane on the left to overtake. However, in slow-moving queued traffic, you may pass on the left if your lane is moving faster. Deliberate undertaking at speed is dangerous and illegal.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 3,
  },
  {
    id: 'ATT_023',
    questionText: 'You are looking for a parking space and see one outside someone\'s driveway. The driveway appears empty. Should you park there?',
    options: [
      'Yes, if the driveway is clearly empty it is acceptable to park briefly',
      'Yes, as long as you leave enough room for a small car to exit',
      'No - parking across a driveway is inconsiderate and may be illegal if it blocks access',
      'Yes, as long as there are no yellow lines on the road',
    ],
    correctIndex: 2,
    explanation: 'Parking across a private driveway obstructs the occupant and can be reported to the local authority. It is inconsiderate and may result in a penalty notice. Always park where you do not inconvenience residents or obstruct access.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_024',
    questionText: 'At a busy motorway merge point, signs say "merge in turn." What does this mean?',
    options: [
      'Traffic in the lane ending must stop and give way before merging',
      'Both lanes should take turns merging, one vehicle at a time, like a zip',
      'Only the left lane should merge - right lane traffic has priority',
      'Drivers in the merging lane should use hazard lights while waiting',
    ],
    correctIndex: 1,
    explanation: 'Merging in turn (sometimes called zip merging) means both lanes alternate entry - one vehicle from each lane in turn. This maximises throughput and is used at lane reductions during roadworks. Blocking to prevent merging causes dangerous situations.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_025',
    questionText: 'An ambulance following you with blue lights and sirens activated is unable to pass due to congestion. What should you do?',
    options: [
      'Speed up to create a gap in traffic ahead',
      'Pull over safely at the first opportunity to let it through',
      'Continue driving - the ambulance crew will find a way through',
      'Use your hazard lights and stop where you are immediately',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 219 requires you to give way to emergency vehicles. Pull over safely as soon as possible - not suddenly or dangerously. Never stop on a motorway hard shoulder solely to let an emergency vehicle pass.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_026',
    questionText: 'A school crossing patrol officer is holding up a stop sign. What must you do?',
    options: [
      'Slow down and prepare to stop only if children are visible',
      'Stop and wait until the officer has moved to the pavement and signals you to proceed',
      'Stop briefly and then move on if no more children are crossing',
      'Give way to children but you do not have to stop for the patrol officer',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 198 states you must stop when a school crossing patrol officer shows a stop sign. Wait until they have returned to the pavement and indicated it is safe to proceed. Failing to stop is an offence.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_027',
    questionText: 'You want to park close to a shop for convenience. The only space available is in a disabled parking bay and you do not have a blue badge. What should you do?',
    options: [
      'Park there briefly - disabled spaces are rarely needed at this time',
      'Park with two wheels on the pavement to leave the bay clear',
      'Find another space - parking in a disabled bay without a badge is illegal',
      'Park there if you will be less than 10 minutes',
    ],
    correctIndex: 2,
    explanation: 'Parking in a disabled bay without a valid blue badge is illegal and inconsiderate. It may prevent a disabled person from accessing essential services. Penalty fines apply and the vehicle may be clamped or removed.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_028',
    questionText: 'Is it acceptable to flash your headlights to warn other drivers of a speed camera or police speed check ahead?',
    options: [
      'Yes - it is a community courtesy widely practised',
      'Yes - as long as it does not dazzle oncoming drivers',
      'No - the Highway Code only permits flashing lights to warn of your presence, not to signal about speed enforcement',
      'No - it is only illegal if done within 50 metres of the camera',
    ],
    correctIndex: 2,
    explanation: 'Highway Code Rule 110 states that headlights should only be flashed to warn others of your presence. Using them to signal speed enforcement locations is not a recognised or legal use. It can also be construed as perverting the course of justice.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 3,
  },
  {
    id: 'ATT_029',
    questionText: 'You are driving a large vehicle and your slow progress is causing a queue behind you. What is the considerate action?',
    options: [
      'Speed up beyond your comfortable limit to reduce the queue',
      'Ignore the queue - other drivers must be patient',
      'Pull over when safe and allow the queue to pass before continuing',
      'Flash your hazard lights to warn drivers in the queue',
    ],
    correctIndex: 2,
    explanation: 'If you are causing a long queue on a road where overtaking is difficult, pulling over when safe to let traffic pass is considerate and improves safety for everyone. This applies particularly on narrow rural roads with limited passing opportunities.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_030',
    questionText: 'A motorcyclist rides up to the front of a queue at traffic lights. What should your attitude be?',
    options: [
      'Sound your horn as this is lane filtering and is illegal',
      'Move to prevent them passing - they must wait in the queue like everyone else',
      'Allow them to filter safely - lane filtering is legal and reduces congestion',
      'Accelerate away quickly when lights change to make them wait',
    ],
    correctIndex: 2,
    explanation: 'Motorcyclists are permitted to filter through slow or stationary traffic. This legal manoeuvre reduces congestion and is safer than leaving motorcyclists between lanes of fast-moving traffic. Give motorcyclists space and do not block their path deliberately.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_031',
    questionText: 'You are following a slow-moving farm tractor on a country road that prevents overtaking. How should you behave?',
    options: [
      'Sit very close behind it as a signal you want it to move over',
      'Sound your horn repeatedly to urge the driver to find a gateway and pull in',
      'Be patient and wait for a safe and legal opportunity to overtake',
      'Flash your headlights to indicate you want to pass',
    ],
    correctIndex: 2,
    explanation: 'Agricultural vehicles have as much right to use the road as any other vehicle. They often cannot go faster or pull over easily. The correct attitude is patience. Wait for a safe, clear, legal opportunity to overtake rather than intimidating the driver.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_032',
    questionText: 'You are involved in a minor bump with another driver who becomes aggressive. What should you do?',
    options: [
      'Argue your case firmly - do not let them bully you',
      'Stay calm, do not engage aggressively, exchange insurance details, and contact police if needed',
      'Drive away quickly to avoid a confrontation',
      'Record video of their behaviour on your phone',
    ],
    correctIndex: 1,
    explanation: 'After any collision, you must stop and exchange insurance details. If the other driver is aggressive, stay calm, call the police if you feel threatened, and do not engage in confrontation. Your safety is the priority.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_033',
    questionText: 'An elderly driver ahead of you is driving very slowly and appears uncertain. What should you do?',
    options: [
      'Overtake immediately as they are a hazard to other road users',
      'Sound your horn to alert them to the fact they are driving slowly',
      'Be patient and give them extra space - do not intimidate them',
      'Flash your headlights to suggest they pull over',
    ],
    correctIndex: 2,
    explanation: 'Elderly drivers may drive more cautiously, which is a rational response to declining reflexes. Impatience or intimidation makes them more anxious and more likely to make errors. Be patient and allow extra space.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_034',
    questionText: 'You are waiting to emerge from a side road and a driver on the main road flashes their headlights at you. What does this mean?',
    options: [
      'It is a definite signal that it is safe for you to emerge',
      'It means the driver is warning you of a hazard ahead',
      'It may mean the driver is giving way, but you should check it is safe before emerging',
      'It means the driver wants to turn into your road',
    ],
    correctIndex: 2,
    explanation: 'A flashed headlight is not a guaranteed safe signal - it may mean the driver intends to give way, or they may be flashing at someone else. Only you can judge when it is truly safe to emerge. Never pull out based solely on a flash.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_035',
    questionText: 'You are parked on a residential street and a delivery van is blocking the road while making a delivery. How should you react?',
    options: [
      'Sound your horn to hurry them up',
      'Try to squeeze past even if it means mounting the pavement',
      'Wait patiently - deliveries are often brief and part of everyday road use',
      'Report the van to the local authority immediately',
    ],
    correctIndex: 2,
    explanation: 'Delivery vehicles are essential services and may need to stop briefly in inconvenient locations. A patient attitude towards brief obstructions is part of considerate road use. If a delivery causes a prolonged hazard, you can report it calmly.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_036',
    questionText: 'You have been let out at a junction by a considerate driver. What is the appropriate response?',
    options: [
      'No acknowledgement is necessary - they were expected to give way',
      'Flash your hazard lights twice as a thank-you',
      'A brief acknowledgement such as a hand wave is courteous and appreciated',
      'Sound the horn briefly to show appreciation',
    ],
    correctIndex: 2,
    explanation: 'A brief hand wave to thank a driver who has given way is a courteous and positive habit. It acknowledges considerate behaviour and promotes goodwill. Hazard lights are not an approved signal for thanks, and the horn should not be used for social purposes.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_037',
    questionText: 'You park on the pavement because there are no other spaces nearby. Is this acceptable?',
    options: [
      'Yes, if you leave enough room for pedestrians to pass',
      'Yes, if you are only stopping for a few minutes',
      'No - pavement parking can trap pedestrians, wheelchair users, and pushchairs in the road',
      'Yes, as long as you are not on a red route or yellow lines',
    ],
    correctIndex: 2,
    explanation: 'Pavement parking forces pedestrians, wheelchair users, and people with pushchairs into the road, creating danger. Highway Code Rule 244 advises not to park on the pavement. In London it is already illegal; legislation is in progress elsewhere in the UK.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_038',
    questionText: 'Another driver makes a mistake that causes you to brake sharply, but no accident occurs. What is the appropriate response?',
    options: [
      'Follow them and confront them at the next safe opportunity',
      'Sound your horn at length to express your displeasure',
      'Accept that mistakes happen, stay calm, and continue driving safely',
      'Flash your headlights repeatedly to let them know what they did',
    ],
    correctIndex: 2,
    explanation: 'All drivers make mistakes occasionally. Reacting with aggression, horn use, or headlight flashing escalates the situation and can lead to road rage. The safest response is to stay calm, maintain your distance, and continue driving safely.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_039',
    questionText: 'You are stuck in a traffic jam and keep seeing the same car repeatedly pulling out of line and trying to cut in. What should you do?',
    options: [
      'Prevent them from merging by closing the gap in front of you',
      'Sound your horn to alert other drivers to their behaviour',
      'Stay calm, do not react, and allow normal traffic flow to manage the situation',
      'Follow them to report their number plate to the police',
    ],
    correctIndex: 2,
    explanation: 'Aggressive or inconsiderate behaviour from other drivers is best ignored. Attempting to block a driver escalates the situation and distracts you from safe driving. Staying calm and allowing the situation to resolve itself is the correct attitude.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_040',
    questionText: 'You are driving past roadworks with a 50 mph speed limit. Workers are on the road nearby. What is the correct attitude?',
    options: [
      'The 50 mph limit is advisory - keep to a speed you feel safe at',
      'The limit applies only during working hours',
      'Obey the speed limit strictly - road workers\' safety depends on drivers slowing down',
      'The limit only applies to the lane nearest the workers',
    ],
    correctIndex: 2,
    explanation: 'Roadworks speed limits are legally enforceable and are set to protect workers who may be very close to live traffic. Cameras often enforce these limits 24 hours a day. Exceeding the limit puts workers\' lives at risk.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_041',
    questionText: 'You are stationary at red traffic lights and feel the urge to check your mobile phone briefly. What should you do?',
    options: [
      'Check it quickly - you are stationary so it is safe',
      'Check it only if the queue is long and you will have time to put it away',
      'Leave it - using a handheld phone while the engine is running is illegal even when stationary',
      'Check it only if the phone is on the passenger seat',
    ],
    correctIndex: 2,
    explanation: 'It is illegal to use a handheld mobile phone while driving, which includes being stationary with the engine running at traffic lights. Fines and penalty points apply. Switch the phone to silent and leave it until you are parked with the engine off.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_042',
    questionText: 'You are merging from a motorway slip road onto a busy motorway. Who has priority?',
    options: [
      'Vehicles on the slip road - they must be allowed to merge',
      'There is no legal priority - both sides must cooperate',
      'Vehicles already on the motorway have priority',
      'The vehicle with more speed has priority',
    ],
    correctIndex: 2,
    explanation: 'Traffic already on the motorway has priority. Those joining from a slip road must match speed and find a safe gap. However, considerate motorway drivers will move to the middle or outer lane where possible to make merging easier.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_043',
    questionText: 'You accidentally cut up a motorcyclist. They ride up alongside you gesturing angrily. What is the safest response?',
    options: [
      'Roll down the window and apologise',
      'Speed up to get ahead of them',
      'Stay calm, do not engage or make eye contact, and maintain safe driving',
      'Pull over immediately and speak to them',
    ],
    correctIndex: 2,
    explanation: 'Engaging with an angry motorcyclist while moving is dangerous for both parties. Stay calm, do not react or make eye contact, and continue driving safely. If they are acting dangerously, report it to the police when it is safe to stop.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 3,
  },
  {
    id: 'ATT_044',
    questionText: 'You are driving in heavy spray and poor visibility. A cyclist ahead is hard to see. What attitude should guide your driving?',
    options: [
      'Sound your horn so the cyclist is aware of your presence',
      'Flash your headlights to warn the cyclist you are close',
      'Slow down significantly and give the cyclist much more space than you would in dry conditions',
      'Overtake quickly to get past before visibility worsens further',
    ],
    correctIndex: 2,
    explanation: 'Spray reduces visibility and stopping distances significantly. Cyclists are particularly vulnerable and can be very difficult to see in poor conditions. Slowing down and giving extra space is essential for the safety of vulnerable road users.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_045',
    questionText: 'You want to overtake a long vehicle such as an articulated lorry. What attitude should inform your decision?',
    options: [
      'Start the overtake and rely on the lorry driver to slow if needed',
      'Only commit to overtaking if you can see the road is clear far enough ahead to complete the manoeuvre safely',
      'Overtake in short stages using the lorry as cover from oncoming traffic',
      'Flash your headlights to signal the lorry to slow while you overtake',
    ],
    correctIndex: 1,
    explanation: 'Overtaking a long vehicle requires a much longer clear road ahead than overtaking a car. Never start the manoeuvre unless you can see it is safe to complete it fully. Committing to an overtake you cannot complete is extremely dangerous.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_046',
    questionText: 'You notice a driver in a car park struggling to reverse out because another car is parked too close. What is the considerate thing to do if you see this from your vehicle?',
    options: [
      'Sound your horn to alert other shoppers',
      'Drive past quickly so they have room to manoeuvre',
      'Stop and allow them extra space to complete the manoeuvre safely',
      'Wait in the space behind them until they have finished',
    ],
    correctIndex: 2,
    explanation: 'Being considerate in car parks means giving other drivers room to manoeuvre. Stopping to allow a struggling driver more space is a small act that prevents damage and frustration. Consideration for others in confined spaces reflects good driving attitude.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_047',
    questionText: 'You are driving and another driver makes a rude gesture at you. How should you respond?',
    options: [
      'Make a gesture back to let them know you will not be bullied',
      'Brake sharply to make them pay more attention',
      'Ignore it completely and focus on your driving',
      'Follow them to get their registration number',
    ],
    correctIndex: 2,
    explanation: 'Responding to rude gestures escalates aggression and distracts you from safe driving. The safest and most mature response is to ignore it entirely. Engaging with aggressive drivers puts you and others at risk.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_048',
    questionText: 'A disabled pedestrian using a mobility scooter is crossing in front of you at a junction. You have priority. What should you do?',
    options: [
      'Assert your right of way and proceed carefully',
      'Sound your horn to make them aware of your priority',
      'Wait patiently until they have safely completed their crossing',
      'Edge forward slowly to indicate they should hurry',
    ],
    correctIndex: 2,
    explanation: 'Vulnerable road users such as disabled pedestrians and mobility scooter users may need more time to cross. Regardless of legal priority, the considerate action is to wait patiently. Edging forward or sounding the horn is intimidating and dangerous.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: 'ATT_049',
    questionText: 'You are waiting at a level crossing with the barriers down. The train has passed but the barriers remain down. What should you do?',
    options: [
      'Drive around the barriers carefully if you can see the line is clear',
      'Sound your horn to alert the signal operator',
      'Wait patiently - there may be a second train approaching or a technical delay',
      'Reverse away from the crossing and find an alternative route immediately',
    ],
    correctIndex: 2,
    explanation: 'Level crossing barriers may remain down after a train has passed if a second train is approaching or if there is a technical fault. Never attempt to cross when barriers are down or lights are showing. Wait until barriers fully rise before proceeding.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
  {
    id: 'ATT_050',
    questionText: 'Which best describes the attitude of a responsible driver?',
    options: [
      'Always driving at the speed limit to maximise road efficiency',
      'Taking responsibility for their own safety and considering the safety of all other road users',
      'Asserting their right of way firmly at junctions and roundabouts',
      'Driving defensively only in poor weather or at night',
    ],
    correctIndex: 1,
    explanation: 'Responsible driving means taking responsibility for your own safety and having consideration for all other road users at all times - regardless of conditions or legal priority. Good attitude is the foundation of safe driving.',
    topicCategory: TopicCategory.Attitude,
    difficulty: 2,
  },
];
