import { Question, TopicCategory } from '@clearpass/core';

export const attitudeQuestions: Question[] = [
  {
    id: "AB2012",
    questionText: "What must you do when the amber light is flashing at a pelican crossing?",
    options: [
    "Stop and wait for the green light",
    "Stop and wait for the red light",
    "Give way to pedestrians waiting to cross",
    "Give way to pedestrians already on the crossing",
    ],
    correctIndex: 3,
    explanation: "Pelican crossings are signal-controlled crossings operated by pedestrians. Push-button controls change the signals. Pelican crossings have no red-and-amber stage before green; instead, they have a flashing amber light. This means you must give way to pedestrians who are on the crossing but if the crossing is clear you can continue.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2015",
    questionText: "Why should you never wave people across at pedestrian crossings?",
    options: [
    "Another vehicle may be coming",
    "They may not be looking",
    "It's safer for you to carry on",
    "They may not be ready to cross",
    ],
    correctIndex: 0,
    explanation: "If people are waiting to use a pedestrian crossing, slow down and be prepared to stop. Do not wave them across the road, because another driver may not have seen them, may not have seen your signal, and may not be able to stop safely.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2022",
    questionText: "Why is it dangerous to travel too close to the vehicle ahead?",
    options: [
    "Your engine will overheat",
    "Your mirrors will need adjusting",
    "Your view of the road ahead will be restricted",
    "Your sat nav will be confused",
    ],
    correctIndex: 2,
    explanation: "‘Tailgating’ is the term used when a driver or rider follows the vehicle in front too closely. It's dangerous because it restricts your view of the road ahead and leaves no safety margin if the vehicle in front needs to slow down or stop suddenly. Tailgating is often the underlying cause of rear-end collisions or multiple pile-ups.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2023",
    questionText: "What will happen if you follow this vehicle too closely?",
    options: [
    "Your brakes will overheat",
    "Your fuel consumption will be increased",
    "Your engine will overheat",
    "Your view ahead will be reduced",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1279.jpg",
    explanation: "Staying back will increase your view of the road ahead. This will help you to see any hazards that might occur and give you more time to react.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2025",
    questionText: "What's the minimum time gap you should leave when following a vehicle on a wet road?",
    options: [
    "One second",
    "2 seconds",
    "3 seconds",
    "4 seconds",
    ],
    correctIndex: 3,
    explanation: "Water will reduce your tyres' grip on the road. The safe separation gap of at least 2 seconds in dry conditions should be doubled, to at least 4 seconds, in wet weather.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2028",
    questionText: "You're being overtaken by a long, heavily laden lorry. What should you do if it's taking a long time for it to overtake?",
    options: [
    "Speed up",
    "Slow down",
    "Hold your speed",
    "Change direction",
    ],
    correctIndex: 1,
    explanation: "A long lorry with a heavy load will need more time to pass you than a car, especially on an uphill stretch of road. Slow down and allow the lorry to pass.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2029",
    questionText: "Which vehicle will use a blue flashing beacon?",
    options: [
    "Motorway maintenance",
    "Bomb disposal",
    "Snow plough",
    "Breakdown recovery",
    ],
    correctIndex: 1,
    explanation: "Emergency vehicles use blue flashing lights. If you see or hear one, move out of its way as soon as it's safe and legal to do so.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2031",
    questionText: "What should you do if you're being followed by an ambulance showing flashing blue lights?",
    options: [
    "Pull over as soon as it's safe to do so",
    "Accelerate hard to get away from it",
    "Maintain your speed and course",
    "Brake harshly and stop well out into the road",
    ],
    correctIndex: 0,
    explanation: "Pull over in a place where the ambulance can pass safely. Check that there are no bollards or obstructions in the road that will prevent it from passing.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2033",
    questionText: "What type of emergency vehicle is fitted with a green flashing beacon?",
    options: [
    "Fire engine",
    "Road gritter",
    "Ambulance",
    "Doctor's car",
    ],
    correctIndex: 3,
    explanation: "A green flashing beacon on a vehicle means the driver or passenger is a doctor on an emergency call. Give way to them if it's safe to do so. Be aware that the vehicle may be travelling quickly or may stop in a hurry.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2036",
    questionText: "Who should obey diamond-shaped traffic signs?",
    options: [
    "Tram drivers",
    "Bus drivers",
    "Lorry drivers",
    "Taxi drivers",
    ],
    correctIndex: 0,
    explanation: "These signs apply only to tram drivers, but you should know their meaning so that you're aware of the priorities and are able to anticipate the actions of the driver.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2037",
    questionText: "On a road where trams operate, which vehicles will be most at risk from the tram rails?",
    options: [
    "Cars",
    "Bicycles",
    "Buses",
    "Lorries",
    ],
    correctIndex: 1,
    explanation: "The narrow wheels of a bicycle can become stuck in the tram rails, causing the cyclist to stop suddenly, wobble or even lose balance altogether. The tramlines are also slippery, which could cause a cyclist to slide or fall off.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2040",
    questionText: "You're in a one-way street and want to turn right. Where should you position your vehicle when there are 2 lanes?",
    options: [
    "In the right-hand lane",
    "In the left-hand lane",
    "In either lane, depending on the traffic",
    "Just left of the centre line",
    ],
    correctIndex: 0,
    explanation: "When you’re in a one-way street and want to turn right, you should take up a position in the right-hand lane. This will allow other road users, not wishing to turn, to pass on the left. Indicate your intention and take up the correct position in good time.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2041",
    questionText: "You wish to turn right ahead. Why should you take up the correct position in good time?",
    options: [
    "To allow other drivers to pull out in front of you",
    "To give a better view into the road that you're joining",
    "To help other road users know what you intend to do",
    "To allow drivers to pass you on the right",
    ],
    correctIndex: 2,
    explanation: "If you wish to turn right into a side road, take up your position in good time. Move to the centre of the road when it's safe to do so. This will allow vehicles to pass you on the left. Early planning will show other traffic what you intend to do.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2503",
    questionText: "Which type of crossing allows cyclists to ride across with pedestrians?",
    options: [
    "Toucan",
    "Puffin",
    "Pelican",
    "Zebra",
    ],
    correctIndex: 0,
    explanation: "A toucan crossing is designed to allow pedestrians and cyclists to cross at the same time. Look out for cyclists approaching the crossing at speed.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2620",
    questionText: "You're travelling at the legal speed limit. What should you do if the vehicle behind approaches quickly, flashing its headlights?",
    options: [
    "Accelerate to make a gap behind you",
    "Touch the brakes sharply to show your brake lights",
    "Maintain your speed to prevent the vehicle from overtaking",
    "Allow the vehicle to overtake",
    ],
    correctIndex: 3,
    explanation: "Do not enforce the speed limit by blocking another vehicle’s progress. This will only cause frustration. Allow the other vehicle to pass when you can do so safely.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2643",
    questionText: "When should you flash your headlights at other road users?",
    options: [
    "When showing that you're giving way",
    "When showing that you're about to turn",
    "When telling them that you have right of way",
    "When letting them know that you're there",
    ],
    correctIndex: 3,
    explanation: "You should only flash your headlights to warn others of your presence. Do not use them to greet others, show impatience or give priority to other road users, because they could misunderstand your signal.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2644",
    questionText: "You're approaching an unmarked crossroads. How should you deal with the junction?",
    options: [
    "Accelerate and keep to the middle",
    "Slow down and keep to the right",
    "Accelerate and look to the left",
    "Slow down and look both ways",
    ],
    correctIndex: 3,
    explanation: "Be cautious, especially when your view is restricted by objects like hedges, bushes, walls and large vehicles. In the summer months, these junctions can become more difficult to deal with, because growing foliage may further obscure your view.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2699",
    questionText: "The conditions are good and dry. When should you use the 'two-second rule'?",
    options: [
    "Before restarting the engine after it has stalled",
    "When checking your gap from the vehicle in front",
    "Before using the 'Mirrors - Signal - Manoeuvre' routine",
    "When traffic lights change to green",
    ],
    correctIndex: 1,
    explanation: "In good conditions, the 'two-second rule' can be used to check the distance between your vehicle and the one in front. This technique works on roads carrying faster traffic. Choose a fixed object, such as a bridge, sign or tree. When the vehicle ahead passes this object, say to yourself 'Only a fool breaks the two-second rule.' If you reach the object before you finish saying this, you're too close.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2703",
    questionText: "Which colour follows the green signal at a puffin crossing?",
    options: [
    "Steady red",
    "Flashing amber",
    "Steady amber",
    "Flashing green",
    ],
    correctIndex: 2,
    explanation: "Puffin crossings have infra-red sensors that detect when pedestrians are crossing and hold the red traffic signal until the crossing is clear. The use of a sensor means there's no flashing amber phase as there is with a pelican crossing.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2704",
    questionText: "You're in a line of traffic. What action should you take if the driver behind is following very closely?",
    options: [
    "Ignore the driver behind and continue to travel within the speed limit",
    "Slow down, gradually increasing the gap between you and the vehicle in front",
    "Signal left and wave the driver behind to come past",
    "Move over to a position just left of the centre line of the road",
    ],
    correctIndex: 1,
    explanation: "If the driver behind is following too closely, there’s a danger they’ll collide with the back of your vehicle if you stop suddenly. You can reduce this risk by slowing down and increasing the safety margin in front of you. This reduces the chance that you’ll have to stop suddenly and allows you to spread your braking over a greater distance. This is an example of defensive driving.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "AB2956",
    questionText: "You’re travelling along a single-track road. There’s a passing place on your right. What should you do if you see a vehicle coming towards you?",
    options: [
    "Continue along the single-track road",
    "Stop in the passing place",
    "Move over onto the verge",
    "Wait opposite the passing place",
    ],
    correctIndex: 3,
    explanation: "When you meet oncoming vehicles on a single-track road, you should allow them to pass. You should pull into a passing place on your left or wait opposite a passing place on your right. Do not move onto the verge as there may be hidden hazards.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1591",
    questionText: "Which instrument-panel warning light would show that headlights are on main beam?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    explanation: "You should be aware of all the warning lights and visual aids on the vehicle you're driving. If you're driving a vehicle for the first time, you should familiarise yourself with all the controls, warning lights and visual aids before you set off.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1642",
    questionText: "You're driving a car that has a diesel engine. What can a loose filler cap on your fuel tank cause?",
    options: [
    "It can make the engine difficult to start",
    "It can make the roads slippery for other road users",
    "It can improve your vehicle’s fuel consumption",
    "It can increase the level of exhaust emissions",
    ],
    correctIndex: 1,
    explanation: "Diesel fuel can spill out if your filler cap is not secured properly. This is most likely to occur on bends, junctions and roundabouts, where it will make the road slippery, especially if it's wet. At the end of a spell of dry weather, road surfaces may be especially slippery where diesel has been spilled but it has not been washed away by rain.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1643",
    questionText: "What should you do to avoid fuel spillage?",
    options: [
    "Check that your tank is only three-quarters full",
    "Check that you've used a locking filler cap",
    "Check that your fuel gauge is working",
    "Check that your filler cap is securely fastened",
    ],
    correctIndex: 3,
    explanation: "When learning to drive, it's a good idea to practise filling your car with fuel. Ask your instructor if you can use a petrol station and fill the fuel tank yourself. You need to know where the filler cap is on the car you're driving, so you know which side of the pump to park at. Take care not to overfill the tank and make sure you secure the filler cap correctly, so that no fuel leaks onto the road while you're driving.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1725",
    questionText: "What style of driving causes increased risk to everyone?",
    options: [
    "Considerate",
    "Defensive",
    "Competitive",
    "Responsible",
    ],
    correctIndex: 2,
    explanation: "Competitive driving increases the risks to everyone and is the opposite of responsible, considerate and defensive driving. Defensive driving is about questioning the actions of other road users and being prepared for the unexpected. Do not be taken by surprise.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1011",
    questionText: "You're driving on a clear night. Which lights should you use if the national speed limit applies and there's a steady stream of oncoming traffic?",
    options: [
    "Full-beam headlights",
    "Sidelights",
    "Dipped headlights",
    "Fog lights",
    ],
    correctIndex: 2,
    explanation: "Use the full-beam headlights only when you can be sure that you will not dazzle other road users.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1012",
    questionText: "You're driving behind a heavy goods vehicle. What should you do if it signals left but steers to the right?",
    options: [
    "Slow down and let the vehicle turn",
    "Drive on, keeping to the left",
    "Overtake on the right of it",
    "Hold your speed and sound your horn",
    ],
    correctIndex: 0,
    explanation: "Large, long vehicles need extra room when making turns at junctions. They may move out to the right in order to make a left turn. Keep well back and do not attempt to pass them on their left.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1013",
    questionText: "You're driving along this road. What should you do if the red car cuts in close in front of you?",
    options: [
    "Accelerate to get closer to the red car",
    "Give a long blast on the horn",
    "Drop back to leave the correct separation distance",
    "Flash your headlights several times",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/BB1013.png",
    explanation: "There are times when other drivers make incorrect or ill-judged decisions. Be tolerant and try not to retaliate or react aggressively. Always consider the safety of other road users, your passengers and yourself.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1014",
    questionText: "You're waiting in a traffic queue at night. How can you avoid dazzling drivers behind you?",
    options: [
    "Use the parking brake and release the footbrake",
    "Keep your foot on the footbrake",
    "Balance the clutch with the accelerator",
    "Use the parking brake and footbrake together",
    ],
    correctIndex: 0,
    explanation: "In queuing traffic, your brake lights can dazzle drivers behind you. If you apply your parking brake, you can take your foot off the footbrake. This will turn off the brake lights so that they do not dazzle the driver behind you.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1016",
    questionText: "You're driving in traffic at the speed limit for the road. What should you do if the driver behind is trying to overtake?",
    options: [
    "Move closer to the car ahead, so the driver behind has no room to overtake",
    "Wave the driver behind to overtake when it's safe",
    "Keep a steady course and allow the driver behind to overtake",
    "Accelerate to get away from the driver behind",
    ],
    correctIndex: 2,
    explanation: "Keep a steady course to give the driver behind an opportunity to overtake safely. If necessary, slow down. Reacting incorrectly to another driver's impatience can lead to danger.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1022",
    questionText: "What does it mean if the signs at a bus lane show no times of operation?",
    options: [
    "The lane is not in operation",
    "The lane is only in operation at peak times",
    "The lane is in operation 24 hours a day",
    "The lane is only in operation in daylight hours",
    ],
    correctIndex: 2,
    explanation: "Bus-lane signs show the vehicles allowed to use the lane and its times of operation. Where no times are shown, the bus lane is in operation 24 hours a day.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1026",
    questionText: "What should you do when a person herding sheep asks you to stop?",
    options: [
    "Ignore them as they have no authority",
    "Stop and switch off your engine",
    "Continue on but drive slowly",
    "Try to get past quickly",
    ],
    correctIndex: 1,
    explanation: "If someone in charge of animals asks you to stop, you should do so and switch off your engine. Animals are unpredictable and startle easily; they could turn and run into your path or into the path of another moving vehicle.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1027",
    questionText: "What should you do when you're overtaking a horse and rider?",
    options: [
    "Sound your horn as a warning",
    "Go past as quickly as possible",
    "Flash your headlights as a warning",
    "Go past slowly and carefully",
    ],
    correctIndex: 3,
    explanation: "Horses can be startled by the sound of a car engine or the rush of air caused by a vehicle passing too closely. Keep well back and only pass when it's safe. Leave them plenty of room; you may have to use the other side of the road to go past safely.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1440",
    questionText: "You're approaching a zebra crossing. What should you do if pedestrians are waiting to cross?",
    options: [
    "Give way to older and infirm people only",
    "Slow down and prepare to stop",
    "Use your headlights to indicate they can cross",
    "Wave at them to cross the road",
    ],
    correctIndex: 1,
    explanation: "As you approach a zebra crossing, look for pedestrians waiting to cross. Where you can see them, slow down and prepare to stop. Be especially careful of children and older people, who may have difficulty judging when it's safe to cross.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1444",
    questionText: "What should you do if a vehicle pulls out in front of you at a junction?",
    options: [
    "Swerve past it and sound your horn",
    "Flash your headlights and drive up close behind",
    "Slow down and be ready to stop",
    "Accelerate past it immediately",
    ],
    correctIndex: 2,
    explanation: "Try to anticipate what other drivers might do. Look and plan ahead so that you're ready to respond safely if a hazard develops. Be tolerant of road users who make mistakes.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1636",
    questionText: "When should you leave a two-second gap between your vehicle and the one in front?",
    options: [
    "When it's raining",
    "When it's dry",
    "When it's icy",
    "When it's foggy",
    ],
    correctIndex: 1,
    explanation: "In good, dry conditions, a driver needs to keep a distance of at least 2 seconds from the car in front. This should allow enough space for you to stop if the driver in front has to stop suddenly.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1637",
    questionText: "You're driving at night on an unlit road. What should you do if you're following another vehicle?",
    options: [
    "Flash your headlights",
    "Use dipped headlights",
    "Switch off your headlights",
    "Use full-beam headlights",
    ],
    correctIndex: 1,
    explanation: "If you follow another vehicle with your headlights on full beam, they could dazzle the driver. Leave a safe distance and make sure that the light from your dipped beam falls short of the vehicle in front.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
  {
    id: "BB1638",
    questionText: "What should you do if you're driving a slow-moving vehicle on a narrow winding road?",
    options: [
    "Keep well out to stop vehicles overtaking dangerously",
    "Wave the vehicles behind to come past you if you think they can overtake quickly",
    "Pull in when you can, to let the vehicles behind overtake",
    "Give a left signal when it's safe for vehicles to overtake you",
    ],
    correctIndex: 2,
    explanation: "If you’re driving a slow-moving vehicle along a narrow road, try not to hold up faster traffic. If you see vehicles following behind, pull over in a safe place and let the traffic pass before continuing. Do not wave other traffic past – this could be dangerous if you or they have not noticed a hazard ahead.",
    topicCategory: TopicCategory.Attitude,
    difficulty: 1,
  },
];
