import { Question, TopicCategory } from '@clearpass/core';

export const documentsAndRegulationsQuestions: Question[] = [
  {
    id: "AB2436",
    questionText: "For how long is an MOT certificate normally valid?",
    options: [
    "3 years after the date it was issued",
    "10,000 miles",
    "One year after the date it was issued",
    "30,000 miles",
    ],
    correctIndex: 2,
    explanation: "Some garages will remind you that your vehicle is due for its annual MOT test, but not all do. To ensure continuous cover, you may take your vehicle for its MOT up to one month before its existing MOT certificate expires. The expiry date on the new certificate will be 12 months after the expiry date on the old certificate.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2682",
    questionText: "You've just passed your first practical driving or riding test. What will you have to do if you get 6 penalty points on your licence in the next 2 years?",
    options: [
    "Retake only your theory test",
    "Retake your theory and practical tests",
    "Retake only your practical test",
    "Reapply for your full licence immediately",
    ],
    correctIndex: 1,
    explanation: "If you accumulate 6 or more penalty points within 2 years of gaining your first full licence, it will be revoked. The 6 or more points include any gained due to offences you committed before passing your test. If this happens, you may only drive as a learner until you pass both the theory and practical tests again.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2782",
    questionText: "For how long is a Statutory Off-Road Notification (SORN) valid?",
    options: [
    "Until the vehicle is taxed, sold or scrapped",
    "Until the vehicle is insured and MOT'd",
    "Until the vehicle is repaired or modified",
    "Until the vehicle is used on the road",
    ],
    correctIndex: 0,
    explanation: "A SORN allows you to keep a vehicle off-road and untaxed. SORN will end when the vehicle is taxed, sold or scrapped.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2783",
    questionText: "What's a Statutory Off-Road Notification (SORN)?",
    options: [
    "A notification to tell DVSA that a vehicle does not have a current MOT",
    "Information kept by the police about the owner of a vehicle",
    "A notification to tell DVLA that a vehicle is not being used on the road",
    "Information held by insurance companies to check a vehicle is insured",
    ],
    correctIndex: 2,
    explanation: "If you want to keep a vehicle untaxed and off the public road, you must make a SORN. It's an offence not to do so. Your SORN is valid until your vehicle is taxed, sold or scrapped.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2838",
    questionText: "Who's legally responsible for making sure that a vehicle registration certificate (V5C) is updated?",
    options: [
    "The registered vehicle keeper",
    "The vehicle manufacturer",
    "Your insurance company",
    "The licensing authority",
    ],
    correctIndex: 0,
    explanation: "It's your legal responsibility to keep the details on your vehicle registration certificate (V5C) up to date. You should tell the licensing authority about any changes. These include your name, address or vehicle details. If you do not do this, you may have problems when you try to sell your vehicle.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2874",
    questionText: "Your insurer will issue you with an insurance certificate. When must you produce this document for inspection?",
    options: [
    "When making a SORN",
    "When buying or selling a vehicle",
    "When a police officer asks you for it",
    "When your vehicle is having an MOT test",
    ],
    correctIndex: 2,
    explanation: "You must produce a valid insurance certificate when requested by a police officer. If you cannot do this immediately, you may be asked to take it to a police station. Other documents you may be asked to produce are your driving licence and the vehicle's MOT certificate.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2875",
    questionText: "When must your vehicle have valid insurance cover?",
    options: [
    "Before you can make a SORN",
    "Before you can sell the vehicle",
    "Before you can scrap the vehicle",
    "Before you can tax the vehicle",
    ],
    correctIndex: 3,
    explanation: "Your vehicle must have valid insurance cover before you can tax it. If required, it will also need to have a valid MOT certificate. You can tax your vehicle online, by phone or at certain post offices.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2877",
    questionText: "What do you need before you can legally use a motor vehicle on the road?",
    options: [
    "An appropriate driving licence",
    "Breakdown cover",
    "Proof of your identity",
    "A vehicle handbook",
    ],
    correctIndex: 0,
    explanation: "Using a motor vehicle on the road illegally carries a heavy fine and can lead to penalty points on your driving licence. You must\r\n• hold a valid driving licence for the class of vehicle you're using\r\n• be insured to drive the vehicle.\r\nIf required, the vehicle must have a current MOT test certificate and be taxed for use on the road.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2878",
    questionText: "What must you have when you apply to renew your vehicle tax?",
    options: [
    "Valid insurance",
    "The vehicle's chassis number",
    "The handbook",
    "A valid driving licence",
    ],
    correctIndex: 0,
    explanation: "You can renew your vehicle tax online, at post offices and by phone using the DVLA vehicle tax service. When applying, make sure you have all the relevant valid documents, including a valid MOT test certificate where applicable.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2901",
    questionText: "A police officer asks to see your documents. You do not have them with you. How many days do you have to produce them at a police station?",
    options: [
    "5 days",
    "7 days",
    "14 days",
    "21 days",
    ],
    correctIndex: 1,
    explanation: "You do not have to carry your vehicle's documents wherever you go. If a police officer asks to see them and you do not have them with you, you may be asked to produce them at a police station within 7 days.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2948",
    questionText: "When should you update your vehicle registration certificate?",
    options: [
    "When you pass your driving test",
    "When you move house",
    "When your vehicle needs an MOT",
    "When you have a collision",
    ],
    correctIndex: 1,
    explanation: "As the registered keeper of a vehicle, it's up to you to inform DVLA of any changes in your details; for example, your name or address. You do this by completing and sending off the relevant section of the registration certificate.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1243",
    questionText: "What must you check before you drive someone else's vehicle?",
    options: [
    "That the vehicle owner has third-party insurance cover",
    "That your own vehicle has insurance cover",
    "That the vehicle is insured for your use",
    "That the insurance documents are in the vehicle",
    ],
    correctIndex: 2,
    explanation: "Driving a vehicle without insurance cover is illegal, so be sure that, whoever's car you drive, you're insured – whether on their policy or on your own. If you need to take out insurance, it's worth comparing several quotes before you decide which insurance provider best meets your needs.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1245",
    questionText: "Your car needs to pass an MOT test. What may be invalidated if you drive the car without a current MOT certificate?",
    options: [
    "The vehicle service record",
    "The vehicle insurance",
    "The vehicle tax",
    "The vehicle registration document",
    ],
    correctIndex: 1,
    explanation: "If your vehicle requires an MOT certificate, it’s illegal to drive it without one and your insurance may be invalid if you do so. The only exceptions are that you may drive to a pre-arranged MOT test appointment, or to a garage for repairs required for the test.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1404",
    questionText: "What legal requirement must be met by a newly qualified driver?",
    options: [
    "They must display green L plates",
    "They must have a new photograph taken for their full licence",
    "They must be accompanied on their first motorway journey",
    "They must have valid motor insurance",
    ],
    correctIndex: 3,
    explanation: "It's your responsibility to make sure you're properly insured for the vehicle you're driving. This is the case regardless of whether you're a newly qualified driver or one with more experience.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1506",
    questionText: "What's covered by third-party insurance?",
    options: [
    "Damage to your vehicle",
    "Fire damage to your vehicle",
    "Flood damage to your vehicle",
    "Damage to other vehicles",
    ],
    correctIndex: 3,
    explanation: "Third-party insurance does not cover damage to your own vehicle or injury to yourself. If you have a crash and your vehicle is damaged, you might have to carry out the repairs at your own expense.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1533",
    questionText: "Who's responsible for paying the vehicle tax?",
    options: [
    "The driver of the vehicle",
    "The registered keeper of the vehicle",
    "The car dealer",
    "The Driver and Vehicle Licensing Agency (DVLA)",
    ],
    correctIndex: 1,
    explanation: "The registered keeper of the vehicle is responsible for paying the vehicle tax or making a Statutory Off-Road Notification (SORN) if the vehicle is to be kept untaxed and off the road.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1537",
    questionText: "What information is found on a vehicle registration document?",
    options: [
    "The registered keeper",
    "The type of insurance cover",
    "The service history details",
    "The date of the MOT",
    ],
    correctIndex: 0,
    explanation: "Every vehicle used on the road has a registration document. This shows the vehicle's details, including date of first registration, registration number, registered keeper, previous keeper, make of vehicle, engine size, chassis number, year of manufacture and colour.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1538",
    questionText: "When must you contact the Driver and Vehicle Licensing Agency (DVLA)?",
    options: [
    "When you get a parking ticket",
    "When you change your vehicle",
    "When you use your vehicle for work",
    "When your vehicle's insurance is due",
    ],
    correctIndex: 1,
    explanation: "DVLA needs to keep its records up to date. It sends out a reminder when a vehicle's tax is due for renewal. To do this, it needs to know the name and address of the registered keeper. Every vehicle in the country is registered, so it’s possible to trace its history.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1539",
    questionText: "What circumstances require you to notify the Driver and Vehicle Licensing Agency (DVLA)?",
    options: [
    "When your health affects your driving",
    "When you have to work abroad",
    "When you lend your vehicle to someone",
    "When your vehicle needs an MOT certificate",
    ],
    correctIndex: 0,
    explanation: "DVLA holds the records of all vehicles, drivers and riders in Great Britain and Northern Ireland. They need to know if you have a medical condition that might affect your ability to drive safely. You must tell them if your health deteriorates and you become unfit to drive.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1696",
    questionText: "In order to supervise a learner driver you need to have held a full driving licence for the same category of vehicle, for at least 3 years. What other requirement must you meet?",
    options: [
    "To have a car with dual controls",
    "To be at least 21 years old",
    "To be an approved driving instructor",
    "To hold an advanced driving certificate",
    ],
    correctIndex: 1,
    explanation: "Learner drivers benefit by combining professional driving lessons with private practice. However, you need to be at least 21 years old and have held your driving licence for at least 3 years before you can supervise a learner driver.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1697",
    questionText: "Your car requires an MOT certificate. When is it legal to drive it without an MOT certificate?",
    options: [
    "Up to 7 days after the old certificate has run out",
    "When driving to an MOT centre to arrange an appointment",
    "When driving the car with the owner’s permission",
    "When driving to an appointment at an MOT centre",
    ],
    correctIndex: 3,
    explanation: "When a car is 3 years old (4 years old in Northern Ireland), it must pass an MOT test and have a valid MOT certificate before it can be used on the road. Exceptionally, you may \r\n•  drive to a pre-arranged test appointment or to a garage for repairs required for the test\r\n•  drive vehicles that are more than 40 years old without an MOT test, but they must be in a roadworthy condition before being used on the road. See GOV.UK for more details.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1713",
    questionText: "What does third-party insurance cover?",
    options: [
    "Damage to your vehicle",
    "Damage to other vehicles",
    "Injury to yourself",
    "All damage and injury",
    ],
    correctIndex: 1,
    explanation: "Third-party insurance cover is usually cheaper than comprehensive cover. However, it does not cover any damage caused to your own vehicle or property. It only covers damage and injury you cause to others.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1714",
    questionText: "What's the legal minimum insurance cover you must have to drive on public roads?",
    options: [
    "Third party, fire and theft",
    "Comprehensive",
    "Third party only",
    "Personal injury cover",
    ],
    correctIndex: 2,
    explanation: "The minimum insurance required by law is third-party cover. This covers your liability to others involved in a collision but not damage to your vehicle. Basic third-party insurance also will not cover theft or fire damage. Ask your insurance company for advice on the best cover for you and make sure that you read the policy carefully.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "BB1715",
    questionText: "What does it mean if your insurance policy has an excess of £500?",
    options: [
    "The insurance company will pay the first £500 of any claim",
    "You'll be paid £500 if you do not claim within one year",
    "Your vehicle is insured for a value of £500 if it's stolen",
    "You'll have to pay the first £500 of the cost of any claim",
    ],
    correctIndex: 3,
    explanation: "Having an excess on your policy will help to keep the premium down. However, if you make a claim, you'll have to pay the excess yourself – in this case, £500.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
  {
    id: "AB2819",
    questionText: "What's the maximum fine for driving or riding without insurance?",
    options: [
      "Unlimited",
      "£500",
      "£1,000",
      "£5,000",
    ],
    correctIndex: 0,
    explanation: "Driving or riding without insurance is a serious offence. As well as an unlimited fine, you may be disqualified or incur penalty points.",
    topicCategory: TopicCategory.DocumentsAndRegulations,
    difficulty: 1,
  },
];
