// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const hazardAwarenessQuestions: Question[] = [
  {
    id: 'HAZ_001',
    questionText: 'In the hazard perception test, what is a "developing hazard"?',
    options: [
      'Any road sign or marking',
      'A situation that is likely to require you to change speed or direction',
      'Any other vehicle on the road',
      'A bend or hill that reduces your visibility',
    ],
    correctIndex: 1,
    explanation:
      'A developing hazard is something that requires you to take action - braking, steering, or changing speed. Spotting it early and scoring higher in the hazard perception test means responding as soon as the hazard starts to develop.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_002',
    questionText: 'You are driving past parked cars when a door opens into your path. What should you do?',
    options: [
      'Sound your horn and maintain speed to warn the driver',
      'Brake sharply and swerve into the oncoming lane',
      'Reduce speed and be prepared to stop or steer around the door',
      'Flash your headlights as a warning and accelerate past',
    ],
    correctIndex: 2,
    explanation:
      'Highway Code Rule 239 advises watching for car doors opening when passing parked vehicles. Reducing speed and being ready to respond safely is the correct approach - swerving abruptly into traffic is dangerous.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_003',
    questionText: 'You are driving past a school at 3:30pm on a weekday. What hazard should you be most alert to?',
    options: [
      'Increased HGV and delivery traffic near the school',
      'Children crossing the road unexpectedly between parked cars',
      'Bus engines causing slippery road surfaces',
      'Fallen leaves creating poor grip near the entrance',
    ],
    correctIndex: 1,
    explanation:
      'At school finishing time, large numbers of children may be near the road. Children can be unpredictable and may step out suddenly from between parked cars without looking.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_004',
    questionText: 'A bus has stopped at a bus stop ahead on your side of the road. What is the most significant hazard to anticipate?',
    options: [
      'The bus taking up too much of the road',
      'Pedestrians stepping into the road from in front of or behind the bus',
      'The bus driver making an incorrect signal',
      'Passengers queuing on the pavement',
    ],
    correctIndex: 1,
    explanation:
      'Pedestrians getting off or crossing from in front of stationary buses are a serious hazard because they are hidden from your view. Slow down and be ready to stop when passing any stationary bus.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_005',
    questionText: 'You are following a slow-moving tractor on a narrow rural road. What is the most important hazard to anticipate?',
    options: [
      'The tractor accelerating suddenly and unexpectedly',
      'The tractor turning without warning into a field entrance',
      'Oncoming tractors attempting to overtake from the opposite direction',
      'Exhaust fumes from the tractor affecting your visibility',
    ],
    correctIndex: 1,
    explanation:
      'Farm vehicles often turn into field gateways that may not be immediately visible on your approach. They may slow and turn abruptly - maintain a safe distance and watch for any indication of a turn.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_006',
    questionText: 'What does the "MSM" routine stand for, and when should it be applied?',
    options: [
      'Mirror, Speed, Manoeuvre - used only when overtaking',
      'Mirror, Signal, Manoeuvre - used before any change in speed, direction, or position',
      'Move, Stop, Move - used at junctions',
      'Mirror, Steer, Merge - used when joining a main road',
    ],
    correctIndex: 1,
    explanation:
      'MSM (Mirror, Signal, Manoeuvre) is the core observation routine used before every change in direction, speed, or road position. Always check mirrors first so you know what is behind before you signal or act.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_007',
    questionText: 'Your car begins to skid. What is the correct initial response?',
    options: [
      'Brake firmly and steer hard in the opposite direction of the skid',
      'Take your foot off the accelerator and steer smoothly in the direction you want to go',
      'Apply the handbrake to slow the rear wheels',
      'Accelerate to restore traction to the driven wheels',
    ],
    correctIndex: 1,
    explanation:
      'In a skid, releasing the accelerator reduces the forces causing the skid. Steer gently in the direction you want the front of the car to go. Avoid harsh braking or sudden steering corrections, which can worsen the skid.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_008',
    questionText: 'You are approaching an unmarked crossroads of equal-sized roads. Who has priority?',
    options: [
      'Traffic on the road running left to right always has priority',
      'Vehicles travelling straight ahead have priority over those turning',
      'There is no priority - all drivers must take extra care and be prepared to give way',
      'The first vehicle to reach the junction has absolute priority',
    ],
    correctIndex: 2,
    explanation:
      'At an unmarked crossroads with no signs or markings, no driver has automatic priority. All road users must approach with care and be prepared to give way. Treat it as you would a potential hazard.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_009',
    questionText: 'It is autumn and fallen leaves cover the road surface. Why is this a hazard?',
    options: [
      'Leaves can block the drainage channels and cause flooding',
      'Wet leaves are very slippery and can reduce tyre grip significantly',
      'Leaves blow up and reduce visibility through the windscreen',
      'Leaves can cause damage to the underside of the vehicle',
    ],
    correctIndex: 1,
    explanation:
      'Wet fallen leaves are extremely slippery and can reduce tyre grip to a similar level as ice. Braking distances increase dramatically. Treat leaf-covered roads with extra caution, especially on bends and hills.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_010',
    questionText: 'You are following a large lorry on a single-carriageway road. Why should you hold back rather than drive close behind it?',
    options: [
      'Large vehicles brake faster than cars and could stop suddenly',
      'Holding back gives you a better view of the road ahead and more time to react',
      'It is a legal requirement to leave 10 car lengths behind a lorry',
      'The lorry\'s exhaust fumes can reduce engine performance in following vehicles',
    ],
    correctIndex: 1,
    explanation:
      'Holding back from a large vehicle improves your view of the road ahead, giving you more time to react to developing hazards. It also gives the lorry driver a clearer view in their mirrors and reduces the risk of debris striking your vehicle.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_011',
    questionText: 'In the hazard perception test, how is your score affected if you click the mouse repeatedly in a short period?',
    options: [
      'Your score for that clip is doubled as it shows awareness',
      'You receive the maximum score of 5 for alertness',
      'You score zero for that clip as the system detects a pattern suggesting guessing',
      'You receive a warning but your score is unaffected',
    ],
    correctIndex: 2,
    explanation:
      'The hazard perception test software detects if you click in a regular pattern, which suggests guessing rather than genuine hazard recognition. If this pattern is detected, you score zero for that clip.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_012',
    questionText: 'You are about to overtake on a country road when you see a vehicle approaching from a side road on the right. What should you do?',
    options: [
      'Flash your lights to warn the driver and proceed with the overtake quickly',
      'Abandon the overtake, drop back, and wait until it is clearly safe',
      'Sound your horn and continue with the overtake at increased speed',
      'Proceed with the overtake but move slightly left to create more room',
    ],
    correctIndex: 1,
    explanation:
      'Any new hazard that emerges during an overtake means you must abandon it immediately and drop back. Never commit to an overtake if the road ahead or emerging hazards make completion unsafe.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_013',
    questionText: 'You are approaching a hump-back bridge on a country road. What is the key hazard?',
    options: [
      'The road surface is often uneven, causing steering problems',
      'Oncoming vehicles may be hidden until they appear over the top of the bridge',
      'Bridge structures cause crosswinds that push the car sideways',
      'The road becomes slippery due to water drainage from the bridge',
    ],
    correctIndex: 1,
    explanation:
      'Hump-back bridges severely restrict forward visibility. An oncoming vehicle, cyclist, or pedestrian may only become visible at very close range. Approach slowly and be prepared to stop, especially if the road is narrow.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_014',
    questionText: 'You approach a group of horse riders on a country road. What is the best way to pass them?',
    options: [
      'Sound your horn to warn the riders you are approaching',
      'Pass at normal speed but leave plenty of room',
      'Slow right down, pass wide and slowly, and avoid revving or sudden acceleration',
      'Flash your headlights to warn them and pass quickly to minimise disturbance',
    ],
    correctIndex: 2,
    explanation:
      'Horses are easily startled by noise and sudden movement. Pass slowly and quietly, leaving as much room as possible. Do not rev the engine or accelerate sharply until you are well past the horses.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_015',
    questionText: 'Bright sunshine is directly ahead of you. What steps should you take?',
    options: [
      'Pull over until the sun moves to a less dazzling angle',
      'Slow down, use the sun visor, and allow extra stopping distance',
      'Increase speed to reduce the time spent driving into the sun',
      'Switch on headlights so other road users can see you more clearly',
    ],
    correctIndex: 1,
    explanation:
      'Sun dazzle can temporarily blind you completely, masking hazards including pedestrians and cyclists. Use the sun visor, slow down, allow extra stopping distance, and keep sunglasses in the car for exactly this situation.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_016',
    questionText: 'You are driving at night when you see a pedestrian wearing dark clothing ahead. What is the main hazard?',
    options: [
      'The pedestrian may be intoxicated and unpredictable',
      'The pedestrian is difficult to see and may step out with little warning',
      'The pedestrian\'s shadow may be confused with road markings',
      'Pedestrians at night always have right of way so you must stop',
    ],
    correctIndex: 1,
    explanation: 'Pedestrians in dark clothing are much harder to see at night, particularly between streetlights. Highway Code Rule 3 advises pedestrians to wear light or reflective clothing after dark, but many do not. Assume pedestrians are present even in low-visibility areas.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_017',
    questionText: 'You see mud on the road surface at a farm junction. Why is this significant?',
    options: [
      'It indicates a farm vehicle may be ahead, causing slow progress',
      'Mud on the road is extremely slippery and can cause sudden loss of control',
      'Mud can block road drains and cause flooding on the approach',
      'It may hide damage to the road surface beneath',
    ],
    correctIndex: 1,
    explanation: 'Mud deposited by farm vehicles creates a slippery surface that can reduce tyre grip dramatically, similar to ice. Slow down significantly and avoid harsh braking or steering on muddy road sections.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_018',
    questionText: 'You are approaching a sharp left bend on a country road. Where is the highest risk of encountering a hazard?',
    options: [
      'On the approach to the bend where visibility is longest',
      'At the apex of the bend where oncoming vehicles may have cut the corner',
      'After the bend where the road straightens',
      'On the outside of the bend where the road is widest',
    ],
    correctIndex: 1,
    explanation: 'Drivers may cut the corner of a sharp bend, moving to the wrong side of the road. Approach bends well to the left to maximise your view and avoid conflict with any vehicle that has drifted across the centre line.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_019',
    questionText: 'You see a child on the pavement ahead who is bouncing a ball. What is the hazard to anticipate?',
    options: [
      'The child may throw the ball into your path',
      'The child may run into the road to retrieve the ball if it bounces off the kerb',
      'The child may distract other children onto the road',
      'The ball may roll under your vehicle and damage the steering',
    ],
    correctIndex: 1,
    explanation: 'Children chase moving objects instinctively without looking for traffic. If a ball bounces towards the road, the child will very likely follow it. Slow down whenever children are near the road and be ready to stop.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_020',
    questionText: 'You are driving on a rural road at night. What additional hazards should you anticipate?',
    options: [
      'Roads are quieter so fewer hazards exist',
      'Animals crossing the road, unlit cyclists, and pedestrians are harder to see',
      'Speed limits are relaxed at night on rural roads',
      'Increased heavy vehicle traffic from overnight deliveries',
    ],
    correctIndex: 1,
    explanation: 'Rural roads at night pose particular risks: animals may wander onto the road (watch for reflective eyes), pedestrians and cyclists may lack lights or reflective clothing, and hazards appear more suddenly. Reduce speed and be ready to react.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_021',
    questionText: 'You notice oil or diesel on the road surface. How should you respond?',
    options: [
      'Drive over it quickly so your tyres spread it to a harmless layer',
      'Steer around the edges where the surface is thinner',
      'Reduce speed and avoid braking or steering sharply over the contaminated area',
      'Sound your horn to warn drivers behind you',
    ],
    correctIndex: 2,
    explanation: 'Oil or diesel on the road surface dramatically reduces tyre grip. Treat it like ice - reduce speed before reaching the area and avoid any sudden braking or steering inputs. If you have already driven through it, check your brakes gently when safe.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_022',
    questionText: 'What does "black ice" describe, and why is it particularly dangerous?',
    options: [
      'Ice that forms only on black-surfaced roads',
      'A transparent layer of ice that is almost impossible to see but gives zero grip',
      'Ice that forms when road temperature drops below -5 degrees',
      'Ice formed from road spray from heavy goods vehicles',
    ],
    correctIndex: 1,
    explanation: 'Black ice is a thin, nearly transparent layer of ice that takes on the colour of the road surface beneath it. It offers almost no grip and is very difficult to see. It most commonly forms in shaded areas, bridges, and overnight in cold conditions.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_023',
    questionText: 'You are about to drive through a ford (flooded section of road). What is the key hazard to check before entering?',
    options: [
      'Whether your vehicle has a snorkel air intake fitted',
      'The depth and speed of the water - still and shallow is safer; flowing or deep is very dangerous',
      'Whether other vehicles are waiting on the opposite side',
      'Whether the ford has a concrete base or soft mud',
    ],
    correctIndex: 1,
    explanation: 'Fast-flowing water can push a vehicle sideways. Even 30cm of fast-flowing water can move a car. Flooded roads kill drivers every year. Check depth, test for current, and if unsure, find an alternative route.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_024',
    questionText: 'A large lorry on a roundabout is signalling left but is in the right-hand lane. What hazard should you anticipate?',
    options: [
      'The lorry will mount the pavement and you should give it room on the left',
      'The lorry may need to swing wide into your lane to complete its turn',
      'The signal is an error - the lorry will exit at a later road',
      'Other drivers may brake suddenly thinking the lorry is turning too early',
    ],
    correctIndex: 1,
    explanation: 'Large vehicles often need to approach turns from the right lane because their turning radius requires a wide sweep. Never assume you can squeeze alongside an articulated lorry on a roundabout. Give it space to complete its turn safely.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_025',
    questionText: 'You are driving on an exposed bridge or elevated road. What additional hazard should you be alert to?',
    options: [
      'Road surfaces on bridges are always wetter due to condensation',
      'Strong crosswinds can push you off course, particularly if you are driving a high-sided vehicle',
      'Bridge structures create magnetic interference affecting your sat nav',
      'Bridges are subject to lower speed limits than the approach roads',
    ],
    correctIndex: 1,
    explanation: 'Exposed sections such as bridges are vulnerable to crosswinds that can push a vehicle off course. High-sided vehicles are most affected. Be ready for a sudden gust of wind and maintain a firm grip on the steering wheel.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_026',
    questionText: 'How many clips does the hazard perception test contain, and what is the pass mark?',
    options: [
      '12 clips, pass mark 40',
      '14 clips, pass mark 44',
      '16 clips, pass mark 50',
      '10 clips, pass mark 35',
    ],
    correctIndex: 1,
    explanation: 'The hazard perception test consists of 14 clips, each up to one minute long. One clip contains two developing hazards. The maximum score is 75, and the pass mark is 44. You score up to 5 points for each developing hazard depending on how quickly you identify it.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_027',
    questionText: 'You are driving along a residential street when a pedestrian steps out between parked cars ahead. What hazard follows?',
    options: [
      'A second pedestrian may follow immediately, particularly a child',
      'The parked cars may obscure a cyclist coming the other way',
      'The pedestrian may step back suddenly causing you to brake erratically',
      'You may need to mount the pavement to avoid the pedestrian',
    ],
    correctIndex: 0,
    explanation: 'When one pedestrian steps out, another is likely to follow - particularly a child who may have been hidden by the first person or by parked vehicles. Slow down and prepare for a second hazard whenever the first appears.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_028',
    questionText: 'You are waiting at a T-junction to turn right. A vehicle on the main road flashes its lights. Is it safe to pull out?',
    options: [
      'Yes - the flashing light is a clear signal that you are being given way to',
      'No - a flashing light is not a guaranteed signal of safety, the driver may be warning of something else',
      'Yes - if the driver also nods, this confirms their intention',
      'Only if the driver also slows down noticeably',
    ],
    correctIndex: 1,
    explanation: 'Flashed headlights are not a legally recognised signal to proceed. The driver may be flashing at someone else, may have miscalculated, or another vehicle may be hidden. You are responsible for ensuring it is safe to emerge, regardless of any signals from others.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_029',
    questionText: 'You are driving on a country road and crest a hill to find a stopped vehicle on your side of the road with its hazard lights on. What is the secondary hazard?',
    options: [
      'The stopped vehicle may block emergency services from reaching the area',
      'There may be a further hazard ahead that caused the vehicle to stop',
      'Oncoming drivers may be blinded by the hazard lights',
      'The stopped vehicle may roll backwards if on a hill',
    ],
    correctIndex: 1,
    explanation: 'A stopped vehicle often indicates a hazard ahead - an accident, animal, or obstruction. Do not just navigate around the stopped car; look for what caused it to stop and be prepared for a further hazard just beyond your current view.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_030',
    questionText: 'You are driving in a lane that merges with another. You can see the merge point. What is the hazard?',
    options: [
      'Vehicles from the merging lane may pull in front of you without adequate space',
      'Road markings at merge points are often faded and may be hard to follow',
      'Merge points always have a reduced speed limit',
      'The road surface is often worse at merge points',
    ],
    correctIndex: 0,
    explanation: 'At merge points, vehicles move laterally as well as forward, creating a risk of collision. Be aware of vehicles in adjacent lanes, check your mirrors and blind spots, and adjust your speed to facilitate a smooth merge for all vehicles.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_031',
    questionText: 'You notice a motorcyclist immediately ahead in your lane is wobbling slightly. What should you do?',
    options: [
      'Overtake them immediately before they cause an accident',
      'Sound your horn to alert them',
      'Drop well back to give them more space and time',
      'Flash your lights twice to signal your concern',
    ],
    correctIndex: 2,
    explanation: 'A wobbling motorcyclist may be struggling with a road hazard, a mechanical fault, or may be tired or unwell. Give them much more space than normal - they may need to make sudden corrections. Only overtake when it is clearly safe and there is a very large gap.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_032',
    questionText: 'What hazard is indicated by a low bridge warning sign with a height restriction in metres?',
    options: [
      'The bridge has a weight restriction that applies to all vehicles',
      'Vehicles taller than the stated height will not fit under the bridge and may cause a crash',
      'The road narrows under the bridge to a single lane',
      'The bridge is a historic structure with a 20 mph limit',
    ],
    correctIndex: 1,
    explanation: 'Low bridge signs warn that the clearance is limited to the stated height. A vehicle that is taller than the restriction will strike the bridge, causing serious damage or a crash. Check your vehicle\'s height before using roads with low bridges.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_033',
    questionText: 'You are driving past a row of parked cars when you notice a gap between two of them. What hazard should you anticipate?',
    options: [
      'A vehicle may reverse out into the gap as you pass',
      'A pedestrian or cyclist may step or ride out from the gap without checking',
      'A door may open from the car on the right of the gap',
      'The gap may have a pedestrian crossing hidden within it',
    ],
    correctIndex: 1,
    explanation: 'Gaps between parked vehicles are common places for pedestrians - particularly children - to step out, and for cyclists to emerge. Slow down when passing gaps in parked vehicles, as someone on the other side may not be able to see you approaching.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_034',
    questionText: 'You are approaching a pelican crossing where the amber light is flashing. What does this mean?',
    options: [
      'Prepare to stop - the lights are about to turn red',
      'Give way to any pedestrians still on the crossing, but proceed if the crossing is clear',
      'All pedestrians must now clear the crossing immediately',
      'The crossing is out of order - pass with care',
    ],
    correctIndex: 1,
    explanation: 'A flashing amber light at a pelican crossing means give way to any pedestrians still on the crossing. If the crossing is clear, you may proceed. This differs from a standard amber light which means stop unless it is unsafe to do so.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_035',
    questionText: 'You are driving and see a cyclist signal to turn right, then position themselves in the centre of the lane. What should you do?',
    options: [
      'Overtake the cyclist on the left as they will be blocking the lane',
      'Stay behind the cyclist and give them space to complete their turn safely',
      'Sound your horn gently to let them know you are behind them',
      'Pass close on the right to let them know to speed up',
    ],
    correctIndex: 1,
    explanation: 'Cyclists turning right must position themselves near the centre of the lane to complete the turn. This is the correct technique described in the Highway Code. Stay behind and give them space - attempting to pass is dangerous and unnecessary.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_036',
    questionText: 'You are driving in fog and a vehicle ahead has its hazard lights on. What should you do?',
    options: [
      'Follow closely behind it using its lights as a guide',
      'Match its speed exactly to maintain visibility',
      'Maintain your own safe following distance - do not be drawn closer by the lights',
      'Flash your own hazard lights to signal you are following',
    ],
    correctIndex: 2,
    explanation: 'Hazard lights in fog can be a useful warning but must not lure you into following too closely. The vehicle may brake suddenly. Maintain your own safe following distance regardless of visibility conditions or the lights of the vehicle ahead.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_037',
    questionText: 'You are driving when a deer runs across the road ahead of you. What should you anticipate?',
    options: [
      'The deer is alone - one animal rarely follows another',
      'More deer may follow immediately - slow down and be ready for additional animals',
      'The deer may turn and run back towards you',
      'Deer rarely cross roads twice, so proceed normally once it has passed',
    ],
    correctIndex: 1,
    explanation: 'Deer frequently travel in groups. If you see one deer cross, others are very likely to follow immediately. Slow down and wait until you are confident no more animals are about to cross before proceeding.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_038',
    questionText: 'What is the particular hazard when driving past roadworks where a lane has been closed?',
    options: [
      'Lane closures require you to reduce speed to 20 mph at all times',
      'Vehicles merging late from the closed lane may cut in abruptly',
      'Road workers may direct traffic in ways that conflict with signals',
      'The road surface is always wet in roadworks zones',
    ],
    correctIndex: 1,
    explanation: 'At lane closures, vehicles merge from the closing lane, sometimes at the last moment. Be prepared for vehicles moving into your lane with limited warning. Merge in turn and allow vehicles to join the queue without aggressive blocking.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_039',
    questionText: 'You are driving on a country road when you see a sign for a ford ahead. What should your approach be?',
    options: [
      'Slow down only if there has been recent rain',
      'Slow right down, assess the depth and flow, and only cross if it is clearly safe',
      'Sound your horn to warn any approaching traffic before entering',
      'Engage a lower gear and cross at speed to avoid losing momentum',
    ],
    correctIndex: 1,
    explanation: 'Fords can be deceptively deep, especially after rain. Always slow down significantly, assess the water level (using the depth gauge if present), and check for current. If in doubt, do not cross. Moving water is far more dangerous than still water of the same depth.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_040',
    questionText: 'A vehicle in the next lane on a motorway has its warning light on and is slowing. What is the hazard to you?',
    options: [
      'The driver may pull into your lane to reach the hard shoulder',
      'Debris from their vehicle may strike yours',
      'Following drivers may brake suddenly and cause a rear-end collision',
      'The vehicle may stop suddenly in the lane',
    ],
    correctIndex: 0,
    explanation: 'A driver whose vehicle has broken down will typically try to reach the hard shoulder. They may move into your lane without adequate checking. Create space ahead of such a vehicle and allow them room to manoeuvre safely to safety.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_041',
    questionText: 'What hazard should you watch for when following a bus or coach that has just been overtaken by another vehicle?',
    options: [
      'The bus may accelerate suddenly to prevent being overtaken again',
      'The bus may pull into a bus stop immediately after the overtaking vehicle passes',
      'The overtaking vehicle may brake sharply once ahead of the bus',
      'Passengers on the bus may see the hazard before you',
    ],
    correctIndex: 1,
    explanation: 'Buses and coaches regularly stop at bus stops, which may be positioned immediately past the point where another vehicle overtook them. Anticipate that a bus may slow and stop at any time and maintain a safe following distance.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_042',
    questionText: 'What is a "ghost island" and what is its purpose?',
    options: [
      'An unmarked roundabout with no signage, creating confusion',
      'A hatched area of road markings in the centre of a road that separates opposing traffic flows or creates a right-turn lane',
      'A speed-reduction feature on a rural road with no road markings',
      'A pedestrian refuge island that is not visible at night',
    ],
    correctIndex: 1,
    explanation: 'A ghost island is a hatched area marked in the centre of a road. It may be used to separate opposing traffic flows, create a right-turn waiting area, or narrow the road to calm traffic. Do not drive on the hatched area unless road markings indicate this is permitted.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 3,
  },
  {
    id: 'HAZ_043',
    questionText: 'You are approaching a junction and the visibility is restricted by a hedge on the right. What is the correct approach?',
    options: [
      'Sound your horn as you approach to warn other road users',
      'Creep slowly forward until you can see whether it is safe to emerge',
      'Emerge quickly to minimise time in the path of any approaching vehicle',
      'Flash your headlights to warn vehicles approaching from the right',
    ],
    correctIndex: 1,
    explanation: 'When visibility is restricted at a junction, creep forward slowly and look in both directions before committing. This is called "peeping and creeping" and is the safest way to deal with limited sightlines at emerging junctions.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_044',
    questionText: 'You see an elderly person beginning to cross the road ahead at a point without a crossing. What should you do?',
    options: [
      'Sound your horn to warn them to wait',
      'Maintain speed - you have right of way',
      'Slow down and be prepared to stop and allow them to cross safely',
      'Flash your headlights to acknowledge them and proceed slowly',
    ],
    correctIndex: 2,
    explanation: 'Elderly pedestrians may walk slowly and may not be able to react quickly if a vehicle approaches. Even though drivers have priority on the road, you must always be prepared to stop safely. Being considerate prevents accidents.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_045',
    questionText: 'You are driving and see a football rolling into the road from a driveway. What should you immediately anticipate?',
    options: [
      'A dog may be chasing the ball',
      'A child is very likely to run after the ball without looking for traffic',
      'An adult will follow to collect the ball and is aware of traffic',
      'The ball may roll back across your path unpredictably',
    ],
    correctIndex: 1,
    explanation: 'Children instinctively run after moving objects without checking for traffic. A ball in the road means a child may appear immediately. Reduce speed sharply and be prepared to stop as soon as you see the ball.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_046',
    questionText: 'You are driving behind a skip lorry on a dual carriageway. What specific hazard should you anticipate?',
    options: [
      'The lorry may indicate to stop in the outside lane',
      'Loose material may fly from the skip and strike your vehicle',
      'The lorry is wider than standard and may straddle lanes',
      'Skip lorries are not permitted on dual carriageways',
    ],
    correctIndex: 1,
    explanation: 'Open-topped vehicles such as skip lorries and tipper trucks can shed debris, particularly at speed. Maintain a large following distance and consider whether it is safe to overtake to avoid the hazard.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_047',
    questionText: 'What is the hazard of overtaking on the brow of a hill?',
    options: [
      'Your vehicle may lose traction on the downhill slope',
      'An oncoming vehicle may be hidden by the hill and appear with no time to react',
      'The road surface is usually rougher at the brow of a hill',
      'Your speed is harder to control when cresting a hill',
    ],
    correctIndex: 1,
    explanation: 'The brow of a hill severely restricts your view ahead. An oncoming vehicle could appear at very short range once you are committed to the overtake. Never overtake near the brow of a hill or any other place where your view ahead is restricted.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_048',
    questionText: 'You are driving in a residential area when you see a car reversing out of a driveway ahead. What is the best response?',
    options: [
      'Sound your horn to warn them to stop reversing',
      'Flash your lights and maintain speed',
      'Slow down and be prepared to stop, giving the driver space to complete their manoeuvre',
      'Squeeze past between the reversing car and the kerb on your left',
    ],
    correctIndex: 2,
    explanation: 'A driver reversing out of a driveway may not see you approaching until they are already in the road. Slow down, stop if necessary, and allow them to complete the manoeuvre. Never squeeze past in the gap - the driver may be unaware of you.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: 'HAZ_049',
    questionText: 'What is the maximum score you can achieve on the hazard perception test, and how are points awarded?',
    options: [
      'Maximum 50 points - 5 per clip, no clips have two hazards',
      'Maximum 75 points - each clip has at least one hazard worth up to 5 points, and one clip has two hazards',
      'Maximum 100 points - awarded on a percentage basis across all clips',
      'Maximum 70 points - 5 per clip with bonus points for speed of response',
    ],
    correctIndex: 1,
    explanation: 'The hazard perception test has 14 clips. Each contains one scoreable hazard (worth up to 5 points), except one clip which contains two hazards. The maximum score is therefore 75. You score more points for responding earlier to each developing hazard.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
  {
    id: 'HAZ_050',
    questionText: 'You are driving on a motorway and traffic ahead is stopping rapidly. What hazard management technique should you apply?',
    options: [
      'Move to the hard shoulder immediately to avoid the queue',
      'Switch on hazard lights as you slow to warn vehicles behind',
      'Sound your horn as a warning to following traffic',
      'Accelerate around the slowing traffic in the outside lane',
    ],
    correctIndex: 1,
    explanation: 'When traffic slows rapidly on a motorway, switching on your hazard lights warns drivers behind that traffic is stopping ahead. This gives them more time to react, reducing the risk of a rear-end collision. Turn them off once moving again.',
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 2,
  },
];
