import { Question, TopicCategory } from '@clearpass/core';

export const hazardAwarenessQuestions: Question[] = [
  {
    id: "AB2085",
    questionText: "Where would you expect to see these markers?",
    options: [
    "On a motorway sign",
    "On a railway bridge",
    "On a heavy goods vehicle",
    "On a diversion sign",
    ],
    correctIndex: 2,
    explanation: "These markers must be fitted to vehicles over 13 metres long, heavy goods vehicles, and rubbish skips placed in the road. They're reflective to make them easier to see in the dark.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2087",
    questionText: "What's the main hazard shown in this picture?",
    options: [
    "Vehicles turning right",
    "Vehicles doing U-turns",
    "The cyclist crossing the road",
    "Parked cars around the corner",
    ],
    correctIndex: 2,
    explanation: "Look at the picture carefully and try to imagine you're there. The cyclist in this picture appears to be trying to cross the road. You must be able to deal with the unexpected, especially when you're approaching a hazardous junction. Look well ahead to give yourself time to deal with any hazards.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2088",
    questionText: "Which road user has caused a hazard?",
    options: [
    "The parked car (arrowed A)",
    "The pedestrian waiting to cross (arrowed B)",
    "The moving car (arrowed C)",
    "The car turning (arrowed D)",
    ],
    correctIndex: 0,
    explanation: "The car arrowed A is parked within the area marked by zigzag lines at the pedestrian crossing. Parking here is illegal. It also\r\n• blocks the view for pedestrians wishing to cross the road\r\n• restricts the view of the crossing for approaching traffic.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2089",
    questionText: "What should the driver of the car approaching the crossing do?",
    options: [
    "Continue at the same speed",
    "Sound the horn",
    "Drive through quickly",
    "Slow down and get ready to stop",
    ],
    correctIndex: 3,
    explanation: "Look well ahead to see whether any hazards are developing. This will give you more time to deal with them in the correct way. The man in the picture is clearly intending to cross the road. You should be travelling at a speed that allows you to check your mirror, slow down and stop in good time. You should not have to brake harshly.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2091",
    questionText: "What should the driver of the grey car be especially aware of?",
    options: [
    "The uneven road surface",
    "Traffic following behind",
    "Doors opening on parked cars",
    "Empty parking spaces",
    ],
    correctIndex: 2,
    explanation: "When passing parked cars, there's a risk that a driver or passenger may not check before opening the door into the road. A defensive driver will drive slowly and be looking for people who may be about to get out of their car.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2098",
    questionText: "What should you expect if you see this sign ahead?",
    options: [
    "The road will go steeply uphill",
    "The road will go steeply downhill",
    "The road will bend sharply to the left",
    "The road will bend sharply to the right",
    ],
    correctIndex: 2,
    explanation: "This sign indicates that the road will bend sharply to the left. Slow down in plenty of time and select the correct gear before you start to turn. Braking hard and late, while also sharply changing direction, is likely to cause a skid.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2099",
    questionText: "What should you do as you approach this cyclist?",
    options: [
    "Try to overtake before the cyclist gets to the junction",
    "Flash your headlights at the cyclist",
    "Slow down and allow the cyclist to turn",
    "Rev your engine so the cyclist knows you're following behind",
    ],
    correctIndex: 2,
    explanation: "Keep well back and give the cyclist time and room to turn safely. Do not intimidate them by getting too close or trying to squeeze past.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2100",
    questionText: "Why must you take great care when emerging from this junction?",
    options: [
    "The road surface is poor",
    "The footpath is narrow",
    "The kerbs are high",
    "The view is restricted",
    ],
    correctIndex: 3,
    explanation: "You may have to pull forward slowly until you can see up and down the road. Be aware that the traffic approaching the junction cannot see you either. If you do not know that it’s clear, do not go.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2102",
    questionText: "Which type of vehicle should you be ready to give way to as you approach this bridge?",
    options: [
    "Bicycles",
    "Buses",
    "Motorcycles",
    "Cars",
    ],
    correctIndex: 1,
    explanation: "A bus or high-sided lorry will have to take a position in the centre of the road to clear the bridge. There's normally a sign to show this. Look well ahead, past the bridge and be ready to stop and give way to large oncoming vehicles.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2103",
    questionText: "What type of vehicle could you expect to meet in the middle of the road?",
    options: [
    "Lorry",
    "Bicycle",
    "Car",
    "Motorcycle",
    ],
    correctIndex: 0,
    explanation: "The highest point of the bridge is in the centre, so a large vehicle might have to move to the centre of the road to have enough room to pass safely under the bridge.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2105",
    questionText: "What must you do at this junction?",
    options: [
    "Stop behind the line, then edge forward to see clearly",
    "Stop beyond the line, at a point where you can see clearly",
    "Stop only if there's traffic on the main road",
    "Stop only if you're turning right",
    ],
    correctIndex: 0,
    explanation: "The ‘stop’ sign has been put here because the view into the main road is poor. You must stop because it will not be possible to take proper observation while you're moving.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2114",
    questionText: "What should you do if a driver pulls out of a side road in front of you, causing you to brake hard?",
    options: [
    "Ignore the error and stay calm",
    "Flash your lights to show your annoyance",
    "Sound your horn to show your annoyance",
    "Overtake as soon as possible",
    ],
    correctIndex: 0,
    explanation: "Be tolerant if a vehicle emerges and you have to brake quickly. Anyone can make a mistake, so do not react aggressively. Be alert where there are side roads and be especially careful where there are parked vehicles, because these can make it difficult for emerging drivers to see you.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2116",
    questionText: "Why should you make allowances for older drivers?",
    options: [
    "Older drivers are exempt from wearing seat belts",
    "Older drivers can only drive cars that have automatic gearboxes",
    "Older drivers’ reactions may be slower than other drivers",
    "Older drivers take more risks than other drivers",
    ],
    correctIndex: 2,
    explanation: "As people age, their reaction time gets slower. The rate of decline varies from person to person but you can expect them to take longer to react to a hazard and they may be hesitant in some situations – for example, at a junction.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2558",
    questionText: "Do you need to plan rest stops when you’re planning a long journey?",
    options: [
    "Yes, you should plan to stop every half an hour",
    "Yes, regular stops help concentration",
    "No, you’ll be less tired if you get there as soon as possible",
    "No, only fuel stops will be needed",
    ],
    correctIndex: 1,
    explanation: "Try to plan your journey so that you can take rest stops. It’s recommended that you take a break of at least 15 minutes after every 2 hours of driving or riding. This should help to maintain your concentration.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2596",
    questionText: "What should you do if the red lights start flashing as you approach a level crossing?",
    options: [
    "Go over it quickly",
    "Go over it carefully",
    "Stop before the barrier",
    "Switch on your hazard warning lights",
    ],
    correctIndex: 2,
    explanation: "At level crossings, the red lights flash before and while the barrier is down. At most crossings, an amber light will precede the red lights. You must stop behind the white line unless you've already crossed it when the amber light comes on. Do not be tempted to zigzag around half-barriers.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2651",
    questionText: "You're approaching a crossroads. What should you do if the traffic lights have failed?",
    options: [
    "Brake and stop only for large vehicles",
    "Brake sharply to a stop before looking",
    "Be prepared to brake sharply to a stop",
    "Be prepared to stop for any traffic",
    ],
    correctIndex: 3,
    explanation: "When approaching a junction where the traffic lights have failed, you should proceed with caution. Treat the situation as an unmarked junction and be prepared to stop.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2657",
    questionText: "What should the driver of the red car (arrowed) do?",
    options: [
    "Wave towards the pedestrians who are waiting to cross",
    "Wait for the pedestrian in the road to cross",
    "Quickly drive behind the pedestrian in the road",
    "Tell the pedestrian in the road she should not have crossed",
    ],
    correctIndex: 1,
    explanation: "Some people might take a long time to cross the road. They may be older or have a disability. Be patient and do not hurry them by showing your impatience. If pedestrians are standing at the side of the road, do not signal or wave them to cross. Other road users might not have seen your signal and this could lead the pedestrians into a hazardous situation.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2658",
    questionText: "You're following a slower-moving vehicle. What should you do if there's a junction just ahead on the right?",
    options: [
    "Overtake after checking your mirrors and signalling",
    "Only consider overtaking when you're past the junction",
    "Accelerate quickly to overtake before reaching the junction",
    "Slow down and prepare to overtake on the left",
    ],
    correctIndex: 1,
    explanation: "You should never overtake as you approach a junction. If a vehicle emerged from the junction while you were overtaking, a dangerous situation could develop very quickly.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2659",
    questionText: "What should you do as you approach this overhead bridge?",
    options: [
    "Move out to the centre of the road before going through",
    "Find another route; this one is only for high vehicles",
    "Be prepared to give way to large vehicles in the middle of the road",
    "Move across to the right-hand side before going through",
    ],
    correctIndex: 2,
    explanation: "Oncoming large vehicles may need to move to the middle of the road to pass safely under the bridge. There will not be enough room for you to continue, so you should be ready to stop and wait.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2687",
    questionText: "Why are vehicle mirrors often slightly curved (convex)?",
    options: [
    "They give a wider field of vision",
    "They totally cover blind spots",
    "They make it easier to judge the speed of the traffic behind",
    "They make the traffic behind look bigger",
    ],
    correctIndex: 0,
    explanation: "Although a convex mirror gives a wide view of the scene behind, you should be aware that it will not show you everything behind or to the side of your vehicle. Before you move off, you'll need to look over your shoulder to check for anything not visible in the mirrors.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2701",
    questionText: "You're on a three-lane motorway. How should you overtake a slow-moving lorry in the middle lane if it's showing this sign?",
    options: [
    "Cautiously approach the lorry, then overtake on either side",
    "Follow the lorry until you can leave the motorway",
    "Use the right-hand lane and overtake the lorry normally",
    "Approach with care and overtake on the left of the lorry",
    ],
    correctIndex: 3,
    explanation: "This sign is found on slow-moving or stationary works vehicles. If you wish to overtake it, do so on the left, as indicated. Be aware that there might be people working in the area.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2716",
    questionText: "What should you do if you think the driver of the vehicle in front has forgotten to cancel their right indicator?",
    options: [
    "Flash your lights to alert the driver",
    "Sound your horn before overtaking",
    "Overtake on the left if there's room",
    "Stay behind and do not overtake",
    ],
    correctIndex: 3,
    explanation: "Be cautious and do not attempt to overtake. The driver may be unsure of the location of a junction and may turn suddenly.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2717",
    questionText: "What's the main hazard the driver of the red car (arrowed) should be aware of?",
    options: [
    "Glare from the sun may affect the driver's vision",
    "The black car may stop suddenly",
    "The bus may move out into the road",
    "Oncoming vehicles will assume the driver is turning right",
    ],
    correctIndex: 2,
    explanation: "If you can do so safely, give way to buses signalling to move off at bus stops. Try to anticipate the actions of other road users around you. The driver of the red car should be prepared for the bus pulling out. As you approach a bus stop, look to see how many passengers are waiting to board. If the last one has just got on, the bus is likely to move off.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2718",
    questionText: "What type of vehicle displays this yellow sign?",
    options: [
    "A broken-down vehicle",
    "A school bus",
    "An ice-cream van",
    "A private ambulance",
    ],
    correctIndex: 1,
    explanation: "Buses which carry children to and from school may stop at places other than scheduled bus stops. Be aware that they might pull over at any time to allow children to get on or off. This will normally be when traffic is heavy during rush hour.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2719",
    questionText: "What hazard should you be aware of when travelling along this street?",
    options: [
    "Glare from the sun",
    "Lack of road markings",
    "Children running out between vehicles",
    "Heavy goods vehicles",
    ],
    correctIndex: 2,
    explanation: "On roads where there are many parked vehicles, you might not be able to see children between parked cars and they may run out into the road without looking.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2720",
    questionText: "What's the main hazard you should be aware of when following this cyclist?",
    options: [
    "The cyclist may move to the left and dismount",
    "The cyclist may swerve into the road",
    "The cyclist may get off and push their bicycle",
    "The cyclist may wish to turn right at the end of the road",
    ],
    correctIndex: 1,
    explanation: "When following a cyclist, be aware that they have to deal with the hazards around them. They may wobble or swerve to avoid a pothole in the road or see a potential hazard and change direction suddenly. Do not follow them too closely or rev your engine impatiently.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2721",
    questionText: "A driver’s behaviour has upset you. How can you get over this incident safely?",
    options: [
    "Stop and take a break",
    "Shout abusive language",
    "Gesture to them with your hand",
    "Follow them, flashing your headlights",
    ],
    correctIndex: 0,
    explanation: "If you feel yourself becoming tense or upset, stop in a safe place and take a break. Tiredness can make things worse and may cause a different reaction to upsetting situations.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2723",
    questionText: "How should you drive or ride in areas with traffic-calming measures?",
    options: [
    "At a reduced speed",
    "At the speed limit",
    "In the centre of the road",
    "With headlights on dipped beam",
    ],
    correctIndex: 0,
    explanation: "Traffic-calming measures such as road humps, chicanes and narrowings are intended to slow traffic down to protect vulnerable road users. Do not speed up until you reach the end of the traffic-calmed zone.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2724",
    questionText: "Why should you slow down as you approach this hazard?",
    options: [
    "Because of the level crossing",
    "Because it’s hard to see to the right",
    "Because of approaching traffic",
    "Because of animals crossing",
    ],
    correctIndex: 0,
    explanation: "You should be slowing down and selecting the correct gear in case you have to stop at the level crossing. Look for the signals and be prepared to stop if necessary.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2725",
    questionText: "Why are place names painted on the road surface?",
    options: [
    "To restrict the flow of traffic",
    "To warn of oncoming traffic",
    "To help you select the correct lane in good time",
    "To prevent you from changing lanes",
    ],
    correctIndex: 2,
    explanation: "The names of towns and cities may be painted on the road at busy junctions and complex road systems. They guide you into the correct lane in good time, allowing traffic to flow more freely.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2736",
    questionText: "Some two-way roads are divided into 3 lanes. Why are they particularly dangerous?",
    options: [
    "Traffic in both directions may be able to use the middle lane to overtake",
    "Traffic can travel faster in poor weather conditions",
    "Traffic can overtake on the left",
    "Traffic uses the middle lane for emergencies only",
    ],
    correctIndex: 0,
    explanation: "If you intend to overtake, you must consider that approaching traffic could be planning the same manoeuvre. When you've considered the situation and decided it's safe, indicate your intentions early. This will show the approaching traffic that you intend to pull out.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2844",
    questionText: "What type of vehicle uses an amber flashing beacon on a dual carriageway?",
    options: [
    "An ambulance",
    "A fire engine",
    "A doctor on call",
    "A tractor",
    ],
    correctIndex: 3,
    explanation: "An amber flashing beacon on a vehicle indicates that it's moving slowly or stopped and a possible hazard. Look well ahead on a dual carriageway and you should be able to see and respond to these vehicles in good time.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2847",
    questionText: "What does this signal from a police officer mean to oncoming traffic?",
    options: [
    "Go ahead",
    "Stop",
    "Turn left",
    "Turn right",
    ],
    correctIndex: 1,
    explanation: "Police officers may need to direct traffic; for example, at a junction where the traffic lights have broken down. Check your copy of The Highway Code for the signals that they use.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2848",
    questionText: "Why should you be cautious when going past this bus waiting at a bus stop?",
    options: [
    "There's a zebra crossing ahead",
    "There are driveways on the left",
    "People may cross the road in front of it",
    "The road surface will be slippery",
    ],
    correctIndex: 2,
    explanation: "A bus at a bus stop can hide pedestrians who might try to cross the road just in front of it. Drive at a speed that will allow you to respond safely if you have to.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2871",
    questionText: "Where would it be unsafe to overtake?",
    options: [
    "On a single carriageway",
    "On a one-way street",
    "Approaching a junction",
    "Travelling up a long hill",
    ],
    correctIndex: 2,
    explanation: "You should overtake only when it's really necessary and you can see it’s clear ahead. Look out for road signs and markings that show it's illegal or would be unsafe to overtake; for example, approaching junctions or bends. In many cases, overtaking is unlikely to significantly improve your journey time.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "AB2902",
    questionText: "How can drinking alcohol affect your ability to drive or ride?",
    options: [
    "Your ability to judge speed will be reduced",
    "Your confidence will be reduced",
    "Your reactions will be faster",
    "Your awareness of danger will be improved",
    ],
    correctIndex: 0,
    explanation: "Alcohol will severely reduce your ability to drive or ride safely and there are serious consequences if you’re caught over the drink-drive limit. It's known that alcohol can\r\n•  affect your judgement\r\n•  cause overconfidence\r\n•  reduce coordination and control.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1081",
    questionText: "What does the solid white line at the side of the road indicate?",
    options: [
    "Traffic lights ahead",
    "Edge of the carriageway",
    "Footpath on the left",
    "Cycle path",
    ],
    correctIndex: 1,
    explanation: "The continuous white line shows the edge of the carriageway. It can be especially useful when visibility is restricted, such as at night or in bad weather. It's discontinued in some places; for example, at  junctions, lay-bys, entrances or other openings.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1085",
    questionText: "You're driving towards this level crossing. What would be the first warning of an approaching train?",
    options: [
    "Both half-barriers down",
    "A steady amber light",
    "One half-barrier down",
    "Twin flashing red lights",
    ],
    correctIndex: 1,
    explanation: "The steady amber light will be followed by twin flashing red lights that mean you must stop. An alarm will also sound to alert you to the fact that a train is approaching.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1087",
    questionText: "You're behind this cyclist. When the traffic lights change, what should you do?",
    options: [
    "Try to move off before the cyclist",
    "Allow the cyclist time and room",
    "Turn right but give the cyclist room",
    "Tap your horn and drive through first",
    ],
    correctIndex: 1,
    explanation: "Hold back and allow the cyclist to move off. Some junctions have special areas marked across the front of the traffic lane. These allow cyclists to wait for the lights to change and move off ahead of other traffic.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1095",
    questionText: "You intend to turn left at the traffic lights. What should you do just before turning?",
    options: [
    "Check your right mirror",
    "Move up closer to the car ahead",
    "Move out to the right",
    "Check for bicycles on your left",
    ],
    correctIndex: 3,
    explanation: "If you've been in a queue of traffic and are about to turn left, check your nearside for cyclists as they often filter past on the nearside of slow-moving or stationary vehicles.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1096",
    questionText: "Why should you reduce your speed here?",
    options: [
    "A staggered junction is ahead",
    "A low bridge is ahead",
    "The road surface changes ahead",
    "The road narrows ahead",
    ],
    correctIndex: 0,
    explanation: "Traffic could be turning off or pulling out ahead of you, to the left or right. Vehicles turning left will be slowing down before the junction, and any vehicles turning right may have to stop to allow oncoming traffic to clear. Be prepared for this, as you might have to slow down or stop behind them.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1099",
    questionText: "What might you expect to happen in this situation?",
    options: [
    "Traffic will move into the right-hand lane",
    "Traffic speed will increase",
    "Traffic will move into the left-hand lane",
    "Traffic will not need to change position",
    ],
    correctIndex: 2,
    explanation: "Be courteous and allow the traffic to merge into the left-hand lane.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1100",
    questionText: "You're driving on a road with several lanes. What do these signs above the lanes mean?",
    options: [
    "The 2 right lanes are open",
    "The 2 left lanes are open",
    "Traffic in the left lanes should stop",
    "Traffic in the right lanes should stop",
    ],
    correctIndex: 1,
    explanation: "On some busy roads, lane control signals are used to vary the number of lanes available to give priority to the main traffic flow. A green arrow indicates that the lane is available to traffic facing the signal. A white diagonal arrow means that the lane is closed ahead and traffic should move to the next lane on the left. A red cross means that the lane is closed to traffic facing the signal.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1109",
    questionText: "You're invited to a pub lunch. What should you do if you know that you'll have to drive in the evening?",
    options: [
    "Avoid mixing your alcoholic drinks",
    "Do not drink any alcohol at all",
    "Have some milk before drinking alcohol",
    "Eat a hot meal with your alcoholic drinks",
    ],
    correctIndex: 1,
    explanation: "Alcohol will stay in your body for several hours and may make you unfit to drive later in the day. Drinking during the day will also affect your performance at work or study.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1112",
    questionText: "What will become more expensive after you've been convicted of driving while unfit through drink or drugs?",
    options: [
    "Road fund licence",
    "Insurance premiums",
    "Vehicle test certificate",
    "Driving licence",
    ],
    correctIndex: 1,
    explanation: "You've shown that you're a risk to yourself and others on the road. For this reason, insurance companies may charge you a higher premium.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1113",
    questionText: "What advice should you give to a driver who has had a few alcoholic drinks at a party?",
    options: [
    "Have a strong cup of coffee and then drive home",
    "Drive home carefully and slowly",
    "Go home by public transport",
    "Wait a short while and then drive home",
    ],
    correctIndex: 2,
    explanation: "Drinking black coffee or waiting a few hours will not make any difference. Alcohol takes time to leave the body. \r\nA driver who has been drinking should go home by public transport or taxi. They might even be unfit to drive the following morning.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1115",
    questionText: "What should you do about driving if you've been taking medicine that causes drowsiness?",
    options: [
    "Only drive if your journey is necessary",
    "Drive on quiet roads",
    "Ask someone to come with you",
    "Avoid driving and check with your doctor",
    ],
    correctIndex: 3,
    explanation: "You’re not fit to drive if you're taking medicine that makes you drowsy. Check with your doctor if you're unsure. You must not put other road users, your passengers or yourself at risk.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1116",
    questionText: "What should you do if a doctor prescribes drugs that are likely to affect your driving?",
    options: [
    "Only drive if someone is with you",
    "Avoid driving on motorways",
    "Get someone else to drive",
    "Never drive at more than 30 mph",
    ],
    correctIndex: 2,
    explanation: "You should not drive if you're taking medicine that could cause you to feel drowsy at the wheel. Ask someone else to drive or, if that’s not possible, find another way to get home.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1117",
    questionText: "What must you do if your ability to drive is impaired during a period of illness?",
    options: [
    "See your doctor each time before you drive",
    "Take smaller doses of any medicines",
    "Stop driving until you're fit to drive again",
    "Take all your medicines with you when you drive",
    ],
    correctIndex: 2,
    explanation: "Only drive if you're fit to do so. Driving when you're ill or taking some medicines can affect your concentration and judgement. It may also cause you to become drowsy or even fall asleep.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1120",
    questionText: "What should you do if you begin to feel drowsy while you're driving?",
    options: [
    "Stop and rest as soon as possible",
    "Turn the heater up to keep you warm and comfortable",
    "Close the car windows to help you concentrate",
    "Continue with your journey but drive more slowly",
    ],
    correctIndex: 0,
    explanation: "You'll be putting other road users at risk if you continue to drive when you're drowsy. Pull over and stop in a safe place for a rest. If you're driving a long distance, think about finding some accommodation so you can rest for longer before continuing your journey.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1121",
    questionText: "What should you do if you become tired while you're driving on a motorway?",
    options: [
    "Pull up on the hard shoulder and change drivers",
    "Leave the motorway at the next exit and rest",
    "Increase your speed and turn up the radio volume",
    "Close all your windows and set the heating to warm",
    ],
    correctIndex: 1,
    explanation: "If you feel yourself becoming tired or sleepy, you should leave the motorway at the next exit or services and stop for a rest. If you have to drive a long way, leave earlier and plan your journey to include rest stops. That way, you're less likely to become tired while driving and you'll still arrive in good time.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1123",
    questionText: "You're about to drive home. What should you do if you feel very tired and have a severe headache?",
    options: [
    "Wait until you're fit and well before driving",
    "Drive home, but take a tablet for headaches",
    "Drive home if you can stay awake for the journey",
    "Wait for a short time, then drive home slowly",
    ],
    correctIndex: 0,
    explanation: "All of your concentration should be on your driving. Any pain you feel will distract you, and you should avoid driving when drowsy. The safest course of action is to wait until you've rested and are feeling better before starting your journey.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1127",
    questionText: "What can you do to help prevent tiredness on a long journey?",
    options: [
    "Eat a large meal before driving",
    "Take regular refreshment breaks",
    "Play loud music in the car",
    "Complete the journey without stopping",
    ],
    correctIndex: 1,
    explanation: "Long-distance driving can be boring. This, coupled with a stuffy, warm vehicle, can make you feel tired and sleepy. Make sure you take rest breaks to help you stay awake and alert. Stop in a safe place before you get to the stage of fighting sleep.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1284",
    questionText: "You take some cough medicine given to you by a friend. What should you do before driving your car?",
    options: [
    "Ask your friend if taking the medicine affected their driving",
    "Drink some strong coffee one hour before driving",
    "Check the label to see if the medicine will affect your driving",
    "Drive a short distance to see if the medicine is affecting your driving",
    ],
    correctIndex: 2,
    explanation: "If you've taken medicine, never drive without first checking what the side effects might be; they might affect your judgement and perception, and therefore endanger lives.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1353",
    questionText: "You're driving on a one-way street. What should you do if you realise you've taken the wrong route?",
    options: [
    "Reverse out of the road",
    "Turn around in a side road",
    "Continue and find another route",
    "Reverse into a driveway",
    ],
    correctIndex: 2,
    explanation: "Never reverse or turn your vehicle around in a one-way street. It's illegal and could even cause a collision. If you've taken a wrong turn, carry on along the one-way street and find another route, checking the direction signs as you drive. Stop in a safe place if you need to check a map.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1380",
    questionText: "What will be a serious distraction while you're driving?",
    options: [
    "Looking at road maps",
    "Switching on your demister",
    "Using your windscreen washers",
    "Looking in your door mirror",
    ],
    correctIndex: 0,
    explanation: "Looking at road maps while driving is very dangerous. If you’re not sure of your route, stop in a safe place and check the map. You must not allow anything to take your attention away from the road while you’re driving.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1397",
    questionText: "What should you do if the vehicle starts reversing off the driveway?",
    options: [
    "Move to the opposite side of the road",
    "Drive through as you have priority",
    "Sound your horn and be prepared to stop",
    "Speed up and drive through quickly",
    ],
    correctIndex: 2,
    explanation: "White lights at the rear of a car show that the driver has selected reverse gear. The driver is hidden from view so cannot see you approaching. Sound your horn to warn of your presence, and be ready to stop if the car reverses into your path.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1398",
    questionText: "You've been involved in an argument that's made you feel angry. What should you do before starting your journey?",
    options: [
    "Open a window",
    "Turn on your radio",
    "Have an alcoholic drink",
    "Calm down",
    ],
    correctIndex: 3,
    explanation: "If you're feeling upset or angry, you'll find it much more difficult to concentrate on your driving. You should wait until you've calmed down before starting a journey.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1454",
    questionText: "You're driving on this dual carriageway. Why may you need to slow down?",
    options: [
    "There's a broken white line in the centre",
    "There are solid white lines on either side",
    "There are roadworks ahead of you",
    "There are no footpaths",
    ],
    correctIndex: 2,
    explanation: "Look well ahead and read any road signs as you drive. They're there to inform you of what's ahead. In this case, you may need to slow down and change direction. \r\nCheck your mirrors so you know what's happening around you before you change speed or direction.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1455",
    questionText: "You've just been overtaken by this motorcyclist. What should you do if the rider cuts in sharply?",
    options: [
    "Sound the horn",
    "Brake firmly",
    "Keep a safe gap",
    "Flash your lights",
    ],
    correctIndex: 2,
    explanation: "If another vehicle cuts in sharply, ease off the accelerator and drop back to allow a safe separation distance. Try not to overreact by braking sharply or swerving, as you could lose control. If vehicles behind you are too close or unprepared, it could lead to a crash.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1457",
    questionText: "You're about to drive your car back home. What should you do if you cannot find the glasses you need to wear?",
    options: [
    "Drive home slowly, keeping to quiet roads",
    "Borrow a friend’s glasses and use those",
    "Drive home at night, so that the lights will help you",
    "Find a way of getting home without driving",
    ],
    correctIndex: 3,
    explanation: "If you need to wear glasses for driving, it's illegal to drive without them. You must be able to see clearly when you're driving.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1459",
    questionText: "How does drinking alcohol affect your driving behaviour?",
    options: [
    "It improves judgement skills",
    "It increases confidence",
    "It leads to faster reactions",
    "It increases concentration",
    ],
    correctIndex: 1,
    explanation: "Alcohol can increase confidence to a point where your driving behaviour might become ‘out of character’. Sensible behaviour might change to risk-taking behaviour. Never let yourself or your friends get into this situation.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1461",
    questionText: "Why should you check the information leaflet before taking any medicine?",
    options: [
    "Drug companies want customer feedback on their products",
    "You may have to let your insurance company know about the medicine",
    "Some types of medicine can affect your ability to drive safely",
    "The medicine you take may affect your hearing",
    ],
    correctIndex: 2,
    explanation: "Always check the label or information leaflet for any medication you take. The medicine might affect your driving. If you’re not sure, ask your doctor or pharmacist.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1514",
    questionText: "You need glasses to read a vehicle number plate at the required distance. When must you wear them?",
    options: [
    "Only in bad weather conditions",
    "Whenever you're driving",
    "When you think it's necessary",
    "Only at night time",
    ],
    correctIndex: 1,
    explanation: "Have your eyesight tested before you start your practical training. Then, throughout your driving life, have checks periodically, as your vision may change.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1546",
    questionText: "Which type of glasses would make driving at night more difficult?",
    options: [
    "Half-moon",
    "Round",
    "Bifocal",
    "Tinted",
    ],
    correctIndex: 3,
    explanation: "If you're driving at night or in poor visibility, tinted lenses will reduce the efficiency of your vision by reducing the amount of light reaching your eyes.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1564",
    questionText: "What can seriously reduce your ability to concentrate?",
    options: [
    "Drugs",
    "Busy roads",
    "Tinted windows",
    "Weather conditions",
    ],
    correctIndex: 0,
    explanation: "Both recreational drugs and prescribed medicine can affect your concentration. It's also an offence to drive with certain drugs in your body and a positive test could lead to a conviction.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1568",
    questionText: "What must you do if your eyesight has become very poor and you're no longer able to meet the driver's eyesight requirements?",
    options: [
    "Tell the driver licensing authority",
    "Tell your doctor",
    "Tell the police",
    "Tell your optician",
    ],
    correctIndex: 0,
    explanation: "Having very poor eyesight will have a serious effect on your ability to drive safely. If you cannot meet the driver's eyesight requirements, you must tell DVLA (or DVA in Northern Ireland).",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1575",
    questionText: "When should you use hazard warning lights?",
    options: [
    "When you're double-parked on a two-way road",
    "When your direction indicators are not working",
    "When warning oncoming traffic that you intend to stop",
    "When your vehicle has broken down and is causing an obstruction",
    ],
    correctIndex: 3,
    explanation: "Hazard warning lights are an important safety feature and should be used if you've broken down and are causing an obstruction. Do not use them as an excuse to park illegally. You may also use them on motorways or unrestricted dual carriageways to warn traffic behind you of danger ahead.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1576",
    questionText: "You want to turn left at this junction. What should you do if your view of the main road is restricted?",
    options: [
    "Stay well back and wait to see if anything comes",
    "Build up your speed so that you can emerge quickly",
    "Stop and apply the parking brake even if the road is clear",
    "Approach slowly and edge out until you can see more clearly",
    ],
    correctIndex: 3,
    explanation: "You should slow right down, and stop if necessary, at any junction where your view is restricted. Edge forward until you can see properly. Only then can you decide whether it's safe to go.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1596",
    questionText: "You're driving a car fitted with automatic transmission. When would you use ‘kick-down’?",
    options: [
    "To engage cruise control",
    "To accelerate quickly",
    "To brake progressively",
    "To improve fuel economy",
    ],
    correctIndex: 1,
    explanation: "‘Kick-down’ selects a lower gear, allowing the vehicle to accelerate faster.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1664",
    questionText: "What should you do if it's raining and you're following this lorry on a motorway?",
    options: [
    "Allow a two-second separation gap",
    "Switch your headlights onto main beam",
    "Move into a lane that has less spray",
    "Be aware of spray reducing your vision",
    ],
    correctIndex: 3,
    explanation: "The usual two-second time gap increases to 4 seconds when the roads are wet. If you stay well back, you’ll\r\n• be able to see past the vehicle\r\n• be out of the spray thrown up by the lorry’s tyres\r\n• give yourself more time to stop if the need arises\r\n• increase your chances of being seen by the lorry driver.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1665",
    questionText: "You're driving towards this left-hand bend. What danger should you be anticipating?",
    options: [
    "A vehicle overtaking you",
    "Mud on the road",
    "The road getting narrower",
    "Pedestrians walking towards you",
    ],
    correctIndex: 3,
    explanation: "Pedestrians walking on a road with no pavement should walk against the direction of the traffic. You cannot see around this bend and if pedestrians are in the road you need to be able to deal with the situation safely. Always keep this in mind and give yourself time to react if a hazard does appear.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1666",
    questionText: "What should you do if the traffic in the left-hand lane is slowing?",
    options: [
    "Slow down, keeping a safe separation distance",
    "Accelerate past the vehicles in the left-hand lane",
    "Pull up on the left-hand verge",
    "Move across and continue in the right-hand lane",
    ],
    correctIndex: 0,
    explanation: "Allow the traffic to merge into the left-hand lane. Leave enough room so that you can maintain a safe separation distance, even if vehicles pull in ahead of you.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1670",
    questionText: "When may you use hazard warning lights?",
    options: [
    "When driving on a motorway to warn traffic behind of a hazard ahead",
    "When you're double-parked on a two-way road",
    "When your direction indicators are not working",
    "When warning oncoming traffic that you intend to stop",
    ],
    correctIndex: 0,
    explanation: "Hazard warning lights are an important safety feature. Use them when driving on a motorway or unrestricted dual carriageway to warn traffic behind you of danger ahead. \r\nYou should also use them if your vehicle has broken down and is causing an obstruction.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1727",
    questionText: "You're waiting to emerge at a junction. Your view is restricted by parked vehicles. What can help you to see traffic on the road you're joining?",
    options: [
    "Looking for traffic behind you",
    "Reflections of traffic in windows",
    "Making eye contact with other road users",
    "Checking for traffic in your interior mirror",
    ],
    correctIndex: 1,
    explanation: "You must be completely sure it's safe to emerge. Try to look for traffic through the windows of the parked cars or in the reflections in windows. Keep looking in all directions as you slowly edge forwards until you can see it's safe.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1743",
    questionText: "What must you do if poor health affects your driving?",
    options: [
    "Inform your local police",
    "Avoid using motorways",
    "Always drive accompanied",
    "Inform the licensing authority",
    ],
    correctIndex: 3,
    explanation: "You must tell DVLA (or DVA in Northern Ireland) if your health is likely to affect your ability to drive. The licensing authority will investigate your situation and then make a decision on whether you're fit enough to drive safely.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1748",
    questionText: "Why should the junction on the left be kept clear?",
    options: [
    "To allow vehicles to enter and emerge",
    "To allow the bus to reverse",
    "To allow vehicles to make a U-turn",
    "To allow vehicles to park",
    ],
    correctIndex: 0,
    explanation: "You should always try to keep junctions clear. If you're in queuing traffic, make sure that when you stop you leave enough space for traffic to flow in and out of the junction.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
  {
    id: "BB1779",
    questionText: "What should you do if you start to feel drowsy while you're driving on a motorway?",
    options: [
    "Stop on the hard shoulder for a sleep",
    "Open a window and stop as soon as it’s safe and legal",
    "Speed up to arrive at your destination sooner",
    "Slow down and let other drivers overtake",
    ],
    correctIndex: 1,
    explanation: "Never stop on the hard shoulder to rest. If there's no service area for several miles, leave the motorway at the next exit and find somewhere safe and legal to pull over.",
    topicCategory: TopicCategory.HazardAwareness,
    difficulty: 1,
  },
];
