import { Question, TopicCategory } from '@clearpass/core';

export const motorwayRulesQuestions: Question[] = [
  {
    id: "AB2951",
    questionText: "How should you rejoin the motorway after a breakdown on the hard shoulder?",
    options: [
    "Build up speed on the hard shoulder before looking for a safe gap in the traffic",
    "Move straight out into the left-hand lane as you’re not allowed to drive on the hard shoulder",
    "Wait until a vehicle in the left-hand lane signals to you that it's safe to rejoin",
    "Keep your hazard lights flashing until you have safely rejoined the carriageway",
    ],
    correctIndex: 0,
    explanation: "To rejoin a motorway from the hard shoulder, you first need to build up speed on the hard shoulder. You can then look for a safe gap in the traffic in the left-hand lane. Watch for traffic that may be returning from a lane on the right into the left-hand lane.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2219",
    questionText: "You're joining a motorway from a slip road. How should you deal with traffic already on the motorway?",
    options: [
    "Carry on along the hard shoulder until you see a safe gap",
    "Stop at the end of the slip road and look for a safe gap",
    "Use the slip road to accelerate until you're moving much faster than the motorway traffic",
    "Match your speed to traffic in the left-hand lane and filter into a safe gap",
    ],
    correctIndex: 3,
    explanation: "You should give way to traffic already on the motorway. Where possible, traffic may move over to let you in, but do not force your way into the traffic stream. Traffic could be travelling at high speed, so try to match your speed to filter in without affecting the traffic flow.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2222",
    questionText: "What's the national speed limit on motorways for cars and motorcycles?",
    options: [
    "30 mph",
    "50 mph",
    "60 mph",
    "70 mph",
    ],
    correctIndex: 3,
    explanation: "Travelling at the national speed limit does not allow you to hog the right-hand lane. Always use the left-hand lane whenever possible. When leaving a motorway, get into the left-hand lane well before your exit. Reduce your speed on the slip road and look out for sharp bends or curves and traffic queuing at roundabouts.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2223",
    questionText: "Which vehicles should use the left-hand lane on a three-lane motorway?",
    options: [
    "Any vehicle that’s not overtaking",
    "Large vehicles only",
    "Emergency vehicles only",
    "Slow vehicles only",
    ],
    correctIndex: 0,
    explanation: "On a motorway, all traffic should use the left-hand lane unless overtaking. When overtaking a number of slower vehicles, move back to the left-hand lane when you’re safely past. Check your mirrors frequently and do not stay in the middle or right-hand lane if the left-hand lane is free.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2232",
    questionText: "Your vehicle breaks down on a motorway and you need to call for help. Why might it be better to use an emergency roadside telephone rather than a mobile phone?",
    options: [
    "It connects you to a local garage",
    "Using a mobile phone will distract other drivers",
    "It allows easy location by the emergency services",
    "Mobile phones do not work on motorways",
    ],
    correctIndex: 2,
    explanation: "On a motorway, it's best to use a roadside emergency telephone so that the emergency services are able to find you easily. The location of the nearest telephone is shown by an arrow on marker posts at the edge of the hard shoulder. If you use a mobile, find out the number on the nearest marker post before you call. This number will let the operator know where you are and in which direction you're travelling.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2236",
    questionText: "Your vehicle broke down on the hard shoulder of a motorway, but has now been repaired. How should you rejoin the main carriageway?",
    options: [
    "Move out onto the carriageway, then build up your speed",
    "Move out onto the carriageway using your hazard warning lights",
    "Gain speed on the hard shoulder before moving out onto the carriageway",
    "Wait on the hard shoulder until someone flashes their headlights at you",
    ],
    correctIndex: 2,
    explanation: "Signal your intention and build up sufficient speed on the hard shoulder so that you can filter into a safe gap in the traffic. Do not push your way into a small gap or cause other traffic to alter speed or direction.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2237",
    questionText: "You're travelling along a motorway. Where would you find a crawler or climbing lane?",
    options: [
    "On a steep gradient",
    "Before a service area",
    "Before a junction",
    "Along the hard shoulder",
    ],
    correctIndex: 0,
    explanation: "Large, slow-moving vehicles can hinder the progress of other traffic. On a steep gradient, an extra crawler lane may be provided for slow-moving vehicles to allow faster-moving traffic to flow more easily.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2241",
    questionText: "What do these motorway signs mean?",
    options: [
    "They're countdown markers to a bridge",
    "They're distance markers to the next telephone",
    "They're countdown markers to the next exit",
    "They warn of a police control ahead",
    ],
    correctIndex: 2,
    explanation: "The exit from a motorway is indicated by countdown markers. These are positioned 90 metres (100 yards) apart, the first being 270 metres (300 yards) from the start of the slip road. Move into the left-hand lane well before you reach the start of the slip road.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2242",
    questionText: "Where are amber reflective studs found on a motorway?",
    options: [
    "Between the hard shoulder and the carriageway",
    "Between the acceleration lane and the carriageway",
    "Between the central reservation and the carriageway",
    "Between each pair of lanes",
    ],
    correctIndex: 2,
    explanation: "On motorways, reflective studs of various colours are fixed in the road between the lanes. These help you to identify which lane you're in when it's dark or in poor visibility. Amber-coloured studs are found on the right-hand edge of the main carriageway, next to the central reservation.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2243",
    questionText: "What colour are the reflective studs between the lanes on a motorway?",
    options: [
    "Green",
    "Amber",
    "White",
    "Red",
    ],
    correctIndex: 2,
    explanation: "White studs are found between the lanes on motorways. They reflect back the light from your headlights. This is especially useful in bad weather, when visibility is restricted.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2244",
    questionText: "What colour are the reflective studs between a motorway and a slip road?",
    options: [
    "Amber",
    "White",
    "Green",
    "Red",
    ],
    correctIndex: 2,
    explanation: "The studs between the carriageway and the hard shoulder are normally red. These change to green where there's a slip road, helping you to identify slip roads when visibility is poor or when it's dark.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2525",
    questionText: "Your vehicle has broken down on a motorway. In which direction should you walk to find the nearest emergency telephone?",
    options: [
    "With the traffic flow",
    "Facing oncoming traffic",
    "In the direction shown on the marker posts",
    "In the direction of the nearest exit",
    ],
    correctIndex: 2,
    explanation: "Along the hard shoulder there are marker posts at 100-metre intervals. These will direct you to the nearest emergency telephone.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2573",
    questionText: "Why is it important to make full use of the slip road as you join a motorway?",
    options: [
    "Because there's space available to turn round if you need to",
    "To allow you direct access to the overtaking lanes",
    "To allow you to fit safely into the traffic flow in the left-hand lane",
    "Because you can continue on the hard shoulder",
    ],
    correctIndex: 2,
    explanation: "Try to join the motorway without affecting the progress of the traffic in the left-hand lane and always give way to traffic already on the motorway. At busy times, you may have to slow down to merge into slow-moving traffic.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2575",
    questionText: "How should you position yourself when you use the emergency telephone on a motorway?",
    options: [
    "Stay close to the carriageway",
    "Face the oncoming traffic",
    "Keep your back to the traffic",
    "Stand on the hard shoulder",
    ],
    correctIndex: 1,
    explanation: "Traffic is passing you at speed. If the draught from a large lorry catches you by surprise, it could blow you off balance and even onto the carriageway. By facing the oncoming traffic, you can see approaching lorries and so be prepared for their draught. You'll also be in a position to see any other hazards approaching.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2576",
    questionText: "What colour are the reflective studs between the hard shoulder and the left-hand lane of a motorway?",
    options: [
    "Green",
    "Red",
    "White",
    "Amber",
    ],
    correctIndex: 1,
    explanation: "Red studs are placed between the edge of the carriageway and the hard shoulder. Where slip roads leave or join the motorway, the studs are green.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2609",
    questionText: "On a three-lane motorway, which lane should you use if there's no traffic ahead?",
    options: [
    "Left",
    "Right",
    "Centre",
    "Either the right or centre",
    ],
    correctIndex: 0,
    explanation: "On a three-lane motorway, you should travel in the left-hand lane unless you’re overtaking. This applies regardless of the speed at which you’re travelling.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2611",
    questionText: "What should you do when going through a contraflow system on a motorway?",
    options: [
    "Use dipped headlights",
    "Keep a good distance from the vehicle ahead",
    "Switch lanes to keep the traffic flowing",
    "Stay close to the vehicle ahead to reduce queues",
    ],
    correctIndex: 1,
    explanation: "At roadworks, and especially where a contraflow system is operating, a speed restriction is likely to be in place. Keep to the lower speed limit and do not\r\n• switch lanes\r\n• get too close to the vehicle in front of you.\r\nBe aware that there will be no permanent barrier between you and the oncoming traffic.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2612",
    questionText: "You're on a three-lane motorway. Which lane are you in if there are red reflective studs on your left and white ones to your right?",
    options: [
    "In the right-hand lane",
    "In the middle lane",
    "On the hard shoulder",
    "In the left-hand lane",
    ],
    correctIndex: 3,
    explanation: "The colours of the reflective studs on the motorway and their locations are\r\n• red – between the hard shoulder and the carriageway\r\n• white – between lanes\r\n• amber – between the carriageway and the central reservation\r\n• green – along slip-road exits and entrances\r\n• bright green/yellow – at roadworks and contraflow systems.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2694",
    questionText: "What should you do when you're approaching roadworks on a motorway?",
    options: [
    "Speed up to clear the area quickly",
    "Always use the hard shoulder",
    "Obey the speed limit",
    "Stay very close to the vehicle in front",
    ],
    correctIndex: 2,
    explanation: "Be aware of reduced speed limits at roadworks. Speed limits shown inside a red circle are mandatory and cameras are often used to enforce the reduced limit. Slow down in good time and keep your distance from the vehicle in front.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2743",
    questionText: "Which vehicles are prohibited from using the motorway?",
    options: [
    "Powered mobility scooters",
    "Motorcycles over 50 cc",
    "Double-deck buses",
    "Cars with automatic transmission",
    ],
    correctIndex: 0,
    explanation: "Motorways must not be used by pedestrians, cyclists, motorcycles under 50 cc, certain slow-moving vehicles without permission, and powered wheelchairs/mobility scooters.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2744",
    questionText: "What should you do while you're driving or riding along a motorway?",
    options: [
    "Look much further ahead than you would on other roads",
    "Travel much faster than you would on other roads",
    "Maintain a shorter separation distance than you would on other roads",
    "Concentrate more than you would on other roads",
    ],
    correctIndex: 0,
    explanation: "Traffic on motorways usually travels faster than on other roads. You need to be looking further ahead to give yourself more time to react to any hazard that may develop.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2745",
    questionText: "What should you do immediately after joining a motorway?",
    options: [
    "Try to overtake",
    "Re-adjust your mirrors",
    "Position your vehicle in the centre lane",
    "Stay in the left-hand lane",
    ],
    correctIndex: 3,
    explanation: "When you've just joined a motorway, stay in the left-hand lane long enough to get used to the higher speeds of motorway traffic before considering overtaking.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2746",
    questionText: "When would you use the right-hand lane on a three-lane motorway?",
    options: [
    "When you're turning right",
    "When you're overtaking",
    "When you're travelling above the speed limit",
    "When you're trying to save fuel",
    ],
    correctIndex: 1,
    explanation: "The right-hand lane of the motorway is for overtaking. Sometimes you may be directed into a right-hand lane as a result of roadworks or a traffic incident. This will be indicated by signs or officers directing the traffic.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2747",
    questionText: "You're on a motorway. The hard shoulder is not being used as a running lane. When should you use the hard shoulder?",
    options: [
    "When you're stopping in an emergency",
    "When you're leaving the motorway",
    "When you're stopping for a rest",
    "When you're joining the motorway",
    ],
    correctIndex: 0,
    explanation: "Do not use the hard shoulder for stopping unless it's an emergency. If you want to stop for any other reason, go to the next exit or service area.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2748",
    questionText: "You're in the right-hand lane of a three-lane motorway. What do these overhead signs mean?",
    options: [
    "Move to the left and reduce your speed to 50 mph",
    "There are roadworks 50 metres (55 yards) ahead",
    "Use the hard shoulder until you've passed the hazard",
    "Leave the motorway at the next exit",
    ],
    correctIndex: 0,
    explanation: "You must obey these signs even if there appear to be no problems ahead. There could be queuing traffic or another hazard that you cannot see yet.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2749",
    questionText: "When are you allowed to stop on a motorway?",
    options: [
    "When you need to walk and get fresh air",
    "When you wish to pick up hitchhikers",
    "When you're signalled to do so by traffic signals",
    "When you need to use a mobile telephone",
    ],
    correctIndex: 2,
    explanation: "You must stop if overhead gantry signs show a red cross above every lane on the motorway. If any of the other lanes does not show a red cross, you may move into that lane and continue if it's safe to do so.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2750",
    questionText: "You're travelling in the left-hand lane of a three-lane motorway. How should you react to traffic joining from a slip road?",
    options: [
    "Increase your speed to make sure they join behind you",
    "Adjust your speed or change lane if you can do so safely",
    "Maintain a steady speed",
    "Switch on your hazard warning lights",
    ],
    correctIndex: 1,
    explanation: "Plan well ahead when approaching a slip road. If you see traffic joining the motorway, be prepared to adjust your speed or move to another lane if it's safe to do so. This can help the flow of traffic joining the motorway, especially at peak times.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2751",
    questionText: "How should you use the lanes on a motorway?",
    options: [
    "Use the lane that has the least traffic",
    "Keep to the left-hand lane unless you're overtaking",
    "Overtake using the lane that’s clearest",
    "Stay in one lane until you reach your exit",
    ],
    correctIndex: 1,
    explanation: "You should normally travel in the left-hand lane unless you're overtaking a slower-moving vehicle. When you've finished overtaking, move back into the left-hand lane, but do not cut across in front of the vehicle that you’ve overtaken.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2752",
    questionText: "You're travelling along a motorway. When are you allowed to overtake on the left?",
    options: [
    "When you can see well ahead that the hard shoulder is clear",
    "When the traffic in the right-hand lane is signalling right",
    "When you warn drivers behind by signalling left",
    "When in queues and traffic to your right is moving more slowly than you are",
    ],
    correctIndex: 3,
    explanation: "Never overtake on the left, unless the traffic is moving in queues and the queue on your right is moving more slowly than the one you're in.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2786",
    questionText: "When would you use an emergency area on a motorway?",
    options: [
    "In cases of emergency or breakdown",
    "If you think you'll be involved in a road rage incident",
    "To stop and check where you are",
    "To make a private phone call",
    ],
    correctIndex: 0,
    explanation: "On some motorways, emergency areas are built at the side of the carriageway. If you break down, try to get your vehicle into the emergency area where there's an emergency telephone. The phone connects directly to a control centre. Before rejoining the motorway, you must call the control centre - a lane may need to be closed to allow you to rejoin safely.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2788",
    questionText: "Traffic officers operate on motorways and some primary routes in England and Wales. What are they authorised to do?",
    options: [
    "Stop and arrest drivers who break the law",
    "Repair broken-down vehicles on the motorway",
    "Issue fixed penalty notices",
    "Stop and direct anyone on a motorway",
    ],
    correctIndex: 3,
    explanation: "Traffic officers do not have enforcement powers but are able to stop and direct people on motorways and some ‘A’ class roads. They operate in England and Wales and work in partnership with the police at incidents, providing a highly trained and visible service. They're recognised by an orange-and-yellow jacket and their vehicle has yellow-and-black markings.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2789",
    questionText: "You're on a motorway. What does it mean when a red cross is displayed above the hard shoulder?",
    options: [
    "Pull up in this lane to answer your mobile phone",
    "Use this lane as a running lane",
    "This lane can be used if you need a rest",
    "You must not travel in this lane",
    ],
    correctIndex: 3,
    explanation: "At certain times, the hard shoulder will be open as a running lane. However, a red cross above the hard shoulder shows that it is not open as a running lane and should only be used for emergencies and breakdowns.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2790",
    questionText: "You're on a motorway. What does it mean when a mandatory speed limit is displayed above the hard shoulder?",
    options: [
    "You should not travel in this lane",
    "The hard shoulder can be used as a running lane",
    "You can park on the hard shoulder if you feel tired",
    "You can pull up in this lane to answer a mobile phone",
    ],
    correctIndex: 1,
    explanation: "A mandatory speed limit sign above the hard shoulder shows that this part of the road can be used as a running lane between junctions. You must stay within the speed limit. Look out for vehicles that may have broken down and could be blocking the hard shoulder.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2792",
    questionText: "How is bunching reduced on motorways?",
    options: [
    "By using higher speed limits",
    "By using advisory speed limits",
    "By using minimum speed limits",
    "By using variable speed limits",
    ],
    correctIndex: 3,
    explanation: "You must follow the mandatory signs on the gantries above motorway lanes, including the hard shoulder. Variable speed limits help keep the traffic moving and also help to prevent bunching.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2839",
    questionText: "What helps to reduce traffic bunching on a motorway?",
    options: [
    "Variable speed limits",
    "Contraflow systems",
    "National speed limits",
    "Lane closures",
    ],
    correctIndex: 0,
    explanation: "Congestion can be reduced by keeping traffic at a constant speed. At busy times, maximum speed limits are displayed on overhead gantries. These can be varied quickly, depending on the amount of traffic. By keeping to a constant speed on busy sections of motorway, overall journey times are normally improved.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2843",
    questionText: "When may you stop on a motorway?",
    options: [
    "If you have to read a map",
    "When you're tired and need a rest",
    "If your mobile phone rings",
    "In an emergency or breakdown",
    ],
    correctIndex: 3,
    explanation: "You should not normally stop on a motorway, but there may be occasions when you need to do so. If your vehicle breaks down or there's an emergency, stop on the hard shoulder and use the emergency telephones to call for assistance.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2845",
    questionText: "What's the national speed limit for a car or motorcycle on a motorway?",
    options: [
    "50 mph",
    "60 mph",
    "70 mph",
    "80 mph",
    ],
    correctIndex: 2,
    explanation: "The national speed limit for a car or motorcycle on a motorway is 70 mph. Lower speed limits may be in force; for example, at roadworks. Variable speed limits also operate in some areas when the motorway is very busy. Cars or motorcycles towing trailers are subject to a lower speed limit.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2846",
    questionText: "You stop on the hard shoulder of a motorway and use the emergency telephone. Where's the best place to wait for help to arrive?",
    options: [
    "Next to the phone",
    "Well away from the carriageway",
    "With your vehicle",
    "On the hard shoulder",
    ],
    correctIndex: 1,
    explanation: "When you're on the hard shoulder, you're at risk of being injured by motorway traffic. The safest place to wait is away from the carriageway, but near enough to see the emergency services arriving.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2852",
    questionText: "You're on a motorway. What must you do if there's a red cross showing above every lane?",
    options: [
    "Pull onto the hard shoulder",
    "Slow down and watch for further signals",
    "Leave at the next exit",
    "Stop and wait",
    ],
    correctIndex: 3,
    explanation: "A red cross signal above all lanes means you must stop and wait. Do not change lanes and do not try to continue any further along the motorway.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2856",
    questionText: "You're on a motorway. What does it mean if a red cross is showing above the hard shoulder and mandatory speed limits above all other lanes?",
    options: [
    "The hard shoulder can be used as a rest area if you feel tired",
    "The hard shoulder is for emergency or breakdown use only",
    "The hard shoulder can be used as a normal running lane",
    "The hard shoulder has a speed limit of 50 mph",
    ],
    correctIndex: 1,
    explanation: "A red cross above the hard shoulder shows that it's closed as a running lane and should only be used for emergencies or breakdowns. On some motorways, the hard shoulder may be used as a running lane at busy times. This will be shown by a mandatory speed limit on the gantry above the hard shoulder.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2857",
    questionText: "What does this motorway sign mean?",
    options: [
    "Use any lane except the hard shoulder",
    "Use the hard shoulder only",
    "Use the 3 right-hand lanes only",
    "Use all the lanes, including the hard shoulder",
    ],
    correctIndex: 3,
    explanation: "You must obey mandatory speed limit signs above motorway lanes, including the hard shoulder. In this case, you can use the hard shoulder as a running lane but you should look for any vehicles that may have broken down and may be blocking the hard shoulder.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2882",
    questionText: "Where should you stop to rest if you feel tired while you're travelling along a motorway?",
    options: [
    "On the hard shoulder",
    "At the nearest service area",
    "On a slip road",
    "On the central reservation",
    ],
    correctIndex: 1,
    explanation: "If you feel tired, stop at the nearest service area. If that's too far away, leave the motorway at the next exit and find a safe place to stop. You must not stop on the carriageway or hard shoulder of a motorway except in an emergency, when in a traffic queue, or when signalled to do so by a police officer, a traffic officer or traffic signals. Plan your journey so that you have regular rest stops.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1193",
    questionText: "What's the speed limit for a car towing a trailer on a motorway?",
    options: [
    "40 mph",
    "50 mph",
    "60 mph",
    "70 mph",
    ],
    correctIndex: 2,
    explanation: "If you’re towing a small, light trailer, it will not reduce your vehicle’s performance by very much and it may not be visible in your mirrors. However, strong winds or buffeting from large vehicles might cause the trailer to snake from side to side. Be aware of your speed and do not exceed the reduced speed limit imposed on vehicles towing trailers.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1197",
    questionText: "When should you use the left-hand lane of a motorway?",
    options: [
    "When your vehicle breaks down",
    "When you're overtaking slower traffic in the other lanes",
    "When you're making a phone call",
    "When the road ahead is clear",
    ],
    correctIndex: 3,
    explanation: "You should drive in the left-hand lane whenever possible. Only use the other lanes for overtaking or when directed to do so by signals. Using other lanes when the left-hand lane is empty can frustrate drivers behind you.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1198",
    questionText: "You're driving on a motorway and have to slow down suddenly due to a hazard ahead. How can you warn drivers behind of the hazard?",
    options: [
    "Switch on your hazard warning lights",
    "Switch on your headlights",
    "Sound your horn",
    "Flash your headlights",
    ],
    correctIndex: 0,
    explanation: "Using your hazard warning lights, as well as your brake lights, will give the traffic behind an extra warning of the problem ahead. Only use them for long enough for your warning to be seen.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1199",
    questionText: "Your car gets a puncture while you're driving on the motorway. What should you do when you've stopped on the hard shoulder?",
    options: [
    "Carefully change the wheel yourself",
    "Use an emergency telephone and call for help",
    "Try to wave down another vehicle for help",
    "Only change the wheel if you have a passenger to help you",
    ],
    correctIndex: 1,
    explanation: "Park as far to the left as you can and leave the vehicle by the nearside door. Do not attempt even simple repairs. Instead, walk to an emergency telephone on your side of the road and phone for help. While waiting for help to arrive, stay by your car, keeping well away from the carriageway and hard shoulder.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1204",
    questionText: "What should you do if you're driving on a motorway and you miss the exit that you wanted to take?",
    options: [
    "Carefully reverse along the hard shoulder",
    "Carry on to the next exit",
    "Carefully reverse in the left-hand lane",
    "Make a U-turn at the next gap in the central reservation",
    ],
    correctIndex: 1,
    explanation: "It's illegal to reverse, cross the central reservation or drive against the traffic flow on a motorway. If you miss your exit, carry on until you reach the next one. Ask yourself why you missed your exit – if you think that your concentration is fading, take a break before continuing your journey.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1481",
    questionText: "Your vehicle has broken down on a motorway. What should you do if you’re not able to get onto the hard shoulder?",
    options: [
    "Switch on your hazard warning lights",
    "Stop the traffic behind and ask for help",
    "Attempt to repair your vehicle quickly",
    "Stand behind your vehicle to warn others",
    ],
    correctIndex: 0,
    explanation: "If you cannot get your vehicle onto the hard shoulder, use your hazard warning lights to warn others. Leave your vehicle only when you can safely get clear of the carriageway. Do not try to repair the vehicle or attempt to place any warning device on the carriageway.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1520",
    questionText: "Why is it particularly important to check your vehicle before making a long motorway journey?",
    options: [
    "You'll have to do more harsh braking on motorways",
    "Motorway services areas do not deal with breakdowns",
    "The road surface will wear down the tyres faster",
    "Continuous high speeds increase the risk of your vehicle breaking down",
    ],
    correctIndex: 3,
    explanation: "Before you start your journey, make sure that your vehicle can cope with the demands of high-speed driving. You should check a number of things; the main ones being fuel, oil, water and tyres. You also need to plan rest stops if you’re making a long journey.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1523",
    questionText: "You're driving on a motorway. What does it mean if the car in front shows its hazard warning lights for a short time?",
    options: [
    "The driver wants you to overtake",
    "The other car is going to change lanes",
    "Traffic ahead is slowing or stopping suddenly",
    "There's a police speed check ahead",
    ],
    correctIndex: 2,
    explanation: "If the vehicle in front shows its hazard warning lights, there may be an incident, stopped traffic or queuing traffic ahead. By keeping a safe distance from the vehicle in front, you're able to look beyond it and see any hazards well ahead.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1525",
    questionText: "You're driving on the motorway. Which lane should you get into well before you reach your exit?",
    options: [
    "The middle lane",
    "The left-hand lane",
    "The hard shoulder",
    "The right-hand lane",
    ],
    correctIndex: 1,
    explanation: "You’ll see the first advance direction sign one mile from a motorway exit. If you’re travelling at 60 mph in the right-hand lane, you’ll only have about 50 seconds before you reach the countdown markers. There'll be another sign at the half-mile point. Do not cut across lanes of traffic at the last moment – move to the left-hand lane in good time.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1618",
    questionText: "What restrictions apply to people who have a provisional driving licence?",
    options: [
    "They cannot drive over 30 mph",
    "They cannot drive at night",
    "They cannot drive unaccompanied",
    "They cannot drive with more than one passenger",
    ],
    correctIndex: 2,
    explanation: "You will not be able to drive unaccompanied until you've passed your practical driving test. If you’ve not driven on the motorway while you were learning, ask your instructor to take you for a lesson on the motorway when you've passed your test. Alternatively, you could take part in the Pass Plus scheme. This has been created for new drivers and includes motorway driving. Ask your instructor for details.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1688",
    questionText: "Your vehicle breaks down on a motorway and you manage to stop on the hard shoulder. What should you do if you use your mobile phone to call for help?",
    options: [
    "Stand at the rear of the vehicle while making the call",
    "Phone a friend and ask them to come and collect you",
    "Wait in the car for the emergency services to arrive",
    "Check your location from the nearest marker posts beside the hard shoulder",
    ],
    correctIndex: 3,
    explanation: "You should use an emergency telephone when you break down on the motorway; only use your mobile if this is not possible. The emergency services need to know your exact location so they can reach you as quickly as possible. Look for a number on the nearest marker post beside the hard shoulder. Give this number when you call the emergency services.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "BB1690",
    questionText: "What would you expect to find at a contraflow system on a motorway?",
    options: [
    "Temporary traffic lights",
    "Lower speed limits",
    "Wider lanes than normal",
    "Road humps",
    ],
    correctIndex: 1,
    explanation: "When approaching a contraflow system, reduce speed in good time and obey all speed limits. You may be travelling in a narrower lane than normal, with no permanent barrier between you and the oncoming traffic. Be aware that the hard shoulder may be used for traffic and the road ahead could be obstructed by slow-moving or broken-down vehicles.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2225",
    questionText: "Which vehicles are not allowed to use the right-hand lane of a three-lane motorway?",
    options: [
      "Small delivery vans",
      "Motorcycles",
      "Vehicles towing a trailer",
      "Motorcycle and sidecar outfits",
    ],
    correctIndex: 2,
    explanation: "On the motorway, any vehicle towing a trailer is restricted to 60 mph. It's not allowed in the right-hand lane, as it might hold up faster-moving traffic that wishes to overtake in that lane.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
  {
    id: "AB2950",
    questionText: "You have stopped in an emergency area. What must you do before you rejoin the carriageway?",
    options: [
      "Use the emergency telephone",
      "Give an arm signal as you're moving off",
      "Switch on your vehicle's headlights",
      "Move away with your hazard lights on",
    ],
    correctIndex: 0,
    explanation: "To rejoin the carriageway from an emergency area, you must use the emergency telephone and follow the operator's advice. A lane may have to be closed so that you can rejoin the carriageway safely.",
    topicCategory: TopicCategory.MotorwayRules,
    difficulty: 1,
  },
];
