import { Question, TopicCategory } from '@clearpass/core';

export const otherTypesQuestions: Question[] = [
  {
    id: "AB2176",
    questionText: "You're about to overtake a slow-moving motorcyclist. Which sign would make you take special care?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4664.png",
    explanation: "In windy weather, watch out for motorcyclists and also cyclists, as they can be blown sideways into your path. When you pass them, leave plenty of room and check their position in your mirror before pulling back in.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2177",
    questionText: "You're waiting to turn right out of a minor road. It's clear to the left but a lorry is coming from the right. Why should you wait, even if you have enough time to turn?",
    options: [
    "Anything overtaking the lorry will be hidden from view",
    "The lorry could suddenly speed up",
    "The lorry might be slowing down",
    "The load on the lorry might be unstable",
    ],
    correctIndex: 0,
    explanation: "Large vehicles can hide other vehicles that are overtaking – especially motorcycles. You need to be aware of the possibility of hidden vehicles and not assume that it's safe to turn.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2179",
    questionText: "You're following a long vehicle as it approaches a crossroads. What should you do if it signals left but moves out to the right?",
    options: [
    "Get closer in order to pass it quickly",
    "Stay well back and give it room",
    "Assume the signal is wrong and that it's turning right",
    "Overtake it as it starts to slow down",
    ],
    correctIndex: 1,
    explanation: "A long vehicle may need to swing out in the opposite direction as it approaches a turn, to allow the rear wheels to clear the kerb. Do not try to filter through if you see a gap; as the lorry turns, the gap will close.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2180",
    questionText: "You're following a long vehicle approaching a crossroads. What should you do if the driver signals right but moves close to the left-hand kerb?",
    options: [
    "Warn the driver about the wrong signal",
    "Wait behind the long vehicle",
    "Report the driver to the police",
    "Overtake on the right-hand side",
    ],
    correctIndex: 1,
    explanation: "When a long vehicle is going to turn right, it may need to keep close to the left-hand kerb. This is to prevent the rear end of the trailer cutting the corner. You need to be aware of how long vehicles behave in such situations. Do not overtake the lorry, because it could turn as you’re alongside. Stay behind and wait for it to turn.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2181",
    questionText: "You’re approaching a mini-roundabout. What should you do if a long vehicle in front signals left but positions over to the right?",
    options: [
    "Sound your horn",
    "Overtake on the left",
    "Follow the same course as the lorry",
    "Keep well back",
    ],
    correctIndex: 3,
    explanation: "At mini-roundabouts, there’s not much room for a long vehicle to manoeuvre. It will have to swing out wide so that it can complete the turn safely. Keep well back and do not try to move up alongside it.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2184",
    questionText: "You're travelling on a single carriageway road. Why should you keep well back while you're following a large vehicle?",
    options: [
    "To give yourself acceleration space if you decide to overtake",
    "To get the best view of the road ahead",
    "To leave a gap in case the vehicle stops and rolls back",
    "To offer other drivers a safe gap if they want to overtake you",
    ],
    correctIndex: 1,
    explanation: "When following a large vehicle, keep well back. If you’re too close, you will not be able to see the road ahead and the driver of the long vehicle might not be able to see you in their mirrors.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2189",
    questionText: "You're travelling behind a bus. What should you do if it pulls up at a bus stop?",
    options: [
    "Accelerate past the bus",
    "Look for pedestrians",
    "Sound your horn",
    "Pull in closely behind the bus",
    ],
    correctIndex: 1,
    explanation: "People may be running to catch the bus or passengers leaving the bus might wish to cross the road in front of the bus. Look out for them if you intend to go past it. Consider how many people are waiting to get on the bus – check the queue if you can. The bus might move off straight away if no-one is waiting to get on.\r\nIf a bus is signalling to pull out, give it priority if it’s safe to do so.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2193",
    questionText: "You're following a lorry on a wet road. What should you do when spray makes it difficult to see the road ahead?",
    options: [
    "Drop back until you can see better",
    "Put your headlights on full beam",
    "Keep close to the lorry, away from the spray",
    "Speed up and overtake quickly",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1940.jpg",
    explanation: "Large vehicles can throw up a lot of spray when it's wet. This makes it difficult for drivers behind to see the road ahead. You'll be able to see more by dropping back further, out of the spray. This will also increase your separation distance, giving you more room to stop if you have to.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2568",
    questionText: "You're leaving a safe gap as you follow a large vehicle. What should you do if a car moves into this gap?",
    options: [
    "Sound your horn",
    "Drop back further",
    "Flash your headlights",
    "Start to overtake",
    ],
    correctIndex: 1,
    explanation: "Sometimes your separation distance is shortened by a driver moving into the gap you've allowed. When this happens, react positively, stay calm and drop further back to re-establish a safe following distance.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2733",
    questionText: "What should you do when you're approaching a bus that's signalling to move away from a bus stop?",
    options: [
    "Get past before it moves",
    "Allow it to pull away, if it's safe to do so",
    "Flash your headlights as you approach",
    "Signal left and wave the bus on",
    ],
    correctIndex: 1,
    explanation: "Try to give way to buses if you can do so safely, especially when the driver signals to pull away from a bus stop. Look out for people getting off the bus or running to catch it, because they may cross the road without looking. Do not accelerate to get past the bus, and do not flash your lights, as this could mislead other road users.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2734",
    questionText: "What should you do if you want to overtake a long, slow-moving vehicle on a busy road?",
    options: [
    "Follow it closely and keep moving out to see the road ahead",
    "Flash your headlights for the oncoming traffic to give way",
    "Stay behind until the driver waves you past",
    "Keep well back so that you get a good view of the road ahead",
    ],
    correctIndex: 3,
    explanation: "When you're following a long vehicle, stay well back so that you can get a better view of the road ahead. The closer you get, the less you'll be able to see of the road. Be patient and do not take a gamble. Only overtake when you're certain that you can complete the manoeuvre safely.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2735",
    questionText: "Which vehicles are least likely to be affected by side wind?",
    options: [
    "Cyclists",
    "Motorcyclists",
    "High-sided vehicles",
    "Cars",
    ],
    correctIndex: 3,
    explanation: "Although cars are the least likely to be affected, side winds can take anyone by surprise. This is most likely to happen after overtaking a large vehicle, when passing gaps between hedges or buildings, and on exposed sections of road.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2737",
    questionText: "What should you do as you approach this lorry?",
    options: [
    "Slow down and be prepared to wait",
    "Make the lorry wait for you",
    "Flash your lights at the lorry",
    "Move to the right-hand side of the road",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/AB2737.png",
    explanation: "When turning, long vehicles need much more room on the road than other vehicles. At junctions, they may take up the whole of the road space, so be patient and allow them the room they need.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2739",
    questionText: "You're following a large vehicle as it approaches a crossroads. What should you do if the driver signals to turn left?",
    options: [
    "Overtake if you can leave plenty of room",
    "Overtake if there are no oncoming vehicles",
    "Wait for the driver to cancel their signal",
    "Wait for the vehicle to finish turning",
    ],
    correctIndex: 3,
    explanation: "Hold back and wait until the vehicle has turned before proceeding. Do not overtake, because the vehicle turning left could hide another vehicle emerging from the same junction.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "AB2881",
    questionText: "Why is it more difficult to overtake a large vehicle than a car?",
    options: [
    "It will take longer to overtake a large vehicle",
    "A large vehicle will be fitted with a speed limiter",
    "A large vehicle will have air brakes",
    "It will take longer for a large vehicle to accelerate",
    ],
    correctIndex: 0,
    explanation: "Depending on relative speed, it will usually take you longer to pass a lorry than other vehicles. Hazards to watch for include oncoming traffic, junctions ahead, bends or dips that could restrict your view, and signs or road markings that prohibit overtaking. Make sure you can see that it’s safe to complete the manoeuvre before you start to overtake.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1157",
    questionText: "It's very windy. What should you do if you're behind a motorcyclist who's overtaking a high-sided vehicle?",
    options: [
    "Overtake the motorcyclist immediately",
    "Keep well back",
    "Stay level with the motorcyclist",
    "Keep close to the motorcyclist",
    ],
    correctIndex: 1,
    explanation: "Windy weather affects motorcyclists more than other vehicles. In windy conditions, high-sided vehicles cause air turbulence. You should keep well back, as the motorcyclist could be blown off course.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1162",
    questionText: "What should you do if there's a bus at a bus stop ahead of you?",
    options: [
    "Flash your lights to warn the driver of your presence",
    "Continue at the same speed but sound your horn as a warning",
    "Watch carefully for the sudden appearance of pedestrians",
    "Pass the bus as quickly as you possibly can",
    ],
    correctIndex: 2,
    explanation: "As you approach, look out for any signal the driver might make. If you pass the vehicle, watch out for pedestrians attempting to cross the road from behind the bus. They’ll be hidden from view until the last moment.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1399",
    questionText: "What should you be prepared to do in this situation?",
    options: [
    "Sound your horn and continue",
    "Slow down and give way",
    "Report the driver to the police",
    "Squeeze through the gap",
    ],
    correctIndex: 1,
    explanation: "Sometimes, large vehicles may need more space than other road users. If a vehicle needs more time and space to turn, be prepared to stop and wait.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1578",
    questionText: "Why should drivers be more careful on roads where trams also operate?",
    options: [
    "Because trams do not have a horn",
    "Because trams cannot stop for cars",
    "Because trams do not have lights",
    "Because trams cannot steer to avoid obstructions",
    ],
    correctIndex: 3,
    explanation: "You should take extra care when you first encounter trams. You'll have to get used to dealing with a different traffic system. \r\nBe aware that trams can accelerate and travel very quickly, and they cannot change direction to avoid obstructions.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1679",
    questionText: "You're towing a caravan. Which is the safest type of rear-view mirror to use?",
    options: [
    "Interior wide-angle mirror",
    "Extended-arm side mirrors",
    "Ordinary door mirrors",
    "Ordinary interior mirror",
    ],
    correctIndex: 1,
    explanation: "Towing a large trailer or caravan can greatly reduce your view of the road behind. You may need to fit extended-arm side mirrors so that you can see clearly behind and down both sides of the caravan or trailer.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1680",
    questionText: "You're driving in heavy traffic on a wet road. Which lights should you use if there's a lot of surface spray?",
    options: [
    "Main-beam headlights",
    "Sidelights only",
    "Rear fog lights if visibility is more than 100 metres (328 feet)",
    "Dipped headlights",
    ],
    correctIndex: 3,
    explanation: "You must make sure that other road users can see you, but you do not want to dazzle them. Use your dipped headlights during the day if visibility is poor. If visibility falls below 100 metres (328 feet), you may use your rear fog lights, but do not forget to turn them off when the visibility improves.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
  {
    id: "BB1720",
    questionText: "What should you do if you overtake a cyclist when it's very windy?",
    options: [
    "Overtake very slowly",
    "Keep close as you pass",
    "Sound your horn repeatedly",
    "Allow extra room",
    ],
    correctIndex: 3,
    explanation: "Cyclists, and motorcyclists, are very vulnerable in high winds. They can easily be blown well off course and veer into your path. Always allow plenty of room when overtaking them. Passing too close could cause a draught and unbalance the rider.",
    topicCategory: TopicCategory.OtherTypes,
    difficulty: 1,
  },
];
