// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const roadsignsQuestions: Question[] = [
  {
    id: 'SGN_001',
    questionText: 'What shape are UK warning signs, such as "slippery road" or "road narrows"?',
    options: [
      'Circular with a red border',
      'Rectangular with a blue background',
      'Triangular with a red border',
      'Rectangular with a green background',
    ],
    correctIndex: 2,
    explanation:
      'Warning signs in the UK are red-bordered equilateral triangles pointing upwards. They warn of hazards ahead and require you to be prepared to respond.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_002',
    questionText: 'What does an inverted triangle (pointing downwards) with a red border mean at a junction?',
    options: [
      'No entry - do not proceed',
      'Stop and give way to all traffic',
      'Give way to traffic on the major road ahead',
      'Reduce speed to 20mph',
    ],
    correctIndex: 2,
    explanation:
      'An inverted triangle is the "give way" sign. You must give way to traffic on the road you are entering. It is different from the octagonal STOP sign, which requires you to stop completely.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_003',
    questionText: 'What does a circular sign with a white background and a single diagonal black stripe indicate?',
    options: [
      'No entry for all vehicles',
      'The national speed limit applies',
      'No overtaking permitted',
      'End of all speed restrictions',
    ],
    correctIndex: 1,
    explanation:
      'The national speed limit sign is a white circle with a diagonal black stripe. On a single carriageway this means 60mph; on a motorway or dual carriageway it means 70mph.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_004',
    questionText: 'A red circle containing a horizontal white bar in the centre means:',
    options: [
      'Give way to oncoming traffic',
      'No entry for vehicular traffic',
      'Stop - controlled junction ahead',
      'Speed limit 50mph',
    ],
    correctIndex: 1,
    explanation:
      'The "no entry" sign is a red circle with a white horizontal bar. You must not enter the road or lane displaying this sign. It is commonly used on one-way streets and exit roads.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_005',
    questionText: 'What does a blue circular sign displaying a white arrow indicate?',
    options: [
      'A mandatory direction you must follow',
      'A recommended route',
      'A warning that traffic turns ahead',
      'A one-way street in the arrow direction',
    ],
    correctIndex: 0,
    explanation:
      'Blue circular signs give mandatory instructions - you must follow them. A blue circle with a directional arrow means you must travel in that direction. (Compare: blue rectangles are merely informational.)',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_006',
    questionText: 'What is the correct sequence of UK traffic lights when they change from red to green?',
    options: [
      'Red - Green - Amber - Red',
      'Red - Red and Amber - Green - Amber',
      'Red - Amber - Green - Amber',
      'Red - Flashing Amber - Green - Amber',
    ],
    correctIndex: 1,
    explanation:
      'UK traffic lights follow the sequence: Red (stop) - Red and Amber together (prepare to go) - Green (go if safe) - Amber (stop if safe to do so) - back to Red. The red-and-amber phase warns you to prepare to move.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_007',
    questionText: 'What do double yellow lines painted along the edge of the road mean?',
    options: [
      'No stopping at any time',
      'No parking at any time',
      'No waiting during certain hours shown on nearby signs or plates',
      'No parking or loading at any time',
    ],
    correctIndex: 2,
    explanation:
      'Double yellow lines mean no waiting (parking) during the times shown on nearby kerb plates or signs. Single yellow lines apply during specific hours; double yellows extend the restriction. The exact hours must be checked locally.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_008',
    questionText: 'What colour background do motorway direction signs have?',
    options: [
      'Green',
      'White',
      'Blue',
      'Yellow',
    ],
    correctIndex: 2,
    explanation:
      'Motorway direction and information signs have a blue background with white text and yellow route numbers. Primary route signs on A-roads use green backgrounds; local route signs use white backgrounds.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_009',
    questionText: 'At a school crossing, a patrol officer displays a "STOP - CHILDREN" sign. What must you do?',
    options: [
      'Slow to 20mph and proceed with care',
      'Stop and wait until the officer signals it is safe to proceed',
      'Give way to children if any are crossing but otherwise continue',
      'Stop only if children are actually in the road',
    ],
    correctIndex: 1,
    explanation:
      'You must obey a school crossing patrol officer displaying the "STOP - CHILDREN" sign. Stop and wait. You must not proceed until the officer signals it is safe and clears the crossing.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_010',
    questionText: 'What does a "clearway" sign indicate?',
    options: [
      'A road where you must not stop at any time, except in an emergency',
      'A road with no speed limit',
      'A road that has been gritted and is clear of ice',
      'A road where no parking is permitted during the day',
    ],
    correctIndex: 0,
    explanation:
      'A clearway is a route where stopping is prohibited at all times (including by the driver), except in an emergency or breakdown. They are typically found on busy roads where stopping would cause obstruction.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_011',
    questionText: 'Diagonal white lines fill the area between two solid white lines in the centre of a road. What do they mean?',
    options: [
      'Traffic may use this area for overtaking if the road ahead is clear',
      'This area separates traffic streams and must not be entered unless safe and necessary',
      'The road narrows ahead and you must merge into one lane',
      'Lane markings indicating the end of a motorway',
    ],
    correctIndex: 1,
    explanation:
      'Areas of diagonal white lines (chevrons) bordered by solid lines are designed to separate opposing traffic or protect turning vehicles. You must not enter them unless it is safe and, in some cases, unless it is necessary to do so.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_012',
    questionText: 'A speed limit sign shows "30" inside a red circle. What does this mean?',
    options: [
      'The recommended speed on this road is 30mph',
      'The maximum permitted speed is 30mph',
      'A 30mph zone begins ahead',
      'Lorries over 3.5 tonnes must not exceed 30mph',
    ],
    correctIndex: 1,
    explanation:
      'A number inside a red circle is a mandatory maximum speed limit sign. You must not exceed 30mph on that road. This applies to all vehicles unless a lower limit is separately signed for specific vehicle types.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_013',
    questionText: 'What do zigzag lines on the road at a pedestrian crossing indicate?',
    options: [
      'You may park briefly here to collect or set down passengers',
      'No parking or overtaking within this marked area',
      'Road surface is uneven - reduce speed',
      'You must slow to 20mph when pedestrians are present',
    ],
    correctIndex: 1,
    explanation:
      'Zigzag lines mark the area approaching a pedestrian crossing where parking and overtaking are prohibited. Parking here would obstruct the view for both drivers and pedestrians, and is therefore illegal.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_014',
    questionText: 'An amber traffic light is showing. When can you continue through it without stopping?',
    options: [
      'Whenever oncoming traffic has already stopped',
      'Only if stopping would be unsafe because you are too close to the stop line',
      'Always - amber means prepare to stop but you may proceed',
      'When a vehicle is following closely behind you',
    ],
    correctIndex: 1,
    explanation:
      'Amber means stop at the stop line. You may continue only if stopping would be unsafe - for example, if you are already so close to the stop line that stopping would cause a skid or collision. Amber does not mean "hurry through".',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_015',
    questionText: 'What does a continuous solid white line along the centre of the road mean for a driver?',
    options: [
      'You may cross it only if you are overtaking and the road ahead is clear',
      'You must not cross or straddle it unless turning, passing a stationary obstruction, or in an emergency',
      'It is a warning line and crossing it is not legally prohibited',
      'It indicates the edge of the hard shoulder on a dual carriageway',
    ],
    correctIndex: 1,
    explanation:
      'A continuous solid white centre line is a mandatory road marking. You must not cross or straddle it except to turn into a premises, pass a stationary vehicle or road worker, or in an emergency. Hazard warning lines (broken) allow crossing when safe.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_016',
    questionText: 'What does a red route sign (red lines at the kerb) indicate?',
    options: [
      'No stopping at any time in this zone',
      'No parking during the times shown - stopping to drop off passengers may be permitted',
      'A bus priority route where private vehicles are not permitted',
      'A red line route is the same as double yellow lines nationwide',
    ],
    correctIndex: 0,
    explanation: 'Red route signs, primarily used in London, indicate that stopping is prohibited at all times. Double red lines mean no stopping at any time. Single red lines apply during certain hours shown on signs. These are strictly enforced.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_017',
    questionText: 'What do countdown markers (100, 200, 300 metres) on motorways indicate?',
    options: [
      'The distance to the next motorway exit junction',
      'The distance to the start of the next zone of variable speed limits',
      'The distance to a point where you must exit or take a lane decision',
      'Countdown to the next service area',
    ],
    correctIndex: 0,
    explanation: 'Countdown markers at motorway exits show 300, 200, and 100 metres to the start of the deceleration lane. They help drivers prepare to exit in good time without late lane changes. Three bars = 300m, two = 200m, one = 100m.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_018',
    questionText: 'What does a flashing amber light at a level crossing mean?',
    options: [
      'A train is approaching - stop before the stop line or crossing',
      'The crossing is temporarily out of use',
      'A slow-moving vehicle is approaching on the crossing',
      'Cyclists and pedestrians only must stop',
    ],
    correctIndex: 0,
    explanation: 'Flashing red lights at a level crossing (not amber) signal that a train is approaching and you must stop before the stop line. Never drive onto a level crossing when the lights are showing or barriers are closing.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_019',
    questionText: 'What colour background are temporary road signs used at roadworks?',
    options: [
      'Orange',
      'White',
      'Yellow',
      'Red',
    ],
    correctIndex: 2,
    explanation: 'Temporary signs used at roadworks and other short-term situations have a yellow (fluorescent yellow-green) background. This distinguishes them from permanent signs and alerts drivers that the instructions apply only while the temporary situation exists.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_020',
    questionText: 'A traffic light shows a green arrow pointing left alongside a red light. What does this mean?',
    options: [
      'You must not turn left - the red light overrides the arrow',
      'You may turn left even though the main light is red, but must give way to pedestrians and other traffic',
      'Turn left is permitted only for buses',
      'You must wait for the green arrow to flash before turning',
    ],
    correctIndex: 1,
    explanation: 'A green filter arrow allows movement in the indicated direction even when the main light is red. You must give way to pedestrians crossing the road you are entering. Traffic travelling in other directions remains stopped by the red light.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_021',
    questionText: 'What does a triangular warning sign showing a figure carrying bags indicate?',
    options: [
      'A pedestrian crossing ahead',
      'A pedestrian zone where driving is restricted to certain hours',
      'A warning that pedestrians commonly cross the road ahead',
      'A supervised school crossing ahead',
    ],
    correctIndex: 2,
    explanation: 'A triangular sign with a pedestrian figure warns of a pedestrian crossing or a location where pedestrians frequently cross. It alerts drivers to be prepared to slow down or stop for pedestrians.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_022',
    questionText: 'What does a sign with a blue rectangle showing a white bus symbol and "Mon-Sat 7am-7pm" mean?',
    options: [
      'Buses may use this lane at any time',
      'A bus lane operates during the hours shown - other vehicles must not use it during those times',
      'Buses must use this lane during the stated hours',
      'This is a bus stop bay for the stated hours',
    ],
    correctIndex: 1,
    explanation: 'Bus lane signs show the hours during which the lane is restricted to buses (and sometimes other specified vehicles such as cycles or taxis). Outside stated hours, all vehicles may use the lane. Entering a bus lane during restricted hours results in a fine.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_023',
    questionText: 'What does a blue circular sign with a red "X" in the centre mean?',
    options: [
      'No entry for any vehicle',
      'No cycling permitted',
      'Keep clear - do not block this junction',
      'No waiting or stopping at any time',
    ],
    correctIndex: 1,
    explanation: 'A blue circle with a red bicycle and a bar through it means no cycling. A blue circle without restrictions indicates cycling is permitted. A red circle with an "X" does not appear on UK roads - always check the exact symbol displayed.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_024',
    questionText: 'A sign shows a white arrow pointing upward with a smaller red arrow pointing down below it. What does this mean?',
    options: [
      'Priority over oncoming traffic on a narrow road',
      'Give way to oncoming vehicles - they have priority',
      'Both lanes must drive in the upward direction',
      'Road works - one lane is temporarily closed',
    ],
    correctIndex: 0,
    explanation: 'This sign at a narrow section of road indicates that you have priority over oncoming traffic. The larger white arrow is your direction; the smaller red arrow indicates the other direction must give way. However, drive with care.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_025',
    questionText: 'What does a sign showing two arrows pointing inward towards each other mean?',
    options: [
      'Road narrows from both sides',
      'Priority over oncoming vehicles',
      'Lane merges from both sides ahead',
      'Give way to oncoming traffic - they have priority',
    ],
    correctIndex: 3,
    explanation: 'Two inward-pointing arrows on a sign at a road narrowing indicate that oncoming traffic has priority. The smaller arrow in your direction is red; the larger arrow in the oncoming direction is white. You must wait for a gap before proceeding.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_026',
    questionText: 'What does a white rectangular sign with a blue letter "P" and times displayed beneath it indicate?',
    options: [
      'A public car park',
      'Parking is permitted during the stated hours',
      'Parking is prohibited during the stated hours',
      'A park-and-ride facility',
    ],
    correctIndex: 1,
    explanation: 'A blue "P" on a white rectangle with times shown indicates that parking is permitted in that area during the hours stated. Outside those hours, other restrictions (such as yellow lines) may apply. Always check supplementary plates for details.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_027',
    questionText: 'What does a triangular sign showing a car falling off the edge of a road mean?',
    options: [
      'Road narrows ahead',
      'Danger of skidding on the road ahead',
      'Risk of falling - the road has an unguarded edge, cliff, or waterway',
      'Steep gradient ahead',
    ],
    correctIndex: 2,
    explanation: 'A triangular warning sign with a car appearing to fall from the road edge warns of an unguarded drop alongside the road - typically a cliff, embankment, or waterway. Reduce speed and drive with particular care near the road edge.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_028',
    questionText: 'What does a "STOP" sign at a junction require you to do?',
    options: [
      'Slow to 10mph and give way if vehicles are approaching',
      'Come to a complete stop before the stop line even if the road appears clear',
      'Stop only if traffic is visible on the main road',
      'The same as a give way sign - reduce speed and give way',
    ],
    correctIndex: 1,
    explanation: 'A STOP sign (octagonal, red background) requires you to come to a complete stop before the stop line. Unlike give-way signs, you must stop regardless of whether you can see approaching traffic. Failure to stop is an offence.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_029',
    questionText: 'Overhead gantry signs on a smart motorway show a red X above a lane. What does this mean?',
    options: [
      'The lane is undergoing repairs - use with care',
      'The lane is closed - do not drive in it',
      'A variable speed limit applies in this lane',
      'Lane ends ahead - merge into an adjacent lane',
    ],
    correctIndex: 1,
    explanation: 'A red X displayed on an overhead gantry above a lane means that lane is closed. You must not drive in it. Driving in a closed lane is an offence and can be captured by enforcement cameras. Move to an open lane as safely as possible.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_030',
    questionText: 'A triangular sign shows a steam locomotive. What does it warn of?',
    options: [
      'A level crossing with a gate or barrier ahead',
      'A heritage railway museum nearby',
      'A level crossing without a gate or barrier ahead',
      'A railway bridge with limited headroom',
    ],
    correctIndex: 0,
    explanation: 'The steam locomotive triangle warns of a level crossing with a gate or barrier controlled by a signal or barriers. A similar sign without gates indicates an ungated level crossing. Both require extra caution and you must obey all signals.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_031',
    questionText: 'What does a blue rectangular sign with a white "H" followed by a distance mean?',
    options: [
      'A hospital is located at the stated distance',
      'A fire hydrant is located at the stated offset distance from the sign',
      'A helipad landing zone is ahead',
      'A hard shoulder begins at the stated distance',
    ],
    correctIndex: 1,
    explanation: 'The blue H sign indicates a fire hydrant location. The number on the sign gives the distance in metres from the sign to the actual hydrant. This information is primarily for fire service use, not drivers.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_032',
    questionText: 'What does a green rectangular sign with white text and yellow route numbers indicate?',
    options: [
      'A motorway direction sign',
      'A primary route directional sign for A-roads',
      'A tourist attraction sign',
      'A local direction sign for non-primary routes',
    ],
    correctIndex: 1,
    explanation: 'Green background signs with white text are primary route signs for A-roads. Motorway signs are blue with white text and yellow route numbers. Local route signs use white backgrounds. Tourist information signs are brown.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_033',
    questionText: 'What does a single broken white line along the centre of a road indicate?',
    options: [
      'You must not cross the line under any circumstances',
      'You may overtake if it is safe and you can see the road ahead is clear',
      'The road is a one-way street',
      'The lane ends ahead and you must merge',
    ],
    correctIndex: 1,
    explanation: 'A broken white centre line is the standard lane divider on a two-way road. You may cross it to overtake if the road is clear and you can complete the manoeuvre safely. Longer and more frequent lines (hazard warning lines) appear as you approach junctions and warn you to take extra care before crossing.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_034',
    questionText: 'What does a white rectangular sign reading "URBAN CLEARWAY" mean?',
    options: [
      'No stopping at any time except in a designated loading bay',
      'No parking during the hours shown except to set down or pick up passengers',
      'The road has been cleared of parked cars and is free to use',
      'An urban area where the speed limit is 20mph',
    ],
    correctIndex: 1,
    explanation: 'An urban clearway restricts parking during the hours shown (typically peak times) except to set down or pick up passengers briefly. This differs from a motorway clearway where stopping at any time is prohibited.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_035',
    questionText: 'What does a brown rectangular sign with white text indicate?',
    options: [
      'A restricted parking zone',
      'A tourist attraction or place of interest',
      'A brown route used by agricultural vehicles',
      'A quiet lane advisory route',
    ],
    correctIndex: 1,
    explanation: 'Brown background signs with white text direct drivers to tourist attractions, points of interest, and heritage sites. They are distinct from the green primary route signs and the blue motorway signs.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_036',
    questionText: 'A sign shows a white background with the number "20" surrounded by a red circle and the word "ZONE" below. What does this mean?',
    options: [
      'A 20mph advisory speed for the next section of road',
      'A 20mph zone where the limit applies to all roads in the area until you see a new speed limit sign',
      'A 20mph zone for large vehicles only',
      'A temporary 20mph limit during school hours only',
    ],
    correctIndex: 1,
    explanation: 'A 20mph zone sign marks the entry to an area where all roads are restricted to 20mph. The limit applies throughout the zone without repeated signs on every road. Zone ends are marked with derestriction signs.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_037',
    questionText: 'What does a triangular warning sign showing a bumped road profile (two bumps) mean?',
    options: [
      'Uneven road surface ahead',
      'Speed humps ahead',
      'Two hump-back bridges ahead',
      'Road works with temporary road surface',
    ],
    correctIndex: 1,
    explanation: 'A triangular sign showing a road profile with regular bumps warns of speed humps ahead. These are physical speed-reduction features. Approach at low speed - crossing them too fast damages your vehicle and can throw the car out of control.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_038',
    questionText: 'What does a blue rectangular sign showing a white bicycle alongside a white pedestrian figure mean?',
    options: [
      'A shared pedestrian and cycle path - both must share the same space',
      'A path divided into separate lanes for pedestrians and cyclists',
      'A cycle path with a pedestrian crossing at the end',
      'Cyclists and pedestrians must give way to vehicles here',
    ],
    correctIndex: 1,
    explanation: 'A blue rectangle with a bicycle and pedestrian side by side indicates a shared-use path divided into a pedestrian lane and a separate cycle lane. Keep to your designated section. Where the symbols are on a single rectangle, the path is shared with no segregation.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_039',
    questionText: 'What does a sign showing a red triangle containing a figure slipping mean?',
    options: [
      'Road narrows',
      'Slippery road ahead',
      'Pedestrian crossing ahead',
      'Soft verge',
    ],
    correctIndex: 1,
    explanation: 'A triangular warning sign with a car skidding (appearing to slip sideways) warns that the road ahead is likely to be slippery. This may indicate a known slippery surface, loose chippings after resurfacing, or a section prone to ice.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_040',
    questionText: 'What does a yellow kerb mark (short yellow dash painted on the kerb) mean?',
    options: [
      'Loading and unloading restrictions during times shown on a plate',
      'No parking at any time on the adjacent yellow lines',
      'A taxi rank during stated hours',
      'A school keep clear zone at stated times',
    ],
    correctIndex: 0,
    explanation: 'Yellow marks on the kerb (one or two kerb dashes) indicate loading and unloading restrictions during the hours shown on nearby upright plates. They do not restrict parking per se - the yellow lines on the road restrict waiting. Both must be checked.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_041',
    questionText: 'What is a "toucan crossing" and how is it different from a pelican crossing?',
    options: [
      'A toucan is a pedestrian-only crossing; a pelican allows cycles',
      'A toucan allows both pedestrians and cyclists to cross; a pelican is pedestrian only',
      'A toucan has no traffic lights; a pelican does',
      'They are identical - the names are interchangeable',
    ],
    correctIndex: 1,
    explanation: 'A toucan crossing allows both pedestrians and cyclists to cross at the same time using shared push-button controls. "Two can cross" - hence toucan. A pelican crossing is pedestrian only and has a flashing amber phase. Toucans have no flashing amber phase.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_042',
    questionText: 'What does a "puffin crossing" have that a pelican crossing does not?',
    options: [
      'It allows cyclists to cross with pedestrians',
      'It uses pedestrian detection sensors to keep the red light on while pedestrians are still crossing',
      'It has a longer crossing time programmed into the lights',
      'It does not have a push button - it activates automatically',
    ],
    correctIndex: 1,
    explanation: 'A puffin crossing (Pedestrian User-Friendly INtelligent crossing) uses kerbside sensors to detect pedestrians. If a pedestrian is still crossing when the timer would normally end, the red phase extends automatically. Traffic cannot receive green until the crossing is clear.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_043',
    questionText: 'What does a circular blue sign with two white arrows pointing in opposite directions mean?',
    options: [
      'Two-way traffic ahead',
      'Mini roundabout ahead',
      'Ahead only permitted in both lanes',
      'You may overtake on this road',
    ],
    correctIndex: 0,
    explanation: 'A blue circle with two opposing horizontal arrows warns that a section of road becomes two-way traffic after being one-way. Drivers must be prepared to encounter oncoming vehicles ahead.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_044',
    questionText: 'A sign shows a red circle with the outline of a weight "7.5T" inside. What does this mean?',
    options: [
      'The maximum speed for vehicles over 7.5 tonnes is reduced',
      'No vehicles over 7.5 tonnes maximum gross weight permitted',
      'Vehicles over 7.5 tonnes must use the left lane only',
      'A toll applies to vehicles over 7.5 tonnes',
    ],
    correctIndex: 1,
    explanation: 'A maximum weight sign in a red circle prohibits vehicles exceeding that maximum gross weight from proceeding. This is typically shown on weak bridges or roads that cannot support heavier vehicles. HGV drivers must know their vehicle\'s weight.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_045',
    questionText: 'What does a triangular warning sign showing an exclamation mark inside it mean?',
    options: [
      'A generic hazard warning - check for any supplementary plate below explaining the specific hazard',
      'Road works ahead',
      'Give way to all traffic',
      'A high accident risk area where extra care is needed',
    ],
    correctIndex: 0,
    explanation: 'An exclamation mark in a red-bordered triangle is a general hazard warning sign, often accompanied by a supplementary plate explaining the specific hazard (e.g., "mud on road," "animals," "accident"). Always read the supplementary plate.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_046',
    questionText: 'What does a white painted arrow on the road surface in a lane mean?',
    options: [
      'Overtaking is permitted in the arrow direction',
      'The direction of travel required for that lane at the junction ahead',
      'The lane ends and you must move in the arrow direction',
      'Pedestrian crossing ahead in the direction of the arrow',
    ],
    correctIndex: 1,
    explanation: 'Lane arrows painted on the road surface indicate which direction vehicles in that lane must travel at the junction ahead. Choose the correct lane before reaching the junction and follow the arrow for your intended direction.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: 'SGN_047',
    questionText: 'What does a sign showing a "P" with a picture of a bus and arrow to the right mean at a car park entrance?',
    options: [
      'Bus parking only to the right',
      'Park-and-ride facility with bus connection in the direction shown',
      'Passengers must board buses to the right',
      'A permit-only parking zone is ahead',
    ],
    correctIndex: 1,
    explanation: 'A park-and-ride sign directs drivers to a peripheral car park where they can park and catch a bus into town. These schemes reduce congestion in city centres. The direction shown indicates where bus connections depart.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_048',
    questionText: 'A gantry sign on a smart motorway shows "60" in a red circle above a lane. What does this mean?',
    options: [
      'The recommended speed in that lane is 60mph',
      'A mandatory temporary speed limit of 60mph applies in that lane',
      'Traffic ahead is travelling at 60mph - adjust to match',
      'A 60mph advisory applies to all lanes under the gantry',
    ],
    correctIndex: 1,
    explanation: 'A speed limit in a red circle on a motorway overhead gantry is a mandatory temporary speed limit, enforceable by camera. It applies to the lane(s) showing the sign and must be obeyed. Temporary limits are often set to manage traffic flow or respond to incidents.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 2,
  },
  {
    id: 'SGN_049',
    questionText: 'What does the "end of motorway" sign look like?',
    options: [
      'A red circle with a motorway symbol',
      'A white rectangular sign with the letter "M" and a diagonal red bar',
      'A blue rectangle showing "M" and "END"',
      'A blue-and-white sign with "END" and three lanes shown',
    ],
    correctIndex: 1,
    explanation: 'The end of motorway sign is a white rectangle with an "M" symbol and a diagonal red bar through it. It indicates that motorway regulations no longer apply and you are now on an ordinary road. Speed limits, stopping rules, and lane use revert to standard road rules.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
  {
    id: 'SGN_050',
    questionText: 'What does a pegasus crossing provide for?',
    options: [
      'Pedestrians and cyclists to cross together',
      'Pedestrians with disabilities who need longer crossing times',
      'Horse riders to cross safely alongside pedestrians',
      'Motorcycles to filter through pedestrian crossings',
    ],
    correctIndex: 2,
    explanation: 'A pegasus crossing (also called an equestrian crossing) allows horse riders to cross alongside pedestrians. They have push buttons at a higher level for mounted riders. The crossing gives both horses and pedestrians time to cross safely.',
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 3,
  },
];
