import { Question, TopicCategory } from '@clearpass/core';

export const roadsignsQuestions: Question[] = [
  {
    id: "AB2039",
    questionText: "When should you use your vehicle's horn?",
    options: [
    "To alert others to your presence",
    "To allow you right of way",
    "To greet other road users",
    "To signal your annoyance",
    ],
    correctIndex: 0,
    explanation: "You must not use your vehicle's horn between 11:30pm and 7am in a built-up area or when you're stationary, unless a moving vehicle poses a danger. Its function is to alert other road users to your presence.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2293",
    questionText: "How can you identify traffic signs that give orders?",
    options: [
    "They're rectangular with a yellow border",
    "They're triangular with a blue border",
    "They're square with a brown border",
    "They're circular with a red border",
    ],
    correctIndex: 3,
    explanation: "There are 3 basic types of traffic sign: those that warn, those that inform and those that give orders. Generally, triangular signs warn, rectangular signs give information or directions and circular signs give orders. An exception is the eight-sided 'stop' sign.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2294",
    questionText: "What shape are traffic signs giving orders?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4073d.png",
    explanation: "Road signs in the shape of a circle give orders. Those with a red circle are mostly prohibitive. The ‘stop’ sign is octagonal to give it greater prominence. Signs giving orders must always be obeyed.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2295",
    questionText: "Which type of sign tells you what you must not do?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4003.png",
    explanation: "Signs in the shape of a circle give orders. A sign with a red circle means that you’re not allowed to do something. Study Know Your Traffic Signs to make sure that you understand what the different traffic signs mean.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2296",
    questionText: "What does this sign mean?",
    options: [
    "Maximum speed limit with traffic calming",
    "Minimum speed limit with traffic calming",
    "‘20 cars only’ parking zone",
    "Only 20 cars allowed at any one time",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4677.png",
    explanation: "If you’re in a place where there are likely to be pedestrians (for example, outside a school, near a park, in a residential area or in a shopping area), you should be cautious and keep your speed down. \r\nMany local authorities have taken steps to slow traffic down by creating traffic-calming measures such as road humps. They're there for a reason; slow down.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2299",
    questionText: "What does this sign mean?",
    options: [
    "New speed limit 20 mph",
    "No vehicles over 30 tonnes",
    "Minimum speed limit 30 mph",
    "End of 20 mph zone",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4678.png",
    explanation: "Where you see this sign, the 20 mph restriction ends and a 30 mph restriction starts. Check all around for possible hazards and only increase your speed if it’s safe to do so.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2301",
    questionText: "What does this sign mean?",
    options: [
    "No overtaking",
    "No motor vehicles",
    "Clearway (no stopping)",
    "Cars and motorcycles only",
    ],
    correctIndex: 1,
    explanation: "A sign will indicate which types of vehicles are prohibited from certain roads. Make sure that you know which signs apply to the vehicle you're using.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2302",
    questionText: "What does this sign mean?",
    options: [
    "No parking",
    "No road markings",
    "No through road",
    "No entry",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4667.png",
    explanation: "'No entry' signs are used in places such as one-way streets to prevent vehicles driving against the traffic. To ignore one would be dangerous, both for yourself and for other road users, as well as being against the law.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2303",
    questionText: "What does this sign mean?",
    options: [
    "Bend to the right",
    "Road on the right closed",
    "No traffic from the right",
    "No right turn",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4665.png",
    explanation: "The 'no right turn' sign may be used to warn road users that there's a 'no entry' prohibition on a road to the right ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2304",
    questionText: "Which sign means 'no entry'?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4690.png",
    explanation: "Look for and obey traffic signs. Disobeying or not seeing a sign could be dangerous. It may also be an offence for which you could be prosecuted.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2305",
    questionText: "What does this sign mean?",
    options: [
    "Route for trams only",
    "Route for buses only",
    "Parking for buses only",
    "Parking for trams only",
    ],
    correctIndex: 0,
    explanation: "Avoid blocking tram routes. Trams are fixed on their route and cannot manoeuvre around other vehicles or pedestrians. Modern trams travel quickly and are quiet, so you might not hear them approaching.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2306",
    questionText: "Which type of vehicle does this sign apply to?",
    options: [
    "Wide vehicles",
    "Long vehicles",
    "High vehicles",
    "Heavy vehicles",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4673.png",
    explanation: "The triangular shapes above and below the dimensions indicate a height restriction that applies to the road ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2307",
    questionText: "Which sign means no motor vehicles allowed?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4669.png",
    explanation: "This sign is used to allow pedestrians to walk free from traffic. It's often found in shopping areas.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2308",
    questionText: "What does this sign mean?",
    options: [
    "You have priority",
    "No motor vehicles",
    "Two-way traffic",
    "No overtaking",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4674.png",
    explanation: "Road signs that prohibit overtaking are placed in locations where passing the vehicle in front is dangerous. If you see this sign, do not attempt to overtake. The sign is there for a reason; you must obey it.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2311",
    questionText: "What does this sign mean?",
    options: [
    "Waiting restrictions apply",
    "Waiting permitted",
    "National speed limit applies",
    "Clearway (no stopping)",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4690.png",
    explanation: "There'll be a plate or additional sign to tell you when the restrictions apply.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2313",
    questionText: "What does this sign mean?",
    options: [
    "End of restricted speed area",
    "End of restricted parking area",
    "End of clearway",
    "End of cycle route",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4676.png",
    explanation: "Even though you've left the restricted area, make sure that you park where you will not endanger other road users or cause an obstruction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2314",
    questionText: "Which sign means 'no stopping'?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4691.png",
    explanation: "Stopping where this clearway restriction applies is likely to cause congestion. Allow the traffic to flow by obeying the signs.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2316",
    questionText: "What does this sign mean?",
    options: [
    "National speed limit applies",
    "Waiting restrictions apply",
    "No stopping",
    "No entry",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4691.png",
    explanation: "This is the sign for a clearway. Clearways are stretches of road where you’re not allowed to stop unless it’s an emergency. Stopping where these restrictions apply may be dangerous and is likely to cause an obstruction. Restrictions might apply for several miles and this may be indicated on the sign.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2317",
    questionText: "What does this sign mean?",
    options: [
    "Distance to parking place ahead",
    "Distance to public telephone ahead",
    "Distance to public house ahead",
    "Distance to passing place ahead",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4709.png",
    explanation: "If you intend to stop and rest, this sign allows you time to reduce speed and pull over safely.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2318",
    questionText: "What does this sign mean?",
    options: [
    "Vehicles may not park on the verge or footway",
    "Vehicles may park on the left-hand side of the road only",
    "Vehicles may park fully on the verge or footway",
    "Vehicles may park on the right-hand side of the road only",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4695.png",
    explanation: "In order to keep roads free from parked cars, there are some areas where you're allowed to park on the verge. Only do this where you see the sign. Parking on verges or footways anywhere else could lead to a fine.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2319",
    questionText: "What does this traffic sign mean?",
    options: [
    "No overtaking allowed",
    "Give priority to oncoming traffic",
    "Two-way traffic",
    "One-way traffic only",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4666.png",
    explanation: "Priority signs are normally shown where the road is narrow and there’s not enough room for 2 vehicles to pass. Examples are narrow bridges, roadworks and where there's a width restriction. \r\nMake sure you know who has priority; do not force your way through. Show courtesy and consideration to other road users.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2320",
    questionText: "What's the meaning of this traffic sign?",
    options: [
    "End of two-way road",
    "Give priority to vehicles coming towards you",
    "You have priority over vehicles coming towards you",
    "Bus lane ahead",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4699.png",
    explanation: "Do not force your way through. Show courtesy and consideration to other road users. Although you have priority, make sure oncoming traffic is going to give way before you continue.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2324",
    questionText: "What shape is a 'stop' sign?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4629a.png",
    explanation: "To make it easy to recognise, the ‘stop’ sign is the only sign of this shape. You must stop and take effective observation before proceeding.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2325",
    questionText: "In winter, road signs can become covered by snow. What does this sign mean?",
    options: [
    "Crossroads",
    "Give way",
    "Stop",
    "Turn right",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4558.png",
    explanation: "The 'stop' sign is the only road sign that's octagonal. This is so that it can be recognised and obeyed even if it's obscured (for example, by snow).",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2327",
    questionText: "What does this sign mean?",
    options: [
    "Service area 30 miles ahead",
    "Maximum speed 30 mph",
    "Minimum speed 30 mph",
    "Lay-by 30 miles ahead",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4535.png",
    explanation: "This sign is shown where slow-moving vehicles would impede the flow of traffic; for example, in tunnels. However, if you need to slow down or even stop to avoid an incident or potential collision, you should do so.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2331",
    questionText: "What does this sign mean?",
    options: [
    "Give way to oncoming vehicles",
    "Approaching traffic passes you on both sides",
    "Turn off at the next available junction",
    "Pass either side to get to the same destination",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4526.png",
    explanation: "These signs are often seen in one-way streets that have more than one lane. When you see this sign, use the route that's the most convenient and does not require a late change of direction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2332",
    questionText: "What does this sign mean?",
    options: [
    "Route for trams",
    "Give way to trams",
    "Route for buses",
    "Give way to buses",
    ],
    correctIndex: 0,
    explanation: "Take extra care when you encounter trams. Look out for road markings and signs that alert you to them. Modern trams are very quiet and you may not hear them approaching.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2333",
    questionText: "What messages are given by circular traffic signs that have a blue background?",
    options: [
    "They give temporary directions during a diversion",
    "They give directions to car parks",
    "They give motorway information",
    "They give mandatory instructions",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4003.png",
    explanation: "Signs with blue circles generally give mandatory instruction. These are often found in urban areas and include signs for mini-roundabouts and directional arrows.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2335",
    questionText: "Where would you see a contraflow bus lane?",
    options: [
    "On a dual carriageway",
    "On a roundabout",
    "On an urban motorway",
    "On a one-way street",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4708.png",
    explanation: "The traffic permitted to use a contraflow lane travels in the opposite direction to traffic in the other lanes on the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2336",
    questionText: "What does this sign mean?",
    options: [
    "Bus station on the right",
    "Contraflow bus lane",
    "With-flow bus lane",
    "Give way to buses",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4708.png",
    explanation: "There will also be markings on the road surface to indicate the bus lane. You must not use this lane for parking or overtaking.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2338",
    questionText: "What does a sign with a brown background show?",
    options: [
    "Tourist directions",
    "Primary roads",
    "Motorway routes",
    "Minor roads",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4010.png",
    explanation: "Signs with a brown background give directions to places of interest. They're often seen on a motorway, directing you along the easiest route to the attraction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2339",
    questionText: "What does this sign mean?",
    options: [
    "Tourist attraction",
    "Beware of trains",
    "Level crossing",
    "Beware of trams",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4686.png",
    explanation: "These signs indicate places of interest and are designed to guide you by the easiest route. They're particularly useful when you're unfamiliar with the area.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2340",
    questionText: "What's the purpose of triangular shaped signs?",
    options: [
    "To give warnings",
    "To give information",
    "To give orders",
    "To give directions",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4629.png",
    explanation: "Triangular signs warn you of hazards ahead. Make sure you look at each sign that you pass on the road, so that you do not miss any vital instructions or information.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2341",
    questionText: "What does this sign mean?",
    options: [
    "Turn left ahead",
    "T-junction",
    "No through road",
    "Give way",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4632.png",
    explanation: "This type of sign warns you of hazards ahead. Make sure you look at each sign and road marking that you pass, so that you do not miss any vital instructions or information. This sign shows there's a T-junction with priority over vehicles from the right.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2342",
    questionText: "What does this sign mean?",
    options: [
    "Multi-exit roundabout",
    "Risk of ice",
    "6 roads converge",
    "Place of historical interest",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4651.png",
    explanation: "It will take up to 10 times longer to stop when it’s icy. Where there's a risk of icy conditions, you need to be aware of this and take extra care. If you think the road may be icy, do not brake or steer harshly, as your tyres could lose their grip on the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2343",
    questionText: "What does this sign mean?",
    options: [
    "Crossroads",
    "Level crossing with gate",
    "Level crossing without gate",
    "Ahead only",
    ],
    correctIndex: 0,
    explanation: "The priority through the junction is shown by the broader line. You need to be aware of the hazard posed by traffic crossing or pulling out onto a major road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2344",
    questionText: "What does this sign mean?",
    options: [
    "Ring road",
    "Mini-roundabout",
    "No vehicles",
    "Roundabout",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4634.png",
    explanation: "As you approach a roundabout, look well ahead and check all signs. Decide which exit you wish to take and move into the correct position as you approach the roundabout, signalling as required.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2345",
    questionText: "What information would be shown in a triangular road sign?",
    options: [
    "Road narrows",
    "Ahead only",
    "Keep left",
    "Minimum speed",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4629.png",
    explanation: "Warning signs are there to make you aware of potential hazards on the road ahead. Take note of the signs so you're prepared and can take whatever action is necessary.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2346",
    questionText: "What does this sign mean?",
    options: [
    "Cyclists must dismount",
    "Bicycles are not allowed",
    "Cycle route ahead",
    "Cycle in single file",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4683.png",
    explanation: "Where there's a cycle route ahead, a sign will show a bicycle in a red warning triangle. Watch out for children on bicycles and cyclists rejoining the main road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2347",
    questionText: "Which sign means that pedestrians may be walking along the road?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4648.png",
    explanation: "When you pass pedestrians in the road, leave plenty of room. You might have to use the right-hand side of the road, so look well ahead, as well as in your mirrors, before pulling out. Take great care if a bend in the road obscures your view ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2351",
    questionText: "Which sign means there's a double bend ahead?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4637.png",
    explanation: "Triangular signs give you a warning of hazards ahead. They're there to give you time to prepare for the hazard; for example, by adjusting your speed.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2352",
    questionText: "What does this sign mean?",
    options: [
    "Wait at the barriers",
    "Wait at the crossroads",
    "Give way to trams",
    "Give way to farm vehicles",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4088.png",
    explanation: "Obey the 'give way' signs. Trams are unable to steer around you if you misjudge when it's safe to enter the junction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2353",
    questionText: "What does this sign mean?",
    options: [
    "Hump bridge",
    "Humps in the road",
    "Entrance to tunnel",
    "Soft verges",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4602.png",
    explanation: "These humps have been put in place to slow the traffic down. They're usually found in residential areas. Slow down to an appropriate speed.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2357",
    questionText: "Which sign means the end of a dual carriageway?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4639.png",
    explanation: "If you’re overtaking, make sure you move back safely into the left-hand lane before you reach the end of the dual carriageway.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2358",
    questionText: "What does this sign mean?",
    options: [
    "End of dual carriageway",
    "Tall bridge",
    "Road narrows",
    "End of narrow bridge",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4640.png",
    explanation: "Do not wait until the last moment before moving into the left-hand lane. Plan ahead and do not rely on other traffic letting you in.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2360",
    questionText: "What does this sign mean?",
    options: [
    "Side winds",
    "Road noise",
    "Airport",
    "Adverse camber",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4518.png",
    explanation: "A warning sign with a picture of a windsock indicates that there may be strong side winds. This sign is often found on exposed roads.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2361",
    questionText: "What does this traffic sign mean?",
    options: [
    "Slippery road ahead",
    "Tyres liable to punctures ahead",
    "Danger ahead",
    "Service area ahead",
    ],
    correctIndex: 2,
    explanation: "This sign is there to alert you to the likelihood of danger ahead. It may be accompanied by a plate indicating the type of hazard. Be ready to reduce your speed and take avoiding action.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2362",
    questionText: "You're about to overtake. What should you do when you see this sign?",
    options: [
    "Overtake the other driver as quickly as possible",
    "Move to the right to get a better view",
    "Switch your headlights on before overtaking",
    "Hold back until you can see clearly ahead",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4549.png",
    explanation: "You will not be able to see any hazards that might be hidden in the dip. As well as oncoming traffic, the dip may conceal\r\n• cyclists\r\n• horse riders\r\n• parked vehicles\r\n• pedestrians\r\nin the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2363",
    questionText: "What does this sign mean?",
    options: [
    "Level crossing with gate or barrier",
    "Gated road ahead",
    "Level crossing without gate or barrier",
    "Cattle grid ahead",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4679.png",
    explanation: "Some crossings have gates but no attendant or signals. You should stop, look both ways, listen and make sure that no train is approaching. If there's a telephone, contact the signal operator to make sure it's safe to cross.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2364",
    questionText: "What does this sign mean?",
    options: [
    "No trams ahead",
    "Oncoming trams",
    "Trams crossing ahead",
    "Trams only",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4680.png",
    explanation: "This sign tells you to beware of trams. If you do not usually drive in a town where there are trams, remember to look out for them at junctions and look for tram rails, signs and signals.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2365",
    questionText: "What does this sign mean?",
    options: [
    "Adverse camber",
    "Steep hill downwards",
    "Uneven road",
    "Steep hill upwards",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4643.png",
    explanation: "This sign gives you an early warning that the road ahead will slope downhill. Prepare to alter your speed and gear. Looking at the sign from left to right will show you whether the road slopes uphill or downhill.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2367",
    questionText: "What does this sign mean?",
    options: [
    "Uneven road surface",
    "Bridge over the road",
    "Road ahead ends",
    "Water across the road",
    ],
    correctIndex: 3,
    explanation: "This sign is found where a shallow stream crosses the road. Heavy rainfall could increase the flow of water. If the water looks too deep or the stream has spread over a large distance, stop and find another route.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2369",
    questionText: "What does this sign mean?",
    options: [
    "Turn left for parking area",
    "No through road on the left",
    "No entry for traffic turning left",
    "Turn left for ferry terminal",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4701.png",
    explanation: "This sign shows you that you cannot get through to another route by turning left at the junction ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2370",
    questionText: "What does this sign mean?",
    options: [
    "T-junction",
    "No through road",
    "Telephone box ahead",
    "Toilet ahead",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4700.png",
    explanation: "You will not be able to find a through route to another road. Use this road only for access.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2375",
    questionText: "Which is the sign for a ring road?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4685.png",
    explanation: "Ring roads are designed to relieve congestion in towns and city centres.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2378",
    questionText: "What does this sign mean?",
    options: [
    "The right-hand lane ahead is narrow",
    "Right-hand lane for buses only",
    "Right-hand lane for turning right",
    "The right-hand lane is closed",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4057.png",
    explanation: "Yellow-and-black temporary signs may be used to inform you about roadworks or lane restrictions. Look well ahead. If you have to change lanes, do so in good time.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2379",
    questionText: "What does this sign mean?",
    options: [
    "Change to the left-hand lane",
    "Leave at the next exit",
    "Contraflow system",
    "One-way street",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4578.png",
    explanation: "If you use the right-hand lane in a contraflow system, you’ll be travelling with no permanent barrier between you and the oncoming traffic. Observe speed limits and keep a good distance from the vehicle ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2381",
    questionText: "What does this sign mean?",
    options: [
    "Leave motorway at next exit",
    "Lane for heavy and slow vehicles",
    "All lorries use the hard shoulder",
    "Rest area for lorries",
    ],
    correctIndex: 1,
    explanation: "Where there's a long, steep, uphill gradient on a motorway, a crawler lane may be provided. This helps the traffic to flow by diverting the slower heavy vehicles into a dedicated lane on the left.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2384",
    questionText: "What does a red traffic light mean?",
    options: [
    "You should stop unless turning left",
    "Stop, if you're able to brake safely",
    "You must stop and wait behind the stop line",
    "Proceed with care",
    ],
    correctIndex: 2,
    explanation: "Whatever light is showing, you should know which light is going to appear next and be able to take appropriate action. For example, when amber is showing on its own, you’ll know that red will appear next. This should give you sufficient time to anticipate and respond safely.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2385",
    questionText: "At traffic lights, what does it mean when the amber light shows on its own?",
    options: [
    "Prepare to go",
    "Go if the way is clear",
    "Go if no pedestrians are crossing",
    "Stop at the stop line",
    ],
    correctIndex: 3,
    explanation: "When the amber light is showing on its own, the red light will follow next. The amber light means stop, unless you've already crossed the stop line or you're so close to it that stopping may cause a collision.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2388",
    questionText: "You're at a junction controlled by traffic lights. When should you wait at a green light?",
    options: [
    "When pedestrians are waiting to cross",
    "When your exit from the junction is blocked",
    "When you think the lights may be about to change",
    "When you intend to turn right",
    ],
    correctIndex: 1,
    explanation: "As you approach the traffic lights, look into the road you wish to take. Only proceed if your exit road is clear. If the road is blocked, hold back, even if you have to wait for the next green signal.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2389",
    questionText: "You're in the left-hand lane at traffic lights, waiting to turn left. Which signal means you must wait?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4015.png",
    explanation: "At some junctions, there may be separate signals for different lanes. These are called ‘filter’ lights. They’re designed to help traffic flow at major junctions. Make sure that you’re in the correct lane and proceed if the way is clear and the green light shows for your lane.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2390",
    questionText: "What does this sign mean?",
    options: [
    "Traffic lights out of order",
    "Amber signal out of order",
    "Temporary traffic lights ahead",
    "New traffic lights ahead",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/Out_of_order_tlights.png",
    explanation: "You might see this sign where traffic lights are out of order. Proceed with caution, as nobody has priority at the junction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2392",
    questionText: "Who has priority when traffic lights are out of order?",
    options: [
    "Traffic going straight on",
    "Traffic turning right",
    "Nobody",
    "Traffic turning left",
    ],
    correctIndex: 2,
    explanation: "When traffic lights are out of order, you should treat the junction as an unmarked crossroads. Be cautious, as you may need to give way or stop. Look for traffic attempting to cross the junction, unaware that it does not have priority.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2393",
    questionText: "Where would you find these flashing red light signals?",
    options: [
    "Pelican crossings",
    "Motorway exits",
    "Zebra crossings",
    "Level crossings",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4507b.png",
    explanation: "These signals are found at level crossings, swing or lifting bridges, some airfields and emergency access sites. The flashing red lights mean stop whether or not the way seems to be clear.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2394",
    questionText: "What do these zigzag white lines mean?",
    options: [
    "No parking at any time",
    "Parking allowed only for a short time",
    "Slow down to 20 mph",
    "Sounding horns is not allowed",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/DSCF2954.jpg",
    explanation: "The approach to, and exit from, a pedestrian crossing is marked with zigzag lines. You must not park on them or overtake the leading vehicle when approaching the crossing. Parking here would block the view for pedestrians and approaching traffic.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2396",
    questionText: "When may you cross a double solid white line in the middle of the road?",
    options: [
    "To pass traffic that's queuing back at a junction",
    "To pass a car signalling to turn left ahead",
    "To pass a road maintenance vehicle travelling at 10 mph or less",
    "To pass a vehicle that's towing a trailer",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1871.jpg",
    explanation: "You may cross the solid white line to pass a stationary vehicle or to pass a cyclist, horse or road maintenance vehicle if it's travelling at 10 mph or less. You may also cross the solid white line to enter a side road or access a property.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2398",
    questionText: "What does this road marking mean?",
    options: [
    "Do not cross the line",
    "No stopping allowed",
    "You're approaching a hazard",
    "No overtaking allowed",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_4674.jpg",
    explanation: "A single broken line along the centre of the road, with long markings and short gaps, is a hazard warning line. Do not cross it unless you can see that the road is clear well ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2400",
    questionText: "Where would you see this road marking?",
    options: [
    "At traffic lights",
    "On road humps",
    "Near a level crossing",
    "At a box junction",
    ],
    correctIndex: 1,
    explanation: "Because the road has a dark colour, changes in level are not easily seen. White triangles painted on the road surface give you an indication of where there are road humps.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2401",
    questionText: "Which diagram shows a hazard warning line?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    explanation: "You need to know the difference between the normal centre line and a hazard warning line. If there's a hazard ahead, the markings are longer and the gaps shorter. This gives you advance warning of an unspecified hazard.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2402",
    questionText: "Why does this junction have a 'stop' sign and a stop line on the road?",
    options: [
    "Speed on the major road is derestricted",
    "It's a busy junction",
    "Visibility along the major road is restricted",
    "The junction is on a downhill gradient",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1286.jpg",
    explanation: "Where emerging traffic has a very restricted view of the main road, you may find a 'stop' sign and a solid white stop line. You must stop at the line and then check carefully before you emerge.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2403",
    questionText: "What does this line across the road at the entrance to a roundabout mean?",
    options: [
    "Give way to traffic from the right",
    "Traffic from the left has right of way",
    "You have right of way",
    "Stop at the line",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_0874.jpg",
    explanation: "Slow down as you approach the roundabout and check for traffic from the right. If you need to stop and give way, stay behind the broken line until it's safe to emerge onto the roundabout.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2405",
    questionText: "How will a police officer in a patrol vehicle signal for you to stop?",
    options: [
    "Flash the headlights, indicate left and point to the left",
    "Overtake and give a slowing down arm signal",
    "Use the siren, overtake, cut in front and stop",
    "Pull alongside you, use the siren and wave you to stop",
    ],
    correctIndex: 0,
    explanation: "You must obey signals given by the police. If a police officer in a patrol vehicle wants you to pull over, they'll indicate this without causing danger to you or other traffic.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2407",
    questionText: "You're approaching a junction where the traffic lights are not working. What should you do when a police officer gives this signal?",
    options: [
    "Turn left only",
    "Turn right only",
    "Continue ahead only",
    "Stop at the stop line",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW0961.jpg",
    explanation: "When a police officer or traffic warden is directing traffic, you must obey them. They'll use the arm signals shown in The Highway Code. Learn what these signals mean and obey them.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2408",
    questionText: "What does this arm signal mean?",
    options: [
    "The driver is slowing down",
    "The driver intends to turn right",
    "The driver wishes to overtake",
    "The driver intends to turn left",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_055.jpg",
    explanation: "There might be an occasion where another driver uses an arm signal. This may be because the vehicle’s indicators are obscured by other traffic. In order for such signals to be effective, all drivers should know their meaning. Be aware that the ‘left turn’ signal might look similar to the ‘slowing down’ signal.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2418",
    questionText: "What does this motorway sign mean?",
    options: [
    "Change to the lane on your left",
    "Leave the motorway at the next exit",
    "Change to the opposite carriageway",
    "Pull up on the hard shoulder",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4025.png",
    explanation: "On the motorway, signs sometimes show temporary warnings due to traffic or weather conditions. They may be used to indicate\r\n• lane closures\r\n• temporary speed limits\r\n• weather warnings.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2419",
    questionText: "What does this motorway sign mean?",
    options: [
    "Temporary minimum speed 50 mph",
    "No services for 50 miles",
    "Obstruction 50 metres (164 feet) ahead",
    "Temporary maximum speed 50 mph",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4028.png",
    explanation: "Look out for signs above your lane or on the central reservation. These will give you important information or warnings about the road ahead. To allow for the high speed of motorway traffic, these signs may light up some distance from any hazard. Do not ignore the signs just because the road looks clear to you.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2420",
    questionText: "What does this sign mean?",
    options: [
    "Through traffic to use left lane",
    "Right-hand lane T-junction only",
    "Right-hand lane closed ahead",
    "11 tonne weight limit",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4030.png",
    explanation: "You should change lanes as directed by the sign. Here, the right-hand lane is closed but the left-hand and centre lanes are available. Merging in turn is recommended when it's safe and traffic is going slowly; for example, at roadworks or a road traffic incident. When vehicles are travelling at speed, this is not advisable and you should move into the appropriate lane in good time.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2422",
    questionText: "What does '25' mean on this motorway sign?",
    options: [
    "The distance to the nearest town",
    "The route number of the road",
    "The number of the next junction",
    "The speed limit on the slip road",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4011.png",
    explanation: "Before you set out on your journey, use a road map to plan your route. When you see an advance warning of your junction, make sure you get into the correct lane in plenty of time. Last-minute harsh braking and cutting across lanes at speed is extremely hazardous.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2423",
    questionText: "How should the right-hand lane of a three-lane motorway be used?",
    options: [
    "As a high-speed lane",
    "As an overtaking lane",
    "As a right-turn lane",
    "As an acceleration lane",
    ],
    correctIndex: 1,
    explanation: "You should stay in the left-hand lane of a motorway unless you're overtaking another vehicle. The right-hand lane of a motorway is an overtaking lane; it’s not the 'fast lane'. After overtaking, move back to the left when it's safe to do so.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2424",
    questionText: "Where can you find reflective amber studs on a motorway?",
    options: [
    "Separating the slip road from the motorway",
    "On the left-hand edge of the road",
    "On the right-hand edge of the road",
    "Separating the lanes",
    ],
    correctIndex: 2,
    explanation: "At night or in poor visibility, reflective studs on the road help you to judge your position on the carriageway.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2425",
    questionText: "Where would you find green reflective studs on a motorway?",
    options: [
    "Separating driving lanes",
    "Between the hard shoulder and the carriageway",
    "At slip-road entrances and exits",
    "Between the carriageway and the central reservation",
    ],
    correctIndex: 2,
    explanation: "Knowing the colours of the reflective studs on the road will help you judge your position, especially at night, in foggy conditions or when visibility is poor.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2426",
    questionText: "What should you do when you see this sign as you travel along a motorway?",
    options: [
    "Leave the motorway at the next exit",
    "Turn left immediately",
    "Change lane",
    "Move onto the hard shoulder",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4029.png",
    explanation: "You'll see this sign if the motorway is closed ahead. Pull into the left-hand lane as soon as it's safe to do so. Do not wait until the last moment before you move across, because the lane may be busy and you'll have to rely on another driver making room for you.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2428",
    questionText: "What does this sign mean?",
    options: [
    "No motor vehicles",
    "End of motorway",
    "No through road",
    "End of bus lane",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4590.png",
    explanation: "When you leave the motorway, make sure that you check your speedometer. You may be going faster than you realise. Slow down and look for speed limit signs.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2429",
    questionText: "Which sign means that the national speed limit applies?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4668.png",
    explanation: "You should know the speed limit for the road on which you're travelling and for your vehicle. The different speed limits are shown in The Highway Code.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2430",
    questionText: "What's the national speed limit on a single carriageway road?",
    options: [
    "50 mph",
    "60 mph",
    "40 mph",
    "70 mph",
    ],
    correctIndex: 1,
    explanation: "If you’re travelling on a dual carriageway that becomes a single carriageway road, reduce your speed gradually so that you’re not exceeding the limit as you enter. There might not be a sign to remind you of the limit, so make sure you know the speed limits for different types of road and vehicle.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2529",
    questionText: "What does this sign mean?",
    options: [
    "End of motorway",
    "End of restriction",
    "Lane ends ahead",
    "Free recovery ends",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4086.png",
    explanation: "Temporary restrictions on motorways are shown on signs that have flashing amber lights. At the end of the restriction, you'll see this sign without any flashing lights.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2530",
    questionText: "What does this sign indicate?",
    options: [
    "A diversion route",
    "A picnic area",
    "A pedestrian zone",
    "A cycle route",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4572.png",
    explanation: "When a diversion route has been put in place, drivers are advised to follow a symbol, which may be a black triangle, square, circle or diamond shape on a yellow background.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2578",
    questionText: "What does this traffic sign mean?",
    options: [
    "Compulsory maximum speed limit",
    "Advisory maximum speed limit",
    "Compulsory minimum speed limit",
    "Advised separation distance",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/50_mph_roadworks.png",
    explanation: "The sign gives you an early warning of a speed restriction. If you're travelling at a higher speed, slow down in good time. You could come across queuing traffic due to roadworks or a temporary obstruction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2579",
    questionText: "What should you do when you see this sign at a crossroads?",
    options: [
    "Maintain the same speed",
    "Carry on with great care",
    "Find another route",
    "Telephone the police",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/Out_of_order_tlights.png",
    explanation: "When traffic lights are out of order, treat the junction as an unmarked crossroads. Be very careful and be prepared to stop; no-one has priority.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2591",
    questionText: "What does this sign mean?",
    options: [
    "Motorcycles only",
    "No cars",
    "Cars only",
    "No motorcycles",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4671.png",
    explanation: "You must comply with all traffic signs and be especially aware of those signs that apply specifically to the type of vehicle you're using.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2592",
    questionText: "You're on a motorway. A lorry has stopped in the right-hand lane. What should you do when you see this sign on the lorry?",
    options: [
    "Move into the right-hand lane",
    "Stop behind the flashing lights",
    "Pass the lorry on the left",
    "Leave the motorway at the next exit",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4058.png",
    explanation: "Sometimes work is carried out on the motorway without closing the lanes. When this happens, signs are mounted on the back of lorries to warn other road users of the roadworks ahead.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2623",
    questionText: "You're on a motorway. What should you do if there's a red cross showing on the signs above your lane only?",
    options: [
    "Continue in that lane and look for further information",
    "Do not continue in that lane",
    "Pull onto the hard shoulder",
    "Stop and wait for an instruction to proceed",
    ],
    correctIndex: 1,
    explanation: "A red cross above your lane shows that your lane is closed. You should move into another lane as soon as you can do so safely.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2634",
    questionText: "When may you sound your vehicle's horn?",
    options: [
    "To give you right of way",
    "To attract a friend’s attention",
    "To warn others of your presence",
    "To make slower drivers move over",
    ],
    correctIndex: 2,
    explanation: "Never sound your vehicle's horn aggressively. You must not sound it in a built-up area between 11:30pm and 7am, or when you're stationary, unless another road user poses a danger. Do not scare animals by sounding your horn.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2635",
    questionText: "Your vehicle is stationary. When may you use its horn?",
    options: [
    "When another road user poses a danger",
    "When the road is blocked by queuing traffic",
    "When it's used only briefly",
    "When signalling that you've just arrived",
    ],
    correctIndex: 0,
    explanation: "When your vehicle is stationary, only sound the horn if you think there's a risk of danger from another road user. Do not use it just to attract someone's attention. This causes unnecessary noise and could be misleading.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2670",
    questionText: "What does this sign mean?",
    options: [
    "You can park on the days and times shown",
    "No parking on the days and times shown",
    "No parking at all from Monday to Friday",
    "End of the urban clearway restrictions",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4692.png",
    explanation: "Urban clearways are provided to keep traffic flowing at busy times. You may stop only briefly to set down or pick up passengers. Times of operation will vary from place to place, so always check the signs.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2671",
    questionText: "What does this sign mean?",
    options: [
    "Quayside or river bank",
    "Steep hill downwards",
    "Uneven road surface",
    "Road liable to flooding",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4652.png",
    explanation: "You should be careful in these locations, as the road surface is likely to be wet and slippery. There may be a steep drop to the water, and there may not be a barrier along the edge of the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2674",
    questionText: "Which sign means you have priority over oncoming vehicles?",
    options: [
    "Yellow sign showing two lane-closure arrows and a red bar, warning of a lane restriction ahead",
    "Red warning triangle showing an upward and downward arrow, indicating two-way traffic ahead",
    "Blue square sign with a bold white arrow pointing up and a red arrow pointing down, showing priority over oncoming traffic",
    "Red circular sign with a red arrow pointing up and a black arrow pointing down, showing you must give way to oncoming traffic",
    ],
    correctIndex: 2,
    optionImages: [
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4509-TL.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4509-TR.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4509-BL.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4509-BR.png",
    ],
    explanation: "Even though you have priority, be prepared to give way if other drivers do not. This will help to avoid congestion, confrontation or even a collision.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2676",
    questionText: "What do the long white lines along the centre of the road mean?",
    options: [
    "Bus lane",
    "Hazard warning",
    "Give way",
    "Lane marking",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_4674.jpg",
    explanation: "The centre of the road is usually marked by a broken white line, with lines that are shorter than the gaps. When the lines become longer than the gaps, this is a hazard warning line. Look well ahead for these, especially when you're planning to overtake or turn off.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2681",
    questionText: "What's the reason for the hatched area along the centre of this road?",
    options: [
    "It separates traffic flowing in opposite directions",
    "It marks an area to be used by overtaking motorcyclists",
    "It's a temporary marking to warn of the roadworks",
    "It separates the 2 sides of the dual carriageway",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1165.jpg",
    explanation: "Areas of 'hatched markings' such as these separate traffic streams that could be a danger to each other. They're often seen on bends or where the road becomes narrow. If the area is bordered by a solid white line, you must not enter it except in an emergency.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2693",
    questionText: "Other drivers may sometimes flash their headlights at you. What's the official meaning of this signal?",
    options: [
    "There's a radar speed trap ahead",
    "They're giving way to you",
    "They're warning you of their presence",
    "There's a fault with your vehicle",
    ],
    correctIndex: 2,
    explanation: "If other drivers flash their headlights, this is not a signal to show priority. The flashing of headlights has the same meaning as sounding the horn: it’s a warning of their presence.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2738",
    questionText: "What does this signal mean?",
    options: [
    "Cars must stop",
    "Trams must stop",
    "Both trams and cars must stop",
    "Both trams and cars can continue",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4072.png",
    explanation: "The white light shows that trams must stop. The green light shows that other vehicles can go if the way is clear. Trams are being introduced into more cities, so you're likely to come across them and you should learn which signs apply to them.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2756",
    questionText: "Where would you find these road markings?",
    options: [
    "At a railway crossing",
    "At a mini-roundabout",
    "On a motorway",
    "On a pedestrian crossing",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4054.png",
    explanation: "These markings show the direction in which the traffic should go at a mini-roundabout.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2757",
    questionText: "A police car is following you. What should you do if the police officer flashes the headlights and points to the left?",
    options: [
    "Turn left at the next junction",
    "Pull up on the left",
    "Stop immediately",
    "Move over to the left",
    ],
    correctIndex: 1,
    explanation: "You must pull up on the left as soon as it’s safe to do so and switch off your engine.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2758",
    questionText: "You see this amber traffic light ahead. Which light, or lights, will come on next?",
    options: [
    "Red alone",
    "Red and amber together",
    "Green and amber together",
    "Green alone",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW0508n1.jpg",
    explanation: "At junctions controlled by traffic lights, you must stop behind the white line until the lights change to green. A red light, an amber light, and red and amber lights showing together all mean stop.\r\nYou may proceed when the light is green unless your exit road is blocked or pedestrians are crossing in front of you.\r\nIf you’re approaching traffic lights that are visible from a distance and the light has been green for some time, be ready to slow down and stop, because the lights are likely to change.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2760",
    questionText: "What does it mean if you see this signal on the motorway?",
    options: [
    "Leave the motorway at the next exit",
    "All vehicles use the hard shoulder",
    "Sharp bend to the left ahead",
    "Stop: all lanes ahead closed",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4026.png",
    explanation: "You'll see this sign if there has been an incident ahead and the motorway is closed. You must obey the sign. Make sure that you prepare to leave in good time. \r\nDo not cause drivers to take avoiding action by cutting in at the last moment.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2762",
    questionText: "What must you do when you see this sign?",
    options: [
    "Stop only if traffic is approaching",
    "Stop even if the road is clear",
    "Stop only if children are waiting to cross",
    "Stop only if a red light is showing",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4657.png",
    explanation: "'Stop' signs are situated at junctions where visibility is restricted or where there's heavy traffic. They must be obeyed: you must stop. Look carefully before moving off.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2763",
    questionText: "Which shape is used for a 'give way' sign?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4668.png",
    explanation: "Other warning signs are the same shape and colour, but the 'give way' triangle points downwards. When you see this sign, you must give way to traffic on the road that you're about to enter.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2764",
    questionText: "What does this sign mean?",
    options: [
    "Buses turning",
    "Ring road",
    "Mini-roundabout",
    "Keep right",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4663.png",
    explanation: "When you see this sign, look out for any direction signs and judge whether you need to signal your intentions. Do this in good time so that other road users approaching the roundabout know what you're planning to do.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2765",
    questionText: "What does this sign mean?",
    options: [
    "Two-way traffic straight ahead",
    "Two-way traffic crosses a one-way road",
    "Two-way traffic over a bridge",
    "Two-way traffic crosses a two-way road",
    ],
    correctIndex: 1,
    explanation: "Be prepared for traffic approaching from junctions on either side of you. Try to avoid unnecessary changing of lanes just before the junction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2766",
    questionText: "What does this sign mean?",
    options: [
    "Two-way traffic crosses a one-way road",
    "Traffic approaching you has priority",
    "Two-way traffic straight ahead",
    "Motorway contraflow system ahead",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4641.png",
    explanation: "This sign may be at the end of a dual carriageway or a one-way street. It's there to warn you of oncoming traffic.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2767",
    questionText: "What does this sign mean?",
    options: [
    "Hump bridge",
    "Traffic-calming hump",
    "Low bridge",
    "Uneven road",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4644.png",
    explanation: "You'll need to slow down. At hump bridges, your view ahead will be restricted and the road will often be narrow. If the bridge is very steep, sound your horn to warn others of your approach. Going over the bridge too fast is highly dangerous to other road users and could even cause your wheels to leave the road, with a resulting loss of control.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2768",
    questionText: "Which sign informs you that you're coming to a 'no through road'?",
    options: [
    "Red warning triangle with a black T-junction arrow, warning of a side road ahead",
    "Black and white sign showing two lane-closure arrows and a red bar, warning of a lane restriction ahead",
    "Blue square sign with a white 'T' shape and a red bar across the top, showing the road ahead is a dead end with no through route",
    "Black electronic matrix sign showing illuminated lane-closure symbols",
    ],
    correctIndex: 2,
    optionImages: [
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4682-TL.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4682-TR.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4682-BL.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4682-BR.png",
    ],
    explanation: "This sign is found at the entrance to a road that can only be used for access.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2769",
    questionText: "What does this sign mean?",
    options: [
    "Direction to park-and-ride car park",
    "No parking for buses or coaches",
    "Direction to bus and coach park",
    "Parking area for cars and coaches",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4070.png",
    explanation: "To ease the congestion in town centres, some cities and towns provide park-and-ride schemes. These allow you to park in a designated area and ride by bus into the centre. \r\nPark-and-ride schemes are usually cheaper and easier than car parking in the town centre.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2771",
    questionText: "What should you do when you're approaching traffic lights that have red and amber showing together?",
    options: [
    "Pass the lights if the road is clear",
    "Take care because there's a fault with the lights",
    "Wait for the green light",
    "Stop because the lights are changing to red",
    ],
    correctIndex: 2,
    explanation: "Be aware that other traffic might still be clearing the junction as you approach. A green light means you may go on, but only if the way is clear.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2778",
    questionText: "You've stopped at a railway level crossing. What should you do if the red lights continue to flash after a train has gone by?",
    options: [
    "Phone the signal operator",
    "Alert drivers behind you",
    "Wait",
    "Proceed with caution",
    ],
    correctIndex: 2,
    explanation: "You must always obey red flashing stop lights. If a train passes but the lights continue to flash, another train will be passing soon. Cross only when the lights go off and the barriers open.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2841",
    questionText: "You're in a tunnel and you see this sign. What does it mean?",
    options: [
    "Direction to an emergency pedestrian exit",
    "Beware of pedestrians: no footpath ahead",
    "No access for pedestrians",
    "Beware of pedestrians crossing ahead",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4687.png",
    explanation: "If you have to leave your vehicle and get out of a tunnel by an emergency exit, do so as quickly as you can. Follow the signs directing you to the nearest exit point. If there are several people using the exit, do not panic but try to leave in a calm and orderly manner.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2885",
    questionText: "Which sign shows that you're entering a one-way system?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4693.png",
    explanation: "If the road has 2 lanes, you can use either lane and overtake on either side. Use the lane that’s more convenient for your destination unless signs or road markings indicate otherwise.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2886",
    questionText: "What does this sign mean?",
    options: [
    "With-flow bus and cycle lane",
    "Contraflow bus and cycle lane",
    "No buses and bicycles allowed",
    "No waiting for buses and bicycles",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4757.png",
    explanation: "Buses and bicycles can travel in this lane. In this example, they'll flow in the same direction as other traffic. If it's busy, they may be passing you on the left, so watch out for them. Times on the sign will show the lane's hours of operation; if no times are shown, or there's no sign at all, this means the lane is in operation 24 hours a day. In some areas, other vehicles, such as taxis and motorcycles, are allowed to use bus lanes. The sign will show if this is the case.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2887",
    questionText: "Which of these signs warns you of a zebra crossing?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4647.png",
    explanation: "Look well ahead and check the pavements and surrounding areas for pedestrians. Look for anyone walking towards the crossing. Check your mirrors for traffic behind, in case you have to slow down or stop.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2889",
    questionText: "What does this sign mean?",
    options: [
    "School crossing patrol",
    "No pedestrians allowed",
    "Pedestrian zone - no vehicles",
    "Zebra crossing ahead",
    ],
    correctIndex: 3,
    explanation: "Look well ahead and be ready to stop for any pedestrians crossing, or about to cross, the road. Also check the pavements for anyone who looks like they might step or run into the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2890",
    questionText: "Which sign means there will be two-way traffic crossing your route ahead?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4642.png",
    explanation: "This sign is found in or at the end of a one-way system. It warns you that traffic will be crossing your path from both directions.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2892",
    questionText: "Which arm signal tells you that the car you're following is going to pull up?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_055b.jpg",
    explanation: "There may be occasions when drivers need to give an arm signal to confirm their intentions. This could include in bright sunshine, at a complex road layout, when stopping at a pedestrian crossing or when turning right just after passing a parked vehicle. You should understand what each arm signal means. If you give arm signals, make them clear, correct and decisive.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2897",
    questionText: "Which sign means turn left ahead?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4524.png",
    explanation: "Blue circles tell you what you must do and this sign gives a clear instruction to turn left ahead. You should be looking out for signs at all times and know what they mean.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2899",
    questionText: "What should you be aware of if you've just passed this sign?",
    options: [
    "This is a single-track road",
    "You cannot stop on this road",
    "Only one lane is in use",
    "All traffic is going one way",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4693.png",
    explanation: "In a one-way system, traffic may pass you on either side. Always be aware of all traffic signs and understand their meaning. Look well ahead and react to them in good time.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2909",
    questionText: "You're approaching traffic lights and the red light is showing. What signal will show next?",
    options: [
    "Red and amber",
    "Green alone",
    "Amber alone",
    "Green and amber",
    ],
    correctIndex: 0,
    explanation: "If you know which light is going to show next, you can plan your approach accordingly. This can help prevent excessive braking or hesitation at the junction.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "AB2912",
    questionText: "What does this sign mean?",
    options: [
    "Low bridge ahead",
    "Tunnel ahead",
    "Ancient monument ahead",
    "Traffic danger spot ahead",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4548.png",
    explanation: "When approaching a tunnel, switch on your dipped headlights. Be aware that your eyes might need to adjust to the sudden darkness. You may need to reduce your speed.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1235",
    questionText: "What does the white line along the side of the road indicate?",
    options: [
    "The edge of the carriageway",
    "The approach to a hazard",
    "No parking",
    "No overtaking",
    ],
    correctIndex: 0,
    explanation: "A continuous white line is used on many roads to indicate the edge of the carriageway. This can be useful when visibility is restricted. The line is discontinued at junctions, lay-bys, and entrances to or exits from private drives.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1236",
    questionText: "What does this white arrow on the road mean?",
    options: [
    "Entrance on the left",
    "All vehicles turn left",
    "Return to your side of the road",
    "Road bends to the left",
    ],
    correctIndex: 2,
    explanation: "The arrow indicates the direction in which to pass hatch markings or double white lines. If you're overtaking, you must return to the left-hand side of the road.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1237",
    questionText: "How should you give an arm signal to turn left?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 2,
    explanation: "There may be occasions when other road users are unable to see your indicator, such as in bright sunlight or at a busy, complicated junction. In these cases, an arm signal will help others to understand your intentions.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1239",
    questionText: "You're waiting at a T-junction. What should you do if a vehicle is coming from the right, with its left indicator flashing?",
    options: [
    "Move out and accelerate hard",
    "Wait until the vehicle starts to turn in",
    "Pull out before the vehicle reaches the junction",
    "Move out slowly",
    ],
    correctIndex: 1,
    explanation: "Other road users may give misleading signals. When you’re waiting at a junction, do not emerge until you’re sure of their intentions.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1240",
    questionText: "When may you use hazard warning lights while you're driving?",
    options: [
    "Instead of sounding the horn in a built-up area between 11:30pm and 7am",
    "On a motorway or unrestricted dual carriageway, to warn of a hazard ahead",
    "On rural routes, after a sign warning of animals",
    "On the approach to toucan crossings, where cyclists are waiting to cross",
    ],
    correctIndex: 1,
    explanation: "When there’s queuing traffic ahead and you have to slow down or even stop, briefly showing your hazard warning lights will help alert the traffic behind to the hazard.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1582",
    questionText: "Why should you make sure that your indicators are cancelled after turning at a junction?",
    options: [
    "To avoid flattening the battery",
    "To avoid misleading other road users",
    "To avoid dazzling other road users",
    "To avoid damage to the indicator relay",
    ],
    correctIndex: 1,
    explanation: "Leaving your indicators on could confuse other road users and may even lead to a crash. Be aware that if you’ve not turned sharply, your indicators may not self-cancel and you'll need to turn them off manually.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
  {
    id: "BB1583",
    questionText: "You're driving in busy traffic. You want to pull up just after a junction on the left. When should you signal?",
    options: [
    "As you're passing or just after the junction",
    "Just before you reach the junction",
    "Well before you reach the junction",
    "It would be better not to signal at all",
    ],
    correctIndex: 0,
    explanation: "You need to signal to let other drivers know your intentions. However, if you indicate too early, they may think you're turning left into the junction. Correct timing of the signal is very important to avoid misleading others.",
    topicCategory: TopicCategory.RoadAndTrafficSigns,
    difficulty: 1,
  },
];
