import { Question, TopicCategory } from '@clearpass/core';

export const rulesOfTheRoadQuestions: Question[] = [
  {
    id: "AB2246",
    questionText: "What's the meaning of this sign?",
    options: [
    "Local speed limit applies",
    "No waiting on the carriageway",
    "National speed limit applies",
    "No entry for vehicles",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4675.png",
    explanation: "This sign does not tell you the speed limit in figures. You should know the speed limit for the type of road that you're on and the type of vehicle that you're driving or riding. Study your copy of The Highway Code.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2248",
    questionText: "What's the national speed limit for cars and motorcycles on a dual carriageway?",
    options: [
    "30 mph",
    "50 mph",
    "60 mph",
    "70 mph",
    ],
    correctIndex: 3,
    explanation: "Make sure that you know the speed limit for the road that you're on. The speed limit on a dual carriageway or motorway is 70 mph for cars and motorcycles, unless signs indicate otherwise. The speed limits for different types of vehicle are listed in The Highway Code.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2249",
    questionText: "There are no speed limit signs on the road. In England, Scotland and Northern Ireland how is a 30 mph limit generally indicated?",
    options: [
    "By hazard warning lines",
    "By street lighting",
    "By pedestrian islands",
    "By double or single yellow lines",
    ],
    correctIndex: 1,
    explanation: "In England, Scotland and Northern Ireland, there's a 30 mph speed limit where there are street lights, unless signs show another limit. \r\nIn Wales, street lights indicate the limit is 20 mph, unless signs show otherwise.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2250",
    questionText: "In England, Scotland and Northern Ireland what will the speed limit usually be where you can see street lights but no speed limit signs?",
    options: [
    "30 mph",
    "40 mph",
    "50 mph",
    "60 mph",
    ],
    correctIndex: 0,
    explanation: "In England, Scotland and Northern Ireland, the presence of street lights generally indicates that there's a 30 mph speed limit, unless signs tell you otherwise.\r\nIn Wales, street lights indicate a 20 mph limit, unless signs show otherwise.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2254",
    questionText: "What does this sign mean?",
    options: [
    "Minimum speed 30 mph",
    "End of maximum speed",
    "End of minimum speed",
    "Maximum speed 30 mph",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4698.png",
    explanation: "The red slash through the sign indicates that the restriction has ended. In this case, the restriction was a minimum speed limit of 30 mph.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2255",
    questionText: "What should you do if you want to overtake a tractor but are not sure that it's safe?",
    options: [
    "Follow another vehicle as it overtakes the tractor",
    "Sound your horn to make the tractor driver pull over",
    "Speed past, flashing your lights at oncoming traffic",
    "Stay behind it if you're in any doubt",
    ],
    correctIndex: 3,
    explanation: "Following a tractor can be frustrating, but never overtake if you’re unsure whether it’s safe. Ask yourself: 'Can I see far enough down the road to be sure that I can complete the manoeuvre safely?' It's better to be delayed for a minute or 2 than to take a chance that may cause a collision.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2256",
    questionText: "Which vehicle is most likely to take an unusual course at a roundabout?",
    options: [
    "Estate car",
    "Taxi",
    "Delivery van",
    "Long vehicle",
    ],
    correctIndex: 3,
    explanation: "Long vehicles might have to take a slightly different position when approaching the roundabout or going around it. This is to stop the rear of the vehicle cutting in and mounting the kerb.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2262",
    questionText: "When may you stop on a clearway?",
    options: [
    "Never",
    "When it's busy",
    "In the rush hour",
    "During daylight hours",
    ],
    correctIndex: 0,
    explanation: "Clearways are in place so that traffic can flow without the obstruction of parked vehicles. Just one parked vehicle can cause an obstruction for all other traffic. You must not stop where a clearway is in force, not even to pick up or set down passengers.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2264",
    questionText: "What's the meaning of this sign?",
    options: [
    "No entry",
    "Waiting restrictions",
    "National speed limit",
    "School crossing patrol",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4690.png",
    explanation: "This sign indicates that there are waiting restrictions. It's normally accompanied by details of when the restrictions are in force.\r\nDetails of most signs in common use are shown in The Highway Code. For more comprehensive coverage, see Know Your Traffic Signs.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2268",
    questionText: "You're looking for somewhere to park at night. When may you park on the right-hand side of the road?",
    options: [
    "When you're in a one-way street",
    "When you have your sidelights on",
    "When you're more than 10 metres (32 feet) from a junction",
    "When you're under a lamppost",
    ],
    correctIndex: 0,
    explanation: "Red rear reflectors show up when headlights shine on them. These are useful when you're parked at night, but they'll only reflect if you park in the same direction as the traffic flow. Normally you should park on the left, but in a one-way street you may also park on the right-hand side of the road.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2269",
    questionText: "When should you use the right-hand lane of a three-lane dual carriageway?",
    options: [
    "When you're overtaking only",
    "When you're overtaking or turning right",
    "When you're using cruise control",
    "When you're turning right only",
    ],
    correctIndex: 1,
    explanation: "You should normally use the left-hand lane on any dual carriageway unless you're overtaking or turning right. \r\nWhen overtaking on a dual carriageway, look for vehicles ahead that are turning right. They may be slowing or stopped. You need to see them in good time so that you can take appropriate action.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2272",
    questionText: "You're approaching a busy junction. What should you do when, at the last moment, you realise you're in the wrong lane?",
    options: [
    "Continue in that lane",
    "Force your way into the lane you need",
    "Stop until the area has cleared",
    "Use arm signals to help you change lane",
    ],
    correctIndex: 0,
    explanation: "There are times when road markings are obscured by queuing traffic, or you're unsure which lane to use. If, at the last moment, you find you're in the wrong lane, do not cut across or bully other drivers to let you in. Follow the lane you’re in and find somewhere safe to turn around and rejoin your route.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2273",
    questionText: "Where may you overtake on a one-way street?",
    options: [
    "Only on the left-hand side",
    "Overtaking is not allowed",
    "Only on the right-hand side",
    "On either the right or the left",
    ],
    correctIndex: 3,
    explanation: "You can overtake other traffic on either side when travelling in a one-way street. Make full use of your mirrors and make sure it's clear all around before you attempt to overtake. Look for signs and road markings, and use the most suitable lane for your destination.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2275",
    questionText: "What signal should you give when you're going straight ahead at a roundabout?",
    options: [
    "Signal left before leaving the roundabout",
    "Do not signal at any time",
    "Signal right when you're approaching the roundabout",
    "Signal left when you're approaching the roundabout",
    ],
    correctIndex: 0,
    explanation: "When going straight ahead at a roundabout, do not signal as you approach it. Signal left just after passing the exit before the one you wish to take.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2276",
    questionText: "Which vehicle might have to take a different course from normal at a roundabout?",
    options: [
    "Sports car",
    "Van",
    "Estate car",
    "Long vehicle",
    ],
    correctIndex: 3,
    explanation: "A long vehicle may have to straddle lanes either on or approaching a roundabout so that the rear wheels do not mount the kerb. \r\nIf you’re following a long vehicle, stay well back and give it plenty of room.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2281",
    questionText: "When may you enter a box junction?",
    options: [
    "When there are fewer than 2 vehicles ahead",
    "When signalled by another road user",
    "When your exit road is clear",
    "When traffic signs direct you",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW1216.jpg",
    explanation: "Yellow box junctions are marked on the road to prevent the road becoming blocked. Do not enter the box unless your exit road is clear. You may wait in the box if you want to turn right and your exit road is clear but oncoming traffic or other vehicles waiting to turn right are preventing you from making the turn.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2282",
    questionText: "When may you stop and wait in a box junction?",
    options: [
    "When oncoming traffic prevents you from turning right",
    "When you're in a queue of traffic turning left",
    "When you're in a queue of traffic going ahead",
    "When you're on a roundabout",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW1216.jpg",
    explanation: "The purpose of yellow box markings is to keep junctions clear of queuing traffic. You may only wait in the marked area when you’re turning right and your exit lane is clear but you cannot complete the turn because of oncoming traffic or other traffic waiting to turn right.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2284",
    questionText: "Who is authorised to signal you to stop?",
    options: [
    "A motorcyclist",
    "A pedestrian",
    "A police officer",
    "A bus driver",
    ],
    correctIndex: 2,
    explanation: "You must obey signals to stop given by police and traffic officers, traffic wardens and school crossing patrols. Failure to do so is an offence and could lead to prosecution.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2288",
    questionText: "What should you do if you see a pedestrian waiting at a zebra crossing?",
    options: [
    "Go on quickly before they step onto the crossing",
    "Stop before you reach the zigzag lines and let them cross",
    "Be ready to slow down or stop to let them cross",
    "Ignore them as they're still on the pavement",
    ],
    correctIndex: 2,
    explanation: "By standing on the pavement, the pedestrian is showing an intention to cross. By looking well ahead, you'll give yourself time to see the pedestrian, check your mirrors and respond safely.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2290",
    questionText: "Which road users benefit from toucan crossings?",
    options: [
    "Car drivers and motorcyclists",
    "Cyclists and pedestrians",
    "Bus and lorry drivers",
    "Tram and train drivers",
    ],
    correctIndex: 1,
    explanation: "Toucan crossings are similar to pelican crossings but there's no flashing amber phase. Cyclists share the crossing with pedestrians and are allowed to cycle across when the green bicycle symbol is shown.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2292",
    questionText: "You’re waiting at a pelican crossing. What does it mean when the red light changes to flashing amber?",
    options: [
    "Give way to pedestrians on the crossing",
    "Move off immediately without any hesitation",
    "Wait for the green light before moving off",
    "Get ready and go when the continuous amber light shows",
    ],
    correctIndex: 0,
    explanation: "This light allows pedestrians already on the crossing to get to the other side in their own time, without being rushed. Do not rev your engine or start to move off while they’re still crossing.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2528",
    questionText: "You see these double white lines along the centre of the road. When may you park on the left?",
    options: [
    "If the line nearest to you is broken",
    "When there are no yellow lines",
    "To pick up or set down passengers",
    "During daylight hours only",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/IMG_1873.jpg",
    explanation: "You must not park or stop on a road marked with double white lines (even where one of the lines is broken) except to pick up or set down passengers.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2577",
    questionText: "You're turning right at a crossroads. An oncoming driver is also turning right. What's the advantage of turning behind the oncoming vehicle?",
    options: [
    "You'll have a clearer view of any approaching traffic",
    "You'll use less fuel because you can stay in a higher gear",
    "You'll have more time to turn",
    "You'll be able to turn without stopping",
    ],
    correctIndex: 0,
    explanation: "When turning right at a crossroads where oncoming traffic is also turning right, it's generally safer to turn behind the approaching vehicle. This allows you a clear view of approaching traffic and is called 'turning offside to offside'. However, some junctions, usually controlled by traffic-light filters - are marked for vehicles to turn nearside to nearside.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2614",
    questionText: "You're travelling along a residential street. There are parked vehicles on the left-hand side. Why should you keep your speed down?",
    options: [
    "So that oncoming traffic can see you more clearly",
    "You may set off car alarms",
    "There may be delivery lorries on the street",
    "Children may run out from between the vehicles",
    ],
    correctIndex: 3,
    explanation: "Travel slowly and carefully near parked vehicles. Beware of\r\n• vehicles pulling out, especially bicycles and motorcycles\r\n• pedestrians, especially children, who may run out from between cars\r\n• drivers opening their doors.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2615",
    questionText: "What should you do when there's an obstruction on your side of the road?",
    options: [
    "Carry on, as you have priority",
    "Give way to oncoming traffic",
    "Wave oncoming vehicles through",
    "Accelerate to get past first",
    ],
    correctIndex: 1,
    explanation: "Take care if you have to pass an obstruction, such as a parked vehicle, on your side of the road. Give way to oncoming traffic if there’s not enough room for you both to continue safely.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2616",
    questionText: "When would you use the right-hand lane of a two-lane dual carriageway?",
    options: [
    "When you're turning right or overtaking",
    "When you're passing a side road on the left",
    "When you're staying at the minimum allowed speed",
    "When you're travelling at a constant high speed",
    ],
    correctIndex: 0,
    explanation: "Normally you should travel in the left-hand lane and only use the right-hand lane for overtaking or turning right. Move back into the left lane as soon as it’s safe but do not cut in across the path of the vehicle you’ve just passed.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2617",
    questionText: "Who has priority at an unmarked crossroads?",
    options: [
    "The larger vehicle",
    "No-one has priority",
    "The faster vehicle",
    "The smaller vehicle",
    ],
    correctIndex: 1,
    explanation: "Practise good observation in all directions before you emerge or make a turn. Proceed only when you're sure it's safe to do so.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2629",
    questionText: "You're looking for somewhere to safely park your vehicle. Where would you choose to park?",
    options: [
    "At or near a bus stop",
    "In a designated parking space",
    "Near the brow of a hill",
    "On the approach to a level crossing",
    ],
    correctIndex: 1,
    explanation: "It may be tempting to park where you should not while you run a quick errand. Careless parking is a selfish act and could endanger other road users.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2630",
    questionText: "You're waiting at a level crossing. What must you do if a train passes but the lights keep flashing?",
    options: [
    "Carry on waiting",
    "Phone the signal operator",
    "Edge over the stop line and look for trains",
    "Park and investigate",
    ],
    correctIndex: 0,
    explanation: "If the lights at a level crossing keep flashing after a train has passed, you should continue to wait, because another train might be coming. Time seems to pass slowly when you’re held up in a queue. Be patient and wait until the lights stop flashing.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2669",
    questionText: "What does this sign mean?",
    options: [
    "No through road",
    "End of traffic-calming zone",
    "Free-parking zone ends",
    "End of controlled parking zone",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/664.png",
    explanation: "This sign shows that you're leaving a controlled parking zone and those restrictions no longer apply.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2698",
    questionText: "What must you do if you come across roadworks that have a temporary speed limit displayed?",
    options: [
    "Obey the speed limit",
    "Obey the limit, but only during rush hour",
    "Ignore the displayed limit",
    "Use your own judgement; the limit is only advisory",
    ],
    correctIndex: 0,
    explanation: "Where there are extra hazards, such as at roadworks, it’s often necessary to slow traffic by imposing a lower speed limit. These speed limits are not advisory; they must be obeyed.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2754",
    questionText: "You're in a built-up area at night and the road is well lit. Why should you use dipped headlights?",
    options: [
    "So that you can see further along the road",
    "So that you can go at a much faster speed",
    "So that you can switch to main beam quickly",
    "So that you can be easily seen by others",
    ],
    correctIndex: 3,
    explanation: "You may be difficult to see when you’re travelling at night, even on a well-lit road. If you use dipped headlights rather than sidelights, other road users should be able to see you more easily.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2755",
    questionText: "You're turning right onto a dual carriageway. What should you do if the central reservation is too narrow to contain your vehicle?",
    options: [
    "Proceed to the central reservation and wait",
    "Wait until the road is clear in both directions",
    "Stop in the first lane so that other vehicles give way",
    "Emerge slightly to show your intentions",
    ],
    correctIndex: 1,
    explanation: "When the central reservation is narrow, it may not be able to contain your vehicle. In this case, you should treat a dual carriageway as one road. Wait until the road is clear in both directions before emerging to turn right. If you try to treat it as 2 separate roads and wait in the middle, your vehicle will stick out and cause an obstruction that may lead to a collision.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2824",
    questionText: "What's the national speed limit on a single carriageway road for cars and motorcycles?",
    options: [
    "30 mph",
    "50 mph",
    "60 mph",
    "70 mph",
    ],
    correctIndex: 2,
    explanation: "Exceeding the speed limit is dangerous and can result in you receiving penalty points on your licence. It’s not worth it. You should know the speed limit for the road that you're on by observing the road signs. Different speed limits apply if you're towing a trailer.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2825",
    questionText: "What should you do when you park at night on a road that has a 40 mph speed limit?",
    options: [
    "Park facing the traffic",
    "Leave parking lights switched on",
    "Leave dipped headlights switched on",
    "Park near a street light",
    ],
    correctIndex: 1,
    explanation: "You must use parking lights when parking at night on a road or in a lay-by on a road with a speed limit greater than 30 mph. You must also park in the direction of the traffic flow and not close to a junction.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2826",
    questionText: "Where will you see these red and white markers?",
    options: [
    "Approaching the end of a motorway",
    "Approaching a concealed level crossing",
    "Approaching a concealed speed limit sign",
    "Approaching the end of a dual carriageway",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4059.png",
    explanation: "If there's a bend just before a level crossing, you may not be able to see the level-crossing barriers or waiting traffic. These signs give you an early warning that you may find these hazards just around the bend.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2832",
    questionText: "You're travelling on a motorway in England. When must you stop your vehicle?",
    options: [
    "When signalled to stop by a roadworks supervisor",
    "When signalled to stop by a traffic officer",
    "When signalled to stop by a pedestrian on the hard shoulder",
    "When signalled to stop by a driver who has broken down",
    ],
    correctIndex: 1,
    explanation: "You'll find traffic officers on motorways and some primary routes in England and Wales. They work in partnership with the police, helping to keep traffic moving and helping to make your journey as safe as possible. It's an offence not to comply with the directions given by a traffic officer.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2884",
    questionText: "How should you signal if you're going straight ahead at a roundabout?",
    options: [
    "Signal right on the approach and then left to leave the roundabout",
    "Signal left after you leave the roundabout and enter the new road",
    "Signal right on the approach to the roundabout and keep the signal on",
    "Signal left just after you pass the exit before the one you're going to take",
    ],
    correctIndex: 3,
    explanation: "To go straight ahead at a roundabout, you should normally approach in the left-hand lane, but check the road markings. At some roundabouts, the left lane on approach is marked ‘left turn only’, so make sure you use the correct lane to go ahead. You will not normally need to signal as you approach, but signal before you leave the roundabout, as other road users need to know your intentions.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1206",
    questionText: "When may you drive over a pavement?",
    options: [
    "To overtake slow-moving traffic",
    "When the pavement is very wide",
    "If there are no pedestrians nearby",
    "To gain access to a property",
    ],
    correctIndex: 3,
    explanation: "It's illegal to drive on or over a pavement, except to gain access to a property. If you need to cross a pavement, give priority to pedestrians.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1207",
    questionText: "A single carriageway road has this sign. What's the maximum permitted speed for a car towing a trailer?",
    options: [
    "30 mph",
    "40 mph",
    "50 mph",
    "60 mph",
    ],
    correctIndex: 2,
    explanation: "When you're towing a trailer, a reduced speed limit also applies on dual carriageways and motorways. These lower speed limits apply to vehicles pulling all sorts of trailers, including caravans and horse boxes.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1209",
    questionText: "What's the speed limit for a car towing a caravan on a dual carriageway?",
    options: [
    "50 mph",
    "40 mph",
    "70 mph",
    "60 mph",
    ],
    correctIndex: 3,
    explanation: "The speed limit for cars towing caravans or trailers on dual carriageways or motorways is 60 mph. Due to the increased weight and size of the combination, you should plan further ahead. Take care in windy weather, as a strong side wind can make a caravan or large trailer unstable.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1213",
    questionText: "You want to park and you see this sign. What should you do on the days and times shown?",
    options: [
    "Park in a bay and not pay",
    "Park on yellow lines and pay",
    "Park on yellow lines and not pay",
    "Park in a bay and pay",
    ],
    correctIndex: 3,
    explanation: "Parking restrictions apply in a variety of places and situations. Make sure you know the rules and understand where and when restrictions apply. Controlled parking areas will be indicated by signs and road markings. Parking in the wrong place could cause an obstruction and danger to other traffic. It can also result in a fine.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1220",
    questionText: "A cycle lane, marked by a solid white line, is in operation. What does this mean for car drivers?",
    options: [
    "They may park in the lane",
    "They may drive in the lane at any time",
    "They may use the lane when necessary",
    "They must not drive in the lane",
    ],
    correctIndex: 3,
    explanation: "While it's in operation, other vehicles must not use this part of the carriageway. At other times, when the lane is not in operation, you should still be aware that there may be cyclists using the lane. Give them plenty of room as you pass and allow for their movement from side to side, especially in windy weather or on a bumpy road.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1225",
    questionText: "You're going to turn left from a main road into a minor road. What should you do as you approach the junction?",
    options: [
    "Keep just left of the middle of the road",
    "Keep in the middle of the road",
    "Swing out to the right just before turning",
    "Keep well to the left of the road",
    ],
    correctIndex: 3,
    explanation: "Your road position can help other road users to anticipate your actions. Keep to the left as you approach a left turn and do not swing out into the centre of the road in order to make the turn easier. This could endanger oncoming traffic and may cause other road users to misunderstand your intentions.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1226",
    questionText: "You're waiting at a level crossing. What should you do if the red warning lights continue to flash after a train has passed by?",
    options: [
    "Get out and investigate",
    "Telephone the signal operator",
    "Continue to wait",
    "Drive across carefully",
    ],
    correctIndex: 2,
    explanation: "At a level crossing, flashing red lights mean you must stop. If the train passes but the lights keep flashing, wait. Another train may be coming.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1227",
    questionText: "What should you do if the amber lights come on and a warning sounds while you're driving over a level crossing?",
    options: [
    "Get everyone out of the vehicle immediately",
    "Stop and reverse back to clear the crossing",
    "Keep going and clear the crossing",
    "Stop immediately and use your hazard warning lights",
    ],
    correctIndex: 2,
    explanation: "Keep going; do not stop on the crossing. If the warning sounds and the amber lights come on as you’re approaching the crossing, you must stop unless it's unsafe to do so. Red flashing lights together with the audible warning mean you must stop.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1228",
    questionText: "You're driving on a busy main road. What should you do if you find that you're driving in the wrong direction?",
    options: [
    "Turn into a side road on the right and reverse into the main road",
    "Make a U-turn in the main road",
    "Make a ‘three-point’ turn in the main road",
    "Turn around in a side road",
    ],
    correctIndex: 3,
    explanation: "Do not turn around in a busy street or reverse from a side road into a main road. Find a quiet side road and choose a place to turn around where you will not obstruct an entrance or exit. Look out for pedestrians and cyclists as well as other traffic.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1229",
    questionText: "When may you drive without wearing your seat belt?",
    options: [
    "When you're carrying out a manoeuvre that includes reversing",
    "When you're moving off on a hill",
    "When you're testing your brakes",
    "When you're driving slowly in queuing traffic",
    ],
    correctIndex: 0,
    explanation: "You may remove your seat belt while you're carrying out a manoeuvre that includes reversing. However, you must remember to put it back on again before you resume driving.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1230",
    questionText: "How far are you allowed to reverse?",
    options: [
    "No further than is necessary",
    "No more than a car’s length",
    "As far as it takes to reverse around a corner",
    "The length of a residential street",
    ],
    correctIndex: 0,
    explanation: "You must not reverse further than is necessary. You may decide to turn your vehicle around by reversing into an opening or side road. When you reverse, always look all around you and watch for pedestrians. Do not reverse from a side road into a main road.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1232",
    questionText: "What should you do when you're unsure whether it's safe to reverse your vehicle?",
    options: [
    "Sound your horn",
    "Rev your engine",
    "Get out and check",
    "Reverse slowly",
    ],
    correctIndex: 2,
    explanation: "A small child could be hidden directly behind you, so, if you cannot see all around your vehicle, get out and have a look. You could also ask someone reliable outside the vehicle to guide you.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1233",
    questionText: "Why could it be dangerous to reverse from a side road into a main road?",
    options: [
    "Your reverse sensors will beep",
    "Your view will be restricted",
    "Your reversing lights will be hidden",
    "Your mirrors will need adjusting",
    ],
    correctIndex: 1,
    explanation: "Do not reverse into a main road from a side road because your view will be restricted. The main road is likely to be busy and the traffic on it moving quickly.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1355",
    questionText: "You want to turn right at a box junction. What should you do if there's oncoming traffic?",
    options: [
    "Wait in the box junction if your exit is clear",
    "Wait before the junction until it's clear of all traffic",
    "Drive on; you cannot turn right at a box junction",
    "Drive slowly into the box junction when signalled by oncoming traffic",
    ],
    correctIndex: 0,
    explanation: "You can wait in the box junction as long as your exit is clear. At some point there'll be a gap in the oncoming traffic, or the traffic lights will change, allowing you to proceed.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1381",
    questionText: "You're reversing into a side road. When would your vehicle be the greatest hazard to passing traffic?",
    options: [
    "After you’ve completed the manoeuvre",
    "Just before you begin to manoeuvre",
    "After you’ve entered the side road",
    "When the front of your vehicle swings out",
    ],
    correctIndex: 3,
    explanation: "Always check in all directions before reversing. Keep a good lookout throughout the manoeuvre and remember that the front will swing out as you reverse into the side road. Act on what you see and wait if necessary.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1435",
    questionText: "Where's the safest place to park your vehicle at night?",
    options: [
    "In a garage",
    "On a busy road",
    "In a quiet car park",
    "Near a red route",
    ],
    correctIndex: 0,
    explanation: "If you have a garage, use it. Your vehicle is less likely to be a victim of car crime if it's in a garage. Also, in winter, the windows will be kept free from ice and snow.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1527",
    questionText: "When may you stop on an urban clearway?",
    options: [
    "To set down and pick up passengers",
    "To use a mobile telephone",
    "To ask for directions",
    "To load or unload goods",
    ],
    correctIndex: 0,
    explanation: "Urban clearways have their times of operation clearly signed. You may only stop to pick up or set down passengers.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1528",
    questionText: "You're looking for somewhere to park your vehicle. Neither you or your passenger are disabled. What should you do if the only free spaces are marked for disabled drivers?",
    options: [
    "Use one of these spaces",
    "Park in one of these spaces but stay with your vehicle",
    "Use one of the spaces as long as one is kept free",
    "Wait for a regular parking space to become free",
    ],
    correctIndex: 3,
    explanation: "It's illegal to park in a space reserved for disabled drivers unless you're permitted to do so. These spaces are provided for people with limited mobility, who may need extra space to get in and out of their vehicle.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1554",
    questionText: "You're on a road that's only wide enough for one vehicle. What should you do if a car is coming towards you?",
    options: [
    "Pull into a passing place on your right",
    "Force the other driver to reverse",
    "Pull into a passing place if your vehicle is wider",
    "Pull into a passing place on your left",
    ],
    correctIndex: 3,
    explanation: "Pull into the nearest passing place on the left if you meet another vehicle on a narrow road. If the nearest passing place is on the right, wait opposite it.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1566",
    questionText: "You're driving at night with your headlights on main beam. A vehicle is overtaking you. When should you dip your headlights?",
    options: [
    "Some time after the vehicle has passed you",
    "Before the vehicle starts to pass you",
    "Only if the other driver dips their headlights",
    "As soon as the vehicle passes you",
    ],
    correctIndex: 3,
    explanation: "On main beam, your lights could dazzle the driver in front. Dip your headlights as soon as the driver passes you and drop back so that the dipped beam falls short of the vehicle in front.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1581",
    questionText: "When may you drive a car in this bus lane?",
    options: [
    "Outside its hours of operation",
    "To get to the front of a traffic queue",
    "You may not use it at any time",
    "To overtake slow-moving traffic",
    ],
    correctIndex: 0,
    explanation: "Some bus lanes operate only during peak hours and other vehicles may use them outside these hours. Make sure you check the sign for the hours of operation before driving in a bus lane.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1622",
    questionText: "Other than direction indicators, how can you give signals to other road users?",
    options: [
    "By using brake lights",
    "By using sidelights",
    "By using fog lights",
    "By using interior lights",
    ],
    correctIndex: 0,
    explanation: "Your brake lights will give an indication to traffic behind that you're slowing down. Good anticipation will allow you time to check your mirrors before slowing.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1692",
    questionText: "You're parked in a busy high street. What's the safest way to turn your vehicle around so you can drive in the opposite direction?",
    options: [
    "Turn around in a quiet side road",
    "Drive into a side road and reverse out into the main road",
    "Ask someone to stop the traffic",
    "Carry out a U-turn",
    ],
    correctIndex: 0,
    explanation: "Make sure you carry out the manoeuvre without causing a hazard to other vehicles. Choose a place to turn that's safe and considers other road users.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1693",
    questionText: "Where should you park your vehicle at night?",
    options: [
    "Near a police station",
    "In a quiet road",
    "On a red route",
    "In a well-lit area",
    ],
    correctIndex: 3,
    explanation: "When you're parking at night, park in a well-lit area. This can help deter criminals from targeting your vehicle.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1694",
    questionText: "You're driving in the right-hand lane of a dual carriageway. What should you do if you see a sign showing that the right-hand lane is closed 800 yards ahead?",
    options: [
    "Keep in that lane until you reach the queue",
    "Move to the left immediately",
    "Wait and see which lane is moving faster",
    "Move to the left in good time",
    ],
    correctIndex: 3,
    explanation: "Keep a lookout for traffic signs. If you’re directed to change lanes, do so in good time. Do not\r\n• push your way into traffic in another lane\r\n• try to gain advantage by delaying changing lanes.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1747",
    questionText: "You're driving on a road that has a cycle lane. What does it mean if the lane is marked by a broken white line?",
    options: [
    "You should not drive in the lane unless it's unavoidable",
    "There's a reduced speed limit for motor vehicles using the lane",
    "Cyclists can travel in both directions in that lane",
    "The lane must be used by motorcyclists in heavy traffic",
    ],
    correctIndex: 0,
    explanation: "Cycle lanes are marked with either a solid or a broken white line. If the line is solid, you should check the times of operation shown on the signs, and not drive or park in the lane during those times. If the line is broken, you should not drive or park in the lane unless it's unavoidable.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1784",
    questionText: "When are you allowed to park in a parking bay for disabled drivers?",
    options: [
    "When you have a Blue Badge",
    "When you have a wheelchair",
    "When you have an advanced driver certificate",
    "When you have an adapted vehicle",
    ],
    correctIndex: 0,
    explanation: "Do not park in a space reserved for disabled people unless you or your passenger are a Blue Badge holder. The badge must be displayed on the dashboard or fascia panel, where it can be clearly read through the front windscreen.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "BB1794",
    questionText: "When must you stop your vehicle?",
    options: [
    "If you’re involved in an incident that causes damage or injury",
    "At a junction where there are ‘give way’ lines",
    "At the end of a one-way street",
    "Before merging onto a motorway",
    ],
    correctIndex: 0,
    explanation: "You must stop your vehicle when signalled to do so by a \r\n• police, DVSA or traffic officer\r\n• traffic warden\r\n• school crossing patrol \r\n• red traffic light. \r\nYou must also stop if you're involved in an incident that causes damage or injury to any other person, vehicle, animal or property.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: "AB2628",
    questionText: "What's the nearest you may park to a junction?",
    options: [
      "10 metres (32 feet)",
      "12 metres (39 feet)",
      "15 metres (49 feet)",
      "20 metres (66 feet)",
    ],
    correctIndex: 0,
    explanation: "Do not park within 10 metres (32 feet) of a junction (unless in an authorised parking place). This is to allow drivers emerging from, or turning into, the junction a clear view of the road they're joining. It also allows them to see hazards such as pedestrians or cyclists at the junction.",
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
];
