// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const rulesOfTheRoadQuestions: Question[] = [
  {
    id: 'RUL_001',
    questionText: 'What is the national speed limit for a car on a UK motorway?',
    options: [
      '60mph',
      '70mph',
      '80mph',
      '90mph',
    ],
    correctIndex: 1,
    explanation:
      'The national speed limit on a motorway is 70mph for cars and motorcycles. Lower limits apply for vehicles towing trailers, HGVs, and where variable speed limit signs are displayed.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_002',
    questionText: 'What is the default speed limit in a built-up area unless otherwise signed?',
    options: [
      '20mph',
      '30mph',
      '40mph',
      '50mph',
    ],
    correctIndex: 1,
    explanation:
      'The default speed limit in a built-up area (where there are street lights no more than 185m apart) is 30mph. This can be reduced to 20mph if signed.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_003',
    questionText: 'Which lane should you use for normal driving on a three-lane motorway when the road is clear?',
    options: [
      'The middle lane for safety',
      'Any lane, whichever is most convenient',
      'The left-hand lane',
      'The lane that allows you to travel fastest',
    ],
    correctIndex: 2,
    explanation:
      'Highway Code Rule 264 states you should always drive in the left-hand lane when the road ahead is clear. Middle and right lanes are for overtaking only. Staying in the middle lane (lane hogging) is an offence.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_004',
    questionText: 'In which of these situations must you NOT overtake?',
    options: [
      'On a straight road with good visibility ahead',
      'When approaching a junction, the brow of a hill, or a bend',
      'When the vehicle ahead is travelling below the speed limit',
      'On a dual carriageway in the right-hand lane',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rules 163-168 prohibit overtaking where you cannot see far enough ahead to do so safely - including near junctions, at bends, and on the approach to the brow of a hill.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_005',
    questionText: 'You want to turn right at a roundabout to take the third exit. Which lane and signal should you use on approach?',
    options: [
      'Left lane, no signal on approach',
      'Right lane, signal right on approach',
      'Either lane, signal left as you pass the second exit',
      'Middle lane if available, no approach signal needed',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rule 186 states that for exits beyond 12 o\'clock (right turns) you should approach in the right-hand lane, signalling right. Signal left after passing the exit before the one you intend to take.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_006',
    questionText: 'When are you allowed to use hazard warning lights while moving?',
    options: [
      'Whenever you need to warn drivers behind you of a hazard',
      'When driving slowly on a motorway or dual carriageway to warn of a hazard ahead',
      'When making a delivery stop in a restricted area',
      'When driving in heavy rain to increase your visibility',
    ],
    correctIndex: 1,
    explanation:
      'Hazard warning lights should not normally be used while moving. An exception is on motorways or dual carriageways to warn drivers behind of a sudden hazard ahead, such as a queue. Switch them off as soon as drivers behind have had adequate warning.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_007',
    questionText: 'You are overtaking a cyclist on a narrow road. How much space should you leave?',
    options: [
      'Half a metre - enough to pass safely without touching',
      'At least 1 metre at low speeds; at least 1.5 metres at higher speeds',
      'The same as overtaking a car - one lane width',
      'Any amount is acceptable as long as you do not make contact',
    ],
    correctIndex: 1,
    explanation:
      'The Highway Code states you should give cyclists at least 1.5 metres when overtaking at speeds over 30mph and a similar or greater distance at lower speeds. Cyclists can wobble unexpectedly and need substantial clearance.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_008',
    questionText: 'What is a yellow box junction and when may you enter one?',
    options: [
      'A pedestrian crossing area - enter only when no pedestrians are present',
      'A junction marked with criss-cross yellow lines - enter only when your exit road is clear',
      'A bus priority zone - private vehicles must not enter',
      'A loading area - enter only to collect or set down passengers',
    ],
    correctIndex: 1,
    explanation:
      'Yellow box junctions have criss-cross yellow lines and you must not enter unless your exit is clear. One exception: you may wait in the box when turning right if only oncoming traffic or vehicles ahead turning right are preventing you from completing the turn.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_009',
    questionText: 'What is the maximum speed limit for a car towing a trailer on a motorway?',
    options: [
      '50mph',
      '60mph',
      '70mph',
      'The same as for cars without trailers',
    ],
    correctIndex: 1,
    explanation:
      'When towing a trailer, the maximum speed limit on a motorway or dual carriageway is 60mph. The limit on a single carriageway is 50mph. These limits apply even where the national speed limit would otherwise allow higher speeds.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_010',
    questionText: 'What is the national speed limit for a car on a single carriageway road with no street lighting?',
    options: [
      '50mph',
      '60mph',
      '70mph',
      '80mph',
    ],
    correctIndex: 1,
    explanation:
      'The national speed limit for a car on a single carriageway is 60mph. Dual carriageways and motorways have a national limit of 70mph. The presence or absence of street lights distinguishes a built-up area (30mph limit) from an open road.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_011',
    questionText: 'When is it legal to sound your horn?',
    options: [
      'To greet someone you know',
      'To warn others of your presence when it may prevent a collision',
      'To encourage a slow driver to move out of the way',
      'When reversing in a car park',
    ],
    correctIndex: 1,
    explanation:
      'Highway Code Rule 112 states you must only use the horn to warn other road users of your presence. It must not be used to show impatience or aggression, or when stationary except to avoid danger.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_012',
    questionText: 'You are on a one-way street and want to turn right. Which lane should you use?',
    options: [
      'Stay in the left lane throughout to avoid cutting across traffic',
      'Move to the right-hand lane before turning right',
      'Use the middle lane if there is one',
      'It does not matter - either lane is acceptable on a one-way street',
    ],
    correctIndex: 1,
    explanation:
      'On a one-way street, position yourself in the lane appropriate to your intended direction before you reach the junction. To turn right, use the right-hand lane. Signal early and check mirrors thoroughly.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_013',
    questionText: 'A pelican crossing shows a steady amber light. What must you do?',
    options: [
      'Proceed normally as the amber phase means pedestrians should not cross',
      'Stop unless you are so close that stopping would be dangerous',
      'Give way to pedestrians if they are on the crossing',
      'Sound your horn to warn any pedestrians thinking of crossing',
    ],
    correctIndex: 2,
    explanation:
      'At a pelican crossing showing a steady amber light, you must give way to any pedestrian who is still on the crossing. This is different from a normal amber traffic light because pedestrians may lawfully be crossing during this phase.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_014',
    questionText: 'What does "lane hogging" mean and why is it an offence?',
    options: [
      'Driving at the maximum speed limit in any lane',
      'Remaining in the middle or outer lane of a motorway when the lane to the left is clear',
      'Switching between lanes repeatedly without signalling',
      'Driving too slowly in the left-hand lane of a dual carriageway',
    ],
    correctIndex: 1,
    explanation:
      'Lane hogging means unnecessarily occupying the middle or right lane when the left lane is clear. It obstructs other drivers, forces unnecessary overtaking on the left, and is classified as careless driving, carrying penalty points.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_015',
    questionText: 'At a mini roundabout, who has priority?',
    options: [
      'The vehicle that arrived at the roundabout first',
      'The largest vehicle',
      'Traffic already on the roundabout, coming from the right',
      'Vehicles travelling straight on, over those turning',
    ],
    correctIndex: 2,
    explanation:
      'At a mini roundabout, as at all roundabouts, you give way to traffic already on the roundabout from your right. Mini roundabouts are often tighter and require all drivers to be prepared to give way and navigate carefully.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_016',
    questionText: 'What is the speed limit for a car on a dual carriageway (not a motorway)?',
    options: [
      '60mph',
      '70mph',
      '80mph',
      'Same as a motorway at 70mph',
    ],
    correctIndex: 1,
    explanation: 'The national speed limit on a dual carriageway for a car is 70mph - the same as a motorway. On a single carriageway it is 60mph. Lower limits may be signed. The type of road (separated carriageways) determines which limit applies.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_017',
    questionText: 'When must you switch on your headlights?',
    options: [
      'Only between midnight and 5am',
      'Between sunset and sunrise and whenever visibility is seriously reduced',
      'Whenever you are driving on an unlit road',
      'Only when weather conditions are poor',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 113 requires headlights between sunset and sunrise. You must also use them (or front fog lights) when visibility is seriously reduced, generally regarded as less than 100 metres. Daytime running lights are not a substitute for headlights at night.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_018',
    questionText: 'When may you use rear fog lights?',
    options: [
      'Whenever it is raining heavily',
      'When visibility is seriously reduced to less than 100 metres',
      'Whenever you are driving in the dark',
      'Only on motorways where traffic is fast-moving',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 226 states you should use rear fog lights when visibility is seriously reduced to less than 100 metres (the length of a motorway chevron spacing). Switch them off when visibility improves - they can dazzle following drivers and mask brake lights.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_019',
    questionText: 'What is the speed limit on a single carriageway for a car towing a trailer?',
    options: [
      '40mph',
      '50mph',
      '60mph',
      'The same as without a trailer',
    ],
    correctIndex: 1,
    explanation: 'When towing, the speed limits are lower: 50mph on a single carriageway and 60mph on dual carriageways and motorways. These apply even where the national limit would allow higher speeds, because towing reduces stability and increases stopping distance.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_020',
    questionText: 'You are approaching a junction where you must give way. There are no vehicles on the main road. Must you still stop?',
    options: [
      'Yes - you must always come to a complete stop at a give way line',
      'No - if there is no traffic, slow down and proceed if safe',
      'Yes - but only if there is a stop line painted on the road',
      'No - but you must check carefully in both directions before emerging',
    ],
    correctIndex: 1,
    explanation: 'A give way line (broken) requires you to give way to traffic on the main road. If there is no approaching traffic, you do not legally have to stop - but you must slow down and check thoroughly before emerging. A STOP sign requires a full stop regardless.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_021',
    questionText: 'In which circumstance is it legal to reverse from a main road into a side road?',
    options: [
      'It is never legal to reverse from a main road into a side road',
      'It is legal but considered bad practice - always try to reverse into, then emerge forward',
      'It is legal in a residential area if no other option exists',
      'It is legal but only if a second person guides you on the pavement',
    ],
    correctIndex: 1,
    explanation: 'Reversing from a main road into a side road is legal but inadvisable because it places your vehicle across the path of main road traffic. It is always safer to reverse into the side road first and then drive forward out onto the main road.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_022',
    questionText: 'You are parked on a hill facing downhill. How should you position your steering wheel before leaving the vehicle?',
    options: [
      'Straight ahead so the vehicle rolls to the kerb',
      'Turn the wheel so the front wheels point away from the kerb',
      'Turn the wheel so the front wheels point towards the kerb',
      'The wheel position does not matter if the handbrake is applied',
    ],
    correctIndex: 2,
    explanation: 'When parked facing downhill, turn the front wheels towards the kerb. If the handbrake fails, the wheels will contact the kerb and prevent the car rolling away. Facing uphill, turn wheels away from the kerb for the same reason.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_023',
    questionText: 'When approaching a roundabout to take the first exit (turning left), which lane should you use?',
    options: [
      'Right-hand lane - always approach in the right lane to give way to all traffic',
      'Left-hand lane, signalling left on approach',
      'Left-hand lane with no approach signal - only signal left on the roundabout',
      'Either lane is acceptable',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 186 states that for the first exit (left) at a roundabout, use the left lane and signal left on approach. Maintain the signal throughout the roundabout and exit from the left lane.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_024',
    questionText: 'When approaching a roundabout to go straight ahead (second exit at twelve o\'clock), what signal should you give on approach?',
    options: [
      'Signal left throughout',
      'Signal right throughout',
      'No signal on approach - signal left after passing the first exit',
      'Signal right on approach, left after passing the first exit',
    ],
    correctIndex: 2,
    explanation: 'For a straight-ahead exit, Highway Code Rule 186 states use the left lane where possible and do not signal on approach. Signal left after passing the exit before the one you want to take.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_025',
    questionText: 'You are driving at 35mph in a 30mph zone. Is this an offence?',
    options: [
      'No - there is a standard 10% plus 2mph tolerance built into law',
      'Yes - exceeding the posted speed limit at any level is an offence',
      'No - police only enforce limits above 40mph in 30mph zones',
      'Only if a camera records it - police cannot issue fines without proof',
    ],
    correctIndex: 1,
    explanation: 'Exceeding any posted speed limit is an offence under the Road Traffic Regulation Act 1984. While prosecution thresholds exist in practice, there is no legal tolerance. Exceeding the limit by any amount can result in a fine, penalty points, or a speed awareness course.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_026',
    questionText: 'When is it permitted to use full-beam (main beam) headlights?',
    options: [
      'Whenever driving at night on any road',
      'At night on unlit roads when no other vehicles are nearby to be dazzled',
      'Only on motorways at night when the road is unlit',
      'Whenever visibility drops below 100 metres',
    ],
    correctIndex: 1,
    explanation: 'Full-beam headlights should only be used where they do not dazzle other road users. Switch to dipped headlights when you see oncoming vehicles, when following another vehicle, or when in a well-lit area. In fog, full beam makes visibility worse by reflecting glare back.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_027',
    questionText: 'Which vehicles may use bus lanes?',
    options: [
      'Buses and taxis only',
      'It depends on the signage - the sign will list permitted vehicles',
      'Any vehicle if the lane is empty',
      'Emergency vehicles and local authority vehicles only',
    ],
    correctIndex: 1,
    explanation: 'Vehicles permitted in bus lanes depend on the local designation shown on signs. Most allow buses, but signs may also permit motorcycles, cycles, or taxis. Outside operating hours, the lane may be open to all vehicles. Always check the sign.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_028',
    questionText: 'What is the legal minimum age to drive a car on a public road in the UK?',
    options: [
      '16',
      '17',
      '18',
      '16 with a provisional licence and an adult supervisor',
    ],
    correctIndex: 1,
    explanation: 'You must be 17 to hold a provisional car driving licence and drive on public roads in the UK. Exceptions exist for those receiving certain disability benefits who may apply from age 16. Driving before 17 on public roads is illegal.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_029',
    questionText: 'When do you legally need to give way to pedestrians at a junction?',
    options: [
      'Only at marked pedestrian crossings',
      'When turning and a pedestrian is crossing or is about to cross the road you are turning into',
      'Pedestrians never have right of way over vehicles at unmarked junctions',
      'Only in a 20mph zone',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 195 states that when turning into a road, you should give way to pedestrians who are crossing or waiting to cross the road you are entering. This applies even where there is no marked crossing.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_030',
    questionText: 'What is the current penalty for being caught using a handheld mobile phone while driving?',
    options: [
      '£60 fine and 3 penalty points',
      '£200 fine and 6 penalty points',
      '£100 fine and 3 penalty points',
      '£500 fine and 6 penalty points',
    ],
    correctIndex: 1,
    explanation: 'From 2022, the penalty for using a handheld mobile phone while driving increased to a £200 fine and 6 penalty points. New drivers lose their licence if they accumulate 6 points within two years of passing their test.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_031',
    questionText: 'Which of the following does NOT require a seat belt to be worn?',
    options: [
      'Front seat passengers over 14 years old',
      'Rear seat passengers over 14 years old',
      'Drivers who hold a medical exemption certificate',
      'Children under 3 travelling in the rear seat',
    ],
    correctIndex: 2,
    explanation: 'Seat belts are compulsory for all occupants. Medical exemptions exist but require a certificate from a doctor. Children under 3 must use the appropriate child restraint. Between 3 and 14 years the driver is responsible for ensuring a restraint is used.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_032',
    questionText: 'What does the term "careless driving" mean in law?',
    options: [
      'Driving above the speed limit on any road',
      'Driving without due care and attention or without reasonable consideration for others',
      'Failing to stop after an accident',
      'Driving with a faulty vehicle',
    ],
    correctIndex: 1,
    explanation: 'Careless driving is defined under the Road Traffic Act 1988 as driving without due care and attention, or without reasonable consideration for others. It covers a wide range of behaviours such as tailgating, lane hogging, and failure to give way.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_033',
    questionText: 'What is the difference between careless driving and dangerous driving?',
    options: [
      'Dangerous driving only applies on motorways',
      'Dangerous driving involves driving far below the standard of a competent driver, creating obvious danger',
      'They are the same offence with different penalty levels',
      'Careless driving only applies to minor infringements; dangerous driving requires an accident to have occurred',
    ],
    correctIndex: 1,
    explanation: 'Dangerous driving is a more serious offence requiring that the standard of driving falls far below what a competent driver would do, with an obvious danger to others. Careless driving falls below the standard of a competent driver but does not need to create obvious danger. Dangerous driving carries a higher maximum penalty.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_034',
    questionText: 'On which side of the road must you normally drive in the UK?',
    options: [
      'The right side, moving to the left only to overtake',
      'The left side, moving to the right to overtake',
      'Either side if the road is clear',
      'The centre of the road unless oncoming vehicles are present',
    ],
    correctIndex: 1,
    explanation: 'In the UK, you drive on the left side of the road. Move to the right (towards the centre) to overtake, then return to the left. Driving on the right is an offence and creates a serious collision risk with oncoming traffic.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_035',
    questionText: 'You are about to signal and manoeuvre. What is the full MSM-PSL routine?',
    options: [
      'Mirror, Signal, Manoeuvre - Position, Speed, Look',
      'Mirror, Speed, Manoeuvre - Position, Signal, Look',
      'Move, Signal, Mirror - Position, Speed, Lane',
      'Mirror, Signal, Maintain - Position, Slow, Look',
    ],
    correctIndex: 0,
    explanation: 'The full routine is Mirror-Signal-Manoeuvre, with the manoeuvre broken into Position-Speed-Look. Check mirrors first, signal your intention, then position correctly, adjust speed, and look again before completing the manoeuvre. This systematic approach prevents accidents.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_036',
    questionText: 'At a junction where there are no road markings or signs, who has priority?',
    options: [
      'The driver on the wider road',
      'The driver who arrived first',
      'The driver turning right',
      'There is no automatic priority - all drivers must exercise care and be prepared to give way',
    ],
    correctIndex: 3,
    explanation: 'At an unmarked junction, no vehicle has automatic priority. All drivers should approach with care, be prepared to give way, and cooperate to avoid conflict. Good judgement and courtesy are required where no markings or signs are present.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_037',
    questionText: 'What does it mean to "pass the driving test" in terms of the two-year probationary period?',
    options: [
      'New drivers are restricted to 50mph for the first two years',
      'If a new driver accumulates 6 or more penalty points within two years, their licence is revoked',
      'New drivers must retake their theory test after two years',
      'There is no probationary period - new drivers are treated the same as experienced drivers',
    ],
    correctIndex: 1,
    explanation: 'Under the Road Traffic (New Drivers) Act 1995, if a newly qualified driver accumulates 6 or more penalty points within two years of passing their test, their licence is automatically revoked. They must retake both theory and practical tests to drive again.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_038',
    questionText: 'You are driving on a road with a 30mph speed limit. What does this limit mean for you?',
    options: [
      'You should try to drive at 30mph at all times to maintain traffic flow',
      '30mph is the maximum permitted speed - you may need to drive slower depending on conditions',
      '30mph applies only when children or pedestrians are nearby',
      'You may exceed 30mph briefly to overtake another vehicle',
    ],
    correctIndex: 1,
    explanation: 'A speed limit is a maximum - not a target. Even on a 30mph road, conditions such as poor weather, pedestrians, or road layout may require a lower speed. Always drive at a speed appropriate to the conditions, up to the maximum allowed.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 1,
  },
  {
    id: 'RUL_039',
    questionText: 'In a 20mph zone, can a driver be prosecuted for driving at 22mph?',
    options: [
      'No - below 25mph is not prosecutable in a 20mph zone',
      'Yes - any speed above the limit is an offence in law',
      'No - prosecution only occurs above 35mph in a 20mph zone',
      'Only if there are children present',
    ],
    correctIndex: 1,
    explanation: '22mph in a 20mph zone is legally above the speed limit and is technically an offence. While prosecution thresholds vary in practice, the legal position is clear - any speed above the limit breaks the law.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_040',
    questionText: 'When may you overtake on the left (underake) on a motorway?',
    options: [
      'When the right lane is moving faster than the left',
      'Never - undertaking on any road is always illegal',
      'When traffic is moving slowly in queues and your lane is progressing faster',
      'When the vehicle ahead is driving below the speed limit',
    ],
    correctIndex: 2,
    explanation: 'Highway Code Rule 268 states you should not normally overtake on the left. However, in slow-moving queued traffic where your lane is moving faster than the lane to your right, you may pass on the left. Deliberate undertaking at normal speeds is illegal.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_041',
    questionText: 'You are driving and wish to turn right at a junction. Oncoming traffic prevents the turn. Where should you wait?',
    options: [
      'Stay behind the stop line until the road is clear',
      'Move forward past the stop line and wait in a position that does not block oncoming traffic',
      'Enter the junction and wait alongside the central white line',
      'Enter the junction and wait on the right side of the road, past the centre',
    ],
    correctIndex: 1,
    explanation: 'At a junction where you intend to turn right, you may move forward past the stop line into the junction to wait for a gap in oncoming traffic. Position yourself so you do not block traffic going straight ahead. Complete the turn when it is safe.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_042',
    questionText: 'What does Highway Code Rule 170 say about emerging from a side road?',
    options: [
      'You may emerge cautiously if you believe the main road is clear',
      'You must give way to all vehicles on the main road and to any pedestrians crossing the road you are entering',
      'You have right of way if there are no give way markings',
      'You must stop and wait until there is a clear view in both directions for at least 200 metres',
    ],
    correctIndex: 1,
    explanation: 'Rule 170 states that when emerging from a side road you must look both ways, take particular care, and give way to all traffic on the main road. Also give way to pedestrians who are crossing the road you are entering. Do not emerge and cause others to brake.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_043',
    questionText: 'What is the maximum speed for a goods vehicle over 7.5 tonnes on a single carriageway?',
    options: [
      '40mph',
      '50mph',
      '60mph',
      '70mph',
    ],
    correctIndex: 1,
    explanation: 'Large goods vehicles over 7.5 tonnes have a maximum speed of 50mph on single carriageways, 60mph on dual carriageways, and 60mph on motorways. These lower limits reflect the greater stopping distances and reduced manoeuvrability of heavy vehicles.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_044',
    questionText: 'Where are you prohibited from parking under the Highway Code (Rule 243)?',
    options: [
      'On any road without a designated parking space',
      'Opposite or within 10 metres of a junction, on a bend, on a hill, or where visibility is reduced',
      'Within 50 metres of a school entrance at any time',
      'On any yellow line regardless of time of day',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 243 lists many prohibited parking locations including within 10 metres of a junction, on a bend, near the brow of a hill, opposite another parked vehicle where it narrows the road, on a clearway, and many others. Always check carefully before stopping.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_045',
    questionText: 'What does it mean to "drive without due care and attention"?',
    options: [
      'Driving without your full licence on your person',
      'Driving in a manner that falls below the standard expected of a careful and competent driver',
      'Driving without checking your vehicle before setting off',
      'Failing to look in your mirrors before setting off',
    ],
    correctIndex: 1,
    explanation: 'Driving without due care and attention is a criminal offence under Section 3 of the Road Traffic Act 1988. It means the standard of driving fell below what a careful and competent driver would demonstrate. It is an objective test - it does not matter whether the driver meant to drive poorly.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 3,
  },
  {
    id: 'RUL_046',
    questionText: 'You are driving at night in a built-up area with street lights. Do you need to use headlights?',
    options: [
      'No - street lights are sufficient and headlights would dazzle pedestrians',
      'Yes - headlights or dipped headlights must be used between sunset and sunrise',
      'Only dipped headlights are required in lit areas',
      'Only sidelights are required in well-lit streets',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 113 requires headlights to be used between sunset and sunrise, regardless of street lighting. Sidelights alone are not sufficient. Dipped headlights are the standard choice in lit streets - full beam would dazzle other road users.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_047',
    questionText: 'You are driving on a motorway and need to stop urgently because of illness. What should you do?',
    options: [
      'Stop in the nearest lane and switch on hazard lights',
      'Drive to the next junction and stop on the slip road',
      'Pull onto the hard shoulder, move to the nearside verge, and call for help from the emergency phone',
      'Slow to 30mph and use the hard shoulder to call for assistance on your mobile',
    ],
    correctIndex: 2,
    explanation: 'If you must stop in an emergency on a motorway, use the hard shoulder, stop as far left as possible, switch on hazard lights, exit via the nearside door, and wait behind the barrier. Use the roadside emergency phone rather than a mobile so the operator knows your exact location.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_048',
    questionText: 'A learner driver must always be accompanied by whom?',
    options: [
      'A qualified driving instructor',
      'An approved driving instructor (ADI) or a person aged 21 or over who has held a full licence for at least 3 years',
      'Any person over 18 with a full driving licence',
      'An DVSA-registered supervising driver only',
    ],
    correctIndex: 1,
    explanation: 'A learner driver on a public road must be accompanied by a person aged 21 or over who has held a full licence for the same category of vehicle for at least 3 years. They do not have to be an ADI unless using dual controls is required.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_049',
    questionText: 'A cyclist is in the middle of your lane ahead. Are they entitled to be there?',
    options: [
      'No - cyclists must always ride in the gutter on the far left',
      'Yes - cyclists can position themselves in the middle of a lane to be more visible or to avoid hazards',
      'Only if the road has no cycle lane',
      'Only on roads with a 20mph limit',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 72 states cyclists should ride in the centre of the lane on quieter roads, in slower-moving traffic, and at certain junctions. This primary position makes them more visible and protects them from being "doored" by parked cars. Do not try to squeeze past.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
  {
    id: 'RUL_050',
    questionText: 'When can you drive on the hard shoulder of a smart motorway?',
    options: [
      'Never - the hard shoulder is only for breakdowns',
      'Only in a genuine emergency or breakdown',
      'When a sign above the hard shoulder shows a speed limit rather than a red X',
      'At any time when traffic is heavy and the hard shoulder is empty',
    ],
    correctIndex: 2,
    explanation: 'On a smart (all-lane running) motorway, the hard shoulder may be used as a live running lane. When an overhead gantry shows a speed limit above the hard shoulder, it is open to traffic. A red X means it is closed. Never use the hard shoulder if a red X is displayed.',
    topicCategory: TopicCategory.RulesOfTheRoad,
    difficulty: 2,
  },
];
