import { Question, TopicCategory } from '@clearpass/core';

export const safetyAndYourVehicleQuestions: Question[] = [
  {
    id: "BB1036",
    questionText: "What should you do if your anti-lock braking system (ABS) warning light stays on?",
    options: [
    "Check the brake-fluid level",
    "Check the footbrake free play",
    "Check that the parking brake is released",
    "Have the brakes checked immediately",
    ],
    correctIndex: 3,
    explanation: "Consult the vehicle handbook or a garage before driving the vehicle any further. Only drive to a garage if it's safe to do so. If you’re not sure, get expert help.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1039",
    questionText: "What does it mean if this light comes on while you're driving?",
    options: [
    "A fault in the braking system",
    "The engine oil is low",
    "A rear light has failed",
    "Your seat belt is not fastened",
    ],
    correctIndex: 0,
    explanation: "If this light comes on, you should have the brake system checked immediately. A faulty braking system could have dangerous consequences.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1043",
    questionText: "Why is it important to wear suitable shoes when you're driving?",
    options: [
    "To prevent wear on the pedals",
    "To maintain control of the pedals",
    "To allow you to adjust your seat",
    "To allow you to walk for assistance if you break down",
    ],
    correctIndex: 1,
    explanation: "When you’re going to drive, make sure that you’re wearing suitable clothing.\r\nComfortable shoes will allow you to keep proper control of the foot pedals.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1045",
    questionText: "If you're involved in a collision, what will reduce the risk of neck injury?",
    options: [
    "An air-sprung seat",
    "Anti-lock brakes",
    "A collapsible steering wheel",
    "A properly adjusted head restraint",
    ],
    correctIndex: 3,
    explanation: "If you’re involved in a collision, head restraints will reduce the risk of neck injury. They must be properly adjusted. Make sure they’re not positioned too low: in a crash, this could cause damage to the neck.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1048",
    questionText: "What does it mean if your vehicle keeps bouncing after you sharply press down and release on the bodywork over a wheel?",
    options: [
    "The tyres are worn",
    "The tyres are under inflated",
    "The vehicle is on soft ground",
    "The shock absorbers are worn",
    ],
    correctIndex: 3,
    explanation: "If you find that your vehicle bounces as you drive around a corner or bend in the road, the shock absorbers might be worn. To test your shock absorbers, sharply press down and release above each wheel. If the vehicle continues to bounce, take it to be checked by a qualified mechanic.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1052",
    questionText: "How will a roof rack affect your car?",
    options: [
    "There will be less wind noise",
    "The engine will use more oil",
    "The car will accelerate faster",
    "Fuel consumption will increase",
    ],
    correctIndex: 3,
    explanation: "A roof rack increases your car's wind resistance. This will cause an increase in fuel consumption, so you should remove it when it’s not being used. An aerodynamically designed roof rack or box will help reduce wind resistance to a minimum, but the rack or box should still be removed when it’s not in use.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1278",
    questionText: "What makes your tyres illegal?",
    options: [
    "If they were bought second-hand",
    "If they have any large, deep cuts in the side wall",
    "If they're of different makes",
    "If they have different tread patterns",
    ],
    correctIndex: 1,
    explanation: "Your tyres may be of different treads and makes. They can even be second-hand, as long as they're in good condition. They must, however, be intact, without cuts or tears. When checking the side walls for cuts and bulges, do not forget to check the side of the tyre that's hidden from view, under the car.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1279",
    questionText: "What's the legal minimum depth of tread for car tyres?",
    options: [
    "1 mm",
    "1.6 mm",
    "2.5 mm",
    "4 mm",
    ],
    correctIndex: 1,
    explanation: "Car tyres must have sufficient depth of tread to give them a good grip on the road surface. The legal minimum for cars is 1.6 mm. This depth should be across the central three-quarters of the breadth of the tyre and around the entire circumference.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1280",
    questionText: "You're carrying 2 13-year-old children and their parents in your car. Who's responsible for seeing that the children wear seat belts?",
    options: [
    "The children's parents",
    "You, the driver",
    "The front-seat passenger",
    "The children",
    ],
    correctIndex: 1,
    explanation: "Seat belts save lives and reduce the risk of injury. If you're carrying passengers under 14 years old, it's your responsibility as the driver to make sure that their seat belts are fastened or they're seated in an approved child restraint.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1301",
    questionText: "How can drivers help the environment?",
    options: [
    "By accelerating harshly",
    "By accelerating gently",
    "By using leaded fuel",
    "By driving faster",
    ],
    correctIndex: 1,
    explanation: "Rapid acceleration and heavy braking lead to increased \r\n• fuel consumption \r\n• wear on your vehicle. \r\nHaving your vehicle serviced regularly will maintain its efficiency, produce cleaner emissions and reduce the risk of a breakdown.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1302",
    questionText: "How can you avoid wasting fuel?",
    options: [
    "By having your vehicle serviced regularly",
    "By revving the engine in the lower gears",
    "By keeping an empty roof rack on your vehicle",
    "By driving at higher speeds where possible",
    ],
    correctIndex: 0,
    explanation: "If you do not have your vehicle serviced regularly, the engine will gradually become less efficient. This will cause increased fuel consumption and, in turn, an increase in the amount of harmful emissions it produces.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1303",
    questionText: "What could you do to reduce the volume of traffic on the roads?",
    options: [
    "Drive in a bus lane",
    "Use a car with a smaller engine",
    "Walk or cycle on short journeys",
    "Travel by car at all times",
    ],
    correctIndex: 2,
    explanation: "Try not to use your car unnecessarily. For shorter journeys, consider walking or cycling instead - this is much better for both you and the environment.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1304",
    questionText: "What's most likely to waste fuel?",
    options: [
    "Reducing your speed",
    "Driving on motorways",
    "Using different brands of fuel",
    "Under-inflated tyres",
    ],
    correctIndex: 3,
    explanation: "Wasting fuel costs you money and also causes unnecessary pollution. Making sure your tyres are correctly inflated, avoiding carrying unnecessary weight and removing a roof rack that's not in use will all help to reduce your fuel consumption.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1347",
    questionText: "What part of the car does the law require you to keep in good condition?",
    options: [
    "The gearbox",
    "The transmission",
    "The door locks",
    "The seat belts",
    ],
    correctIndex: 3,
    explanation: "Unless exempt, you and your passengers must wear a seat belt (or suitable child restraint). The seat belts in your car must be in good condition and working properly; they’ll be checked during its MOT test.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1348",
    questionText: "How much more fuel will you use by driving at 70 mph, compared with driving at 50 mph?",
    options: [
    "About 5%",
    "About 15%",
    "About 75%",
    "About 100%",
    ],
    correctIndex: 1,
    explanation: "Your vehicle will use less fuel if you avoid heavy acceleration. The higher the engine revs, the more fuel you'll use. Using the same gear, and covering the same distance, a vehicle travelling at 70 mph will use about 15% more fuel than it would at 50 mph. However, do not travel so slowly that you inconvenience or endanger other road users.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1368",
    questionText: "What should you do if your vehicle pulls to one side when you use the brakes?",
    options: [
    "Increase the pressure in your tyres",
    "Have the brakes checked as soon as possible",
    "Change gear and pump the brake pedal",
    "Use your parking brake at the same time",
    ],
    correctIndex: 1,
    explanation: "The brakes on your vehicle must be effective and properly adjusted. If your vehicle pulls to one side when braking, take it to be checked by a qualified mechanic as soon as you can.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1392",
    questionText: "What will happen if your car's wheels are unbalanced?",
    options: [
    "The steering will pull to one side",
    "The steering will vibrate",
    "The brakes will fail",
    "The tyres will deflate",
    ],
    correctIndex: 1,
    explanation: "If your wheels are out of balance, it will cause the steering to vibrate at certain speeds. This is not a fault that will put itself right, so take your vehicle to a garage or tyre fitter to have the wheels rebalanced.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1393",
    questionText: "What can be damaged if you turn the steering wheel when the car is not moving?",
    options: [
    "The gearbox",
    "The engine",
    "The brakes",
    "The tyres",
    ],
    correctIndex: 3,
    explanation: "Turning the steering wheel when the car is not moving is known as dry steering. It can cause unnecessary wear to the tyres and steering mechanism.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1414",
    questionText: "What’s the safest thing to do if you have to leave valuables in your car?",
    options: [
    "Put them in a carrier bag",
    "Park near a school entrance",
    "Lock them out of sight",
    "Park near a bus stop",
    ],
    correctIndex: 2,
    explanation: "If you have to leave valuables in your car, lock them out of sight. This is the best way to deter an opportunist thief.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1416",
    questionText: "What may help to deter a thief from stealing your car?",
    options: [
    "Always keeping the headlights on",
    "Fitting reflective glass windows",
    "Always keeping the interior light on",
    "Etching the registration number on the windows",
    ],
    correctIndex: 3,
    explanation: "Having your car registration number etched on all your windows is a cheap and effective way to deter professional car thieves.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1418",
    questionText: "What should you remove from your car before leaving it unattended?",
    options: [
    "The car dealer’s details",
    "The owner’s manual",
    "The service record",
    "The vehicle registration document",
    ],
    correctIndex: 3,
    explanation: "Never leave the vehicle registration document inside your car. This document would help a thief to dispose of your car more easily.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1430",
    questionText: "What should you do when leaving your vehicle parked and unattended?",
    options: [
    "Park near a busy junction",
    "Park in a housing estate",
    "Lock it and remove the key",
    "Leave the left indicator on",
    ],
    correctIndex: 2,
    explanation: "An unlocked car is an open invitation to thieves. Leaving the keys in the ignition not only makes your car easy to steal but could also invalidate your insurance.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1500",
    questionText: "What will reduce fuel consumption?",
    options: [
    "Driving more slowly",
    "Accelerating rapidly",
    "Late and heavy braking",
    "Staying in lower gears",
    ],
    correctIndex: 0,
    explanation: "Harsh braking, frequent gear changes and harsh acceleration increase fuel consumption. A car uses less fuel when travelling at a constant low speed in an appropriate high gear. \r\nYou need to look well ahead so you’re able to anticipate hazards early. Easing off the accelerator and timing your approach at junctions, for example, can reduce the fuel consumption of your vehicle.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1508",
    questionText: "You service your own vehicle. How should you dispose of the old engine oil?",
    options: [
    "Take it to a local authority site",
    "Pour it down a drain",
    "Tip it into a hole in the ground",
    "Put it in your dustbin",
    ],
    correctIndex: 0,
    explanation: "It's illegal to pour engine oil down any drain. Oil is a pollutant and harmful to wildlife. Dispose of it safely at an authorised site.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1511",
    questionText: "Why do MOT tests include an exhaust emission test?",
    options: [
    "To recover the cost of expensive garage equipment",
    "To help protect the environment against pollution",
    "To discover which fuel supplier is used the most",
    "To make sure diesel and petrol engines emit the same fumes",
    ],
    correctIndex: 1,
    explanation: "Emission tests are carried out to make sure your vehicle’s engine is operating efficiently. This keeps the pollution produced by the engine to a minimum. If your vehicle is not serviced regularly, it may fail the MOT emissions test.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1512",
    questionText: "How can you reduce the damage your vehicle causes to the environment?",
    options: [
    "Use narrow side streets",
    "Brake heavily",
    "Use busy routes",
    "Anticipate well ahead",
    ],
    correctIndex: 3,
    explanation: "By looking well ahead and recognising hazards in good time, you can avoid late and heavy braking. Watch the traffic flow and look well ahead for potential hazards so you can control your speed in good time. Avoid over-revving the engine and accelerating harshly, as this increases wear to the engine and uses more fuel.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1557",
    questionText: "How will you benefit from following the manufacturer's service schedule for your vehicle?",
    options: [
    "Your vehicle will be cheaper to insure",
    "Your vehicle tax will be lower",
    "Your vehicle will remain reliable",
    "Your journey times will be reduced",
    ],
    correctIndex: 2,
    explanation: "All vehicles need to be serviced to keep working efficiently. An efficient engine uses less fuel and produces fewer harmful emissions than an engine that's running inefficiently. Keeping the vehicle serviced to the manufacturer's schedule should also keep it reliable and reduce the chance of it breaking down.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1558",
    questionText: "How should you drive when you're driving along a road that has road humps?",
    options: [
    "Maintain a reduced speed throughout",
    "Accelerate quickly between the humps",
    "Always keep to the maximum legal speed",
    "Drive slowly at school times only",
    ],
    correctIndex: 0,
    explanation: "Road humps are there for a reason – to protect vulnerable road users by reducing the speed of traffic. Do not accelerate harshly between the humps. Put the safety of others first and maintain a reduced speed throughout the zone.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1602",
    questionText: "When should you check the engine oil level?",
    options: [
    "Before a long journey",
    "When the engine is hot",
    "Early in the morning",
    "Every time you drive the car",
    ],
    correctIndex: 0,
    explanation: "An engine can use more oil during long journeys than on shorter trips. Insufficient engine oil is potentially dangerous: it can lead to excessive wear, mechanical breakdown and expensive repairs.\r\nMost cars have a dipstick to allow the oil level to be checked. If not, you should refer to the vehicle handbook.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1603",
    questionText: "You're having difficulty finding a parking space in a busy town. Can you park on the zigzag lines of a zebra crossing?",
    options: [
    "No, not unless you stay with your car",
    "Yes, in order to drop off a passenger",
    "Yes, if you do not block people from crossing",
    "No, not under any circumstances",
    ],
    correctIndex: 3,
    explanation: "It’s an offence to park on the zigzag lines of a zebra crossing. You'll be causing an obstruction by obscuring the view of both pedestrians and drivers.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1604",
    questionText: "What should you do when you leave your car unattended for a few minutes?",
    options: [
    "Leave the engine running",
    "Switch the engine off but leave the key in",
    "Lock it and remove the key",
    "Park near a traffic warden",
    ],
    correctIndex: 2,
    explanation: "Always switch off the engine, remove the key and lock your car, even if you're only leaving it for a few minutes.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1607",
    questionText: "Why should you try and park in a secure car park?",
    options: [
    "It makes it easy to find your car",
    "It helps deter thieves",
    "It stops the car being exposed to bad weather",
    "It does not cost anything to park here",
    ],
    correctIndex: 1,
    explanation: "Whenever possible, leave your car in a secure car park. This will help deter thieves.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1609",
    questionText: "Where would parking your vehicle cause an obstruction?",
    options: [
    "Alongside a parking meter",
    "In front of a property entrance",
    "On your driveway",
    "In a marked parking space",
    ],
    correctIndex: 1,
    explanation: "Do not park your vehicle where it may obstruct access to a business or property. Think carefully before you slow down and stop. Look at road markings and signs to make sure that you’re not parking illegally.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1640",
    questionText: "What's the most important reason for having a properly adjusted head restraint?",
    options: [
    "To make you more comfortable",
    "To help you avoid neck injury",
    "To help you relax",
    "To help you maintain your driving position",
    ],
    correctIndex: 1,
    explanation: "In a collision, rapid deceleration will violently throw vehicle occupants forward and then backwards as the vehicle stops. Seat belts and airbags protect occupants against the forward movement. Head restraints should be adjusted so they give maximum protection to the head and neck during the backward movement.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1644",
    questionText: "What can you do to reduce environmental damage caused by your vehicle?",
    options: [
    "Avoid using the cruise control",
    "Use the air conditioning whenever you drive",
    "Use the gears to slow the vehicle",
    "Avoid making a lot of short journeys",
    ],
    correctIndex: 3,
    explanation: "Avoid using your car for short journeys. On a short journey, the engine is unlikely to warm up fully and will therefore be running less efficiently. This will result in the car using more fuel and emitting higher levels of harmful emissions.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1646",
    questionText: "What can people who live or work in towns and cities do to help reduce urban pollution levels?",
    options: [
    "Drive more quickly",
    "Over-rev in a low gear",
    "Walk or cycle",
    "Drive short journeys",
    ],
    correctIndex: 2,
    explanation: "Using a vehicle for short journeys means the engine does not have time to reach its normal operating temperature. When an engine is running below its normal operating temperature, it produces increased amounts of pollution. Walking and cycling do not create pollution and have health benefits as well.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1647",
    questionText: "How can you reduce the chances of your car being broken into when leaving it unattended?",
    options: [
    "Take all valuables with you",
    "Park near a taxi rank",
    "Place any valuables on the floor",
    "Park near a fire station",
    ],
    correctIndex: 0,
    explanation: "When leaving your car, take all valuables with you if you can. Otherwise, lock them out of sight.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1648",
    questionText: "How can you help to prevent your car radio being stolen?",
    options: [
    "Park in an unlit area",
    "Leave the radio turned on",
    "Park near a busy junction",
    "Install a security-coded radio",
    ],
    correctIndex: 3,
    explanation: "A security-coded radio can deter thieves, as it's likely to be of little use when removed from the vehicle.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1653",
    questionText: "How can you reduce the risk of your vehicle being broken into at night?",
    options: [
    "Leave it in a well-lit area",
    "Park in a quiet side road",
    "Do not engage the steering lock",
    "Park in a poorly lit area",
    ],
    correctIndex: 0,
    explanation: "Having your vehicle broken into or stolen can be very distressing and inconvenient. Avoid leaving your vehicle unattended in poorly lit areas.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1655",
    questionText: "On a vehicle, where would you find a catalytic converter?",
    options: [
    "In the fuel tank",
    "In the air filter",
    "On the cooling system",
    "On the exhaust system",
    ],
    correctIndex: 3,
    explanation: "Although carbon dioxide is still produced, a catalytic converter fitted to the exhaust system reduces the toxic and polluting gases by up to 90%.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1710",
    questionText: "What can you achieve if you drive smoothly?",
    options: [
    "Reduction in journey times by about 15%",
    "Increase in fuel consumption by about 15%",
    "Reduction in fuel consumption by about 15%",
    "Increase in journey times by about 15%",
    ],
    correctIndex: 2,
    explanation: "By driving smoothly, you'll not only save about 15% of your fuel but will also reduce the amount of wear and tear on your vehicle and the level of pollution it produces. You're also likely to feel more relaxed and have a more pleasant journey.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1711",
    questionText: "Which driving technique can help you save fuel?",
    options: [
    "Using lower gears as often as possible",
    "Accelerating sharply in each gear",
    "Using each gear in turn",
    "Missing out some gears",
    ],
    correctIndex: 3,
    explanation: "Missing out intermediate gears, when appropriate, helps to reduce the amount of time spent accelerating and decelerating - the times when your vehicle uses the most fuel.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1722",
    questionText: "How can driving in a fuel-efficient manner help protect the environment?",
    options: [
    "Through the legal enforcement of speed regulations",
    "By increasing the number of cars on the road",
    "Through increased fuel bills",
    "By reducing exhaust emissions",
    ],
    correctIndex: 3,
    explanation: "Fuel-efficient driving is all about looking and planning further ahead. This helps raise your hazard awareness and reduces the need for late and heavy braking. This will make your journeys more comfortable, as well as considerably reducing your fuel bills and reducing emissions that can damage the environment.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1723",
    questionText: "What does fuel-efficient driving achieve?",
    options: [
    "Increased fuel consumption",
    "Improved road safety",
    "Damage to the environment",
    "Increased exhaust emissions",
    ],
    correctIndex: 1,
    explanation: "The emphasis is on hazard awareness and planning ahead. By looking well ahead, you'll have plenty of time to deal with hazards safely and will not need to brake sharply. This will also reduce damage to the environment.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1737",
    questionText: "What's the legal minimum tread depth for tyres on your trailer or caravan?",
    options: [
    "1 mm",
    "1.6 mm",
    "2 mm",
    "2.6 mm",
    ],
    correctIndex: 1,
    explanation: "Trailers and caravans may be left in storage over the winter months, and tyres can deteriorate. It’s important to check their tread depth and also their pressures and general condition. The legal tread depth of 1.6 mm applies to the central three-quarters of a tyre's breadth, over its entire circumference.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1741",
    questionText: "When is fuel consumption at its highest?",
    options: [
    "When you're braking",
    "When you're coasting",
    "When you're accelerating",
    "When you're turning sharply",
    ],
    correctIndex: 2,
    explanation: "Accelerating uses a lot of fuel, so always try to use the accelerator smoothly. Taking your foot off the accelerator allows the momentum of the car to take you forward, especially when going downhill. This can save a considerable amount of fuel without any loss of control over the vehicle.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1752",
    questionText: "When may a passenger travel in a car without wearing a seat belt?",
    options: [
    "When they're under 14 years old",
    "When they're under 1.5 metres (5 feet) in height",
    "When they're sitting in the rear seat",
    "When they're exempt for medical reasons",
    ],
    correctIndex: 3,
    explanation: "If you have adult passengers, it's their responsibility to wear a seat belt, but you should still remind them to use one as they get in the car. It's your responsibility to make sure that all children under 14 years old in your car are secured with an appropriate restraint. Exemptions are allowed for those with a medical exemption certificate.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1755",
    questionText: "You're driving a friend's children home from school. They're both under 14 years old. Who's responsible for making sure they wear a seat belt or approved child restraint where required?",
    options: [
    "An adult passenger",
    "The children",
    "You, the driver",
    "Your friend",
    ],
    correctIndex: 2,
    explanation: "Passengers should always be secured and safe. Children should be encouraged to fasten their seat belts or approved restraints themselves from an early age, so that it becomes a habit. As the driver, you must check that they're fastened securely. It's your responsibility.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1756",
    questionText: "What's likely to happen if you put too much oil in your engine?",
    options: [
    "The clutch pedal will lock",
    "The air intake will become blocked",
    "The timing belt will slip",
    "The oil seals will leak",
    ],
    correctIndex: 3,
    explanation: "Too much oil will lead to increased pressure in the engine. This could damage oil seals and lead to oil leaks. Any excess oil should be drained off.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1763",
    questionText: "You have to make an unexpected journey. You're carrying a 5-year-old child on the back seat of your car. They're under 1.35 metres (4 feet 5 inches) tall. How should you seat them if a correct child restraint is not available?",
    options: [
    "Behind the passenger seat",
    "Using an adult seat belt",
    "Sharing a belt with an adult",
    "Between 2 other children",
    ],
    correctIndex: 1,
    explanation: "In journeys of unexpected necessity, and when a correct child restraint is not available, the child must sit on the rear seat and use an adult seat belt. In a collision, unrestrained objects and people can cause serious injury or even death.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1765",
    questionText: "You're carrying an 11-year-old child on the front seat of your car. They're under 1.35 metres (4 feet 5 inches) tall. What seat belt security must be in place?",
    options: [
    "They must use an adult seat belt",
    "They must be able to fasten their own seat belt",
    "They must use a suitable child restraint",
    "They must be able to see clearly out of the front window",
    ],
    correctIndex: 2,
    explanation: "As the driver, it's your responsibility to make sure that children under 14 years old are secure and safe in your vehicle. Make yourself familiar with the rules. When young children are carried on the back seat, there are a few very exceptional cases when an adult seat belt can be used instead of a correct child restraint.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1769",
    questionText: "You're stopped at the side of the road. What must you do if you'll be waiting there for some time?",
    options: [
    "Switch off the engine",
    "Apply the steering lock",
    "Switch off the radio",
    "Use your headlights",
    ],
    correctIndex: 0,
    explanation: "If your vehicle is stationary and is likely to remain so for some time, you must switch off the engine unless you're stationary in traffic or diagnosing a fault.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1770",
    questionText: "You want to put a rear-facing baby seat on the front passenger seat. What must you do if the passenger seat is protected by a frontal airbag?",
    options: [
    "Deactivate the airbag",
    "Turn the seat to face sideways",
    "Ask a passenger to hold the baby",
    "Put the child in an adult seat belt",
    ],
    correctIndex: 0,
    explanation: "It's illegal to fit a rear-facing baby seat into a passenger seat protected by an active frontal airbag. If the airbag activates, it could cause serious injury or even death to the child. You must secure it in a different seat or deactivate the relevant airbag. Follow the manufacturer's advice when fitting a baby seat.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB1777",
    questionText: "You're leaving your vehicle parked on a road and unattended. When may you leave the engine running?",
    options: [
    "If you'll be parking for less than 5 minutes",
    "If the battery keeps going flat",
    "When parked in a 20 mph zone",
    "Never if you're away from the vehicle",
    ],
    correctIndex: 3,
    explanation: "When you leave your vehicle parked on a road, switch off the engine and secure the vehicle. Make sure no valuables are visible, shut all the windows, lock the vehicle, and set the alarm if the vehicle has one.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2045",
    questionText: "How would under-inflated tyres affect your vehicle?",
    options: [
    "The vehicle's stopping distance would increase",
    "The flash rate of the vehicle's indicators would increase",
    "The vehicle's gear change mechanism would become stiff",
    "The vehicle's headlights would aim high",
    ],
    correctIndex: 0,
    explanation: "Your tyres are your only contact with the road. To prevent problems with braking and steering, keep your tyres free from defects; they must have sufficient tread depth and be correctly inflated. Correct tyre pressures help reduce the risk of skidding and provide a safer and more comfortable drive or ride.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2056",
    questionText: "When are you not allowed to sound your vehicle's horn?",
    options: [
    "Between 10pm and 6am in a built-up area",
    "At any time in a built-up area",
    "Between 11:30pm and 7am in a built-up area",
    "Between 11:30pm and 6am on any road",
    ],
    correctIndex: 2,
    explanation: "Every effort must be made to prevent excessive noise, especially in built-up areas at night. Do not rev your engine or sound the horn unnecessarily. It's illegal to sound your horn in a built-up area between 11:30pm and 7am, except when another road user poses a danger.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2060",
    questionText: "What makes the vehicle in the picture 'environmentally friendly'?",
    options: [
    "It's powered by gravity",
    "It's powered by diesel",
    "It's powered by electricity",
    "It's powered by unleaded petrol",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4681.png",
    explanation: "Trams are powered by electricity and therefore do not emit exhaust fumes. They ease traffic congestion by offering drivers an alternative to using their car, particularly in busy cities and towns.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2062",
    questionText: "Why have 'red routes' been introduced in major cities?",
    options: [
    "To raise the speed limits",
    "To help the traffic flow",
    "To provide better parking",
    "To allow lorries to load more freely",
    ],
    correctIndex: 1,
    explanation: "Inconsiderate parking can obstruct the flow of traffic and so make traffic congestion worse. Red routes are designed to prevent this by enforcing strict parking restrictions. Driving slowly in traffic increases fuel consumption and causes a build-up of exhaust fumes.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2064",
    questionText: "What's the purpose of road humps, chicanes and narrowings?",
    options: [
    "To separate lanes of traffic",
    "To increase traffic speed",
    "To allow pedestrians to cross",
    "To reduce traffic speed",
    ],
    correctIndex: 3,
    explanation: "Traffic-calming measures help to keep vehicle speeds low in congested areas where there are pedestrians and children. A pedestrian is much more likely to survive a collision with a vehicle travelling at 20 mph than they are with a vehicle travelling at 40 mph.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2508",
    questionText: "What's the purpose of a catalytic converter?",
    options: [
    "To reduce fuel consumption",
    "To reduce the risk of fire",
    "To reduce harmful exhaust gases",
    "To reduce engine wear",
    ],
    correctIndex: 2,
    explanation: "Catalytic converters reduce a large percentage of harmful exhaust emissions. They work more efficiently when the engine has reached its normal working temperature.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2550",
    questionText: "When should tyre pressures be checked?",
    options: [
    "After any lengthy journey",
    "After travelling at high speed",
    "When tyres are hot",
    "When tyres are cold",
    ],
    correctIndex: 3,
    explanation: "Check the tyre pressures when the tyres are cold. This will give you a more accurate reading. The heat generated on a long journey will raise the pressure inside the tyre.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2637",
    questionText: "When will your vehicle use more fuel?",
    options: [
    "When its tyres are under-inflated",
    "When its tyres are of different makes",
    "When its tyres are over-inflated",
    "When its tyres are new",
    ],
    correctIndex: 0,
    explanation: "Check your tyre pressures frequently - normally once a week. If they're lower than those recommended by the manufacturer, there will be more 'rolling resistance'. The engine will have to work harder to overcome this, leading to increased fuel consumption.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2638",
    questionText: "How should you dispose of a used vehicle battery?",
    options: [
    "Bury it in your garden",
    "Put it in the dustbin",
    "Take it to a local authority disposal site",
    "Leave it on waste land",
    ],
    correctIndex: 2,
    explanation: "Batteries contain acid, which is hazardous, and they must be disposed of safely. This means taking them to an appropriate disposal site.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2641",
    questionText: "What's most likely to increase fuel consumption?",
    options: [
    "Poor steering control",
    "Accelerating around bends",
    "Staying in high gears",
    "Harsh braking and accelerating",
    ],
    correctIndex: 3,
    explanation: "Accelerating and braking gently and smoothly will help to save fuel and reduce wear on your vehicle. This makes it better for the environment too.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2689",
    questionText: "You're parked on the road at night. When must you use parking lights?",
    options: [
    "When there are continuous white lines in the middle of the road",
    "When the speed limit exceeds 30 mph",
    "When you're facing oncoming traffic",
    "When you're near a bus stop",
    ],
    correctIndex: 1,
    explanation: "When parking at night, park in the direction of the traffic. This will allow other road users to see the reflectors on the rear of your vehicle. Use your parking lights if the speed limit is over 30 mph.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2707",
    questionText: "How can you reduce the environmental harm caused by your motor vehicle?",
    options: [
    "Only use it for short journeys",
    "Do not service it",
    "Drive faster than normal",
    "Keep engine revs low",
    ],
    correctIndex: 3,
    explanation: "Engines that burn fossil fuels produce exhaust emissions that are harmful to health. The harder you make the engine work, the more emissions it will produce. Engines also use more fuel and produce higher levels of emissions when they're cold. Anything you can do to reduce your use of fossil fuels will help the environment.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2708",
    questionText: "What can cause excessive or uneven tyre wear?",
    options: [
    "A faulty gearbox",
    "A faulty braking system",
    "A faulty electrical system",
    "A faulty exhaust system",
    ],
    correctIndex: 1,
    explanation: "If you see that parts of the tread on your tyres are wearing before others, it may indicate a brake, suspension or wheel-alignment fault. Regular servicing will help to detect faults at an early stage and this will avoid the risk of minor faults becoming serious or even dangerous.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2800",
    questionText: "How can you plan your route before starting a long journey?",
    options: [
    "Check your vehicle handbook",
    "Ask your local garage",
    "Use a route planner on the internet",
    "Consult a travel agent",
    ],
    correctIndex: 2,
    explanation: "Various route planners are available on the internet. Most of them give you several options, allowing you to choose between the most direct route and quieter roads. They may also identify rest and fuel stops. Print off the directions and take them with you.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2802",
    questionText: "Why is it a good idea to plan your journey to avoid busy times?",
    options: [
    "You'll have an easier journey",
    "You'll have a more stressful journey",
    "Your journey time will be longer",
    "It will cause more traffic congestion",
    ],
    correctIndex: 0,
    explanation: "No-one likes to spend time in traffic queues. Try to avoid busy times related to school or work travel.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2805",
    questionText: "How will your journey be affected by travelling outside the busy times of day?",
    options: [
    "Your journey will use more fuel",
    "Your journey will take longer",
    "Your journey will be more hazardous",
    "Your journey will have fewer delays",
    ],
    correctIndex: 3,
    explanation: "If possible, avoid the early morning, late afternoon and early evening ‘rush hour’. Doing this should allow you to have a better journey, with fewer delays. This should help you to arrive at your destination feeling less stressed.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2813",
    questionText: "You plan your route before starting a journey. Why should you also plan an alternative route?",
    options: [
    "Your original route may be blocked",
    "Your maps may have different scales",
    "You may find you have to pay a congestion charge",
    "You may get held up by a tractor",
    ],
    correctIndex: 0,
    explanation: "It can be frustrating and worrying to find your planned route is blocked by roadworks or diversions. If you've planned an alternative, you'll feel less stressed and more able to concentrate fully on your driving or riding. If your original route is mostly on motorways, it’s a good idea to plan an alternative using non-motorway roads. Always carry a map with you just in case you need to refer to it.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2818",
    questionText: "You have to arrive on time for an appointment. How should you plan for the journey?",
    options: [
    "Allow plenty of time for the trip",
    "Plan to travel at busy times",
    "Avoid roads with the national speed limit",
    "Prevent other drivers from overtaking",
    ],
    correctIndex: 0,
    explanation: "Always allow plenty of time for your journey in case of unforeseen problems. Anything can happen; for example, punctures, breakdowns, road closures, diversions and delays. You'll feel less stressed and less inclined to take risks if you’re not ‘pushed for time’.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2830",
    questionText: "What can you expect if you drive using rapid acceleration and heavy braking?",
    options: [
    "Reduced pollution",
    "Increased fuel consumption",
    "Reduced exhaust emissions",
    "Increased road safety",
    ],
    correctIndex: 1,
    explanation: "Using the controls smoothly can reduce fuel consumption by about 15%, as well as reducing wear and tear on your vehicle. Plan ahead and anticipate changes of speed well in advance. This will reduce the need to accelerate rapidly or brake sharply.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "AB2940",
    questionText: "What could cause you to crash if the level is allowed to get too low?",
    options: [
    "Anti-freeze level",
    "Brake-fluid level",
    "Battery-water level",
    "Fuel level",
    ],
    correctIndex: 1,
    explanation: "You should carry out frequent checks on all fluid levels but particularly brake fluid. As the brake pads or shoes wear down, the brake-fluid level will drop. If it drops below the minimum mark on the fluid reservoir, air could enter the hydraulic system and lead to a loss of braking efficiency or even complete brake failure.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4430",
    questionText: "You’re driving along a motorway and switch on adaptive cruise control. What are you now allowed to do?",
    options: [
    "Remove your seatbelt",
    "Eat and drink",
    "Use your handheld mobile phone",
    "Check the road signs",
    ],
    correctIndex: 3,
    explanation: "When using advanced driver assistance systems (ADAS) you’re responsible for your vehicle and you need to stay in control of the systems. ADAS are not the same as self-driving functions so you must remain alert and be ready to intervene if the system does not work correctly.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4431",
    questionText: "You’re driving along a dual carriageway. This symbol is displayed on your dashboard. Which advanced driver assistance system (ADAS) is turned on?",
    options: [
    "Blind-spot assist",
    "Intelligent speed assist",
    "Lane-keep assist",
    "Traffic jam assist",
    ],
    correctIndex: 2,
    explanation: "Lane-keep assist is designed to stop your car from drifting out of the lane it’s in. You should consult your manufacturer’s guidance to make sure you’re familiar with the ADAS in your car and use them when its appropriate.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4432",
    questionText: "You’re driving a car with blind-spot monitoring function. What must you regularly check to make sure that the function will work properly?",
    options: [
    "That the sensors on the car are clean",
    "That the tyres are correctly inflated",
    "That the dash cam is securely attached",
    "That the car has a GPS signal",
    ],
    correctIndex: 0,
    explanation: "Blind-spot monitoring works using a system of sensors that alert you to objects in your blind-spots. The function only works correctly if you keep the sensors clean.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4433",
    questionText: "Which advanced driver assistance system (ADAS) is designed to actively prevent collisions?",
    options: [
    "Automotive night vision",
    "Driver drowsiness detection",
    "Advanced emergency braking system",
    "Cruise control",
    ],
    correctIndex: 2,
    explanation: "Advanced emergency braking uses sensors on the car to detect objects ahead. The system analyses whether you’re reacting and the collision risk. If it calculates that you’re likely to crash, the system applies the brakes to try to prevent a collision.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4434",
    questionText: "Modern cars are often fitted with a variety of technologies, called advanced driver assistance systems (ADAS). What is the main purpose of these systems?",
    options: [
    "To make the roads safer",
    "To reduce journey times",
    "To make driving easier",
    "To reduce environmental pollution",
    ],
    correctIndex: 0,
    explanation: "ADAS are designed to improve road safety. When used correctly, ADAS reduce the chances of you being involved in an incident. However, they are not self-driving features, you must continue to stay alert and be ready to take over at all times.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4435",
    questionText: "You’re driving along a quiet motorway. Which advanced driver assistance system (ADAS) is most likely to help you?",
    options: [
    "Traffic jam assist",
    "Automotive night vision",
    "Intelligent speed assist",
    "Lane-departure warning",
    ],
    correctIndex: 3,
    explanation: "Lane-departure warning alerts you that you’re about to leave your lane. If you’re drifting towards the lane markings, this can help you to keep your car positioned safely and prevent a collision.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4436",
    questionText: "You’re driving a car fitted with driver drowsiness detection. When will your car alert you to take a break?",
    options: [
    "After driving without a break for 4 hours",
    "When sensors identify behaviours that suggest you’re tired",
    "At pre-programmed times of day",
    "When you pass ‘take a break’ road signs",
    ],
    correctIndex: 1,
    explanation: "Driver drowsiness detection helps to prevent accidents by spotting patterns of behaviour that indicate you might be tired. When the sensors detect these patterns they alert you and suggest you take a break. This is designed to reduce the risk of you falling asleep while driving.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: "BB4437",
    questionText: "You’re driving an unfamiliar car fitted with advanced driver assistance systems (ADAS). Where would you find information about how to use the ADAS correctly?",
    options: [
    "Ask at your local garage",
    "In the manufacturer’s handbook",
    "In the Highway Code",
    "Ask a motoring association",
    ],
    correctIndex: 1,
    explanation: "Information about the ADAS fitted to a car can be found in the manufacturer’s handbook. Different manufacturers sometimes have their own names for the features and the technologies work in slightly different ways.",
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
];
