// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const safetyAndYourVehicleQuestions: Question[] = [
  {
    id: 'SVH_001',
    questionText: 'What is the minimum legal tyre tread depth for a car in the UK?',
    options: [
      '1mm across the full width of the tyre',
      '1.6mm across the central three-quarters of the tyre',
      '2mm across the central three-quarters of the tyre',
      '3mm across the full width of the tyre',
    ],
    correctIndex: 1,
    explanation:
      'The minimum legal tread depth is 1.6mm across the central three-quarters of the tread width, around the entire circumference of the tyre. Most tyre manufacturers recommend changing tyres at 3mm for safety.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_002',
    questionText: 'You want to check the engine oil level. When is the best time to do this?',
    options: [
      'Immediately after turning off the engine after a long drive',
      'When the engine is cold and the car is on level ground',
      'With the engine running at idle speed',
      'Only when the oil warning light illuminates',
    ],
    correctIndex: 1,
    explanation:
      'Oil should be checked when the engine is cold and the car is on level ground. This allows oil to drain back into the sump, giving an accurate reading on the dipstick between the minimum and maximum markers.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_003',
    questionText: 'When should you check your tyre pressures?',
    options: [
      'Immediately after a long motorway journey when tyres are warm',
      'When the tyres are cold, before a long journey',
      'Once a month regardless of temperature',
      'Only when the vehicle feels unstable at high speed',
    ],
    correctIndex: 1,
    explanation:
      'Tyre pressure should be checked when the tyres are cold, as driving increases pressure temporarily. Check before long journeys or at least once a month. Correct pressures are shown in the vehicle handbook and often inside the fuel cap.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_004',
    questionText: 'Your oil warning light comes on while driving. What should you do?',
    options: [
      'Continue to your destination as it is likely a sensor fault',
      'Stop as soon as safely possible and check the oil level',
      'Drive slowly at below 30mph to reduce engine damage',
      'Top up with oil at the next petrol station without stopping',
    ],
    correctIndex: 1,
    explanation:
      'An illuminated oil warning light indicates low oil pressure, which can cause serious engine damage within seconds. Stop safely as soon as possible, switch off the engine, and check the oil level before proceeding.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_005',
    questionText: 'What is the purpose of an Anti-lock Braking System (ABS)?',
    options: [
      'It shortens stopping distance on all road surfaces',
      'It prevents wheels locking under heavy braking, allowing the driver to maintain steering control',
      'It automatically applies maximum braking force in an emergency',
      'It reduces wear on brake pads by limiting braking force',
    ],
    correctIndex: 1,
    explanation:
      'ABS prevents wheels from locking during emergency braking. Locked wheels cause loss of steering. With ABS, you can apply maximum brake pressure and still steer around obstacles. ABS does not always shorten stopping distance on loose surfaces.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_006',
    questionText: 'You are driving and notice that steering requires much more effort than usual. What is the most likely cause?',
    options: [
      'The front tyres are over-inflated',
      'Power steering failure',
      'The wheel alignment is slightly out',
      'The road surface is causing extra resistance',
    ],
    correctIndex: 1,
    explanation:
      'A sudden increase in steering effort usually indicates power steering failure. You can still steer the vehicle but will need much greater physical force. Slow down gradually and get the fault investigated before driving further.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_007',
    questionText: 'When should your vehicle first have an MOT test?',
    options: [
      'After one year from first registration',
      'After two years from first registration',
      'After three years from first registration',
      'After four years from first registration',
    ],
    correctIndex: 2,
    explanation:
      'A vehicle must have its first MOT test when it is three years old. After that, an annual MOT is required. Vehicles manufactured before a certain date may be exempt from MOT as historic vehicles.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_008',
    questionText: 'Where should new tyres be fitted if you are only replacing two?',
    options: [
      'On the front axle, to improve steering response',
      'On the rear axle, to reduce the risk of oversteer',
      'On whichever axle has the most worn tyres',
      'It does not matter which axle',
    ],
    correctIndex: 1,
    explanation:
      'New tyres should be fitted to the rear axle. Rear tyre failure causes oversteer, which is much harder to control than understeer caused by front tyre failure. Fitting new tyres to the rear improves overall stability.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_009',
    questionText: 'When using ABS brakes in an emergency, what is the correct technique?',
    options: [
      'Pump the brake pedal rapidly to avoid wheel lock',
      'Apply firm, continuous pressure to the brake pedal and steer as needed',
      'Apply moderate pressure only - never stamp on the brake pedal',
      'Press the brake pedal firmly and hold the steering wheel straight',
    ],
    correctIndex: 1,
    explanation:
      'With ABS, apply firm, continuous pressure to the brake pedal - do not pump it. The ABS system modulates brake pressure automatically to prevent wheel lock. You can continue to steer while braking firmly.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_010',
    questionText: 'What does a flashing brake warning light on your dashboard most likely indicate?',
    options: [
      'The brake fluid is overheating after sustained use',
      'The brake fluid level is low or there is a fault with the braking system',
      'The ABS is currently active',
      'The handbrake is partially engaged',
    ],
    correctIndex: 1,
    explanation:
      'A brake warning light usually indicates low brake fluid or a fault in the braking system. This is a serious safety issue. Do not continue driving - stop safely, check the fluid level, and seek professional assistance before driving further.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_011',
    questionText: 'Why is it important to check your windscreen wipers regularly?',
    options: [
      'Worn wipers can scratch the windscreen and reduce visibility in rain',
      'Worn wipers increase fuel consumption significantly',
      'Faulty wipers are an immediate MOT failure and carry a fine',
      'Wipers affect the aerodynamics and top speed of the vehicle',
    ],
    correctIndex: 0,
    explanation:
      'Worn or damaged wiper blades leave smears and miss areas of the windscreen, reducing visibility in rain. In heavy rain, visibility can be reduced to near zero with faulty wipers. Wiper condition is checked as part of the MOT.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_012',
    questionText: 'What is the purpose of the vehicle\'s coolant/antifreeze?',
    options: [
      'It lubricates the engine cylinders during cold starts',
      'It regulates engine temperature and prevents freezing in winter',
      'It cleans fuel injectors and improves combustion efficiency',
      'It protects brake lines from corrosion',
    ],
    correctIndex: 1,
    explanation:
      'Coolant (antifreeze) circulates through the engine to remove heat and prevent overheating. In winter it also prevents the water in the cooling system from freezing, which could crack the engine block. The level should be checked regularly.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_013',
    questionText: 'Your car starts to pull to one side under braking. What does this most likely indicate?',
    options: [
      'The steering alignment is out - a normal wear item',
      'A possible brake fault such as a seized caliper or uneven pad wear',
      'One of the front tyres is under-inflated',
      'The road surface is cambered heavily to one side',
    ],
    correctIndex: 1,
    explanation:
      'Pulling to one side when braking is a sign of unequal braking force, often caused by a seized brake caliper, worn brake pads on one side, or contaminated brake discs. This is a safety-critical fault that must be investigated immediately.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_014',
    questionText: 'What is the legal requirement regarding vehicle defects you discover after an MOT certificate has been issued?',
    options: [
      'You can drive the vehicle freely until the MOT expires',
      'You are responsible for keeping the vehicle in a roadworthy condition at all times',
      'Defects discovered after an MOT are covered for 30 days',
      'You must return the vehicle to the MOT station within a week',
    ],
    correctIndex: 1,
    explanation:
      'An MOT certificate confirms a vehicle met minimum safety standards at the time of test. The driver is legally responsible for ensuring their vehicle is roadworthy at all times. A defect discovered after the MOT must be repaired before driving.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_015',
    questionText: 'What should you do if you notice your vehicle\'s headlights are not working properly before setting off at night?',
    options: [
      'Drive carefully with hazard lights on until you can reach a garage',
      'Do not drive the vehicle until the headlights have been repaired',
      'Drive at reduced speed keeping to well-lit roads only',
      'Use fog lights as a substitute for headlights',
    ],
    correctIndex: 1,
    explanation:
      'Driving at night without properly functioning headlights is illegal and extremely dangerous. You must not drive the vehicle until the fault is repaired. Fog lights are not a substitute - they are designed for low-visibility conditions, not normal night driving.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_016',
    questionText: 'You notice a bulge in the sidewall of one of your tyres. What should you do?',
    options: [
      'Monitor it and replace the tyre at your next service',
      'Replace the tyre immediately - a bulge indicates internal structural damage',
      'Re-inflate the tyre to maximum pressure to stabilise the bulge',
      'Only replace it if the bulge is on the load-bearing section of the tread',
    ],
    correctIndex: 1,
    explanation: 'A bulge in a tyre sidewall indicates that the internal cords have been damaged, likely from an impact. The tyre could fail suddenly and without warning. It must be replaced immediately - do not drive on a tyre with a bulge in the sidewall.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_017',
    questionText: 'You notice blue smoke coming from your exhaust. What does this typically indicate?',
    options: [
      'The engine is running normally on a cold morning',
      'The engine is burning oil',
      'The catalytic converter is failing',
      'The fuel mixture is running too rich',
    ],
    correctIndex: 1,
    explanation: 'Blue smoke from the exhaust indicates that engine oil is being burned in the combustion chamber. This suggests worn piston rings, valve seals, or other internal engine wear. Have the vehicle inspected promptly, and check the oil level regularly in the meantime.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_018',
    questionText: 'Your engine temperature gauge shows the needle in the red zone. What should you do?',
    options: [
      'Turn the heater on full to help cool the engine',
      'Stop safely and switch off the engine immediately - do not remove the radiator cap',
      'Drive to the nearest garage as quickly as possible',
      'Reduce speed and monitor the temperature for five minutes',
    ],
    correctIndex: 1,
    explanation: 'An engine in the red zone on the temperature gauge is overheating. Continuing to drive risks severe and expensive engine damage. Stop safely, turn off the engine, and wait for it to cool before investigating. Never remove the radiator cap from a hot engine.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_019',
    questionText: 'What does white smoke from the exhaust that persists once the engine is warm indicate?',
    options: [
      'Normal behaviour on cold mornings',
      'Coolant entering the combustion chamber, possibly due to a blown head gasket',
      'The exhaust is wet from rain',
      'The engine oil level is low',
    ],
    correctIndex: 1,
    explanation: 'A small amount of white smoke on cold starts is normal condensation. Persistent white smoke once the engine is warm suggests coolant is entering the combustion chamber - often due to a blown head gasket. This is a serious fault requiring immediate attention.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_020',
    questionText: 'What does a battery warning light on the dashboard indicate while driving?',
    options: [
      'The battery is nearly flat and needs recharging',
      'The alternator is not charging the battery - the vehicle may lose power soon',
      'The battery terminals need cleaning',
      'The battery is fully charged and no action is required',
    ],
    correctIndex: 1,
    explanation: 'A battery warning light while driving usually means the alternator (which charges the battery as the engine runs) has failed. The vehicle will drain its battery and eventually lose all electrical functions. Get the vehicle checked as soon as possible.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_021',
    questionText: 'How should you clear a misted (fogged-up) windscreen quickly?',
    options: [
      'Use windscreen wipers on the lowest setting',
      'Blow air from the heater at the windscreen and use the air conditioning or heated rear screen',
      'Open all windows until the glass clears',
      'Apply screenwash to the outside to draw condensation off',
    ],
    correctIndex: 1,
    explanation: 'The most effective method to demist is to direct warm, dry air from the heater at the windscreen. Turning on air conditioning removes moisture from the air and speeds demisting. The heated rear screen tackles the back window. Only drive when you have full, clear visibility.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_022',
    questionText: 'You accidentally put petrol into a diesel engine car. What should you do?',
    options: [
      'Drive gently - petrol will burn off in the diesel engine without damage',
      'Do not start the engine - contact a recovery service immediately',
      'Add more diesel to dilute the petrol before driving',
      'Only a small amount of petrol is problematic - up to 10% is acceptable',
    ],
    correctIndex: 1,
    explanation: 'Petrol in a diesel engine can cause severe damage to fuel injectors and the fuel pump, which rely on diesel\'s lubricating properties. Do not start the engine. Have the fuel tank professionally drained before driving. It is one of the most common and expensive misfuelling mistakes.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_023',
    questionText: 'When adjusting your seat before driving, what is the correct position for the headrest?',
    options: [
      'The headrest should sit below the level of your ears',
      'The headrest should be positioned so the top aligns with the top of your head',
      'The headrest position does not affect safety',
      'The headrest should be removed to allow a better view through the rear window',
    ],
    correctIndex: 1,
    explanation: 'The headrest should be positioned so its top is level with the top of your head. This provides maximum protection against whiplash in a rear-end collision. A headrest set too low provides little protection and may actually increase whiplash injury.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_024',
    questionText: 'What should you check on your tyres beyond tread depth?',
    options: [
      'Only tread depth matters - condition and age are secondary',
      'Tread depth, tyre pressure, and condition (cuts, bulges, embedded objects)',
      'Just pressure and tread depth - the rest is checked at service intervals',
      'Age of the tyre as printed on the sidewall is the only important factor',
    ],
    correctIndex: 1,
    explanation: 'A complete tyre check involves tread depth (minimum 1.6mm), correct tyre pressure, and a visual inspection for cuts, bulges, embedded objects, and sidewall damage. Cracked or aged rubber is also a concern even if tread is adequate.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_025',
    questionText: 'How should you check that your brake lights are working when driving alone?',
    options: [
      'Press the brake pedal firmly and watch for shadows on the road behind',
      'Reverse close to a wall, apply brakes, and check for red reflections on the wall',
      'Only a garage can check brake lights safely',
      'Apply the handbrake instead - it activates the same bulbs',
    ],
    correctIndex: 1,
    explanation: 'To check brake lights alone, reverse close to a garage door, wall, or reflective surface at night, then apply the brakes. You should see a red glow reflected back. Alternatively, ask someone to stand behind while you press the brake pedal.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_026',
    questionText: 'You are about to drive in very cold weather. What fluid level is especially important to check?',
    options: [
      'Engine oil - cold weather thickens oil and increases consumption',
      'Windscreen washer fluid - it must contain antifreeze additive to prevent freezing in the washer system',
      'Brake fluid - cold weather makes it thicker and less effective',
      'Power steering fluid - cold weather requires more fluid pressure',
    ],
    correctIndex: 1,
    explanation: 'In cold weather, plain water in the screenwash reservoir will freeze, blocking the jets and potentially cracking the reservoir. Always use a proper screenwash fluid with antifreeze properties appropriate for the forecast temperature.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_027',
    questionText: 'What is the purpose of the engine management light (often shaped like an engine outline)?',
    options: [
      'It indicates the engine oil needs changing at the next service',
      'It warns of a fault detected by the engine control unit - requires investigation',
      'It indicates the engine is running efficiently',
      'It only illuminates when the vehicle needs an emissions test',
    ],
    correctIndex: 1,
    explanation: 'The engine management light (EML) illuminates when the ECU detects a fault in the engine or emissions system. If it is steady, have it checked soon. If it is flashing, the fault is more serious and you should reduce speed and seek advice promptly.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_028',
    questionText: 'What does black smoke from the exhaust typically indicate?',
    options: [
      'The engine is burning oil due to worn rings',
      'The engine is running too rich - too much fuel relative to air',
      'The exhaust system is condensing water on a cold morning',
      'The catalytic converter has failed',
    ],
    correctIndex: 1,
    explanation: 'Black smoke indicates an overly rich fuel mixture - too much fuel and too little air is being burned. Common causes include a faulty injector, clogged air filter, or a diesel particulate filter (DPF) issue. It also indicates wasted fuel and high emissions.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_029',
    questionText: 'You hear a grinding noise when applying the brakes. What does this most likely indicate?',
    options: [
      'The brake pads have worn through to the metal backing plate',
      'The brake fluid needs topping up',
      'The ABS system is activating unnecessarily',
      'The handbrake cable is too tight',
    ],
    correctIndex: 0,
    explanation: 'Grinding when braking usually means the brake pad friction material has worn away completely, and metal is contacting the brake disc. This seriously reduces braking performance and will damage the disc. Have brakes inspected and repaired immediately.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_030',
    questionText: 'What is the function of a catalytic converter?',
    options: [
      'It increases fuel efficiency by optimising the fuel/air mixture',
      'It reduces harmful exhaust emissions by converting them to less harmful gases',
      'It acts as a silencer to reduce exhaust noise',
      'It prevents fuel vapour from escaping when the engine is off',
    ],
    correctIndex: 1,
    explanation: 'A catalytic converter contains precious metals that promote chemical reactions converting harmful exhaust gases (carbon monoxide, nitrogen oxides, hydrocarbons) into less harmful substances (carbon dioxide, nitrogen, water vapour). Petrol cars must use unleaded fuel to protect the catalyst.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_031',
    questionText: 'A chip or crack in your windscreen is in your line of vision. Is it legal to drive?',
    options: [
      'Yes, as long as the crack does not extend to the edge of the glass',
      'No - a crack or chip in the driver\'s critical zone (an area around the wiper sweep) is an MOT failure and is illegal to drive with',
      'Yes, as long as it is less than 10mm in size',
      'Only if the windscreen is otherwise clean and you can see clearly',
    ],
    correctIndex: 1,
    explanation: 'A windscreen chip or crack in Zone A (a 290mm band in front of the driver, within the wiper sweep) larger than 10mm, or a crack of any size in the driver\'s primary line of vision, is an MOT failure. A crack anywhere exceeding 40mm in Zone B is also a failure. Get chips repaired quickly - they spread.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_032',
    questionText: 'What should you do before driving a vehicle you have not driven before, such as a hire car?',
    options: [
      'Drive it for a few miles to familiarise yourself before checking anything',
      'Adjust the seat, mirrors, and headrest, and locate all key controls before setting off',
      'Only check the fuel level and mirror positions',
      'It is not necessary to make any adjustments if you are an experienced driver',
    ],
    correctIndex: 1,
    explanation: 'Before driving any unfamiliar vehicle, adjust the seat, steering wheel (if adjustable), mirrors, and headrest. Locate lights, wipers, hazard lights, and horn controls. This preparation prevents dangerous fumbling for controls while moving.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_033',
    questionText: 'Your vehicle\'s power steering fails while driving. What is the main effect?',
    options: [
      'The steering wheel will lock completely',
      'The steering will feel very heavy and require significantly more effort',
      'The wheels will not respond to steering inputs',
      'The vehicle will automatically steer straight ahead',
    ],
    correctIndex: 1,
    explanation: 'If power steering fails, you can still steer but it requires much more physical effort, particularly at low speeds. Slow down gently, be aware of the change in handling, and get the fault repaired promptly. Never grip the wheel too tightly - stay calm and maintain control.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_034',
    questionText: 'How often should you check your engine oil level?',
    options: [
      'Only when the oil warning light comes on',
      'At least weekly or before any long journey',
      'Every 3,000 miles regardless of the service interval',
      'Only at each service interval as specified by the manufacturer',
    ],
    correctIndex: 1,
    explanation: 'Engine oil should be checked at least once a week and before any long journey. Oil levels can drop between service intervals due to consumption, leaks, or burning. Checking regularly catches problems early and prevents expensive engine damage.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_035',
    questionText: 'What is the purpose of a TPMS (Tyre Pressure Monitoring System) warning light?',
    options: [
      'It warns when tyre tread depth is approaching the legal minimum',
      'It alerts the driver when one or more tyre pressures have fallen significantly below the correct level',
      'It monitors for tyre damage such as punctures or sidewall bulges',
      'It measures road grip and adjusts traction control accordingly',
    ],
    correctIndex: 1,
    explanation: 'TPMS continuously monitors tyre pressure and triggers a warning light when pressure drops significantly below the recommended level. It does not monitor tread depth or damage. Always check pressures manually with a gauge when the TPMS light illuminates.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_036',
    questionText: 'What should you do if your accelerator pedal sticks while driving?',
    options: [
      'Steer towards the kerb and apply the handbrake',
      'Knock it free with your foot, then switch off the ignition if necessary and brake firmly',
      'Put the vehicle in neutral and coast to a stop',
      'Depress the clutch and apply both footbrake and handbrake simultaneously',
    ],
    correctIndex: 1,
    explanation: 'If the accelerator sticks, try to free it by tapping it, then put the vehicle in neutral if needed to disengage the drive. Apply the footbrake to slow down. Switch off the ignition as a last resort, but be aware this may engage steering lock on some vehicles. Brake firmly and safely.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_037',
    questionText: 'Which of the following is a key pre-drive check covered by the DVSA\'s "POWER" routine?',
    options: [
      'Petrol, Oil, Water, Electrical, Rubber',
      'Pressure, Oil, Wipers, Engine, Reflectors',
      'Position, Observation, Warning, Engine, Radar',
      'Pedals, Oil, Windscreen, Engine, Road',
    ],
    correctIndex: 0,
    explanation: 'POWER is a handy checklist: Petrol (fuel), Oil (engine oil level), Water (coolant and screenwash), Electrics (lights, indicators, battery), Rubber (tyres). Completing this check before a journey identifies potential problems before they cause breakdowns or accidents.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_038',
    questionText: 'When is a vehicle exempt from requiring an MOT certificate?',
    options: [
      'When it is under 5 years old',
      'When it is a historic vehicle manufactured over 40 years ago and has not been substantially changed',
      'When it is kept off public roads and has a SORN declaration',
      'When it has been recently serviced at a manufacturer-approved garage',
    ],
    correctIndex: 1,
    explanation: 'Vehicles manufactured over 40 years ago and not substantially changed (in terms of engine, axles, or bodywork) are currently exempt from the annual MOT test. SORN vehicles may also be exempt but must not be driven on public roads. All other vehicles over 3 years old require an annual MOT.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_039',
    questionText: 'What should you do if you notice your vehicle has a slow puncture?',
    options: [
      'Drive to the nearest garage at normal speed, topping up air at fuel stations if needed',
      'Stop safely, change to the spare tyre or call for assistance, and do not drive on a tyre that has lost significant pressure',
      'Inflate the tyre to maximum pressure to last the journey',
      'Reduce speed to 20mph and continue to your destination',
    ],
    correctIndex: 1,
    explanation: 'A tyre with a slow puncture will eventually fail. Driving on a significantly deflated tyre risks the tyre coming off the rim, causing sudden loss of control. Stop safely, change the wheel, use a repair kit if provided, or call for roadside assistance.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_040',
    questionText: 'You are fitting a child seat in the front passenger seat of a car that has a passenger airbag. What must you do?',
    options: [
      'Fit the seat normally - airbags are compatible with all child seats',
      'Deactivate the passenger airbag before fitting a rear-facing child seat in the front',
      'Only fit forward-facing child seats in the front - rear-facing seats are banned there',
      'Adjust the airbag to low-power mode using the vehicle\'s settings menu',
    ],
    correctIndex: 1,
    explanation: 'A rear-facing child seat must never be used in a seat protected by an active frontal airbag. The airbag inflates with enormous force and can cause fatal injuries to a child. Either deactivate the airbag (if the vehicle has this facility) or place the rear-facing seat in the back.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_041',
    questionText: 'When are you legally required to report a defect discovered during a walk-around check before driving a goods vehicle professionally?',
    options: [
      'Only defects affecting brakes, steering, or lights',
      'All defects must be reported to the vehicle operator before driving',
      'Only defects that would cause an immediate MOT failure',
      'Only if the defect is visible from outside the vehicle',
    ],
    correctIndex: 1,
    explanation: 'Professional drivers of goods vehicles and passenger-carrying vehicles are required to conduct a pre-use inspection and report any defects to the operator before driving. All defects must be recorded. The operator is responsible for ensuring they are rectified before the vehicle goes on the road.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_042',
    questionText: 'Your indicators are flashing too quickly. What does this usually indicate?',
    options: [
      'The indicators are working correctly and the flash rate is normal',
      'One of the indicator bulbs has failed',
      'The indicator relay needs replacing',
      'The battery is low',
    ],
    correctIndex: 1,
    explanation: 'Indicators that flash unusually fast typically indicate that one of the bulbs in the indicator circuit has failed. The circuit detects increased resistance with a failed bulb and speeds up the flash rate as a warning to the driver. Check and replace the faulty bulb.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_043',
    questionText: 'What is the purpose of the vehicle\'s handbrake in normal driving?',
    options: [
      'To slow the vehicle in an emergency when the footbrake fails',
      'To hold the vehicle stationary when parked or stopped',
      'To provide additional braking power when descending steep hills',
      'To assist turning at low speed by braking the rear wheels',
    ],
    correctIndex: 1,
    explanation: 'The handbrake (or parking brake) is designed to hold the vehicle stationary when parked or stopped. On most modern cars it applies only to the rear wheels and should not be used as an emergency brake - this could cause the rear wheels to lock and lead to loss of control.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_044',
    questionText: 'You notice your fuel consumption has increased significantly without any change in driving style. What might this indicate?',
    options: [
      'Seasonal variation - fuel consumption is always higher in winter',
      'A potential engine, tyre, or brake fault worth investigating',
      'The fuel quality at the last station was poor',
      'It is normal for fuel consumption to vary by up to 30%',
    ],
    correctIndex: 1,
    explanation: 'A significant unexplained increase in fuel consumption can indicate under-inflated tyres (increasing rolling resistance), a dragging brake, a dirty air filter, a faulty sensor, or other mechanical issues. It is worth having the vehicle checked if consumption rises without obvious cause.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_045',
    questionText: 'What is the legal position on driving a vehicle you know to have a dangerous defect?',
    options: [
      'You may drive it a short distance to a garage if no alternative exists',
      'You must not drive the vehicle - doing so is an offence under the Road Traffic Act',
      'You may drive it if you drive slowly and notify your insurer',
      'It is only an offence if the defect is visible to an observer outside the vehicle',
    ],
    correctIndex: 1,
    explanation: 'Knowingly driving a vehicle in a dangerous condition is an offence. The Road Traffic Act requires all vehicles to be maintained in a roadworthy condition at all times. If a vehicle has a known dangerous defect, arrange alternative transport or recovery.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_046',
    questionText: 'How should you test whether your brakes are working normally at the start of a journey?',
    options: [
      'Brake hard from 30mph to check stopping distance',
      'Apply the brakes lightly while driving slowly and check the car stops smoothly and in a straight line',
      'Only test brakes if you suspect a fault - testing them unnecessarily wears the pads',
      'Check only by depressing the pedal while stationary',
    ],
    correctIndex: 1,
    explanation: 'At the start of a journey in a quiet area, apply the brakes gently while moving slowly to check they respond promptly, the vehicle stops in a straight line, and the pedal feels firm. Unusual pulls or sponginess indicate a fault that should be investigated.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_047',
    questionText: 'When is a spare tyre not legally required to be carried?',
    options: [
      'When the vehicle is a new model manufactured after 2012',
      'A spare tyre is not a legal requirement - but your vehicle must have a way to deal with a puncture such as run-flat tyres or a repair kit',
      'When the vehicle is under 2 years old',
      'When the vehicle weighs less than 1,500 kg',
    ],
    correctIndex: 1,
    explanation: 'There is no legal requirement to carry a spare tyre in the UK. Many modern vehicles come with run-flat tyres or a puncture repair kit instead. However, you must have some means of dealing with a puncture, and a standard spare is the most reliable option.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
  {
    id: 'SVH_048',
    questionText: 'What does it mean if the brake pedal feels spongy or goes further towards the floor than normal?',
    options: [
      'The brake pads are wearing and will need replacement soon',
      'There may be air in the brake fluid or the fluid level is low - a serious safety fault',
      'The brake servo is working harder than normal - this is acceptable',
      'Cold weather causes the brake fluid to contract slightly, causing this sensation',
    ],
    correctIndex: 1,
    explanation: 'A spongy brake pedal or excessive travel indicates air in the hydraulic braking system or a loss of brake fluid. This seriously compromises braking efficiency. Do not drive the vehicle - get it inspected and repaired immediately.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 2,
  },
  {
    id: 'SVH_049',
    questionText: 'What check should you carry out on your lights during daylight before an evening journey?',
    options: [
      'No check is needed - warning lights will illuminate if a bulb fails',
      'Walk around the vehicle to check all lights illuminate and both indicators work correctly on each side',
      'Only check headlights - other lights are checked automatically by the vehicle ECU',
      'Check only if you will be driving after 10pm',
    ],
    correctIndex: 1,
    explanation: 'Walk around the vehicle before any evening journey to check headlights (dipped and main beam), sidelights, indicators front and rear, brake lights, hazard lights, and number plate illumination. A failed light you discover at home is much easier to fix than being stopped by police.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 1,
  },
  {
    id: 'SVH_050',
    questionText: 'What does a diesel particulate filter (DPF) do, and what must you do to maintain it?',
    options: [
      'It filters water from diesel fuel - replace the filter every 30,000 miles',
      'It captures soot particles from exhaust gases - it requires regular motorway driving or active regeneration to burn off accumulated soot',
      'It prevents fuel vapour from entering the engine bay - service annually',
      'It reduces fuel consumption by optimising combustion - no maintenance needed',
    ],
    correctIndex: 1,
    explanation: 'A DPF captures soot particles from diesel exhaust. It periodically burns off (regenerates) the soot at high temperatures, which requires sustained motorway speeds. Frequent short urban journeys can clog the DPF. A blocked DPF warning light requires prompt attention - ignoring it can result in an expensive replacement.',
    topicCategory: TopicCategory.SafetyAndYourVehicle,
    difficulty: 3,
  },
];
