// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const safetyMarginsQuestions: Question[] = [
  {
    id: 'SAF_001',
    questionText: 'What is the total stopping distance (thinking + braking) for a car travelling at 30mph in good conditions?',
    options: [
      '12 metres (40 feet)',
      '23 metres (75 feet)',
      '36 metres (120 feet)',
      '53 metres (175 feet)',
    ],
    correctIndex: 1,
    explanation:
      'At 30mph, thinking distance is 9m and braking distance is 14m, giving a total of 23m (75ft). These figures assume dry roads and good tyres.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_002',
    questionText: 'How does wet weather affect your braking distance compared to dry conditions?',
    options: [
      'It stays the same if you have good tyres',
      'It increases by roughly 25%',
      'It at least doubles',
      'It triples on modern roads',
    ],
    correctIndex: 2,
    explanation:
      'In wet conditions braking distances at least double. Reduced tyre grip means you should leave at least twice the normal gap and approach hazards much more gently.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_003',
    questionText: 'What is the total stopping distance at 70mph in good dry conditions?',
    options: [
      '53 metres (175 feet)',
      '73 metres (240 feet)',
      '96 metres (315 feet)',
      '120 metres (396 feet)',
    ],
    correctIndex: 2,
    explanation:
      'At 70mph, thinking distance is 21m and braking distance is 75m - a total of 96m (315ft). This is roughly 24 car lengths, demonstrating why tailgating at motorway speeds is so dangerous.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_004',
    questionText: 'In icy conditions, how much greater can your braking distance be compared to a dry road?',
    options: [
      'Twice as long',
      'Four times as long',
      'Six times as long',
      'Up to ten times as long',
    ],
    correctIndex: 3,
    explanation:
      'The Highway Code states that on icy roads braking distances can be up to ten times longer than in dry conditions. Extra caution, gentle inputs, and much lower speeds are essential.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_005',
    questionText: 'What is the "two-second rule" when following another vehicle?',
    options: [
      'Leave at least two car lengths between you and the vehicle ahead',
      'After the vehicle ahead passes a fixed point, at least two seconds must pass before you reach that same point',
      'Apply your brakes two seconds before reaching a hazard',
      'Leave two seconds when changing lanes on a motorway',
    ],
    correctIndex: 1,
    explanation:
      'The two-second rule gives a minimum safe following distance in dry conditions. In wet weather this should be at least four seconds. Choose a fixed object (bridge, sign) and count "only a fool breaks the two-second rule".',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_006',
    questionText: 'What is the total stopping distance at 50mph in good dry conditions?',
    options: [
      '36 metres (118 feet)',
      '53 metres (175 feet)',
      '73 metres (240 feet)',
      '96 metres (315 feet)',
    ],
    correctIndex: 1,
    explanation:
      'At 50mph, thinking distance is 15m and braking distance is 38m, giving a total of 53m (175ft). Doubling your speed from 30 to 60 mph more than doubles your braking distance.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_007',
    questionText: 'What is the thinking distance when travelling at 60mph in good conditions?',
    options: [
      '12 metres',
      '15 metres',
      '18 metres',
      '21 metres',
    ],
    correctIndex: 2,
    explanation:
      'Thinking distance at 60mph is 18 metres. The rule is straightforward: speed in mph = thinking distance in feet, or roughly 0.3m per mph. This assumes a typical reaction time of about 0.67 seconds.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_008',
    questionText: 'Which of these factors increases your thinking distance?',
    options: [
      'Cold weather and low temperatures',
      'Tiredness, alcohol, drugs, or distraction',
      'Driving a heavier vehicle',
      'Having worn tyres',
    ],
    correctIndex: 1,
    explanation:
      'Thinking distance is determined by reaction time. Anything that slows your reaction - tiredness, alcohol, drugs, distraction, or illness - increases thinking distance and therefore total stopping distance.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_009',
    questionText: 'You are driving in thick fog. What is the most important adjustment to make?',
    options: [
      'Keep close to the vehicle ahead so you can follow its tail lights',
      'Switch on hazard warning lights so others can see you',
      'Slow down significantly and increase your following distance',
      'Use full-beam headlights to see further ahead',
    ],
    correctIndex: 2,
    explanation:
      'In fog, visibility is reduced and therefore you need more time to react. Slow down and increase your following distance. Full-beam headlights cause dazzling glare in fog - use dipped headlights and front/rear fog lights when visibility drops below 100 metres.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_010',
    questionText: 'What is aquaplaning and what is the correct response if it occurs?',
    options: [
      'The car vibrating on a motorway - accelerate through it',
      'Tyres losing contact with the road surface due to a film of water - ease off the accelerator gently',
      'Windscreen misting caused by rain - use the demister fan',
      'Loss of steering caused by flooded brakes - apply the handbrake',
    ],
    correctIndex: 1,
    explanation:
      'Aquaplaning occurs when a layer of water builds up between the tyres and road surface, causing a loss of grip and steering. Ease off the accelerator gently and do not brake or steer sharply until grip is restored.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_011',
    questionText: 'How does alcohol consumption affect stopping distance?',
    options: [
      'It has no effect on stopping distance, only on steering accuracy',
      'It increases braking distance only, not thinking distance',
      'It can significantly increase thinking distance by slowing reaction times',
      'It reduces stopping distance by making drivers more focused',
    ],
    correctIndex: 2,
    explanation:
      'Alcohol slows reaction times, which increases thinking distance and therefore total stopping distance. Even small amounts of alcohol affect the speed at which the brain processes information and sends signals to the muscles.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_012',
    questionText: 'What is the total stopping distance at 20mph in good dry conditions?',
    options: [
      '6 metres (20 feet)',
      '12 metres (40 feet)',
      '18 metres (59 feet)',
      '23 metres (75 feet)',
    ],
    correctIndex: 1,
    explanation:
      'At 20mph, thinking distance is 6m and braking distance is 6m, giving a total of 12m (40ft). This is why 20mph zones near schools and residential areas significantly reduce the severity of collisions with pedestrians.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_013',
    questionText: 'You are following a large lorry on a wet motorway. What following distance should you aim for?',
    options: [
      'The same as in dry conditions - 2 seconds',
      'At least 4 seconds, as wet roads at least double braking distances',
      '1 second, so you can react before the lorry gets too far away',
      '10 seconds, as lorries take much longer to stop than cars',
    ],
    correctIndex: 1,
    explanation:
      'In wet conditions, braking distances at least double. The standard two-second rule becomes a minimum four-second rule. Behind a large vehicle, your view ahead is also obscured, requiring even more caution.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_014',
    questionText: 'What is the main danger of following the vehicle ahead too closely (tailgating)?',
    options: [
      'It can cause overheating of your front brakes due to restricted airflow',
      'You will not have enough stopping distance if the vehicle ahead brakes suddenly',
      'It confuses other drivers and may cause them to change lanes unexpectedly',
      'Your headlights will dazzle the driver in front through their mirrors',
    ],
    correctIndex: 1,
    explanation:
      'Tailgating is one of the main causes of rear-end collisions. If the vehicle ahead brakes suddenly, you may not have enough time and distance to stop safely. Always maintain at least the two-second gap (four seconds in wet conditions).',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_015',
    questionText: 'What is the total stopping distance at 60mph in good dry conditions?',
    options: [
      '53 metres (175 feet)',
      '73 metres (240 feet)',
      '85 metres (280 feet)',
      '96 metres (315 feet)',
    ],
    correctIndex: 1,
    explanation:
      'At 60mph, thinking distance is 18m and braking distance is 55m - a total of 73m (240ft). Note that braking distance increases with the square of speed, so doubling speed quadruples braking distance.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_016',
    questionText: 'What is the total stopping distance at 40mph in good dry conditions?',
    options: [
      '23 metres (75 feet)',
      '36 metres (118 feet)',
      '53 metres (175 feet)',
      '73 metres (240 feet)',
    ],
    correctIndex: 1,
    explanation: 'At 40mph, thinking distance is 12m and braking distance is 24m, giving a total of 36m (118ft). Stopping distance does not increase in a straight line with speed - braking distance increases with the square of speed.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_017',
    questionText: 'How does doubling your speed from 30mph to 60mph affect your braking distance?',
    options: [
      'It doubles the braking distance',
      'It triples the braking distance',
      'It quadruples the braking distance',
      'It increases braking distance by 50%',
    ],
    correctIndex: 2,
    explanation: 'Braking distance increases with the square of speed. Doubling speed from 30 to 60 mph therefore quadruples the braking distance (from approximately 14m to 55m). This is why speed has such a dramatic effect on crash severity.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_018',
    questionText: 'What is the minimum legal tyre tread depth across the central three-quarters of the tyre for cars?',
    options: [
      '1mm',
      '1.6mm',
      '2mm',
      '3mm',
    ],
    correctIndex: 1,
    explanation: 'The minimum legal tread depth for cars (and motorcycles over 50cc) is 1.6mm across the central three-quarters of the tread around the entire circumference. Below this level, wet-weather grip is seriously reduced and the penalty is a fine and penalty points.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_019',
    questionText: 'How much space should you give when overtaking a cyclist on a road with a 30 mph limit?',
    options: [
      'At least 0.5 metres clearance',
      'At least 1.5 metres clearance',
      'At least 2 metres clearance',
      'There is no minimum - use common sense',
    ],
    correctIndex: 1,
    explanation: 'The Highway Code Rule 163 states you should give cyclists at least 1.5 metres when overtaking at speeds up to 30 mph. At higher speeds, give them more space. Cyclists can wobble or swerve to avoid obstacles, so this margin is essential.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_020',
    questionText: 'On a motorway at night, why might your stopping distance exceed the distance illuminated by your headlights?',
    options: [
      'Headlights dip automatically at high speed, reducing range',
      'At high speeds, dipped headlights may only illuminate 30m while stopping distance at 70mph is 96m',
      'Road markings reflect light and make the road appear shorter',
      'Headlights are designed for urban use and reduce power on motorways',
    ],
    correctIndex: 1,
    explanation: 'At 70 mph the total stopping distance is 96 metres, yet dipped headlights typically illuminate around 30 to 40 metres ahead. This means you may be driving into a zone you cannot see in time to stop. This is "over-driving your headlights" and requires a speed reduction.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_021',
    questionText: 'What is the main risk of driving too close to parked vehicles?',
    options: [
      'Your tyres may pick up debris from the gutter',
      'A car door may be opened into your path with no warning',
      'Oncoming vehicles may think you are turning right',
      'You may miss pedestrian crossing points on the nearside',
    ],
    correctIndex: 1,
    explanation: 'Drivers or passengers may open doors without checking their mirrors. Highway Code Rule 163 advises leaving a door\'s width (about 1 metre) when passing parked vehicles. This safety margin is sometimes called the "door zone."',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_022',
    questionText: 'You are driving downhill on a steep gradient. How does this affect your stopping distance?',
    options: [
      'It has no effect if your brakes are in good condition',
      'It increases stopping distance because gravity adds to the vehicle\'s momentum',
      'It reduces stopping distance because the engine provides additional braking',
      'It only increases stopping distance if the road is also wet',
    ],
    correctIndex: 1,
    explanation: 'On a downhill gradient, gravity increases the vehicle\'s momentum. This means more braking force is needed to stop in the same distance, so stopping distance increases. Select a lower gear on steep hills to assist braking and prevent brake fade.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_023',
    questionText: 'How does anti-lock braking system (ABS) affect stopping distance?',
    options: [
      'ABS always reduces stopping distance compared to non-ABS vehicles',
      'ABS prevents wheel lock-up and allows steering control during emergency braking, but may not shorten stopping distance',
      'ABS doubles the effective braking force',
      'ABS only operates at speeds above 30 mph',
    ],
    correctIndex: 1,
    explanation: 'ABS prevents wheels from locking under heavy braking, allowing the driver to maintain steering control. It does not necessarily reduce stopping distance - on some surfaces, such as loose gravel, stopping distance may be longer. Its main benefit is maintaining directional control.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_024',
    questionText: 'When towing a trailer, how does this affect your following distance?',
    options: [
      'There is no change needed - modern tow vehicles have enhanced brakes',
      'You should increase your following distance as the total weight and length increase stopping distance',
      'You should decrease your following distance as the trailer provides additional drag',
      'The following distance only changes if the trailer exceeds 750kg',
    ],
    correctIndex: 1,
    explanation: 'Towing a trailer increases total vehicle weight and length, significantly increasing stopping distance. Allow greater following distances and plan well ahead. Also bear in mind that trailer brakes (where fitted) may not engage as quickly as the towing vehicle\'s brakes.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_025',
    questionText: 'You are driving on snow. Compared to dry conditions, stopping distances can be how much greater?',
    options: [
      'About twice as long',
      'About four times as long',
      'About six times as long',
      'About ten times as long',
    ],
    correctIndex: 3,
    explanation: 'The Highway Code states that stopping distances in icy and snowy conditions can be up to ten times greater than in dry conditions. This is why speeds must be dramatically reduced in winter conditions and following distances greatly increased.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_026',
    questionText: 'You are emerging from a side road onto a main road. What is the key factor in judging a safe gap?',
    options: [
      'The speed limit of the main road',
      'The speed and distance of approaching vehicles combined with your vehicle\'s acceleration',
      'The length of the side road behind you',
      'Whether the main road is a priority road with a give-way or stop line',
    ],
    correctIndex: 1,
    explanation: 'A safe gap depends on how fast approaching vehicles are travelling, how far away they are, and how quickly your vehicle can accelerate to match traffic speed. On fast roads, gaps that look adequate can close very quickly - always err on the side of caution.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_027',
    questionText: 'At 70mph, approximately how many car lengths does your vehicle travel in the typical reaction time of 0.67 seconds before braking begins?',
    options: [
      'About 2 car lengths',
      'About 5 car lengths',
      'About 8 car lengths',
      'About 13 car lengths',
    ],
    correctIndex: 1,
    explanation: 'At 70mph you travel approximately 31 metres per second. In a 0.67-second reaction time, you cover about 21 metres - roughly 5 car lengths - before your foot even reaches the brake. This is why thinking distance at 70mph is 21 metres.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_028',
    questionText: 'Tyres that are under-inflated affect braking distance. In which way?',
    options: [
      'Under-inflation reduces braking distance by increasing the tyre contact patch',
      'Under-inflation increases braking distance and reduces directional stability',
      'Under-inflation has no measurable effect on braking distance',
      'Under-inflation only affects braking in wet conditions',
    ],
    correctIndex: 1,
    explanation: 'Under-inflated tyres have reduced structural rigidity, causing the sidewalls to flex excessively. This generates heat, reduces grip, and increases braking distance. Tyres should be checked at least monthly and before long journeys when cold.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_029',
    questionText: 'You are following a large lorry on a dry motorway at 70mph. What following distance should you ideally maintain?',
    options: [
      'At least one second',
      'At least two seconds',
      'At least three seconds due to the lorry\'s height blocking your view',
      'At least six seconds because lorries take longer to stop',
    ],
    correctIndex: 1,
    explanation: 'Even behind a lorry, the two-second rule applies as a minimum in dry conditions. In practice, a larger gap is advisable because the lorry blocks your view ahead and debris can fall from poorly loaded vehicles. Four seconds or more is recommended.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_030',
    questionText: 'How does being tired affect your thinking distance?',
    options: [
      'It has no effect - thinking distance is a fixed physical constant',
      'It reduces thinking distance by making you more alert to danger',
      'It increases thinking distance by slowing your reaction time',
      'It only affects thinking distance if you have been awake for more than 18 hours',
    ],
    correctIndex: 2,
    explanation: 'Fatigue slows the brain\'s processing speed and reaction time, directly increasing thinking distance. Research shows that driving after 17 to 19 hours without sleep can impair driving similarly to a blood alcohol level above the legal limit.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_031',
    questionText: 'What is the relationship between kinetic energy and vehicle speed?',
    options: [
      'Kinetic energy increases in direct proportion to speed',
      'Kinetic energy doubles when speed doubles',
      'Kinetic energy increases with the square of speed',
      'Kinetic energy is determined by vehicle weight alone',
    ],
    correctIndex: 2,
    explanation: 'Kinetic energy equals half the mass multiplied by the square of speed. Doubling speed therefore quadruples kinetic energy, which means four times more energy must be dissipated in a crash or by braking. This is a key reason why small increases in speed dramatically increase crash severity.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_032',
    questionText: 'You are driving a heavily loaded car. How does this affect stopping distance?',
    options: [
      'A heavier load reduces stopping distance by providing more tyre contact',
      'A heavier load increases stopping distance because greater mass requires more braking force',
      'A heavier load has no effect if the brakes are correctly adjusted',
      'A heavier load only affects stopping distance on wet roads',
    ],
    correctIndex: 1,
    explanation: 'A heavier vehicle has greater momentum and requires more force to stop in the same distance. When fully loaded, allow greater following distances and brake earlier. Check that tyre pressures are increased to the loaded vehicle setting.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_033',
    questionText: 'A vehicle overtakes you on a dual carriageway and pulls in sharply ahead of you. What should you do?',
    options: [
      'Brake sharply to express your displeasure',
      'Sound your horn and flash your lights to protest',
      'Drop back to re-establish a safe following distance',
      'Match their speed to maintain the original gap',
    ],
    correctIndex: 2,
    explanation: 'When another vehicle cuts in front and reduces your safety margin, drop back to re-establish a safe following distance. Reacting aggressively escalates the situation. Staying calm and increasing your gap is the safe and rational response.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_034',
    questionText: 'What is the stopping distance rule of thumb to use on a motorway in dry conditions?',
    options: [
      'One car length for every 10 mph',
      'Two seconds between your vehicle and the one ahead',
      'One metre for every mph of speed',
      'Three seconds between vehicles at all times',
    ],
    correctIndex: 1,
    explanation: 'The two-second rule is the standard minimum for following distance in dry conditions. Count the time from when the vehicle ahead passes a fixed point until you reach it. In wet conditions use at least four seconds; in fog or on ice, more still.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: 'SAF_035',
    questionText: 'You notice the vehicle ahead begins to brake for a hazard. You are maintaining a two-second gap. What happens?',
    options: [
      'You will definitely hit the vehicle because two seconds is insufficient',
      'You have enough time and distance to brake safely before reaching the hazard',
      'Two seconds is sufficient only if you have good brakes and dry roads',
      'You must also have good tyres - otherwise two seconds is dangerous',
    ],
    correctIndex: 1,
    explanation: 'A two-second gap in dry conditions gives enough reaction time and braking distance to stop safely if the vehicle ahead brakes suddenly. This assumes good tyres, brakes, and road conditions. The gap must be increased in adverse conditions.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_036',
    questionText: 'What is the danger of brake fade on a long downhill stretch?',
    options: [
      'Brakes overheat and lose effectiveness due to continuous application',
      'Brake fluid evaporates causing pedal travel to increase',
      'The handbrake activates automatically when brakes overheat',
      'Brake fade is only a risk on vehicles built before 2000',
    ],
    correctIndex: 0,
    explanation: 'Continuous braking on a long descent causes brake components to overheat, reducing effectiveness - known as brake fade. Use engine braking in a lower gear on long descents and apply brakes firmly and briefly rather than continuously to allow cooling.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_037',
    questionText: 'How does motorway driving at 70mph compare to 50mph in terms of stopping distance?',
    options: [
      'Stopping distance at 70mph is about 50% greater',
      'Stopping distance at 70mph is about 80% greater',
      'Stopping distance at 70mph is about twice as long',
      'Stopping distance at 70mph is more than twice as long',
    ],
    correctIndex: 3,
    explanation: 'At 50mph the total stopping distance is 53m; at 70mph it is 96m - nearly twice the distance. The non-linear relationship (due to braking distance increasing with the square of speed) means relatively small speed increases have a large effect on stopping distance.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_038',
    questionText: 'Why should you keep well back from the vehicle ahead in queuing traffic on a motorway?',
    options: [
      'To allow other vehicles to merge from slip roads',
      'To allow emergency vehicles to pass between lanes',
      'To give yourself time to react and avoid a rear-end collision if traffic stops suddenly',
      'To prevent your engine overheating in stationary traffic',
    ],
    correctIndex: 2,
    explanation: 'In slow-moving or stop-start motorway traffic, leaving space ahead gives you time to react if traffic stops suddenly. Rear-end collisions in queues are common. Rule 126 of the Highway Code emphasises the need to maintain a safe following distance at all times.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_039',
    questionText: 'You are driving on a road with tram lines. Why do tram lines present a particular hazard to cyclists and motorcyclists?',
    options: [
      'Trams always have right of way over cyclists and motorcyclists',
      'The lines conduct electricity which can affect sensitive vehicle electronics',
      'Narrow tyres can become trapped in the rails, causing a sudden loss of control',
      'Tram lines are usually wet because of cooling water from the trams',
    ],
    correctIndex: 2,
    explanation: 'Tram rails present a particular hazard to cyclists and motorcyclists because narrow tyres can get trapped in the gap between the rail and road surface, causing sudden and violent loss of control. Cross tram lines at a clear angle where possible.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_040',
    questionText: 'When following another vehicle through a ford or flood water, what is the key safety margin to maintain?',
    options: [
      'The standard two-second gap',
      'A much larger gap - the vehicle ahead creates a bow wave that can push water into your engine',
      'No gap is needed - follow closely for the wake effect to reduce water resistance',
      'Move alongside to avoid the deepest water in the centre',
    ],
    correctIndex: 1,
    explanation: 'The vehicle ahead creates a bow wave that can splash into your engine bay. Allow a much larger gap and drive slowly and steadily through water. If the water is moving or of unknown depth, do not enter - flooded roads kill drivers every year.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_041',
    questionText: 'What safety margin should you observe when approaching a blind bend on a country road?',
    options: [
      'Drive at the speed limit unless there is a sign indicating otherwise',
      'Slow to a speed at which you can stop within the distance you can see to be clear',
      'Move to the centre of the road to get a better view around the bend',
      'Sound your horn to warn oncoming traffic of your presence',
    ],
    correctIndex: 1,
    explanation: 'You should always be able to stop within the distance you can see to be clear. On a blind bend, this means reducing speed considerably. Moving to the centre of the road to see around a bend is dangerous as it puts you in the path of oncoming traffic.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_042',
    questionText: 'You are driving in very bright sunshine and your windscreen is dirty. How does this affect your safety margin?',
    options: [
      'It has no effect - sun visors compensate for a dirty windscreen',
      'It can cause severe glare that dramatically reduces visibility, increasing the danger',
      'A dirty windscreen slightly reduces visibility but is not a significant hazard',
      'It only becomes a problem when driving directly into the sun',
    ],
    correctIndex: 1,
    explanation: 'A dirty windscreen can scatter bright sunlight, creating an almost total white-out of vision. Always keep your windscreen clean inside and out. Carry screenwash and ensure windscreen wipers are in good condition.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_043',
    questionText: 'What is the minimum gap recommended by the Highway Code when pulling out to overtake a cyclist?',
    options: [
      '0.5 metres at speeds up to 30 mph',
      '1 metre at all speeds',
      '1.5 metres at speeds up to 30 mph; more at higher speeds',
      '2 metres at all speeds',
    ],
    correctIndex: 2,
    explanation: 'Highway Code Rule 163 recommends at least 1.5 metres when overtaking cyclists at speeds up to 30 mph, and more space at higher speeds. This accounts for cyclists who may need to swerve to avoid road hazards such as potholes or drain covers.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_044',
    questionText: 'You are driving at 30mph when a child runs out from behind a parked car 15 metres ahead. Can you stop in time?',
    options: [
      'Yes - the stopping distance at 30mph is only 23m so 15m should be enough',
      'No - the stopping distance at 30mph is 23m, and 15m is not sufficient',
      'Yes - modern ABS reduces stopping distance to under 10 metres',
      'It depends on the road surface condition',
    ],
    correctIndex: 1,
    explanation: 'The total stopping distance at 30mph is 23 metres (9m thinking + 14m braking). At 15 metres, there is insufficient distance to stop - a collision is likely. This illustrates why slower speeds in residential areas where children may be present are so important.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_045',
    questionText: 'You are driving in convoy with a group of motorcyclists. What following distance should you maintain?',
    options: [
      'The same as following any other vehicle - two seconds',
      'Motorcyclists should be given a full two-second gap each, not shared',
      'A smaller gap is acceptable because motorcyclists stop faster than cars',
      'One second per motorcycle in the group',
    ],
    correctIndex: 1,
    explanation: 'Each motorcycle in a convoy deserves the same following distance you would give to any individual vehicle. Do not reduce your gap just because multiple motorcycles occupy the same lane. Motorcyclists are vulnerable and need space to react to road hazards.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_046',
    questionText: 'How does a worn tyre with 1.5mm tread (just below legal minimum) compare to a new tyre in wet braking?',
    options: [
      'Performance is marginally reduced but within acceptable limits',
      'Wet braking distance increases significantly - potentially by 50% or more',
      'Wet braking distance doubles at speeds above 50mph only',
      'There is no difference in braking distance - only aquaplaning risk changes',
    ],
    correctIndex: 1,
    explanation: 'Tyre tread channels water away from the contact patch. At the legal minimum of 1.6mm, wet braking performance is already seriously degraded compared to a new tyre. Tests show wet braking distances increasing by 44% or more at the legal limit versus a new tyre.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_047',
    questionText: 'You are about to overtake on a country road. What is the minimum clear distance you need to see ahead?',
    options: [
      'Enough to see you can pass the vehicle ahead',
      'Enough that you can complete the overtake and return to your side safely with a margin for error',
      'The same distance as your stopping distance at current speed',
      'At least 100 metres of clear road',
    ],
    correctIndex: 1,
    explanation: 'To overtake safely you need to see far enough ahead to accelerate past the vehicle, return to your lane, and have a safety margin in case an unseen hazard emerges. This is considerably more than just seeing past the vehicle you are overtaking.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
  {
    id: 'SAF_048',
    questionText: 'What happens to stopping distance in fog compared to clear conditions?',
    options: [
      'Stopping distance is unchanged - only visibility is affected',
      'Fog makes roads slippery so stopping distance increases slightly',
      'Stopping distance is physically unchanged but visibility may be less than your stopping distance, creating danger',
      'Fog lights reduce stopping distance by improving road visibility',
    ],
    correctIndex: 2,
    explanation: 'Fog does not directly change tyre grip or stopping distance, but it reduces visibility so you may not see a hazard until you are already too close to stop. The effective danger is that you are driving beyond your visible stopping distance. Reduce speed in fog.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_049',
    questionText: 'If a vehicle ahead brakes suddenly and you react in one second at 60mph, how far have you travelled before you begin to brake?',
    options: [
      'About 9 metres',
      'About 18 metres',
      'About 27 metres',
      'About 36 metres',
    ],
    correctIndex: 2,
    explanation: 'At 60mph you travel approximately 27 metres per second. Even with a one-second reaction time, you cover 27 metres before your foot reaches the brake. The standard thinking distance at 60mph (0.67 seconds) is 18m, but real reaction times under surprise braking are often one second or longer.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 3,
  },
  {
    id: 'SAF_050',
    questionText: 'Why is the safety margin particularly important when driving near large goods vehicles on a motorway?',
    options: [
      'LGVs create more wind turbulence that can affect your steering',
      'LGVs have longer stopping distances and may also obscure your view ahead',
      'LGVs are allowed to travel faster than other vehicles on motorways',
      'LGVs carry hazardous loads that require a legal exclusion zone',
    ],
    correctIndex: 1,
    explanation: 'Large goods vehicles have significantly greater stopping distances due to their weight. They also obstruct your view of the road ahead, preventing you from seeing and reacting to developing hazards. Allow a larger gap and avoid sitting directly behind an LGV for extended periods.',
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 2,
  },
];
