import { Question, TopicCategory } from '@clearpass/core';

export const safetyMarginsQuestions: Question[] = [
  {
    id: "AB2076",
    questionText: "How much can stopping distances increase in icy conditions?",
    options: [
    "2 times",
    "3 times",
    "5 times",
    "10 times",
    ],
    correctIndex: 3,
    explanation: "Tyre grip is greatly reduced in icy conditions. For this reason, you need to allow up to 10 times the stopping distance you would allow on dry roads.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2080",
    questionText: "What requires extra care when you're driving or riding in windy conditions?",
    options: [
    "Using the brakes",
    "Moving off on a hill",
    "Turning into a narrow road",
    "Passing cyclists",
    ],
    correctIndex: 3,
    explanation: "Always give cyclists plenty of room when overtaking them. You need to give them even more room when it’s windy. A sudden gust could easily blow them off course and into your path.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2624",
    questionText: "Why should you keep well to the left as you approach a right-hand bend?",
    options: [
    "To improve your view of the road",
    "To overcome the effect of the road’s slope",
    "To let faster traffic from behind overtake",
    "To be positioned safely if you skid",
    ],
    correctIndex: 0,
    explanation: "Keeping to the left as you approach right-hand bends will give you an earlier view around the bend and allow you to see any hazards sooner. It also reduces the risk of collision with any oncoming vehicle that may have drifted over the centre line while taking the bend.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2639",
    questionText: "You’ve just gone through flood water. What should you do to make sure your brakes are working properly?",
    options: [
    "Accelerate and keep to a high speed for a short time",
    "Go slowly while gently applying the brakes",
    "Avoid using the brakes at all for a few miles",
    "Stop for at least an hour to allow them time to dry",
    ],
    correctIndex: 1,
    explanation: "Water on the brakes will act as a lubricant, causing them to work less efficiently. Using the brakes lightly as you go along will quickly dry them out.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2712",
    questionText: "What will be affected if the road surface becomes soft in very hot weather?",
    options: [
    "The suspension",
    "The exhaust emissions",
    "The fuel consumption",
    "The tyre grip",
    ],
    correctIndex: 3,
    explanation: "If the road surface becomes very hot, it can soften. Tyres are unable to grip a soft surface as well as they can a firm dry one. Take care when cornering and braking.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2713",
    questionText: "Where is your vehicle most likely to be affected by side winds?",
    options: [
    "On a narrow country lane",
    "On an open stretch of road",
    "On a busy stretch of road",
    "On a long, straight road",
    ],
    correctIndex: 1,
    explanation: "In windy conditions, care must be taken on exposed roads. A strong gust of wind can blow you off course. Watch out for other road users who are particularly likely to be affected, such as cyclists, motorcyclists, high-sided lorries and vehicles towing trailers.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2740",
    questionText: "You're following a vehicle on a wet road. You stay a safe distance behind it. What should you do if a driver overtakes you and pulls into the gap you've left?",
    options: [
    "Flash your headlights as a warning",
    "Try to overtake safely as soon as you can",
    "Drop back to regain a safe distance",
    "Stay close to the other vehicle until it moves on",
    ],
    correctIndex: 2,
    explanation: "Wet weather will affect the time it takes for you to stop and can affect your control. Your speed should allow you to stop safely and in good time. If another vehicle pulls into the gap you’ve allowed, ease back until you’ve regained your stopping distance.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2911",
    questionText: "You're travelling on the motorway. How can you lower the risk of a collision when the vehicle behind is following too closely?",
    options: [
    "Increase your distance from the vehicle in front",
    "Brake sharply",
    "Switch on your hazard warning lights",
    "Move onto the hard shoulder and stop",
    ],
    correctIndex: 0,
    explanation: "On busy roads, traffic may still travel at high speeds. Do not follow the vehicle in front too closely. If a driver behind seems to be ‘pushing’ you, gradually increase your distance from the vehicle in front by slowing down gently. This will give you more space in front if you have to brake, and will reduce the risk of a collision involving several vehicles.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2942",
    questionText: "You're following other vehicles in fog. You have your headlights on dipped beam. What else can you do to reduce the chances of being in a collision?",
    options: [
    "Keep close to the vehicle in front",
    "Use main beam instead of dipped headlights",
    "Keep up with the faster vehicles",
    "Keep a safe distance from the vehicle in front",
    ],
    correctIndex: 3,
    explanation: "When it’s foggy, use your headlights on dipped beam. This will help you see and be seen by other road users. If visibility is seriously reduced, consider using front and rear fog lights if you have them. Keep to a sensible speed and do not follow the vehicle in front too closely. If the road is wet and slippery, you’ll need to allow twice the normal stopping distance.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "AB2944",
    questionText: "What should you do when you're using a contraflow system?",
    options: [
    "Choose an appropriate lane in good time",
    "Switch lanes to make better progress",
    "Increase speed to get through the contraflow more quickly",
    "Follow other motorists closely to avoid long queues",
    ],
    correctIndex: 0,
    explanation: "In a contraflow system, you'll be travelling close to oncoming traffic and sometimes in narrow lanes. You should get into the correct lane in good time, obey any temporary speed limit signs and keep a safe separation distance from the vehicle ahead.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1059",
    questionText: "How can you avoid wheelspin when you're driving on an icy road?",
    options: [
    "Drive at a slow speed in the highest gear possible",
    "Use the parking brake if the wheels start to slip",
    "Brake gently and repeatedly",
    "Drive in a low gear at all times",
    ],
    correctIndex: 0,
    explanation: "If you’re travelling on an icy road, extra caution will be required to avoid loss of control. Keeping your speed down and using the highest gear possible will reduce the risk of the tyres losing their grip on this slippery surface.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1060",
    questionText: "What's the main cause of skidding?",
    options: [
    "The weather",
    "The driver",
    "The vehicle",
    "The road",
    ],
    correctIndex: 1,
    explanation: "Skidding is usually caused by driver error. You should always adjust your driving to take account of the road and weather conditions.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1062",
    questionText: "You're driving in freezing conditions. What should you do as you approach a sharp bend?",
    options: [
    "Coast into the bend",
    "Apply your parking brake",
    "Firmly use your footbrake",
    "Slow down gently",
    ],
    correctIndex: 3,
    explanation: "Harsh use of the accelerator, brakes or steering is likely to lead to skidding, especially on slippery surfaces. Avoid steering and braking at the same time. In icy conditions, it’s very important that you constantly assess what’s ahead so that you can take appropriate action in plenty of time.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1066",
    questionText: "You're about to start a journey in freezing weather. What part of your vehicle should you clear of ice and snow?",
    options: [
    "The aerial",
    "The windows",
    "The bumper",
    "The boot",
    ],
    correctIndex: 1,
    explanation: "Driving in bad weather increases your risk of having a collision. If you absolutely have to travel, clear your lights, mirrors, number plates and windows of any snow or ice, so that you can see and be seen.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1068",
    questionText: "What will help you to move off on a snowy surface?",
    options: [
    "Using the car's lowest gear",
    "Using a higher gear than normal",
    "Using a high engine speed",
    "Using the parking brake and footbrake together",
    ],
    correctIndex: 1,
    explanation: "If you attempt to move off in a low gear, there'll be more torque (turning force) at the driven wheels than if you use a higher gear. More torque makes it easier for the tyres to lose grip and so spin the wheels.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1069",
    questionText: "What should you do when you're driving in snowy conditions?",
    options: [
    "Brake firmly and quickly",
    "Be ready to steer sharply",
    "Use sidelights only",
    "Brake gently in plenty of time",
    ],
    correctIndex: 3,
    explanation: "In snowy conditions, be careful with the steering, accelerator and brakes. Braking sharply while you're driving on snow is likely to make your car skid.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1070",
    questionText: "What's the main benefit of driving a four-wheel-drive vehicle?",
    options: [
    "Improved grip on the road",
    "Lower fuel consumption",
    "Shorter stopping distances",
    "Improved passenger comfort",
    ],
    correctIndex: 0,
    explanation: "By driving all 4 wheels, the vehicle has maximum grip on the road. This grip is especially helpful when travelling on slippery or uneven surfaces. However, having four-wheel drive does not replace the skills you need to drive safely.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1073",
    questionText: "You're about to go down a steep hill. What should you do to control the speed of your vehicle?",
    options: [
    "Select a high gear and use the brakes carefully",
    "Select a high gear and use the brakes firmly",
    "Select a low gear and use the brakes carefully",
    "Select a low gear and avoid using the brakes",
    ],
    correctIndex: 2,
    explanation: "When driving down a steep hill, gravity will cause your vehicle to speed up. This will make it more difficult for you to stop. To help keep your vehicle's speed under control, select a lower gear to give you more engine braking and make careful use of the brakes.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1075",
    questionText: "What should you do when you park a car facing downhill?",
    options: [
    "Turn the steering wheel towards the kerb",
    "Park close to the bumper of another car",
    "Park with 2 wheels on the kerb",
    "Turn the steering wheel away from the kerb",
    ],
    correctIndex: 0,
    explanation: "Turning the wheels towards the kerb will allow them to act as a chock, preventing any forward movement of the vehicle. It will also help to leave your car in gear, or select ‘Park’ if you have an automatic.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1076",
    questionText: "You're driving in a built-up area that has traffic-calming measures. What should you do when you approach a road hump?",
    options: [
    "Move across to the left-hand side of the road",
    "Wait for any pedestrians to cross",
    "Check your mirror and slow down",
    "Stop and check both pavements",
    ],
    correctIndex: 2,
    explanation: "Many towns have road humps as part of traffic-calming measures, designed to slow down traffic. Reduce your speed when driving over them. If you go too fast, you could lose control or damage your car. Look out for pedestrians or cyclists while you're driving in these areas.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1317",
    questionText: "On what type of road surface may anti-lock brakes be ineffective?",
    options: [
    "Dry",
    "Loose",
    "Firm",
    "Smooth",
    ],
    correctIndex: 1,
    explanation: "Poor contact with the road surface could cause one or more of the tyres to lose grip on the road. This is more likely to happen when braking in poor weather conditions and when the road has a loose, slippery or uneven surface.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1322",
    questionText: "You're driving a vehicle that has an anti-lock braking system (ABS). How should you apply the footbrake when you need to stop in an emergency?",
    options: [
    "Slowly and gently",
    "Slowly but firmly",
    "Rapidly and gently",
    "Rapidly and firmly",
    ],
    correctIndex: 3,
    explanation: "You may have to stop in an emergency due to a misjudgement by another driver or a hazard arising suddenly, such as a child running out into the road. If your vehicle has ABS, you should apply the brakes immediately and keep them firmly applied until you stop.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1351",
    questionText: "You're driving along a country road. You see this sign. What should you do after dealing safely with the hazard?",
    options: [
    "Check your tyre pressures",
    "Switch on your hazard warning lights",
    "Accelerate briskly",
    "Test your brakes",
    ],
    correctIndex: 3,
    explanation: "If your brakes have been thoroughly soaked, you should check that they're working properly before you build up speed again. Before you do this, remember to check your mirrors and consider what's behind you.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1396",
    questionText: "What would suggest you're driving on an icy road?",
    options: [
    "There's less wind noise",
    "There's less tyre noise",
    "There's less transmission noise",
    "There's less engine noise",
    ],
    correctIndex: 1,
    explanation: "Drive extremely carefully when the roads are icy. When travelling on ice, tyres make virtually no noise and the steering feels light and unresponsive.\r\nIn icy conditions, be very gentle when braking, accelerating and steering.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1405",
    questionText: "You're driving along a wet road. How can you tell if your vehicle’s tyres are losing their grip on the surface?",
    options: [
    "The engine will stall",
    "The steering will feel very heavy",
    "The engine noise will increase",
    "The steering will feel very light",
    ],
    correctIndex: 3,
    explanation: "If you drive at speed in very wet conditions, your steering may suddenly feel lighter than usual. This means that the tyres have lifted off the surface of the road and are floating on the surface of the water. This is known as aquaplaning. Reduce speed but do not brake until your steering returns to normal.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1448",
    questionText: "In which conditions will your overall stopping distance increase?",
    options: [
    "In the rain",
    "In fog",
    "At night",
    "In strong winds",
    ],
    correctIndex: 0,
    explanation: "Extra care should be taken in wet weather. On wet roads, your stopping distance could be double that in dry conditions.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1657",
    questionText: "You're driving on an open road in dry weather. What distance should you keep from the vehicle in front?",
    options: [
    "A two-second time gap",
    "One car length",
    "2 metres (6 feet 6 inches)",
    "2 car lengths",
    ],
    correctIndex: 0,
    explanation: "One way of checking there's a safe distance between you and the vehicle in front is to use the two-second rule. To check for a two-second time gap, choose a stationary object ahead, such as a bridge or road sign. When the car in front passes the object, say 'Only a fool breaks the two-second rule'. If you reach the object before you finish saying the phrase, you're too close and need to increase the gap.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1659",
    questionText: "How can you use your vehicle's engine as a brake?",
    options: [
    "By changing to a lower gear",
    "By selecting reverse gear",
    "By changing to a higher gear",
    "By selecting neutral gear",
    ],
    correctIndex: 0,
    explanation: "When driving on downhill stretches of road, selecting a lower gear gives increased engine braking. This will prevent excessive use of the brakes, which become less effective if they overheat.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1660",
    questionText: "How should you use anti-lock brakes when you need to stop in an emergency?",
    options: [
    "Keep pumping the footbrake to prevent skidding",
    "Brake normally but grip the steering wheel tightly",
    "Brake promptly and firmly until you've stopped",
    "Apply the parking brake to reduce the stopping distance",
    ],
    correctIndex: 2,
    explanation: "If you have an anti-lock braking system (ABS) and need to stop in an emergency, keep your foot firmly on the brake pedal until the vehicle has stopped. When the ABS operates, you may hear a grating sound and feel vibration through the brake pedal. This is normal and you should maintain pressure on the brake pedal until the vehicle stops.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1681",
    questionText: "What lights should you use when you're driving on a wet motorway and vehicles are throwing up surface spray?",
    options: [
    "Hazard warning lights",
    "Dipped headlights",
    "Rear fog lights",
    "Sidelights",
    ],
    correctIndex: 1,
    explanation: "When surface spray reduces visibility, switch on your headlights on dipped beam. This will help other road users to see you.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1742",
    questionText: "What can result when you travel for long distances in neutral (known as coasting)?",
    options: [
    "Improvement in control",
    "Easier steering",
    "Reduction in control",
    "Increased fuel consumption",
    ],
    correctIndex: 2,
    explanation: "Coasting is the term used when the clutch is held down, or the gear lever is in neutral, and the vehicle is allowed to freewheel. This reduces the driver's control of the vehicle. When you coast, the engine cannot drive the wheels to stabilise you through a corner, or give the assistance of engine braking to help slow the car.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB1774",
    questionText: "What should you do before starting a journey in foggy weather?",
    options: [
    "Wear a hi-visibility jacket",
    "Have a caffeinated drink",
    "Allow more time",
    "Reduce your tyre pressures",
    ],
    correctIndex: 2,
    explanation: "Do not venture out if your journey is not necessary. If you have to travel and someone is expecting you at the other end, let them know that you’ll be taking longer than usual for your journey. This will stop them worrying if you do not turn up on time and will also take the pressure off you, so you do not feel you have to rush.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB2894",
    questionText: "What should you do when you're overtaking a motorcyclist on a windy day?",
    options: [
    "Pass closely",
    "Pass very slowly",
    "Pass widely",
    "Pass immediately",
    ],
    correctIndex: 2,
    explanation: "In strong winds, riders of two-wheeled vehicles are particularly vulnerable. When you overtake them, allow plenty of room. Check to the left as you pass to make sure they're safe.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
  {
    id: "BB4417",
    questionText: "What does it mean if the Electronic Stability Control (ESC) indicator light comes on briefly while you’re driving?",
    options: [
    "The ESC system has activated",
    "The ESC system has a fault",
    "The ESC system is running a routine test",
    "The ESC system is switched off",
    ],
    correctIndex: 0,
    explanation: "ESC is a computer controlled technology that detects reduced traction and automatically makes corrective adjustments to prevent loss of control. The ESC light comes on briefly to alert the driver that the system has activated and the car is approaching its handling limits. It’s a powerful driver aid but it cannot save a car once its traction limits have been exceeded.",
    topicCategory: TopicCategory.SafetyMargins,
    difficulty: 1,
  },
];
