import { Question, TopicCategory } from '@clearpass/core';

export const vehicleLoadingQuestions: Question[] = [
  {
    id: "BB1271",
    questionText: "What should you do if you're towing a trailer and it starts to swing from side to side?",
    options: [
    "Ease off the accelerator to reduce your speed",
    "Let go of the steering wheel and let it correct itself",
    "Brake hard and hold the pedal down",
    "Accelerate until it stabilises",
    ],
    correctIndex: 0,
    explanation: "Strong winds or buffeting from large vehicles can cause a trailer or caravan to swing from side to side ('snake'). If this happens, ease off the accelerator. Do not brake harshly, steer sharply or increase your speed.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1364",
    questionText: "When would you increase the pressure in your tyres so that it's above the normal value?",
    options: [
    "When the roads are slippery",
    "When the vehicle is fitted with anti-lock brakes",
    "When the tyre tread is worn below 2 mm",
    "When carrying a heavy load",
    ],
    correctIndex: 3,
    explanation: "Check the vehicle handbook. This should give you guidance on the correct tyre pressures for your vehicle and when you may need to adjust them. If you’re carrying a heavy load, you may need to adjust the headlights as well. Most cars have a switch on the dashboard to do this.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1365",
    questionText: "How will a heavy load on your roof rack affect your vehicle's handling?",
    options: [
    "It will improve the road holding",
    "It will reduce the stopping distance",
    "It will make the steering lighter",
    "It will reduce stability",
    ],
    correctIndex: 3,
    explanation: "A heavy load on your roof rack will reduce the stability of the vehicle because it moves the centre of gravity away from that designed by the manufacturer. Be aware of this when you drive round bends and corners. If you change direction at speed, your vehicle and/or load could become unstable and you could lose control.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1543",
    questionText: "What would be affected if you carry a very heavy load on your vehicle?",
    options: [
    "The vehicle's gearbox",
    "The vehicle's ventilation",
    "The vehicle's handling",
    "The vehicle's battery",
    ],
    correctIndex: 2,
    explanation: "Any load will have an effect on the handling of your vehicle, and this becomes worse as you increase the load. You need to be aware of this when carrying passengers or heavy loads, fitting a roof rack or towing a trailer.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1544",
    questionText: "Who's responsible for making sure that a vehicle is not overloaded?",
    options: [
    "The driver of the vehicle",
    "The owner of the items being carried",
    "The person who loaded the vehicle",
    "The licensing authority",
    ],
    correctIndex: 0,
    explanation: "Carrying heavy loads will affect control and the vehicle's handling characteristics. If the vehicle you're driving is overloaded, you'll be held responsible.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1706",
    questionText: "You're planning to tow a caravan. What will help the handling of the combination?",
    options: [
    "A jockey wheel fitted to the tow bar",
    "Power steering fitted to the towing vehicle",
    "Anti-lock brakes fitted to the towing vehicle",
    "A stabiliser fitted to the tow bar",
    ],
    correctIndex: 3,
    explanation: "Towing a caravan or trailer affects the way the towing vehicle handles. A stabiliser device is not designed to overcome instability caused by incorrect loading but it can give added security in side winds and from buffeting caused by large vehicles.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1707",
    questionText: "Are passengers allowed to ride in a caravan that's being towed?",
    options: [
    "Yes, if they're over 14",
    "No, not at any time",
    "Only if all the seats in the towing vehicle are full",
    "Only if a stabiliser is fitted",
    ],
    correctIndex: 1,
    explanation: "Riding in a towed caravan is highly dangerous. The safety of the entire unit is dependent on the stability of the trailer. Moving passengers would make the caravan unstable and could cause loss of control.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1708",
    questionText: "What safety device must be fitted to a trailer braking system?",
    options: [
    "Stabiliser",
    "Jockey wheel",
    "Corner steadies",
    "Breakaway cable",
    ],
    correctIndex: 3,
    explanation: "In the event that the trailer becomes detached from the towing vehicle, the breakaway cable activates the trailer brakes before snapping. This allows the towing vehicle to get free of the trailer and out of danger.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1735",
    questionText: "You wish to tow a trailer. Where would you find the maximum noseweight for your vehicle’s tow hitch?",
    options: [
    "In the vehicle handbook",
    "In The Highway Code",
    "In your vehicle registration certificate",
    "In your licence documents",
    ],
    correctIndex: 0,
    explanation: "You must know how to load your trailer or caravan so that the hitch exerts an appropriate downward force on the tow ball. Information about the maximum permitted noseweight can be found in your vehicle handbook or obtained from your vehicle manufacturer’s agent.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1745",
    questionText: "How should a load be carried on your roof rack?",
    options: [
    "Securely fastened with suitable restraints",
    "Loaded towards the rear of the vehicle",
    "Visible in your exterior mirror",
    "Covered with plastic sheeting",
    ],
    correctIndex: 0,
    explanation: "Any load must be securely fastened to the vehicle. The safest way to carry items on the roof is in a specially designed roof box. This will help to keep your luggage secure and dry, and it also has less wind resistance than loads carried exposed on a roof rack.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB1754",
    questionText: "You're carrying a child under 3 years old in your car. Which restraint is suitable for a child of this age?",
    options: [
    "A child seat",
    "An adult holding a child",
    "An adult seat belt",
    "An adult lap belt",
    ],
    correctIndex: 0,
    explanation: "It’s your responsibility to make sure that all children under 14 years old in your car are secure. Suitable restraints include a child seat, baby seat, booster seat or booster cushion. It’s essential that any restraint used is suitable for the child’s size and weight, and fitted according to the manufacturer’s instructions.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4419",
    questionText: "What should you do before you tow a trailer for the first time?",
    options: [
    "Ask DVLA to update your licence",
    "Fit P plates to your trailer",
    "Take professional training",
    "Pass a special driving test",
    ],
    correctIndex: 2,
    explanation: "You need to know how to tow a trailer safely. This includes hitching the trailer to your vehicle, checking the trailer for defects, reversing with a trailer and how to deal with any problems. There are accredited trainers who can teach you these skills. Professional training will also give you confidence in your ability to tow a trailer safely.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4420",
    questionText: "You're going to tow a trailer that’s wider than your car. What must you fit to your car before you start towing it?",
    options: [
    "Exterior towing mirrors",
    "Projection markers",
    "Parking sensors",
    "Rear-view camera",
    ],
    correctIndex: 0,
    explanation: "You must fit exterior towing mirrors to your vehicle if\r\n•  your vehicle is narrower than your trailer or load\r\n•  your trailer or load obstructs the view behind you.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4422",
    questionText: "What must you do when you hitch an unbraked trailer to a towing vehicle?",
    options: [
    "Fit a secondary coupling device",
    "Grease the tow ball and hitch",
    "Switch off the reversing sensor on the towing vehicle",
    "Make sure you can see the trailer in the mirrors",
    ],
    correctIndex: 0,
    explanation: "If a tow hitch fails, the trailer must stay connected to the towing vehicle. This is achieved by using a secondary coupling device, such as a safety chain.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4423",
    questionText: "What’s the minimum depth of tread on the tyres of a trailer?",
    options: [
    "1 mm",
    "1.6 mm",
    "2 mm",
    "2.2 mm",
    ],
    correctIndex: 1,
    explanation: "Your car or small van must have a minimum tread depth of 1.6 mm across the centre of the tread and around the entire circumference. This also applies to the tyres on your trailer.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4424",
    questionText: "You’re about to start a journey towing a trailer. What should you do if you notice that a light on your trailer is not working?",
    options: [
    "Continue with your journey because the lights on your car are working",
    "Disconnect the trailer electrical coupling before continuing with your journey",
    "Repair the fault before continuing with your journey",
    "Book the trailer in for repair before continuing with your journey",
    ],
    correctIndex: 2,
    explanation: "You must make sure that your vehicle and trailer are roadworthy. Check that your tyres are legal, and the brakes and lights are working properly. \r\nIf any of these things are not working, you must not drive or tow your trailer until the fault is repaired.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4426",
    questionText: "What should you do if your trailer starts to swerve or snake?",
    options: [
    "Reduce speed gently",
    "Brake firmly",
    "Increase speed",
    "Steer sharply",
    ],
    correctIndex: 0,
    explanation: "If your trailer starts to swerve or snake, reduce speed gently to regain control. Do not accelerate or brake harshly.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
  {
    id: "BB4427",
    questionText: "How should you load your trailer?",
    options: [
    "Put heavy items at the front",
    "Put heavy items at the back",
    "Put heavy items over the axles",
    "Put heavy items in the corners",
    ],
    correctIndex: 2,
    explanation: "When loading your trailer, you should spread the weight evenly with heavy items over the axles. This should reduce the risk of it swerving or snaking.",
    topicCategory: TopicCategory.VehicleLoading,
    difficulty: 1,
  },
];
