import { Question, TopicCategory } from '@clearpass/core';

export const vehicleHandlingQuestions: Question[] = [
  {
    id: "BB1166",
    questionText: "What will happen to your car when you drive up a steep hill?",
    options: [
    "The high gears will pull better",
    "The steering will feel heavier",
    "Overtaking will be easier",
    "The engine will work harder",
    ],
    correctIndex: 3,
    explanation: "The engine will need more power to pull the vehicle up the hill. When approaching a steep hill you should select a lower gear to help maintain your speed. You should do this without hesitation, so that you do not lose too much speed before engaging the lower gear.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1168",
    questionText: "You're driving on the motorway in windy conditions. What should you do as you overtake a high-sided vehicle?",
    options: [
    "Increase your speed",
    "Be wary of a sudden gust",
    "Drive alongside very closely",
    "Expect normal conditions",
    ],
    correctIndex: 1,
    explanation: "The draught caused by other vehicles – particularly those with high sides – could be strong enough to push you out of your lane. Be prepared for a sudden gust of wind as you overtake large vehicles. Keep both hands on the steering wheel to help you keep full control.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1177",
    questionText: "You're driving in fog. Why should you keep well back from the vehicle in front?",
    options: [
    "In case it changes direction suddenly",
    "In case its fog lights dazzle you",
    "In case it stops suddenly",
    "In case its brake lights dazzle you",
    ],
    correctIndex: 2,
    explanation: "If you’re following another road user in fog, stay well back. The driver in front will not be able to see hazards until they’re close and might need to brake suddenly. Also, the road surface is likely to be wet and could be slippery.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1181",
    questionText: "What should you do if you park on the road when it's foggy?",
    options: [
    "Leave parking lights switched on",
    "Leave dipped headlights and fog lights switched on",
    "Leave dipped headlights switched on",
    "Leave main-beam headlights switched on",
    ],
    correctIndex: 0,
    explanation: "If you have to park your vehicle in foggy conditions, try to find a place to park off the road. If this is not possible, park on the road facing in the same direction as the traffic. Leave your parking lights switched on and make sure they're clean.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1186",
    questionText: "You're driving at night. What should you do if you're dazzled by headlights coming towards you?",
    options: [
    "Pull down your sun visor",
    "Slow down or stop",
    "Flash your main-beam headlights",
    "Shade your eyes with your hand",
    ],
    correctIndex: 1,
    explanation: "If the headlights of an oncoming vehicle dazzle you, slow down or, if necessary, stop. Do not close your eyes or swerve, as you'll increase your chances of having a collision. Do not flash your headlights either, as this could dazzle other drivers and make the situation worse.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1325",
    questionText: "When may front fog lights be used?",
    options: [
    "When visibility is seriously reduced",
    "When they're fitted above the bumper",
    "When they’re not as bright as the headlights",
    "When an audible warning device is used",
    ],
    correctIndex: 0,
    explanation: "Your fog lights must only be used when visibility is reduced to 100 metres (328 feet) or less. You need to be familiar with the layout of your dashboard so you're aware if your fog lights have been switched on in error, or you've forgotten to switch them off.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1330",
    questionText: "You're driving with your front fog lights switched on. What should you do if the fog has cleared?",
    options: [
    "Leave them on if other drivers have their lights on",
    "Switch them off as long as visibility remains good",
    "Flash them to warn oncoming traffic that it's foggy",
    "Drive with them on instead of your headlights",
    ],
    correctIndex: 1,
    explanation: "Switch off your fog lights if the weather improves, but be prepared to use them again if visibility reduces to less than 100 metres (328 feet).",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1339",
    questionText: "Why should you switch off your rear fog lights when the fog has cleared?",
    options: [
    "To allow your headlights to work",
    "To stop draining the battery",
    "To stop the engine losing power",
    "To prevent dazzling drivers behind",
    ],
    correctIndex: 3,
    explanation: "Do not forget to switch off your fog lights when the weather improves. You could be prosecuted for driving with them on in good visibility. The high intensity of rear fog lights can dazzle drivers behind and make your brake lights difficult to notice.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1343",
    questionText: "What will happen if you use rear fog lights in good conditions?",
    options: [
    "They'll make it safer when towing a trailer",
    "They'll protect you from larger vehicles",
    "They'll dazzle other drivers",
    "They'll make drivers behind keep back",
    ],
    correctIndex: 2,
    explanation: "Rear fog lights shine more brightly than normal rear lights, so that they show up in reduced visibility. When the visibility improves, you must switch them off; this stops them dazzling the driver behind.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1400",
    questionText: "Why would you fit chains to your wheels?",
    options: [
    "To help prevent damage to the road surface",
    "To help prevent wear to the tyres",
    "To help prevent skidding in deep snow",
    "To help prevent the brakes locking",
    ],
    correctIndex: 2,
    explanation: "Chains can be fitted to your wheels in snowy conditions. They can help you to move off without wheelspin, or to keep moving in deep snow. You'll still need to adjust your driving to suit these conditions.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1408",
    questionText: "How can you use your vehicle's engine to control your speed?",
    options: [
    "By changing to a lower gear",
    "By selecting reverse gear",
    "By changing to a higher gear",
    "By selecting neutral",
    ],
    correctIndex: 0,
    explanation: "You should brake and slow down before selecting a lower gear. The gear can then be used to keep the speed low and help you control the vehicle. This is particularly helpful on long downhill stretches, where brake fade can occur if the brakes overheat.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1433",
    questionText: "Why could it be dangerous to keep the clutch down, or select neutral, for long periods of time while you're driving?",
    options: [
    "Fuel spillage will occur",
    "Engine damage may be caused",
    "You'll have less steering and braking control",
    "It will wear tyres out more quickly",
    ],
    correctIndex: 2,
    explanation: "Letting your vehicle roll or coast in neutral reduces your control over steering and braking. This can be dangerous on downhill slopes, where your vehicle could pick up speed very quickly.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1470",
    questionText: "You're driving on an icy road. What distance from the car in front should you drive?",
    options: [
    "4 times the normal distance",
    "6 times the normal distance",
    "8 times the normal distance",
    "10 times the normal distance",
    ],
    correctIndex: 3,
    explanation: "Do not travel in icy or snowy weather unless your journey is essential.\r\nDrive extremely carefully when roads are or may be icy. Stopping distances can be ten times greater than on dry roads.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1473",
    questionText: "Which lights must you use if you're driving on a well-lit motorway at night?",
    options: [
    "Use only your sidelights",
    "Use your headlights",
    "Use rear fog lights",
    "Use front fog lights",
    ],
    correctIndex: 1,
    explanation: "If you’re driving on a motorway at night or in poor visibility, you must always use your headlights, even if the road is well lit. Other road users must be able to see you, but you should avoid causing dazzle.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1474",
    questionText: "You're driving on a motorway at night. Which lights should you have on if there are other vehicles just ahead of you?",
    options: [
    "Front fog lights",
    "Main-beam headlights",
    "Sidelights only",
    "Dipped headlights",
    ],
    correctIndex: 3,
    explanation: "If you’re driving behind other traffic on the motorway at night, use dipped headlights. Main-beam headlights will dazzle the other drivers. Your headlights’ dipped beam should fall short of the vehicle in front.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1518",
    questionText: "What will affect your vehicle's stopping distance?",
    options: [
    "The speed limit",
    "The street lighting",
    "The time of day",
    "The condition of the tyres",
    ],
    correctIndex: 3,
    explanation: "Having tyres correctly inflated and in good condition will make sure they have maximum grip on the road; how well your tyres grip the road has a significant effect on your car's stopping distance.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1579",
    questionText: "When will you feel the effects of engine braking?",
    options: [
    "When you only use the parking brake",
    "When you're in neutral",
    "When you change to a lower gear",
    "When you change to a higher gear",
    ],
    correctIndex: 2,
    explanation: "You will feel the effect of engine braking when you take your foot off the accelerator. Changing to a lower gear will increase the effect.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1597",
    questionText: "Which lights should you switch on when daytime visibility is poor but not seriously reduced?",
    options: [
    "Headlights and fog lights",
    "Front fog lights",
    "Dipped headlights",
    "Rear fog lights",
    ],
    correctIndex: 2,
    explanation: "Only use your fog lights when visibility is seriously reduced. Use dipped headlights in poor conditions because this helps other road users to see you without the risk of causing dazzle.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1598",
    questionText: "Why are vehicles fitted with rear fog lights?",
    options: [
    "To make them more visible when driving at high speed",
    "To show when they've broken down in a dangerous position",
    "To make them more visible in thick fog",
    "To warn drivers following closely to drop back",
    ],
    correctIndex: 2,
    explanation: "Rear fog lights make it easier to spot a vehicle ahead in foggy conditions. Avoid the temptation to use other vehicles' lights as a guide, as they may give you a false sense of security.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1621",
    questionText: "There's been a heavy fall of snow. What should you consider before driving in these conditions?",
    options: [
    "Whether you should fit an amber flashing beacon to your car",
    "Whether you should drive without wearing your seat belt",
    "Whether you should wear sunglasses to reduce the glare",
    "Whether your journey is essential",
    ],
    correctIndex: 3,
    explanation: "Consider whether the increased risk is worth it. If the weather conditions are bad and your journey is not essential, then do not drive. If you have to drive, make sure you're well prepared in case you get stuck.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1682",
    questionText: "What should you check before you start a journey in foggy weather?",
    options: [
    "The radiator has enough anti-freeze",
    "You have a warning triangle in the vehicle",
    "The windows and lights are clean and clear",
    "You have a mobile phone with you",
    ],
    correctIndex: 2,
    explanation: "If you have to drive in fog, switch your dipped headlights on and keep all your windows clear. You should always be able to pull up within the distance you can see ahead.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1683",
    questionText: "You've been driving in fog. What must you do when the visibility improves?",
    options: [
    "Switch off your fog lights",
    "Keep your rear fog lights switched on",
    "Keep your front fog lights switched on",
    "Leave your fog lights switched on in case the fog returns",
    ],
    correctIndex: 0,
    explanation: "You must turn off your fog lights if visibility is more than 100 metres (328 feet). Be prepared for the fact that the fog may be patchy and you may need to turn them on again if the fog returns.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1685",
    questionText: "Why is it dangerous to leave rear fog lights switched on after the fog has cleared?",
    options: [
    "They may be confused with brake lights",
    "The bulbs would fail",
    "Electrical systems could be overloaded",
    "Direction indicators may not work properly",
    ],
    correctIndex: 0,
    explanation: "If your rear fog lights are left on when it’s not foggy, the glare they cause makes it difficult for road users behind to know whether you’re braking or you’ve just forgotten to turn off your rear fog lights. This can be a particular problem on wet roads and on motorways. If you leave your rear fog lights on at night, road users behind you are likely to be dazzled and this could put them at risk.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1686",
    questionText: "What will happen if you hold the clutch pedal down or roll in neutral for too long?",
    options: [
    "It will use more fuel",
    "It will cause the engine to overheat",
    "It will reduce your control",
    "It will improve tyre wear",
    ],
    correctIndex: 2,
    explanation: "Holding the clutch down or staying in neutral for too long will cause your vehicle to freewheel. This is known as 'coasting' and it's dangerous because it reduces your control of the vehicle.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1717",
    questionText: "Why is it bad technique to coast when you're driving downhill?",
    options: [
    "The fuel consumption will increase",
    "The engine will overheat",
    "The tyres will wear more quickly",
    "The vehicle will gain speed more quickly",
    ],
    correctIndex: 3,
    explanation: "Coasting is when you allow the vehicle to freewheel in neutral or with the clutch pedal depressed. When travelling downhill, this will cause the vehicle to gain speed more quickly as you lose the benefits of engine braking; it may even lead to a loss of control. You should not coast, especially when approaching hazards such as junctions or bends and when travelling downhill.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1718",
    questionText: "What should you do when dealing with this hazard?",
    options: [
    "Switch on your hazard warning lights",
    "Use a low gear and drive slowly",
    "Use a high gear to prevent wheelspin",
    "Switch on your windscreen wipers",
    ],
    correctIndex: 1,
    explanation: "In normal conditions, a ford can be crossed quite safely by driving through it slowly. The water may affect your brakes, so when you're clear of the ford, test them before you resume normal driving.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1744",
    questionText: "Why is travelling in neutral for long distances (known as coasting) bad driving technique?",
    options: [
    "It will cause the car to skid",
    "It will make the engine stall",
    "The engine will run faster",
    "There will not be any engine braking",
    ],
    correctIndex: 3,
    explanation: "Try to look and plan well ahead. Plan your approach to hazards and select the correct gear in good time. This will help give you the control you need to deal with anything unexpected that may occur.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB1749",
    questionText: "When must you use dipped headlights during the day?",
    options: [
    "All the time you're driving",
    "When you're driving along narrow streets",
    "When you're driving in poor visibility",
    "When you're parking",
    ],
    correctIndex: 2,
    explanation: "You must use dipped headlights when daytime visibility is seriously reduced, generally to 100 metres (328 feet) or less. You may also use front or rear fog lights, but they must be switched off when visibility improves.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "BB4429",
    questionText: "What should you do when you're driving along a road that has a series of road humps?",
    options: [
    "Brake firmly when you reach each road hump",
    "Vary your speed between each road hump",
    "Stay at a reduced speed for the whole stretch of road",
    "Set your car's cruise control",
    ],
    correctIndex: 2,
    explanation: "Traffic-calming measures are designed to protect vulnerable road users. Keep your speed down where traffic-calming measures are in place.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2199",
    questionText: "When may you overtake another vehicle on their left?",
    options: [
    "When you’re in a one-way street",
    "When approaching a motorway slip road where you’ll be turning off",
    "When the vehicle in front is signalling to turn left",
    "When a slower vehicle is travelling in the right-hand lane of a dual carriageway",
    ],
    correctIndex: 0,
    explanation: "You may pass slower vehicles on their left while travelling along a one-way street. Be aware of drivers who may need to change lanes and may not expect faster traffic passing on their left.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2201",
    questionText: "You're travelling in very heavy rain. How is this likely to affect your overall stopping distance?",
    options: [
    "It will be doubled",
    "It will be halved",
    "It will be 10 times greater",
    "It will be no different",
    ],
    correctIndex: 0,
    explanation: "The road will be very wet and spray from other vehicles will reduce your visibility. Tyre grip will also be reduced, increasing your stopping distance. You should at least double your separation distance to make sure you can stop safely in the space you've allowed.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2208",
    questionText: "What should you do when you're overtaking at night?",
    options: [
    "Wait until a bend so that you can see oncoming headlights",
    "Sound your horn twice before moving out",
    "Go past slowly so that you can react to unseen hazards",
    "Beware of bends in the road ahead",
    ],
    correctIndex: 3,
    explanation: "Do not overtake if there’s a possibility of a road junction, bend or brow of a bridge or hill ahead. There are many hazards that are difficult to see in the dark. Only overtake if you’re certain that the road ahead is clear. Do not take a chance.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2211",
    questionText: "When may you wait in a box junction?",
    options: [
    "When you're stationary in a queue of traffic",
    "When approaching a pelican crossing",
    "When approaching a zebra crossing",
    "When oncoming traffic prevents you turning right",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/J7003.png",
    explanation: "The purpose of a box junction is to keep the junction clear by preventing vehicles from stopping in the path of crossing traffic. \r\nYou must not enter a box junction unless your exit is clear. However, you may enter the box and wait if you want to turn right and are only prevented from doing so by oncoming traffic.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2212",
    questionText: "Which plate may appear with this road sign?",
    options: [
    "White rectangular plate with black text reading 'Humps for 1/2 mile'",
    "White rectangular plate with black text reading 'Hump Bridge'",
    "White rectangular plate with black text reading 'Low Bridge'",
    "White rectangular plate with black text reading 'Soft Verge'",
    ],
    correctIndex: 0,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4602.png",
    optionImages: [
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4654.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4090.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4065.png",
      "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4067.png",
    ],
    explanation: "Road humps are used to slow down traffic. They're found in places where there are often pedestrians, such as\r\n• shopping areas\r\n• near schools\r\n• residential areas. \r\nWatch out for people close to the kerb or crossing the road.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2524",
    questionText: "What's the reason for traffic-calming measures?",
    options: [
    "To stop road rage",
    "To make overtaking easier",
    "To slow traffic down",
    "To make parking easier",
    ],
    correctIndex: 2,
    explanation: "Traffic-calming measures make the roads safer for vulnerable road users, such as cyclists, pedestrians and children. These can be designed as chicanes, road humps or other obstacles that encourage drivers and riders to slow down.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2570",
    questionText: "What colour are the reflective studs along the left-hand edge of the motorway?",
    options: [
    "Green",
    "Amber",
    "Red",
    "White",
    ],
    correctIndex: 2,
    explanation: "Reflective studs are used to help you in poor visibility. Different colours are used so that you’ll know which lane you're in. These are\r\n• red on the left-hand edge of the carriageway\r\n• white between lanes \r\n• amber on the right-hand edge of the carriageway\r\n• green between the carriageway and slip roads.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2572",
    questionText: "What's a rumble device designed to do?",
    options: [
    "Give directions",
    "Prevent cattle escaping",
    "Alert you to low tyre pressure",
    "Alert you to a hazard",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW9940.jpg",
    explanation: "A rumble device consists of raised markings or strips, designed to give drivers an audible, visual and tactile warning. These devices are used in various locations, including in the line separating the hard shoulder and the left-hand lane on the motorway and on the approach to some hazards, to alert drivers to the need to slow down.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2605",
    questionText: "What should you do if you have to make a journey in foggy conditions?",
    options: [
    "Follow other vehicles’ tail lights closely",
    "Avoid using dipped headlights",
    "Leave plenty of time for your journey",
    "Keep 2 seconds behind the vehicle ahead",
    ],
    correctIndex: 2,
    explanation: "If you’re planning to make a journey when it’s foggy, listen to the weather reports. If visibility is very poor, avoid making unnecessary journeys. If you do travel, leave plenty of time – and if someone is waiting for you to arrive, let them know that your journey will take longer than normal. This will also take off any pressure you may feel to rush.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2606",
    questionText: "What must you do when you're overtaking a car at night?",
    options: [
    "Flash your headlights before overtaking",
    "Select a higher gear",
    "Switch your headlights to main beam before overtaking",
    "Make sure you do not dazzle other road users",
    ],
    correctIndex: 3,
    explanation: "To prevent your headlights from dazzling the driver of the car in front, wait until you’ve passed them before switching to main beam.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2640",
    questionText: "You're travelling on a road that has road humps. What should you do when the driver in front is travelling more slowly than you?",
    options: [
    "Sound your horn",
    "Overtake as soon as you can",
    "Flash your headlights",
    "Slow down and stay behind",
    ],
    correctIndex: 3,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4602.png",
    explanation: "Be patient and stay behind the car in front. You should not normally overtake other vehicles in areas subject to traffic calming. If you overtake here, you may easily exceed the speed limit, defeating the purpose of the traffic-calming measures.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2665",
    questionText: "What’s the purpose of the yellow lines painted across the road?",
    options: [
    "To show a safe distance between vehicles",
    "To keep the area clear of traffic",
    "To make you aware of your speed",
    "To warn you to change direction",
    ],
    correctIndex: 2,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/85BW9937.jpg",
    explanation: "These lines may be painted on the road on the approach to a roundabout, a village or a particular hazard. The lines are raised and painted yellow, and their purpose is to make you aware of your speed. Reduce your speed in good time so that you avoid having to brake harshly over the last few metres before reaching the junction.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2742",
    questionText: "What should you do when you meet an oncoming vehicle on a single-track road?",
    options: [
    "Reverse back to the main road",
    "Carry out an emergency stop",
    "Stop at a passing place",
    "Switch on your hazard warning lights",
    ],
    correctIndex: 2,
    explanation: "Take care when using single-track roads. It can be difficult to see around bends, because of hedges or fences, so expect to meet oncoming vehicles. Drive carefully and be ready to pull into or stop opposite a passing place, where you can pass each other safely.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2820",
    questionText: "The road is wet. Why would a motorcyclist steer around drain covers while they were cornering?",
    options: [
    "To avoid puncturing the tyres on the edge of the drain covers",
    "To prevent the motorcycle sliding on the metal drain covers",
    "To help judge the bend using the drain covers as marker points",
    "To avoid splashing pedestrians on the pavement",
    ],
    correctIndex: 1,
    explanation: "Other drivers or riders may have to change course due to the size or characteristics of their vehicle. Understanding this will help you to anticipate their actions. Motorcyclists and cyclists will be checking the road ahead for uneven or slippery surfaces, especially in wet weather. They may need to move across their lane to avoid surface hazards such as potholes and drain covers.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2821",
    questionText: "Why should you test your brakes after this hazard?",
    options: [
    "You'll be on a slippery road",
    "Your brakes will be wet",
    "You'll be going down a long hill",
    "You'll have just crossed a long bridge",
    ],
    correctIndex: 1,
    imageUrl: "https://secavejbaapapvvqbwed.supabase.co/storage/v1/object/public/question-images/TS4516.png",
    explanation: "A ford is a crossing over a stream that’s shallow enough to drive or ride through. After you’ve gone through a ford or deep puddle, your brakes will be wet and they will not work as well as usual. To dry them out, apply a light brake pressure while moving slowly. Do not travel at normal speeds until you're sure your brakes are working properly again.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
  {
    id: "AB2822",
    questionText: "Why should you reduce your speed when you're driving or riding in fog?",
    options: [
    "The brakes do not work as well",
    "You'll be dazzled by other headlights",
    "The engine will take longer to warm up",
    "It's more difficult to see what's ahead",
    ],
    correctIndex: 3,
    explanation: "You will not be able to see as far ahead in fog as you can on a clear day. You'll need to reduce your speed so that, if a hazard looms out of the fog, you have the time and space to take avoiding action.\r\nTravelling in fog is hazardous. If you can, try to delay your journey until it has cleared.",
    topicCategory: TopicCategory.VehicleHandling,
    difficulty: 1,
  },
];
