import { Question, TopicCategory } from '@clearpass/core';

export const vulnerableRoadUsersQuestions: Question[] = [
  {
    id: "AB2954",
    questionText: "You’re about to overtake a cyclist on a road that has a 30 mph speed limit. How much room should you leave them as you overtake?",
    options: [
    "At least as much room as you would if you were overtaking a car",
    "At least a car’s width",
    "At least a car’s length",
    "At least 2 car widths",
    ],
    correctIndex: 0,
    explanation: "You should leave cyclists at least as much room as you would if you were overtaking a car. Leave them more room if you’re overtaking at speeds over 30 mph.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2117",
    questionText: "Which sign means that there may be people walking along the road?",
    options: [
    "",
    "",
    "",
    "",
    ],
    correctIndex: 3,
    explanation: "Always check the road signs. Triangular signs are warning signs: they inform you about hazards ahead and help you to anticipate any problems. There are a number of different signs showing pedestrians. Learn the meaning of each one.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2119",
    questionText: "What should you do if you want to turn left at a junction where pedestrians have started to cross?",
    options: [
    "Go around them, leaving plenty of room",
    "Stop and wave at them to cross",
    "Sound your horn and proceed",
    "Give way to them",
    ],
    correctIndex: 3,
    explanation: "When you’re turning into a side road, pedestrians who are crossing have priority. You should wait to allow them to finish crossing safely. Be patient if they're slow or unsteady. Do not try to rush them by sounding your horn, flashing your lights, revving your engine or giving any other inappropriate signal.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2122",
    questionText: "What hazard should you be especially aware of if you're turning left into a side road?",
    options: [
    "One-way street",
    "Pedestrians",
    "Traffic congestion",
    "Parked vehicles",
    ],
    correctIndex: 1,
    explanation: "Make sure that you've reduced your speed and are in the correct gear for the turn. Look into the road before you turn and always give way to any pedestrians who are crossing.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2123",
    questionText: "Why should you check for motorcyclists just before turning right into a side road?",
    options: [
    "They may be overtaking on your left",
    "They may be following you closely",
    "They may be emerging from the side road",
    "They may be overtaking on your right",
    ],
    correctIndex: 3,
    explanation: "Never attempt to change direction to the right without first checking your right-hand mirror and blind spot. A motorcyclist might not have seen your signal and could be hidden by other traffic. This observation should be routine.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2124",
    questionText: "How is a toucan crossing different from a puffin crossing?",
    options: [
    "Moped riders can use it",
    "It's controlled by a traffic warden",
    "It's controlled by 2 flashing lights",
    "Pedestrians and cyclists can use it together",
    ],
    correctIndex: 3,
    explanation: "Puffin crossings are for use by pedestrians. Cyclists must dismount and push their bicycle over the crossing. Toucan crossings are shared by pedestrians and cyclists, who are permitted to cycle over the crossing. Toucan roadside signals show an icon of a pedestrian and a cyclist together.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2128",
    questionText: "How will a school crossing patrol signal you to stop?",
    options: [
    "By pointing to children waiting to cross",
    "By displaying a red light",
    "By displaying a 'stop' sign",
    "By giving you an arm signal",
    ],
    correctIndex: 2,
    explanation: "If a school crossing patrol steps out into the road with a 'stop' sign, you must stop. Do not wave anyone across the road and do not get impatient or rev your engine.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2129",
    questionText: "Where would you see this sign?",
    options: [
    "In the window of a car taking children to school",
    "At the side of the road",
    "At playground areas",
    "On the rear of a school bus or coach",
    ],
    correctIndex: 3,
    explanation: "Vehicles that are used to carry children to and from school will be travelling at busy times of the day. If you're following a vehicle with this sign, be prepared for it to make frequent stops. It might pick up or set down passengers in places other than normal bus stops.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2134",
    questionText: "What does this sign mean?",
    options: [
    "No route for pedestrians and cyclists",
    "A route for pedestrians only",
    "A route for cyclists only",
    "A route for pedestrians and cyclists",
    ],
    correctIndex: 3,
    explanation: "This sign shows a shared route for pedestrians and cyclists: when it ends, the cyclists are likely to be rejoining the main road.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2136",
    questionText: "You see a pedestrian carrying a white stick that also has a red band. What does this mean?",
    options: [
    "They have limited mobility",
    "They're deaf",
    "They're blind",
    "They're deaf and blind",
    ],
    correctIndex: 3,
    explanation: "When someone is deaf as well as blind, they may carry a white stick with a red reflective band or bands. They may not be aware that you're approaching and they may not be able to hear anything; so, for example, your horn would be ineffective as a warning to them.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2138",
    questionText: "What would you do if you see older people crossing the road ahead?",
    options: [
    "Wave them across so they know that you've seen them",
    "Be patient and allow them to cross in their own time",
    "Rev the engine to let them know that you're waiting",
    "Tap the horn in case they're hard of hearing",
    ],
    correctIndex: 1,
    explanation: "Be aware that older people might take a long time to cross the road. They might also be hard of hearing and not hear you approaching. Do not hurry older people across the road by getting too close to them or revving your engine.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2139",
    questionText: "What should you do when you see an older person about to cross the road ahead?",
    options: [
    "Expect them to wait for you to pass",
    "Speed up to get past them quickly",
    "Stop and wave them across the road",
    "Be careful; they may misjudge your speed",
    ],
    correctIndex: 3,
    explanation: "Older people may have impaired hearing, vision, concentration and judgement. They may also walk slowly and so could take a long time to cross the road.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2143",
    questionText: "You're approaching a roundabout. What should you do if a cyclist ahead is signalling to turn right?",
    options: [
    "Overtake on the right",
    "Give a warning with your horn",
    "Signal the cyclist to move across",
    "Give the cyclist plenty of room",
    ],
    correctIndex: 3,
    explanation: "If you’re following a cyclist who’s signalling to turn right at a roundabout, leave plenty of room. Give them space and time to get into the correct lane.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2147",
    questionText: "Which vehicle should you allow extra room as you overtake them?",
    options: [
    "Lorry",
    "Tractor",
    "Bicycle",
    "Road-sweeper",
    ],
    correctIndex: 2,
    explanation: "Do not pass cyclists too closely, as they may\r\n• need to veer around a pothole, drain or other hazard\r\n• be buffeted by side wind \r\n• be made unsteady by your vehicle. \r\nAlways leave as much room as you would for a car, and do not cut in front of them.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2150",
    questionText: "Why should you look carefully for motorcyclists and cyclists at junctions?",
    options: [
    "They may want to turn into the side road",
    "They may slow down to let you turn",
    "They're harder to see",
    "They might not see you turn",
    ],
    correctIndex: 2,
    explanation: "Cyclists and motorcyclists are smaller than other vehicles and so are more difficult to see. They can easily be hidden from your view by cars parked near a junction.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2151",
    questionText: "You're waiting to come out of a side road. Why should you look carefully for motorcycles?",
    options: [
    "Motorcycles are usually faster than cars",
    "Police patrols often use motorcycles",
    "Motorcycles can easily be hidden behind obstructions",
    "Motorcycles have right of way",
    ],
    correctIndex: 2,
    explanation: "If you're waiting to emerge from a side road, look carefully for motorcycles: they can be difficult to see. Be especially careful if there are parked vehicles or other obstructions restricting your view.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2153",
    questionText: "Why do motorcyclists use dipped headlights in daylight?",
    options: [
    "So that the rider can be seen more easily",
    "To stop the battery overcharging",
    "To improve the rider’s vision",
    "The rider is inviting you to proceed",
    ],
    correctIndex: 0,
    explanation: "A motorcycle can be lost from sight behind another vehicle. The use of headlights helps to make it more conspicuous and therefore more easily seen.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2156",
    questionText: "Why do motorcyclists wear bright clothing?",
    options: [
    "They must do so by law",
    "It helps keep them cool in summer",
    "The colours are popular",
    "To make them more visible",
    ],
    correctIndex: 3,
    explanation: "Motorcycles and mopeds are generally smaller than other vehicles and can be difficult to see. Wearing bright clothing makes it easier for other road users to see a motorcyclist approaching, especially at junctions.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2160",
    questionText: "Why do motorcyclists often look round over their right shoulder just before turning right?",
    options: [
    "To listen for traffic behind them",
    "Motorcycles do not have mirrors",
    "It helps them balance as they turn",
    "To check for traffic in their blind area",
    ],
    correctIndex: 3,
    explanation: "When you see a motorcyclist take a glance over their shoulder, they're probably about to change direction. Recognising a clue like this helps you to anticipate their next action. This can improve road safety for you and others.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2161",
    questionText: "Which is the most vulnerable road user?",
    options: [
    "Car driver",
    "Tractor driver",
    "Lorry driver",
    "Motorcyclist",
    ],
    correctIndex: 3,
    explanation: "Pedestrians and riders on 2 wheels can be harder to see than other road users. Make sure you look for them, especially at junctions. Effective observation, coupled with appropriate action, can save lives.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2168",
    questionText: "You're approaching a roundabout. What should you do if there are horses being ridden in front of you?",
    options: [
    "Sound your horn as a warning",
    "Treat them like any other vehicle",
    "Give them plenty of room",
    "Accelerate past as quickly as possible",
    ],
    correctIndex: 2,
    explanation: "Horse riders often keep to the outside of the roundabout even if they're turning right. Give them plenty of room and remember that they may have to cross lanes of traffic.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2491",
    questionText: "As you approach a pelican crossing, the lights change to green. What should you do if older people are still crossing?",
    options: [
    "Wave them to cross as quickly as they can",
    "Rev your engine to make them hurry",
    "Flash your lights in case they‘ve not noticed you",
    "Wait patiently while they cross",
    ],
    correctIndex: 3,
    explanation: "If the lights turn to green, wait for any pedestrians to clear the crossing. Allow them to finish crossing the road in their own time, and do not try to hurry them by revving your engine.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2516",
    questionText: "What action should you take when you see flashing amber lights under a school warning sign?",
    options: [
    "Reduce speed until you're clear of the area",
    "Keep up your speed and sound the horn",
    "Increase your speed to clear the area quickly",
    "Wait at the lights until they stop flashing",
    ],
    correctIndex: 0,
    explanation: "The flashing amber lights are switched on to warn you that children may be crossing near a school. Slow down and take extra care, as you may have to stop.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2545",
    questionText: "Why should these road markings be kept clear?",
    options: [
    "To allow children to be dropped off at school",
    "To allow teachers to park",
    "To allow children to be picked up after school",
    "To allow children to see and be seen when they're crossing the road",
    ],
    correctIndex: 3,
    explanation: "The markings are there to show that the area should be kept clear. This is to allow an unrestricted view for\r\n• approaching drivers and riders\r\n• children wanting to cross the road.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2559",
    questionText: "Where would you see this sign?",
    options: [
    "Near a school crossing",
    "At a playground entrance",
    "On a school bus",
    "At a ‘pedestrians only’ area",
    ],
    correctIndex: 2,
    explanation: "School buses can stop to pick up or drop off schoolchildren at places that are not designated bus stops. Watch out for children crossing the road to catch the bus or from the far side of the bus if they've just been dropped off.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2561",
    questionText: "You're following 2 cyclists as they approach a roundabout in the left-hand lane. Where would you expect the cyclists to go?",
    options: [
    "Left",
    "Right",
    "Any direction",
    "Straight ahead",
    ],
    correctIndex: 2,
    explanation: "Cyclists approaching a roundabout in the left-hand lane may be turning right but may not have been able to get into the correct lane due to heavy traffic. They may also feel safer keeping to the left all the way around the roundabout. Be aware of them and give them plenty of room.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2562",
    questionText: "You're travelling behind a moped. What should you do if you want to turn left a short distance ahead?",
    options: [
    "Overtake the moped before the junction",
    "Pull alongside the moped and stay level until just before the junction",
    "Sound your horn as a warning and pull in front of the moped",
    "Stay behind until the moped has passed the junction",
    ],
    correctIndex: 3,
    explanation: "Passing the moped and turning into the junction could mean that you cut across the front of the rider. This might force them to slow down, stop or even lose control. Stay behind the moped until it has passed the junction and then you can turn without affecting the rider.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2564",
    questionText: "You see a horse rider as you approach a roundabout. What should you do if they're signalling right but keeping well to the left?",
    options: [
    "Proceed as normal",
    "Keep close to them",
    "Cut in front of them",
    "Stay well back",
    ],
    correctIndex: 3,
    explanation: "Allow the horse rider to enter and exit the roundabout in their own time. They may feel safer keeping to the left all the way around the roundabout. Do not get up close behind or alongside them, because that would probably upset the horse and create a dangerous situation.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2565",
    questionText: "How should you react to inexperienced drivers?",
    options: [
    "Sound your horn to warn them of your presence",
    "Be patient and prepare for them to react more slowly",
    "Flash your headlights to indicate that it's safe for them to proceed",
    "Overtake them as soon as possible",
    ],
    correctIndex: 1,
    explanation: "Learners might not have confidence when they first start to drive. Allow them plenty of room and do not react adversely to their hesitation. We all learn from experience, but new drivers will have had less practice in dealing with all the situations that might occur.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2566",
    questionText: "What should you do when you're following a learner driver who stalls at a junction?",
    options: [
    "Be patient, as you expect them to make mistakes",
    "Stay very close behind and flash your headlights",
    "Start to rev your engine if they take too long to restart",
    "Immediately steer around them and drive on",
    ],
    correctIndex: 0,
    explanation: "Learning to drive is a process of practice and experience. Try to understand this and tolerate those who make mistakes while they're learning.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2587",
    questionText: "You're on a country road. What should you expect to see coming towards you on your side of the road?",
    options: [
    "Motorcycles",
    "Bicycles",
    "Pedestrians",
    "Horse riders",
    ],
    correctIndex: 2,
    explanation: "On a quiet country road, always be aware that there may be a hazard just around the next bend, such as a slow-moving vehicle or pedestrians. Pedestrians are advised to walk on the right-hand side of the road if there's no pavement, so they may be walking towards you on your side of the road.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2601",
    questionText: "You're following a cyclist. What should you do when you wish to turn left a short distance ahead?",
    options: [
    "Overtake the cyclist before you reach the junction",
    "Pull alongside the cyclist and stay level until after the junction",
    "Hold back until the cyclist has passed the junction",
    "Go around the cyclist on the junction",
    ],
    correctIndex: 2,
    explanation: "Make allowances for cyclists, and give them plenty of room. Do not overtake and then immediately turn left. Be patient and turn behind them when they've passed the junction.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2602",
    questionText: "A horse rider is in the left-hand lane approaching a roundabout. Where should you expect the rider to go?",
    options: [
    "In any direction",
    "To the right",
    "To the left",
    "Straight ahead",
    ],
    correctIndex: 0,
    explanation: "Horses and their riders move more slowly than other road users. They might not have time to cut across heavy traffic to take up a position in the right-hand lane. For this reason, a horse and rider may approach a roundabout in the left-hand lane even though they're turning right.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2660",
    questionText: "Powered vehicles used by disabled people are small and can be hard to see. What must they display if they're travelling on a dual carriageway?",
    options: [
    "Flashing red beacon",
    "Flashing green beacon",
    "Flashing blue beacon",
    "Flashing amber beacon",
    ],
    correctIndex: 3,
    explanation: "Powered vehicles used by disabled people are small and low making them hard to see on the road. They also travel very slowly. On an unrestricted dual carriageway, they must display a flashing amber beacon to warn other road users of their presence.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2696",
    questionText: "What does it mean when a moving vehicle is showing a flashing amber beacon?",
    options: [
    "The vehicle is slow moving",
    "The vehicle has broken down",
    "The vehicle is a doctor's car",
    "The vehicle belongs to a school crossing patrol",
    ],
    correctIndex: 0,
    explanation: "Different coloured beacons warn of different types of vehicle needing special attention. Blue beacons are used on emergency vehicles that need priority. Green beacons are found on doctors' cars. Amber beacons generally denote slower moving vehicles, which are often large. These vehicles are usually involved in road maintenance or local amenities and make frequent stops.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2726",
    questionText: "What does this sign mean?",
    options: [
    "Contraflow cycle lane",
    "With-flow cycle lane",
    "Bicycles and buses only",
    "No bicycles or buses",
    ],
    correctIndex: 1,
    explanation: "Usually, a picture of a bicycle will also be painted on the road, and sometimes the lane will have a different coloured surface. Leave these areas clear for cyclists and do not pass too closely when you overtake.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2727",
    questionText: "What should you do when you see these horse riders in front?",
    options: [
    "Pull out to the middle of the road",
    "Slow down and be ready to stop",
    "Switch on your hazard warning lights",
    "Give a right-turn signal",
    ],
    correctIndex: 1,
    explanation: "Be particularly careful when approaching horse riders – slow down and be prepared to stop. Always pass wide and slowly, and look out for signals given by the riders. Horses are unpredictable: always treat them as potential hazards and take great care when passing them.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2729",
    questionText: "What's the purpose of these road markings?",
    options: [
    "To make sure children can see and be seen when they're crossing the road",
    "To allow teachers to have clear access to the school",
    "To make sure delivery vehicles have easy access to the school",
    "To allow parents to pick up or drop off children safely",
    ],
    correctIndex: 0,
    explanation: "These markings are found on the road outside schools. Do not stop or park on them, even to set down or pick up children. The markings are there to make sure that drivers, riders, children and other pedestrians have a clear view of the road in all directions.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2730",
    questionText: "What should you do if the left-hand pavement is closed due to street repairs?",
    options: [
    "Watch out for pedestrians walking in the road",
    "Use your right-hand mirror more often",
    "Speed up to get past the roadworks more quickly",
    "Position close to the left-hand kerb",
    ],
    correctIndex: 0,
    explanation: "Where street repairs have closed off pavements, proceed carefully and slowly, as pedestrians might have to walk in the road.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2731",
    questionText: "What should you do when you're following a motorcyclist along a road that has a poor surface?",
    options: [
    "Follow closely so they can see you in their mirrors",
    "Overtake immediately to avoid delays",
    "Allow extra room in case they swerve to avoid potholes",
    "Allow the same room as normal to avoid wasting road space",
    ],
    correctIndex: 2,
    explanation: "To avoid being unbalanced, a motorcyclist might swerve to avoid potholes and bumps in the road. Be prepared for this and allow them extra space.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2840",
    questionText: "What does this sign mean?",
    options: [
    "No cycling",
    "Cycle route ahead",
    "Bicycle parking only",
    "End of cycle route",
    ],
    correctIndex: 1,
    explanation: "More people are cycling today and cycle routes are being extended in our towns and cities to provide safe cycling routes. Respect the presence of cyclists on the road and give them plenty of room if you need to pass.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2849",
    questionText: "You're approaching this roundabout. What should you do when a cyclist is keeping to the left while signalling to turn right?",
    options: [
    "Sound your horn",
    "Overtake them",
    "Assume they're turning left",
    "Allow them space to turn",
    ],
    correctIndex: 3,
    explanation: "Cycling in today’s heavy traffic can be hazardous. Some cyclists may not feel safe crossing the path of traffic to take up a position in an outside lane. Be aware of this and understand that, although they're in the left-hand lane, the cyclist might be turning right.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2850",
    questionText: "What should you do when you're approaching this crossing?",
    options: [
    "Prepare to slow down and stop",
    "Stop and wave the pedestrians across",
    "Speed up and pass by quickly",
    "Continue unless the pedestrians step out",
    ],
    correctIndex: 0,
    explanation: "Be courteous and prepare to stop. Do not wave people across, because this could be dangerous if another vehicle is approaching the crossing.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2851",
    questionText: "What does it mean if you see a pedestrian with a dog that has a yellow or burgundy coat?",
    options: [
    "The pedestrian is an older person",
    "The pedestrian is a dog trainer",
    "The pedestrian is colour-blind",
    "The pedestrian is deaf",
    ],
    correctIndex: 3,
    explanation: "Dogs trained to help deaf people have a yellow or burgundy coat. If you see one, you should take extra care, as the pedestrian may not be aware of vehicles approaching.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2854",
    questionText: "Who may use toucan crossings?",
    options: [
    "Motorcyclists and cyclists",
    "Motorcyclists and pedestrians",
    "Only cyclists",
    "Cyclists and pedestrians",
    ],
    correctIndex: 3,
    explanation: "There are some crossings where cycle routes lead cyclists to cross at the same place as pedestrians. These are called toucan crossings. Always look out for cyclists, as they're likely to be approaching faster than pedestrians.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2860",
    questionText: "This junction, controlled by traffic lights, has a marked area between 2 stop lines. What's this for?",
    options: [
    "To allow taxis to position in front of other traffic",
    "To allow people with disabilities to cross the road",
    "To allow cyclists and pedestrians to cross the road together",
    "To allow cyclists to position in front of other traffic",
    ],
    correctIndex: 3,
    explanation: "These are known as advanced stop lines. When the lights are red (or about to become red), you should stop at the first white line. However, if you've crossed that line as the lights change, you must stop at the second line even if it means you're in the area reserved for cyclists.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2896",
    questionText: "You're about to overtake a cyclist. Why should you leave them as much room as you would give to a car?",
    options: [
    "The cyclist might speed up",
    "The cyclist might get off their bicycle",
    "The cyclist might be unsettled if you pass too near them",
    "The cyclist might have to make a left turn",
    ],
    correctIndex: 2,
    explanation: "Before overtaking, assess the situation. Look well ahead to see whether the cyclist will need to change direction. Be especially aware of a cyclist approaching parked vehicles, as they'll need to alter course. Do not pass too closely or cut in sharply as this could unsettle the rider.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2908",
    questionText: "What should you do when you're passing loose sheep on the road?",
    options: [
    "Briefly sound your horn",
    "Go very slowly",
    "Pass quickly but quietly",
    "Herd them to the side of the road",
    ],
    correctIndex: 1,
    explanation: "Slow down and be ready to stop if you see animals in the road ahead. Animals are easily frightened by noise and vehicles passing too close to them. Stop if you're signalled to do so by the person in charge.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2941",
    questionText: "At night, what does it mean if you see a pedestrian wearing reflective clothing and carrying a bright red light?",
    options: [
    "You're approaching roadworks",
    "You're approaching an organised walk",
    "You're approaching a slow-moving vehicle",
    "You're approaching a traffic danger spot",
    ],
    correctIndex: 1,
    explanation: "The people on the walk should be keeping to the left, but do not assume this. Pass carefully, making sure you have time to do so safely. Be aware that the pedestrians have their backs to you and may not know that you’re there.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "AB2943",
    questionText: "You’ve just passed your driving or riding test. How can you reduce your risk of being involved in a collision?",
    options: [
    "By always staying close to the vehicle in front",
    "By never going over 40 mph",
    "By staying in the left-hand lane on all roads",
    "By taking further training",
    ],
    correctIndex: 3,
    explanation: "New drivers and riders are often involved in a collision or incident early in their driving career. Due to a lack of experience, they may not react to hazards appropriately. Approved training courses are offered by driver and rider training schools for people who have passed their test but want extra training.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1131",
    questionText: "You want to reverse into a side road. What should you do if you’re not sure that the area behind your car is clear?",
    options: [
    "Look through the rear window only",
    "Get out and check",
    "Check the mirrors only",
    "Carry on, assuming it's clear",
    ],
    correctIndex: 1,
    explanation: "If you cannot tell whether there's anything behind you, it's always safest to check before reversing. There may be a small child or a low obstruction close behind your car.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1132",
    questionText: "You're about to reverse into a side road. What should you do if a pedestrian is waiting to cross behind your car?",
    options: [
    "Wave to the pedestrian to stop",
    "Give way to the pedestrian",
    "Sound your horn to warn the pedestrian",
    "Reverse before the pedestrian starts to cross",
    ],
    correctIndex: 1,
    explanation: "If you need to reverse into a side road, try to find a place that’s free from traffic and pedestrians. Look all around before and during the manoeuvre. Stop and give way to any pedestrians who want to cross behind you. Avoid waving them across, sounding the horn, flashing your lights or giving any signals that could mislead them and create a dangerous situation.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1133",
    questionText: "Which road users are most difficult to see when you're reversing your car?",
    options: [
    "Motorcyclists",
    "Car drivers",
    "Cyclists",
    "Children",
    ],
    correctIndex: 3,
    explanation: "It may not be possible to see a small child through the rear windscreen of your vehicle. Be aware of this before you reverse. If there are children about, get out and check that it's clear before reversing.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1135",
    questionText: "You want to turn right from a junction. What should you do if your view is restricted by parked vehicles?",
    options: [
    "Move out quickly, but be prepared to stop",
    "Sound your horn and pull out if there's no reply",
    "Stop, then move forward slowly until you have a clear view",
    "Stop, get out and look along the main road to check",
    ],
    correctIndex: 2,
    explanation: "If you want to turn right from a junction and your view is restricted, stop. Ease forward until you can see – something might be approaching.\r\nIf you don't know, don't go.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1136",
    questionText: "You're at the front of a queue of traffic waiting to turn right into a side road. Why is it important to check your right mirror just before turning?",
    options: [
    "To look for pedestrians about to cross",
    "To check for overtaking vehicles",
    "To make sure the side road is clear",
    "To check for emerging traffic",
    ],
    correctIndex: 1,
    explanation: "A motorcyclist could be riding along the outside of the queue. Always check your mirror before turning, as situations behind you can change while you've been waiting to turn.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1139",
    questionText: "You've driven up to a pelican crossing. What must you do while the amber light is flashing?",
    options: [
    "Signal the pedestrian to cross",
    "Always wait for the green light before proceeding",
    "Give way to any pedestrians on the crossing",
    "Wait for the red-and-amber light before proceeding",
    ],
    correctIndex: 2,
    explanation: "The flashing amber light allows pedestrians already on the crossing to get to the other side before a green light shows to the traffic. Be aware that some pedestrians, such as older people and young children, need longer to cross. Let them do this at their own pace.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1140",
    questionText: "You've stopped at a pelican crossing. What should you do if a disabled person is crossing slowly in front of you and the lights change to green?",
    options: [
    "Wait for them to finish crossing",
    "Drive in front of them",
    "Edge forward slowly",
    "Sound your horn",
    ],
    correctIndex: 0,
    explanation: "At a pelican crossing, the green light means you may proceed as long as the crossing is clear. If someone has not finished crossing, be patient and wait for them, whether they're disabled or not.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1142",
    questionText: "You're driving past a line of parked cars. What should you do if a ball bounces out into the road ahead?",
    options: [
    "Continue driving at the same speed and sound your horn",
    "Continue driving at the same speed and flash your headlights",
    "Slow down and be prepared to stop for children",
    "Stop and wave the children across to fetch their ball",
    ],
    correctIndex: 2,
    explanation: "Beware of children playing in the street and running out into the road. If a ball bounces out from the pavement, slow down and be prepared to stop. Do not encourage anyone to retrieve it. Other road users may not see your signal and you might lead a child into a dangerous situation.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1145",
    questionText: "You want to turn right from a main road into a side road. What should you do just before turning?",
    options: [
    "Cancel your right-turn signal",
    "Select first gear",
    "Check for traffic overtaking on your right",
    "Stop and set the parking brake",
    ],
    correctIndex: 2,
    explanation: "In some circumstances, your indicators may be difficult to see and another road user may not realise you're about to turn. A final check in your mirror and blind spot can help you to see an overtaking vehicle, so that you can avoid turning across their path.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1147",
    questionText: "You're driving in a slow-moving queue of traffic. What should you do just before changing lane?",
    options: [
    "Sound the horn and flash your lights",
    "Look for motorcyclists filtering through the traffic",
    "Give a ‘slowing down’ arm signal",
    "Change down to first gear",
    ],
    correctIndex: 1,
    explanation: "In queuing traffic, motorcyclists could be passing you on either side. Use your mirrors and check your blind area before changing lanes or changing direction.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1148",
    questionText: "You're driving in town. Why should you be careful if there's a bus at a bus stop on the other side of the road?",
    options: [
    "The bus might have broken down",
    "Pedestrians might come from behind the bus",
    "The bus might move off suddenly",
    "The bus might remain stationary",
    ],
    correctIndex: 1,
    explanation: "If you see a bus ahead, watch out for pedestrians. They might not be able to see you if they’re behind the bus.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1149",
    questionText: "How should you overtake horse riders?",
    options: [
    "Drive up close and overtake as soon as possible",
    "Speed is not important but allow plenty of room",
    "Use your horn just once to warn them",
    "Drive slowly and leave plenty of room",
    ],
    correctIndex: 3,
    explanation: "When you decide to overtake a horse rider, make sure you can do so safely before you move out. Leave them plenty of room and pass slowly. Passing too close could startle the horse and unseat the rider.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1516",
    questionText: "Why should you allow extra room while overtaking a motorcyclist on a windy day?",
    options: [
    "The rider may turn off suddenly to get out of the wind",
    "The rider may be blown in front of you",
    "The rider may stop suddenly",
    "The rider may be travelling faster than normal",
    ],
    correctIndex: 1,
    explanation: "If you’re driving in high winds, be aware that the conditions might make a motorcyclist (or cyclist) swerve or wobble. Take this into consideration if you’re following or wish to overtake a two-wheeled vehicle.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1563",
    questionText: "Where should you take particular care to look for motorcyclists and cyclists?",
    options: [
    "On dual carriageways",
    "At junctions",
    "At zebra crossings",
    "On one-way streets",
    ],
    correctIndex: 1,
    explanation: "Motorcyclists and cyclists are often more difficult to see at junctions. They're easily hidden from view and you may not be able to see them approaching a junction if your view is partially blocked; for example, by other traffic.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1577",
    questionText: "The road outside this school is marked with yellow zigzag lines. What do these lines mean?",
    options: [
    "You may park on the lines when dropping off schoolchildren",
    "You may park on the lines when picking up schoolchildren",
    "You should not wait or park your vehicle here",
    "You must stay with your vehicle if you park here",
    ],
    correctIndex: 2,
    explanation: "Parking here would block other road users' view of the school entrance and would endanger the lives of children on their way to and from school.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1672",
    questionText: "You're driving past parked cars. What should you do if you see a bicycle wheel sticking out between the cars?",
    options: [
    "Accelerate past quickly and sound your horn",
    "Slow down and wave the cyclist across",
    "Brake sharply and flash your headlights",
    "Slow down and be prepared to stop for a cyclist",
    ],
    correctIndex: 3,
    explanation: "Scan the road as you drive. Try to anticipate hazards by being aware of the places where they're likely to occur. You’ll then be able to react in good time.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1674",
    questionText: "You're driving at night. What should you do if you're dazzled by a vehicle behind you?",
    options: [
    "Set your mirror to the anti-dazzle position",
    "Set your mirror to dazzle the other driver",
    "Brake sharply to a stop",
    "Switch your rear lights on and off",
    ],
    correctIndex: 0,
    explanation: "The interior mirror of most vehicles can be set to an anti-dazzle position. You'll still be able to see the lights of the traffic behind you, but the dazzle will be greatly reduced.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: "BB1678",
    questionText: "You're driving towards a zebra crossing. What should you do if a person in a wheelchair is waiting to cross?",
    options: [
    "Continue on your way",
    "Wave to the person to cross",
    "Wave to the person to wait",
    "Be prepared to stop",
    ],
    correctIndex: 3,
    explanation: "You should slow down and be prepared to stop, as you would for an able-bodied person. Do not wave them across, as other traffic may not stop.",
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
];
