// PLACEHOLDER - replace with licensed DVSA content
import { Question, TopicCategory } from '@clearpass/core';

export const vulnerableRoadUsersQuestions: Question[] = [
  {
    id: 'VRU_001',
    questionText: 'How much space should you leave when overtaking a cyclist at speeds above 30mph?',
    options: [
      'At least 0.5 metres',
      'At least 1 metre',
      'At least 1.5 metres',
      'At least 2 metres',
    ],
    correctIndex: 2,
    explanation:
      'The Highway Code states you should give cyclists at least 1.5 metres when overtaking at speeds above 30mph. At lower speeds, leave at least 1 metre. Cyclists can swerve unexpectedly to avoid potholes or debris.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_002',
    questionText: 'A pedestrian has stepped onto a zebra crossing ahead of you. What must you do?',
    options: [
      'Sound your horn to warn them you are approaching',
      'Slow down and give way to the pedestrian',
      'Flash your headlights so they know to wait',
      'Proceed carefully as you have right of way if already moving',
    ],
    correctIndex: 1,
    explanation:
      'At a zebra crossing, once a pedestrian has stepped onto the crossing, they have priority and you must give way. Do not wave or signal to them - let them cross safely without pressure.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_003',
    questionText: 'A horse rider holds out their arm and moves it up and down. What does this signal mean?',
    options: [
      'They are turning right',
      'They are asking you to slow down',
      'They are warning of a hazard ahead',
      'They are turning left',
    ],
    correctIndex: 1,
    explanation:
      'A horse rider moving their arm up and down is asking you to slow down. Horses can be unpredictably frightened by vehicles. Pass slowly and quietly, leaving plenty of room, and do not accelerate sharply until well past.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_004',
    questionText: 'You are approaching a group of young children near a school crossing. What extra precautions should you take?',
    options: [
      'Sound your horn to warn them of your presence',
      'Reduce speed well in advance and be prepared to stop',
      'Move to the centre of the road to pass wide',
      'Flash your lights so they see you approaching',
    ],
    correctIndex: 1,
    explanation:
      'Children are unpredictable - they may step into the road without warning. Reduce speed well in advance near schools, especially at arrival and departure times, and be prepared to stop.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_005',
    questionText: 'A motorcyclist is filtering slowly past stationary traffic. What should you do?',
    options: [
      'Open your door slightly to discourage the motorcyclist from passing',
      'Be aware and do not change lane or position without checking for motorcyclists',
      'Sound your horn to warn the motorcyclist it is not safe to filter',
      'Move closer to the kerb to prevent the motorcyclist from passing',
    ],
    correctIndex: 1,
    explanation:
      'Motorcyclists filtering through slow or stationary traffic is legal. Check for motorcyclists before moving position or opening your door. Do not deliberately obstruct them.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_006',
    questionText: 'An elderly pedestrian is crossing the road slowly when the lights change to green in your favour. What should you do?',
    options: [
      'Proceed slowly - they should move out of the way',
      'Sound a gentle warning with the horn to let them know the lights have changed',
      'Wait patiently until they have safely reached the pavement',
      'Edge forward to show them you need to go',
    ],
    correctIndex: 2,
    explanation:
      'Pedestrians who are already crossing must always be allowed to complete their crossing safely, regardless of the traffic signal state. Elderly or disabled people may need extra time. Never pressure them to hurry.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_007',
    questionText: 'You see a person carrying a white cane at the roadside. What does this tell you?',
    options: [
      'They are a road worker and you should stop for instructions',
      'They have a visual impairment and may not see your vehicle approaching',
      'They are partially deaf and may not hear your approach',
      'They are an older person and may cross slowly',
    ],
    correctIndex: 1,
    explanation:
      'A white cane indicates a visual impairment. The person may not see your vehicle at all. Approach with great care, slow down, and be prepared to stop and wait until they have safely crossed.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_008',
    questionText: 'At a junction with an Advanced Stop Line (ASL) for cyclists, where must you stop when the lights are red?',
    options: [
      'At the second white line, leaving the cycle zone clear',
      'At the first white line, before the cycle zone',
      'Anywhere in the cycle zone if you arrive there before it is occupied',
      'At the same point you would stop at any other junction',
    ],
    correctIndex: 1,
    explanation:
      'When traffic lights are red at a junction with an Advanced Stop Line, you must stop at the first white line, not the second. This leaves the forward cycle zone clear for cyclists to position themselves safely ahead of traffic.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_009',
    questionText: 'You are driving at night and see a pedestrian walking on the road wearing dark clothing. What should you do?',
    options: [
      'Flash your headlights to warn them',
      'Slow down significantly and be prepared to stop',
      'Sound your horn continuously until they move to the pavement',
      'Switch to full-beam headlights to see them more clearly',
    ],
    correctIndex: 1,
    explanation:
      'Pedestrians in dark clothing are very difficult to see at night. Reduce your speed, use dipped headlights, and be prepared to stop. Switching to full-beam could dazzle the pedestrian, making the situation more dangerous.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_010',
    questionText: 'Why are motorcyclists particularly at risk at junctions?',
    options: [
      'Motorcycles have poor braking compared to cars',
      'Their smaller size makes them harder to see, and drivers may misjudge their speed',
      'Motorcycles are not permitted to filter at junctions',
      'Motorcyclists tend to exceed the speed limit more than other drivers',
    ],
    correctIndex: 1,
    explanation:
      'Motorcycles have a smaller profile than cars, making them harder to see, especially in mirrors and blind spots. Their speed is also harder to judge. "Sorry, I did not see the motorcyclist" is one of the most common causes of junction collisions.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_011',
    questionText: 'A school crossing patrol officer is displaying their stop sign as you approach. What must you do?',
    options: [
      'Slow to below 20mph and proceed with care',
      'Stop completely and wait until the officer gives a clear signal to proceed',
      'Give way to any children who are actually in the road',
      'Stop if children are present but proceed if the road is empty',
    ],
    correctIndex: 1,
    explanation:
      'When a school crossing patrol officer displays the stop board, you are legally required to stop and wait. You must not proceed until the officer has cleared the crossing and signals you to go.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_012',
    questionText: 'A cyclist signals to turn right at a junction ahead. How should you respond?',
    options: [
      'Overtake the cyclist quickly before they complete the manoeuvre',
      'Hang back and give the cyclist time and space to complete the turn safely',
      'Sound your horn to acknowledge their signal',
      'Flash your headlights to indicate you have seen them',
    ],
    correctIndex: 1,
    explanation:
      'Give cyclists space and time to complete their manoeuvre. Do not pressure them or attempt to squeeze past. A cyclist turning right will need to move towards the centre of the road and is vulnerable to following traffic.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_013',
    questionText: 'You are passing a horse and rider on a country road. The horse becomes startled. What should you do?',
    options: [
      'Accelerate past quickly to end the disturbance sooner',
      'Stop completely if necessary, switch off the engine, and wait calmly',
      'Sound the horn briefly so the rider knows you are there',
      'Rev the engine to urge the horse forward',
    ],
    correctIndex: 1,
    explanation:
      'If a horse becomes startled, stopping completely and switching off the engine is the safest action. Any noise or sudden movement can cause the horse to bolt and the rider to be injured. Be patient and wait for the horse to calm down.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_014',
    questionText: 'A pedestrian refuge (island) splits a wide road into two halves. How should you treat each half?',
    options: [
      'Treat the entire road as one crossing - give way if any pedestrians are on either half',
      'Treat each half as a separate crossing - give way if pedestrians are on your half',
      'Pedestrians must wait on the island; vehicles always have priority',
      'Give way only at the far side of the road crossing',
    ],
    correctIndex: 1,
    explanation:
      'A pedestrian refuge divides a wide road into two separate crossings. Treat each half independently. Give way to pedestrians if they are on your half of the road, but you are not obliged to stop for pedestrians waiting on the island.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_015',
    questionText: 'Why should you take extra care when overtaking cyclists in windy conditions?',
    options: [
      'Cyclists are legally required to dismount in strong winds',
      'Strong crosswinds can blow a cyclist into your path unexpectedly',
      'Wind noise prevents cyclists from hearing your approach',
      'Cyclists are entitled to ride in the middle of the lane in strong winds',
    ],
    correctIndex: 1,
    explanation:
      'Sudden gusts of wind can push a cyclist unexpectedly into the path of a passing vehicle. In windy conditions, leave extra space when overtaking and be prepared for sudden lateral movement by the cyclist.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_016',
    questionText: 'You are following a motorcyclist on a wet road. Why is extra caution required?',
    options: [
      'Motorcycles have better brakes and will stop faster, requiring you to brake more sharply',
      'Motorcycles are more vulnerable to skidding on wet or painted road markings',
      'Wet roads reduce your field of vision from behind a motorcycle',
      'Motorcycles are required by law to switch to lower speeds on wet roads',
    ],
    correctIndex: 1,
    explanation: 'Wet conditions reduce tyre grip significantly for motorcyclists, who are particularly vulnerable on painted road markings, manhole covers, and wet leaves. Allow extra following distance and be prepared for the motorcyclist to brake or swerve unexpectedly.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_017',
    questionText: 'You see a pedestrian using a white cane with a red band. What does this tell you?',
    options: [
      'They are a traffic marshal',
      'They have both a visual and hearing impairment (deafblind)',
      'They are only partially sighted and can see you approaching',
      'They are a pedestrian who needs assistance crossing',
    ],
    correctIndex: 1,
    explanation: 'A white cane with a red band indicates the person is both blind and deaf (deafblind). They cannot see or hear your vehicle approaching and depend entirely on others and their cane. Approach with extreme caution and give them maximum time to cross safely.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_018',
    questionText: 'What does Highway Code Rule 72 say about cyclists riding two abreast?',
    options: [
      'It is illegal for cyclists to ride two abreast on any road',
      'Cyclists may ride two abreast when it is safe and not unreasonable to do so',
      'Cyclists may only ride two abreast on roads with a speed limit of 20mph or below',
      'Two cyclists abreast may only ride on cycle paths, not on public roads',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 66 (updated 2022) confirms that cyclists can ride two abreast, and this can actually be safer as it makes the group more visible and more predictable. Drivers should be patient and only overtake when there is enough space to do so safely.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_019',
    questionText: 'What child car seat is required for a child aged between 4 and 11 who has not reached 135cm in height?',
    options: [
      'A Group 0 baby seat with harness',
      'A booster cushion or high-backed booster seat secured by the adult seatbelt',
      'No seat is required - the adult seatbelt is sufficient from age 4',
      'A rearward-facing seat until the child weighs 18kg',
    ],
    correctIndex: 1,
    explanation: 'Children aged approximately 4 to 11 (or up to 135cm/12 years) must use an appropriate child car seat or booster that works with the adult seatbelt. The driver is responsible for ensuring children under 14 are properly restrained. Using the wrong or no restraint is an offence.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_020',
    questionText: 'A cyclist is riding on the road when there is a cycle lane available on the pavement. Must they use it?',
    options: [
      'Yes - cyclists must always use a cycle lane if one is provided',
      'No - cyclists may choose to ride on the road even when a cycle lane exists',
      'Only if the cycle lane is on the road surface, not on the pavement',
      'Yes on A-roads and dual carriageways, but not on residential streets',
    ],
    correctIndex: 1,
    explanation: 'Cyclists are not legally required to use cycle lanes or paths. The Highway Code recommends they use them where practical, but some lanes are unsuitable. Cyclists may prefer to stay on the road for safety or directional reasons. Drivers must still give them the same consideration on the road.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_021',
    questionText: 'A mobility scooter user is travelling on the road. What is the maximum speed they are permitted to travel?',
    options: [
      '4mph on the pavement, 8mph on the road',
      '5mph on the pavement, 10mph on the road',
      '6mph on the pavement, 12mph on the road',
      '10mph on both pavements and roads',
    ],
    correctIndex: 0,
    explanation: 'Class 3 mobility scooters are permitted on roads with a maximum speed of 8mph and a pavement speed of 4mph. Class 2 scooters are limited to pavements and pedestrian areas at 4mph. Treat mobility scooter users as vulnerable road users requiring patience and care.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_022',
    questionText: 'You are approaching a pedestrian crossing and a person with a guide dog is waiting to cross. What should you do?',
    options: [
      'Sound your horn gently to alert the guide dog to your presence',
      'Stop and allow them to cross in their own time without pressure',
      'Flash your lights to indicate you are stopping',
      'Wait until they press the button before stopping',
    ],
    correctIndex: 1,
    explanation: 'Guide dog users may be visually impaired and rely entirely on their dog\'s training. Stop without sounding the horn or making sudden gestures - sudden noise can distract or confuse the dog. Allow them to cross without pressure or rushing.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_023',
    questionText: 'You are driving and a large lorry passes a cyclist close by, blowing the cyclist sideways. What does this illustrate?',
    options: [
      'The cyclist was riding too close to the centre of the road',
      'Large vehicles create air turbulence that can destabilise cyclists when passing close',
      'The cyclist was riding an unsuitably light bicycle for road use',
      'The lorry was driving illegally close to the cyclist',
    ],
    correctIndex: 1,
    explanation: 'Large vehicles create significant air turbulence that can push a cyclist sideways, particularly at motorway or dual carriageway speeds. Drivers of large vehicles should give extra width when passing cyclists. Even at legal distances, the turbulence can be significant.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_024',
    questionText: 'What should you do when you want to open your car door after parking near a road where cyclists may be passing?',
    options: [
      'Open the door quickly so cyclists can see it and react',
      'Check your wing mirror and use the "Dutch Reach" technique - open the door with your far hand, which naturally turns you to check',
      'Sound your horn before opening the door as a warning',
      'Open the door a small amount first to alert approaching cyclists',
    ],
    correctIndex: 1,
    explanation: 'The "Dutch Reach" method involves reaching across with your far hand to open the door, which rotates your body so you naturally look backwards to check for approaching cyclists. Car dooring is a significant cause of injuries to cyclists and can be fatal.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_025',
    questionText: 'What is the minimum age for a moped rider to use a public road?',
    options: [
      '14 years old with an AM category provisional licence',
      '16 years old with an AM category provisional licence',
      '17 years old with a full A1 licence',
      '16 years old with a full AM licence',
    ],
    correctIndex: 1,
    explanation: 'You can ride a moped (up to 50cc) on public roads from age 16, provided you hold an AM category provisional licence, have completed Compulsory Basic Training (CBT), and display L plates. Mopeds are limited to 28mph on public roads.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_026',
    questionText: 'When driving past a stationary bus that has stopped to let passengers off, what is the main hazard?',
    options: [
      'The bus driver may pull out suddenly before checking mirrors',
      'Passengers may step into the road in front of or behind the bus without looking',
      'The bus exhaust may reduce visibility for following drivers',
      'The bus may be blocking a bus stop area you need to enter',
    ],
    correctIndex: 1,
    explanation: 'Passengers exiting a bus are at high risk because they may step directly into the road to cross, especially from in front of the bus where they cannot see approaching traffic. Slow down when passing any stationary bus and be prepared to stop.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_027',
    questionText: 'Why are young children between two and five particularly vulnerable near roads?',
    options: [
      'They are not yet subject to Highway Code rules',
      'They lack the ability to judge vehicle speed and distance and may act impulsively',
      'They are too small to be seen over parked cars',
      'They are more likely to be walking on roads without pavements',
    ],
    correctIndex: 1,
    explanation: 'Young children cannot reliably judge the speed or distance of approaching vehicles. They also act impulsively and may run into the road without warning. They require constant supervision near roads. Drivers must be especially alert in areas where young children may be present.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_028',
    questionText: 'A motorcyclist approaching from behind is travelling faster than other traffic. What should you do?',
    options: [
      'Speed up to prevent the motorcyclist from overtaking dangerously',
      'Check your mirrors, be aware of their approach, and do not make any sudden movements',
      'Move to the centre of your lane so the motorcyclist cannot pass',
      'Flash your brake lights to warn them to slow down',
    ],
    correctIndex: 1,
    explanation: 'Check your mirrors regularly and be aware of motorcyclists approaching at speed. Do not make sudden lane changes or speed adjustments. If they intend to overtake, allow them to do so safely by maintaining a steady speed and position.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_029',
    questionText: 'What does an Advanced Stop Line (ASL) at traffic lights provide for cyclists?',
    options: [
      'A designated space where cyclists can wait ahead of other vehicles to enable safe departure',
      'A stop line for cyclists who wish to go straight on rather than turn',
      'A zone where cyclists may stop to allow pedestrians to cross',
      'A separate light phase for cyclists that activates when the main light turns red',
    ],
    correctIndex: 0,
    explanation: 'An ASL allows cyclists to position themselves ahead of waiting vehicles at traffic lights. This improves their visibility, allows them to set off before motor vehicles, and prevents vehicles turning across their path. Motorists must not enter the ASL zone when the lights are red.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_030',
    questionText: 'What is a "Compulsory Basic Training" (CBT) certificate required for?',
    options: [
      'All drivers of vehicles under 50cc on private land',
      'Riders of motorcycles and mopeds on public roads with a provisional licence',
      'Drivers taking their practical test after a theory test pass',
      'All newly qualified drivers during their two-year probationary period',
    ],
    correctIndex: 1,
    explanation: 'CBT is mandatory for anyone riding a moped or motorcycle on public roads with a provisional licence. It covers basic vehicle checks, manoeuvring practice, and on-road riding under instruction. A CBT certificate is valid for two years. Riding without completing CBT is illegal.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_031',
    questionText: 'You are in heavy traffic and a pedestrian is waiting to cross the road where there is no crossing. What should you do?',
    options: [
      'Continue - pedestrians at non-crossing points must wait for a safe gap themselves',
      'Slow down, be prepared to give way, and wave the pedestrian across if it is safe',
      'Flash your headlights to signal that they may cross',
      'Sound your horn to warn other drivers of the pedestrian',
    ],
    correctIndex: 1,
    explanation: 'While pedestrians do not have legal priority at non-crossing points, being considerate and allowing them to cross when it is safe to do so is good practice. Be careful that other drivers can also see the pedestrian before waving them across.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_032',
    questionText: 'What extra check must you make before turning left in a built-up area?',
    options: [
      'Check the off-side mirror for overtaking vehicles',
      'Check the nearside mirror and blind spot for cyclists who may be alongside you',
      'Check the rear-view mirror for pedestrians about to cross',
      'No additional checks are required beyond the standard MSM routine',
    ],
    correctIndex: 1,
    explanation: 'Before turning left, always check the nearside (left) mirror and your blind spot for cyclists who may have moved alongside or be filtering on your left. Turning left across a cyclist\'s path is a common and serious collision type.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_033',
    questionText: 'What is the minimum specification for a cycling helmet to be considered legal in the UK?',
    options: [
      'Helmets must meet EN 1078 standard',
      'There is currently no law requiring cyclists to wear a helmet in the UK',
      'Helmets must meet BS 6863 and carry a BSI kitemark',
      'Helmets are only mandatory for children under 14',
    ],
    correctIndex: 1,
    explanation: 'There is currently no legal requirement for cyclists of any age to wear a helmet in the UK, although it is strongly recommended. The Highway Code advises wearing one. The absence of a helmet does not reduce a driver\'s legal responsibility to exercise due care.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_034',
    questionText: 'You are driving a long vehicle and need to turn left at a junction. What specific risk applies to cyclists?',
    options: [
      'Cyclists may be hidden in your off-side blind spot as you swing right to turn',
      'Cyclists may be in the nearside blind spot and be caught under the rear wheels as the vehicle sweeps left',
      'Cyclists may follow you through the junction thinking you are going straight',
      'Cyclists must give way to turning long vehicles at all junctions',
    ],
    correctIndex: 1,
    explanation: 'Long vehicles turning left have a significant nearside blind spot. A cyclist alongside may be crushed by the rear wheels as the vehicle swings wide. Always check the nearside mirrors thoroughly before turning left in a long vehicle and watch for cyclists in this position.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_035',
    questionText: 'What does the 2022 Highway Code update say about the "hierarchy of road users"?',
    options: [
      'All road users have equal priority and equal responsibility',
      'Those who can cause the greatest harm have the greatest responsibility to reduce risk to others - pedestrians are at the top of the hierarchy',
      'Motorists always have the highest priority on public roads',
      'Cyclists have equal priority to pedestrians on all roads',
    ],
    correctIndex: 1,
    explanation: 'The January 2022 Highway Code update introduced a clear hierarchy: pedestrians at the top, followed by cyclists, then horse riders, then motorcyclists, then cars. Those whose vehicles can cause the most harm (drivers) bear the greatest responsibility to protect those who are most vulnerable.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_036',
    questionText: 'You see a group of pedestrians crossing the road as you are about to turn into a side road. What must you do?',
    options: [
      'Sound your horn and proceed carefully',
      'Give way to the pedestrians crossing the road you are turning into',
      'Continue your turn - pedestrians must give way to turning vehicles',
      'Flash your headlights and proceed as pedestrians should not be in the road',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 195 gives pedestrians who are crossing or about to cross a road priority when a vehicle is turning into that road. Drivers must give way. The 2022 updates strengthened this right for pedestrians. Give way and wait until the road is clear.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_037',
    questionText: 'A cyclist is riding on a narrow road and there is no safe opportunity to overtake. What should you do?',
    options: [
      'Overtake as quickly as possible at the first available gap, even if tight',
      'Sound your horn repeatedly to encourage the cyclist to pull over',
      'Follow at a safe distance behind the cyclist until an opportunity to overtake safely arises',
      'Flash your headlights to let the cyclist know you want to pass',
    ],
    correctIndex: 2,
    explanation: 'If you cannot overtake safely, stay behind the cyclist and wait. A cyclist has as much right to use the road as any other vehicle. Impatience, sounding the horn, or getting too close puts the cyclist at serious risk.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_038',
    questionText: 'A powered wheelchair user is on the road because the pavement is obstructed. How should you treat them?',
    options: [
      'Sound your horn to warn them they must move to the pavement',
      'Treat them as you would a slow-moving vehicle - give plenty of space and pass slowly',
      'Alert the police as they should not be on the road',
      'Overtake at normal speed as they have no legal status on the road',
    ],
    correctIndex: 1,
    explanation: 'Wheelchair users and mobility scooter users may need to use the road if the pavement is blocked or inaccessible. Treat them with the same consideration as any vulnerable road user - give plenty of space, pass slowly, and do not intimidate them.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_039',
    questionText: 'What is the safest way to pass a group of horse riders when one rider asks you to slow down?',
    options: [
      'Pass at 20mph, giving at least 2 metres clearance',
      'Pass at walking pace (under 10mph), giving as much width as possible, and do not accelerate until well past',
      'Slow to 30mph and flash your lights to indicate you have seen them',
      'Stop completely until the group has passed the road junction ahead',
    ],
    correctIndex: 1,
    explanation: 'The Highway Code recommends passing horses at walking pace with as much width as you can safely give. Do not rev the engine or accelerate sharply until you are well past. A startled horse can throw its rider or run into the road, causing serious accidents.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_040',
    questionText: 'A person is walking towards you on the road pushing a pram. There is no pavement. What should you do?',
    options: [
      'Sound your horn to warn them to move off the road',
      'Slow right down and give them as much space as possible',
      'Flash your headlights so they see you approaching',
      'Continue at normal speed as they are responsible for using a pavement if one exists',
    ],
    correctIndex: 1,
    explanation: 'Pedestrians may legally walk on a road without a pavement. They should walk on the right facing oncoming traffic, but if they are on the left with a pram, be considerate. Slow down significantly and give them as much space as safely possible.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_041',
    questionText: 'What does a yellow jacket or high-visibility vest on a cyclist at night indicate to you as a driver?',
    options: [
      'The cyclist is an authorised road worker and has right of way',
      'The cyclist is trying to be visible - but do not assume all cyclists will wear one',
      'The cyclist is a learner and you should give extra space',
      'The cyclist is travelling faster than normal and should be given priority',
    ],
    correctIndex: 1,
    explanation: 'High-visibility clothing improves a cyclist\'s chances of being seen at night. However, do not assume all cyclists will wear it - many do not. Always watch for cyclists even in poor light conditions regardless of their clothing.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
  {
    id: 'VRU_042',
    questionText: 'You are overtaking a cyclist when a car emerges from a side road on the right ahead. What must you do?',
    options: [
      'Complete the overtake quickly and brake for the emerging car',
      'Abandon the overtake, brake, and drop back behind the cyclist',
      'Sound your horn at the emerging car to make them give way',
      'Sound your horn at the cyclist to make them move to the left',
    ],
    correctIndex: 1,
    explanation: 'Any new hazard that develops during an overtake means you must abort the manoeuvre immediately. Drop back behind the cyclist and deal with the emerging car hazard first. Continuing the overtake in these circumstances puts the cyclist and yourself in danger.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_043',
    questionText: 'A pedestrian steps out suddenly from between parked cars and you are unable to stop in time. Who is legally responsible?',
    options: [
      'The pedestrian is always liable for jaywalking',
      'The driver may be found responsible if driving at an unsafe speed or without due care and attention',
      'Responsibility is always shared equally between pedestrian and driver',
      'No one is liable in a sudden accident of this type',
    ],
    correctIndex: 1,
    explanation: 'Even if a pedestrian steps out unexpectedly, a driver may be found responsible if they were exceeding the speed limit, not paying attention, or driving too fast for the conditions. Drivers are expected to anticipate the unexpected, particularly in areas where pedestrians are commonly present.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_044',
    questionText: 'What is the key hazard when passing a line of parked vehicles where doors could open?',
    options: [
      'Vehicles may pull out from the line without signalling',
      'A cyclist may emerge from a gap between parked vehicles into your path',
      'An opening door could strike your vehicle and damage it',
      'All of the above are hazards that require reduced speed',
    ],
    correctIndex: 3,
    explanation: 'Parked vehicle zones present multiple hazards: doors opening into traffic, cyclists emerging from gaps, and vehicles pulling out. Reducing speed and positioning slightly away from the parked vehicles reduces risk from all these hazards simultaneously.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_045',
    questionText: 'Pedestrians are most at risk of serious injury if struck by a vehicle travelling at what speed?',
    options: [
      '20mph',
      '30mph',
      '40mph',
      '50mph',
    ],
    correctIndex: 1,
    explanation: 'Research shows that a pedestrian struck at 30mph has around a 20% chance of being killed. At 20mph this drops to less than 5%, and at 40mph the chance of death is over 80%. This is a key reason why 20mph zones and lower speeds in pedestrian areas dramatically save lives.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_046',
    questionText: 'A cyclist ahead has a bicycle with a child seat fitted to the rear. How does this affect your following distance?',
    options: [
      'It makes no difference - treat them the same as any cyclist',
      'Give more space as the additional weight and higher centre of gravity make the bicycle less stable',
      'Follow more closely so you can react faster if they fall',
      'Overtake more quickly to minimise the time near the vulnerable child',
    ],
    correctIndex: 1,
    explanation: 'A bicycle with a child in a rear seat has a higher centre of gravity and the cyclist may have less ability to manoeuvre quickly. The passenger is also completely vulnerable. Give extra space and be particularly patient - a fall would be very serious.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_047',
    questionText: 'You are driving at night and see a cyclist with only a rear red light and no front light. What should you do?',
    options: [
      'Report them to the police using your hands-free phone',
      'Flash your headlights as a warning to the cyclist',
      'Slow down and give them extra space - they may not be visible to oncoming drivers',
      'Sound your horn to let them know their front light is off',
    ],
    correctIndex: 2,
    explanation: 'A cyclist without a front light at night is poorly visible to oncoming traffic and may not see obstacles ahead. Slow down and give them extra space. There is nothing useful you can safely do while driving. Never use your phone to report while driving.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_048',
    questionText: 'You are turning right when a pedestrian begins to cross the road you are turning into. They are on the far side of the road. Do you have to give way?',
    options: [
      'No - they are on the far side and you have priority',
      'Yes - Highway Code Rule 195 gives way to pedestrians crossing or about to cross the road you are entering',
      'Only if they are already more than halfway across',
      'Only if the pedestrian is within a marked crossing zone',
    ],
    correctIndex: 1,
    explanation: 'Highway Code Rule 195 (strengthened in 2022) requires drivers to give way to pedestrians crossing or about to cross the road you are turning into. This applies anywhere on the road being entered, not just at marked crossings.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 2,
  },
  {
    id: 'VRU_049',
    questionText: 'What extra risk do motorcyclists face in very bright sunshine compared to car drivers?',
    options: [
      'Their visors may mist up more quickly in hot weather',
      'Dark visors may make it harder to see in very bright conditions, and glare can reduce their visibility to others',
      'Motorcycles overheat more quickly in direct sunlight',
      'Bright sunshine increases drag, reducing their braking efficiency',
    ],
    correctIndex: 1,
    explanation: 'Some motorcyclists use dark-tinted visors in bright conditions, which can reduce their own visibility in changing light. Also, sun glare can make motorcycles harder for other drivers to see. Be especially alert for motorcyclists in sunny conditions - they may be coming directly out of sun glare.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 3,
  },
  {
    id: 'VRU_050',
    questionText: 'What behaviour by a pedestrian indicates they are likely to cross the road imminently?',
    options: [
      'Standing on the pavement looking in a shop window',
      'Standing at the kerb edge looking at oncoming traffic',
      'Walking along the pavement towards a pedestrian crossing 50 metres ahead',
      'Standing on the pavement talking on a mobile phone',
    ],
    correctIndex: 1,
    explanation: 'A pedestrian standing at the kerb edge and looking at traffic is the clearest indicator of an imminent road crossing. Slow down as you approach and be prepared to stop. Do not assume they will wait - many will step out when they judge (sometimes incorrectly) that there is a gap.',
    topicCategory: TopicCategory.VulnerableRoadUsers,
    difficulty: 1,
  },
];
